### ISSUE TITLE
Max playbackRate option?

### ISSUE THREAD

**Issue by Astray-git** [sampotts/plyr#1002]
Currently, the video playbackRate is limited to `2.0`.(Maybe because of Safari support)
Latest Chrome can play with sound at 16.0. Firefox can play with sound at 4.0.
Can you provide an option for max speed?

**Comment by sampotts** [comment]
Hey,

I obviously need to document it better but you can specify the options here:
https://github.com/sampotts/plyr/blob/master/src/js/defaults.js#L92

So you can pass in more options in your config to override those defaults. 

Cheers 👍

**Comment by Astray-git** [comment]
Thanks for the quick reply.
https://github.com/sampotts/plyr/blob/a4caba120c76a19fa9424598de119c44776e386d/src/js/plyr.js#L643-L645
I guess there's a 2.0 limit for `speed`

**Comment by sampotts** [comment]
Ahh good spot. Well I can easily lift that. Will do.

**Comment by sampotts** [comment]
In v3.5.7 you can now specify all the options you want. Options outside of 0.5-2x are not available in YouTube and Vimeo so they will get removed automatically.
