### ISSUE TITLE
IE11: Object doesn't support this action

### ISSUE THREAD

**Issue by michaelmano** [sampotts/plyr#1005]
[controls.js](https://github.com/sampotts/plyr/blob/fb22a90d33ad991e1f6de22f201c3b49f54168c1/src/js/controls.js#L18-L26)

Listed above is the line that is causing the issue, even with `babel-polyfill`

### Expected behaviour
No console errors and video player to work.
### Environment

- Browser: Internet Explorer
- Version: 11
- Operating System: Windows
- Version: 7 & 10

### Steps to reproduce
- Open player in IE 11

**Comment by friday** [comment]
It's been fixed in Plyr 3.3.8 https://github.com/sampotts/plyr/commit/41f9a87e0ec01146fe870fa2412ef6d4004221c1 The latest version of Plyr is 3.3.10.

**Comment by mitchellslager** [comment]
I have the same issue, currently using Plyr 3.3.10.

**Comment by friday** [comment]
This happens because IE11 doesn't support `new URL()`, so you need to polyfill `URL`. The polyfill build does this since 3.3.8. The normal build doesn't pollyfill anything. You need to do that yourself. See the links above.
