### ISSUE TITLE
captions does not update

### ISSUE THREAD

**Issue by samanmohamadi** [sampotts/plyr#1013]
I use plyr in a ReactJs Component. 
When switching videos, If one of the videos has subtitle the subtitle will be shown for other videos too.
I tried destroying player before each switch but it seems that the destroy() itself has some issues(#853 ).
how can I force the player to check for subtitles each time?

**Comment by friday** [comment]
You did read this right? https://github.com/sampotts/plyr/issues/994

**Comment by friday** [comment]
With the #994 setup, the tracks should update when the textTracks changes, so it'd be good to know if they did. There's too much else to do right now though, like the other captions and `destroy()` issues, so it has to wait anyway. Maybe fixing them will fix this.

Just added [guidelines for reporting issues](https://github.com/sampotts/plyr/blob/master/CONTRIBUTING.md#reporting-issues). The minimal replication part in particular would help.

**Comment by friday** [comment]
Added the invalid tag until this has a minimal replication link (we have a too much to do, so we can't put the effort into replicating).

Will keep it open though.

**Comment by friday** [comment]
#1015 *might* fix this, but shouldn't have any difference if you didn't set `captions.update` to true I think.

**Comment by samanmohamadi** [comment]
I tried `captions.update`, it updates captions in controls but the previous caption remains on screen. changing the language will update the caption as well so in my project calling `captions.setLanguage.call(player); ` after each update works for now.
Thanks :+1:

**Comment by friday** [comment]
> it updates captions in controls but the previous caption remains on screen

Aha. That should be fixed in #1015 too (which will be released soon as 3.3.11). I changed it so it triggers the event that resets the currently showing captions, as well as the language options. In the current release it only updates the menu. Sounds like what you describe, but since I haven't gotten your issue specifically I can't be sure.

**Comment by samanmohamadi** [comment]
Yes, it will resolve my issue, so it seems that this can be closed.
thanks

**Comment by friday** [comment]
Please let me know when 3.3.11 is out and you have tested this 👍

**Comment by friday** [comment]
3.3.*12* is out with the PR now. Let me know if this fixes it.

**Comment by samanmohamadi** [comment]
It's fixed.

**Comment by friday** [comment]
Cool! Thank you for the update 👍
