### ISSUE TITLE
Volume control not showing

### ISSUE THREAD

**Issue by volkirik** [sampotts/plyr#1022]
Volume control not showing in version v0.9.1

### Expected behaviour
Show volume controller just like other HTML5 players

### Actual behaviour
Shows mute button only.

### Environment

- Browser: Google Chrome
- Version: 67.0.3396.79
- Operating System: MS Windows
- Version: 10.0; Win64; x64

### Steps to reproduce
- Go to https://video-dev.github.io/hls.js/demo/
- Choose any test-stream. Applies to default one, too.
- It shows mute button, you can't control the volume.

**Comment by volkirik** [comment]
![screenshot](https://user-images.githubusercontent.com/33526598/41210796-691f6a7e-6d3c-11e8-8892-9711ee130582.png)

**Comment by friday** [comment]
That's Chrome's native player. Chrome just changed it.

Also, this is the Plyr repo, not Hls.js

**Comment by volkirik** [comment]
OK. sorry.
