### ISSUE TITLE
Unable to see plyr audio content in RSS feed readers previews

### ISSUE THREAD

**Issue by JasonAizkalns** [sampotts/plyr#1026]
I am not certain if this is related to plyr, but I thought it's worth a shot to see if anyone has any experience or can prove otherwise? I am using hugo + netlify for a static site and plyr for various audio snippets. However, when previewing content in RSS readers (e.g. inoreader, feedly), the plyr objects do not render. Other sources of embedded audio media (e.g. SoundCloud, clyp.it) appear to render/preview fine.

**Comment by friday** [comment]
This doesn't have anything to do with client side logic

https://github.com/sampotts/plyr/wiki/FAQ#1-does-plyr-work-with-- 
https://wiki.audacityteam.org/wiki/How_to_publish_a_Podcast
