### ISSUE TITLE
load youtube video from youtube-nocookie.com

### ISSUE THREAD

**Issue by efat33** [sampotts/plyr#1031]
Hi,
I want to load the youtube video from youtube-nocookie.com so as to prevent cookie from loading. I don't seem to find any solution to this as this player doesn't seem to have any.

Can you please help me and let me know if there's any work-out to this.

**Comment by friday** [comment]
"youtube-nocookie.com" has no working API, which we need for our buttons and events to work.

If this is important to you and you can get it to work yourself with a fork of Plyr we could change our regex.

**Comment by DrillSergeant** [comment]
Hope there will be way soon. We need to remove Plyr for YouTube-Videos out of most customer projects.
