### ISSUE TITLE
Support for data-teaser and data-preview tag

### ISSUE THREAD

**Issue by ghost** [sampotts/plyr#1033]
Hi,

I would like to show a preview of my video on :hover but Plyr doesn't seem to support the data-teaser and data-preview tag.

Is it normal behaviour and would it be simple to support it ?
Thanks,

**Comment by friday** [comment]
It's normal.

It's usually normal for us not to support features that aren't supported by native HTML5 media, and that hasn't been documented as a feature we support. 😉 

There's no *the* `data-teaser` or `data-preview` btw. `data`-attributes are used for custom developer data. Browsers don't care about them other than giving developers access to read and set.

You can implement this yourself by listening for `mouseover` and `mouseout`.

**Comment by friday** [comment]
Closing this since it's not something we have intended to support, and the user is now a ghost. If someone else wants it there's a similar PR already. I think there's also a feature suggestion somewhere.
