### ISSUE TITLE
YouTube: sound is muted after a user perform drags on the progress bar

### ISSUE THREAD

**Issue by laurianek** [sampotts/plyr#1045]
Using the plyr for Youtube, after the user performs a dragging action on the progress bar, the sound is muted

### Expected behaviour
The sound should stay the same

### Actual behaviour
The sound is muted and the audio progress bar or button do not reflect the sudden change on the sound system.

### Environment
Production v3.3.12

- Browser: Chrome
- Version: 67.0.3396.79
- Operating System: Mac
- Version: 10.12.6

### Steps to reproduce
1. Go to https://plyr.io/#youtube
1. Click to play the video, make sure that the sound is enabled
1. Drag the progress bar back and forth a couple of times
1. Play the video

Notice how the sound is muted and that the sound button are not on the muted setting

**Comment by tocsinDE** [comment]
Got the same bug with using ``currentTime``to start videos at a specific time. The "volumechanged" event is triggered as well. Having this problem since Plyr 3.3.8, version 3.3.7 works just fine.

**Comment by friday** [comment]
Thanks for the report. This has been mentioned before but I couldn't replicate it. I think I know how this got introduced.
