### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by Ohw222** [sampotts/plyr#1046]
## I have 7 ideas for PLYR !
I think they can make the project better 👍 

### **1 -** Separate Appearance for Mobile Appearance for PCs and Large Screens
**Why ?** Because if an user of plyr would to set differents settings for mobile devices for PCs and Large Screens then he will can.

### **2 -** Double tap to jump into the video
**Examples** 

- Concept :
![idee 1b](https://user-images.githubusercontent.com/24877481/41538803-6472dfb2-730c-11e8-9544-1903c7745037.jpg)
- When the user moves manually on the timeline:
![idee 1c](https://user-images.githubusercontent.com/24877481/41538814-680cda4c-730c-11e8-9c59-416e6f56d91e.jpg)
*(Please note that I have also added a tooltip for cursor time)*

**Why ?** Because it will simplify the user

### **3 -** (or) Control buttons in the middle of the screen
**Examples** 

- ![idee 2a](https://user-images.githubusercontent.com/24877481/41539049-101440e0-730d-11e8-857f-63843d1f1bb4.jpg)
- ![idee 2b](https://user-images.githubusercontent.com/24877481/41539055-1717c3da-730d-11e8-856a-5716b7b90998.jpg)

**Why ?** Because it will simplify the user too, especially on computers *(You can also put a parameter for the size of the middle screen buttons)*

### **4 -** Some Buttons : 
- Download button : 
Example (in code) : 
```js
download-button: {enabled: true, link: "https://link.com/download.php?file=path/to/file.mp4"}
//if someone wants to download the video
```
- Plyr credits : 
Example (in code) : 
```js
plyr-credits: true
//if the webmaster wants to advertise for plyr
```

### **5 -** Have the choice of placement of time information *(and why not of all the elements of the toolbar)*
**Examples** 

- Concept :
![idee 3a](https://user-images.githubusercontent.com/24877481/41539306-bc513764-730d-11e8-9123-7dead8068a06.jpg)
- In the code : 
```js
toolbar-arrangement: [
    {
        actual-time,
        remaining-time
    },
    progress-bar,
    total-time,
    captions,
    settings,
    mute,
    sound-level,
    download-button,
    plyr-credits
]
// Left to right,
// something OR something (change on click, only for some elements) : {something, something}
```

**Why ?** Because it will simplify the webmaster, and that will give him more freedom

### **6 -** Video titles
**Examples** 

- Concept :
![idee 4a](https://user-images.githubusercontent.com/24877481/41539787-f78d05a0-730e-11e8-975c-d43aa950ac55.jpg)
- In the code : 
```js
video-title: "something",
```
**OR**
```html
<video src="https://abc.yxz/video.mp4" data-plyr-title="something"></video>
```

**Why ?** That looks a great idea 😄 

### **7 -** Watermark

**Examples** 

- Classic :
![idee 5a](https://user-images.githubusercontent.com/24877481/41540547-cf59ab36-7310-11e8-9538-9f348b2e273f.jpg)
- Hover : 
![idee 5b](https://user-images.githubusercontent.com/24877481/41540556-d1c63470-7310-11e8-8c68-c8bc615a6abc.jpg)
- In the code : 
```js
watermark: {
    enable: true,
    picture-link: "https://link.com/img.png",
    disappears: true,
    clickable: true,
    hoverable: true,
    link: "https://link.com/page.html"
}
```

**Why ?** Because it's more professional

## To finish
I'm sorry about my spelling, i'm french 😅...

**Comment by friday** [comment]
1. You should be able to do it yourself with media queries, depending on exactly what you mean. You have to be more specific
2. I think this is a good suggestion. Create a separate issue for the ideas in 2-3 if you want it
3. See 2 ^
4. See #193. Not sure plyr-credits is a realistic thing devs want to add.
5. I'm not sure I like adding a separate option for arranging buttons as opposed extending the current ones (which can be made to be backward compatible). See #1047 (just created)
6. I think this is a good suggestion. Title can already be set, but isn't shown afaik. Create a separate issue for this if you want it.
7. No need for Plyr to do this #506. In addition there could be legal issues with putting a logo on top of YouTube or Vimeo.

I think 2-3 and 6 are good suggestions, but it's really not helpful to us to get "here's a list of everything I want" type of issues. We (developers and users watching issues) need to focus on one thing at a time and thread. In fact our [contributions guidelines](https://github.com/sampotts/plyr/blob/master/CONTRIBUTING.md) says this:

> Create one issue per problem or request (i.e. don't combine multiple problems to one git issue).

(It is in the "Reporting issues" section, so maybe this should be copied to the feature request section too)

I'm closing this, but feel free to open new issues with individual features unless they already exist.

**Comment by sampotts** [comment]
Pretty much as above 👍 I'd just add:

1. Element queries will solve this but currently it's hard to know the size of the actual *player* vs the viewport itself (where media queries are useful). It's possible to hack something together with IntersectionObserver as far as I'm aware but not something I've investigated yet. 
5. I agree not sure we'd want to add another option when we could just take the order that the options are specified in the array that was my initial thinking before but never jotted it down. 
6. Title is only currently used for accessibility attributes.

**Comment by dzcpy** [comment]
Actually, is there a way to display `total-time` of a video / audio?
