### ISSUE TITLE
Play button not changing to show pause-icon when video is playing

### ISSUE THREAD

**Issue by wagich** [sampotts/plyr#1048]
### Expected behaviour
The play button shows a pause-icon when media is playing.

### Actual behaviour
The play button shows a play-icon regardless of media state.

### Environment
- Browser: Chrome 67, Edge 42, Firefox 60
- Operating System: Windows 10
- Version: 3.3.15

### Steps to reproduce
- Go to https://plyr.io/
- Click play
- Observe play button in lower left corner

**Comment by wagich** [comment]
It seems to be a tegression introduced in 3.3.15, 3.3.14 works.

**Comment by friday** [comment]
Yeah, it was actually a fix for another issue which I think is non-fatal https://github.com/sampotts/plyr/commit/ea4d91d2a011cdfc835619cb90a25074c039e777#diff-21a888c55f507a76f2a82a75d300d6f7 Stay on  3.3.14 for now.

Thanks for reporting!

**Comment by sampotts** [comment]
This is fixed in v3.3.16 - Sorry @friday I missed your change but ended up writing exactly the same code 👍

**Comment by mogita** [comment]
It seems this issue appears again in 3.4.0

**Comment by sampotts** [comment]
Try the latest version
