### ISSUE TITLE
hide all controls for Vimeo?

### ISSUE THREAD

**Issue by v3nt** [sampotts/plyr#1060]
Is it possible to hide all controls when using the player for Vimeos? I don't mean autohide - we want everything hidden all the time.

We can't use Vimeo's background settings as it disables the listeners so we can't run the desired functions after.

D.

**Comment by friday** [comment]
This should work:

```js
new Plyr(element, {controls: []}
```

You may get an error (maybe only if you have enable captions), but it should be fixed soon (#1061)

**Comment by sampotts** [comment]
This should be ok now in v3.3.21 👍
