### ISSUE TITLE
Iphone, cannot change source of video

### ISSUE THREAD

**Issue by fabulator** [sampotts/plyr#1065]
### Expected behaviour
Change source of video.

### Actual behaviour
Nothing happend.

### Environment

- Browser: Safari
- Version: 9.0
- Operating System: iOS
- Version: 9.3.5

### Steps to reproduce
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel='stylesheet' id='plyr-css'  href='https://cdnjs.cloudflare.com/ajax/libs/plyr/3.3.20/plyr.css' type='text/css' media='all' />
    <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/plyr/3.3.20/plyr.polyfilled.js'></script>
</head>
<body>
<div id="root"></div>

<video id="plyr-player"></video>


<video src="https://catvusa.com/video/spots/uvod.tradition.mp4"></video>


<script type="application/javascript">
    var player = new Plyr('#plyr-player');

    player.source = {
        type: 'video',
        sources: [
            {
                src: 'https://catvusa.com/video/spots/uvod.tradition.mp4',
                type: 'video/mp4'
            }
        ]
    };
</script>

</body>
</html>
```

This html contains two video. The first is handled by Plyr and second is native html5 video. When I click on seconds video, it works OK. When I try to click on plyr video, nothings happens. There is no error in log and src of video element is still https://cdn.plyr.io/static/blank.mp4.

Thank for help.

**Comment by Sikandarkhan** [comment]
in react-js I am still facing this error. Any update ?
