### ISSUE TITLE
Youtube nocookie domain not working

### ISSUE THREAD

**Issue by robinpoort** [sampotts/plyr#1066]
### Expected behaviour
Use the YouTube iframe embed with youtube-nocookie.com domain. Expecting a styled Plyr player

### Actual behaviour
The small non-responsive youtube video is displayed instead

### Environment

- Browser: Chrome
- Version: 67
- Operating System: OSX
- Version: 10.13.5
- Using fastly CDN Plyr 3.3.20 version

### Steps to reproduce
https://jsfiddle.net/074q3k8c/1/

**Comment by robinpoort** [comment]
Ah ok, so it's not possible?

Maybe I'm not getting it right but isn't it possible to change the URL to youtube-nocookie.com based on either a Plyr setting (data-attribute for example) or simply the original url submitted by the developer in the player?

https://jsfiddle.net/074q3k8c/13/

Seems like the API is working just fine with the nocookie domain. Or is "the YouTube SDK" something other than this? https://developers.google.com/youtube/iframe_api_reference Did a Google search but the only thing popping up was the API.

**Comment by friday** [comment]
Plyr needs it's methods (like `play()`), and the Plyr controls using them to be able to trigger the iframe's method. Otherwise we could just use the iframe embed url without any SDK.

You can't pass a url to `new YT.Player()`. `new YT.Player()` _creates_ the URL, so unless there is some magic way it's just not possible.

**Comment by robinpoort** [comment]
Ok, too bad :)

I was checking because I'm located in the EU and with the new GDPR (and older cookie laws, but now everybody woke up) I'd like to only have functional cookies and anonymous analytics cookies on my sites so I won't have to display an annoying cookie consent banner type of thing. Unless the client wants marketing cookies ofcourse.

With this not being possible at the moment, shall we close this ticket?

**Comment by omarkhatibco** [comment]
@friday 
I get it able to work with youtube-nocookie 
can I make a PR ?
