### ISSUE TITLE
mouse clicks are treated as touch interactions

### ISSUE THREAD

**Issue by 0cool-f** [sampotts/plyr#1067]
### Expected behaviour

Pause the video when clicking on it

### Actual behaviour

Controls are showed

### Environment

- Hardware: monitor touchscreen on a desktop pc

- Browser: All
- Version: All
- Operating System: All
- Version: All

### Steps to reproduce
- Click with mouse on Plyr, instead using monitor, that's all

**Comment by friday** [comment]
Just to clarify:
#968 is about not being able to pause by touching a playing video on touch-devices. The reason for this is detailed in the issue (no "hover" / "mouseover"), but the situation could be improved.

This issues is about click-interactions being treated as touch-interactions if your device has both capacities and you are using a click-device.

For people with only click-devices, this can be replicated by loading https://plyr.io/ with Chrome devtools device mode enabled. Then if you disable it without reloading the page you won't be able to pause by clicking the playing video.

It should only happen for HTML5 video.

**Comment by gehaktmolen** [comment]
As a quick solution I simply did this:
```
hideControls: (!/Android/.test(navigator.userAgent))
```

That way I can take advantage of pausing and showing controls on android devices when tapping on the video. And "fallback" to the "hover"-like behaviour for ios and desktop. 

Best solution imo would be to always be able to pause/ resume video by clicking on the video itself,  while also showing/hiding controls. Along with the hover behaviour for mouse controlled devices.

**Comment by noelbank00** [comment]
@gehaktmolen Just use `hideControls: false`, that perfect for me.
