### ISSUE TITLE
Query for DRM Support

### ISSUE THREAD

**Issue by sridhard** [sampotts/plyr#1071]
Does plyr support DRM like widevine, playready and fairplay?

**Comment by friday** [comment]
This is a question ([which you shouldn't ask here](https://github.com/sampotts/plyr/blob/master/CONTRIBUTING.md#reporting-issues)) and is also the [first question in our FAQ](https://github.com/sampotts/plyr/wiki/FAQ#1-does-plyr-work-with-- )

The answer is no, but you can use a streaming library like dash.js, hls.js or Shaka Player to add support to native HTML5. See [our examples](https://github.com/sampotts/plyr#try-plyr-online)
