### ISSUE TITLE
Handle live streams

### ISSUE THREAD

**Issue by mimse** [sampotts/plyr#1072]
### Expected behaviour
When playing a live stream it does not make sense to show current time and progress bar
![image](https://user-images.githubusercontent.com/1250254/42025195-48005980-7ac4-11e8-8278-5d1c3f6ca815.png)
### Actual behaviour
![image](https://user-images.githubusercontent.com/1250254/42025434-d7d291fe-7ac4-11e8-98bb-92d16d54a537.png)

**Comment by sampotts** [comment]
This should be resolved with your PR now 👍
