### ISSUE TITLE
clickToPlay=false still plays/pauses on click in OSX 10.14

### ISSUE THREAD

**Issue by frogg** [sampotts/plyr#1076]
### Expected behavior
Plyr does not react to clicks onto the video.

### Actual behaviour
Plyr still reacts to clicks onto the video (plays/pauses)

### Environment

- Browser: Safari
- Version: Version 12.0 (14606.1.20.40.2)
- Operating System: macOS 10.14 (18A314h)

### Steps to reproduce
Setup plyr and then set
`plyr.clickToPlay = false;`

**Comment by sampotts** [comment]
I'm unable to replicate this on the public beta with Safari 12. Anyone else?

**Comment by friday** [comment]
`clickToPlay` isn't a setter. It's an option, so`plyr.clickToPlay = false;` won't do anything.

You need to pass it as to Plyr when creating the instance:
```js
new Plyr(element, {clickToPlay: false});
```

You can also change the default via `Plyr.defaults.clickToPlay = false;` before creating the instance (this is undocumented).

**Comment by sampotts** [comment]
Good spot @friday , I totalled missed that 😂
