### ISSUE TITLE
Strange jQuery error on Edge

### ISSUE THREAD

**Issue by jbugel** [sampotts/plyr#1077]
### Expected behaviour
Plyr plays without error on Chrome and Safari

### Actual behaviour

I get an console error on Edge, on the same localhost server which i posted below. Please note: The error is in dutch, i used Google Translate to translate to english. Im trying to generate an original english error, which i will post asap:

--------
JQMIGRATE: Migrate is installed, version 1.4.1 
jquery-migrate.min.js (2,495)

HTML1509: Unmatched end tag.

industries (310.2)

 CSP14307: Source https://f.vimeocdn.com has already been given for instruction script-src for Content-Security-Policy.

 CSP14307: Source https://f.vimeocdn.com has already been given for style-src instruction for Content-Security-Policy.

 CSP14307: Source https://f.vimeocdn.com has already been given for instruction img-src for Content-Security-Policy.

 CONSOLE1810304: console.memory is not implemented. 0 returns for all attributes. Use the memory profiling to check the memory consumption.

 CSP14307: Source https://f.vimeocdn.com has already been given for instruction script-src for Content-Security-Policy.

 CSP14307: Source https://f.vimeocdn.com has already been given for style-src instruction for Content-Security-Policy.

 CSP14307: Source https://f.vimeocdn.com has already been given for instruction img-src for Content-Security-Policy.

 HTML1506: Unexpected token.
industries (942.1)

 jQuery.Deferred exception: Unable to get property 'length' or undefined or null reference TypeError: Unable to get property 'length' or undefined or null reference
   at e (http://192.168.178.100:3000/wp-content/themes/base/inc/plyr/plyr.min.js?ver=1:1:84496)
   at Anonymous function (http://192.168.178.100:3000/wp-content/themes/base/app/js/functions.min.js?ver=1:1:3356)
   at l (https://code.jquery.com/jquery-3.3.1.min.js:2:29367)
   at Anonymous function (https://code.jquery.com/jquery-3.3.1.min.js:2:29677) undefined
jquery-3.3.1.min.js (2,30874)

 SCRIPT5007: Unable to get property 'length' or undefined or null reference
jquery-3.3.1.min.js (1,31039)
--------

### Environment

- Browser: Microsoft Edge
- Version: 41.16299.15.0
- Operating System: Windows 10 Home
- Version: 1709
- Build: 16299.125

### Steps to reproduce
- When i remove the plyr player, the error doesnt show and jquery works as expected

**Comment by sampotts** [comment]
Hard for us to debug that without it being public

**Comment by jbugel** [comment]
Thank you for the quick response. The page is publicly visible here:

http://ziuz.b2design.nl/industries/

**Comment by jbugel** [comment]
Im amashamed admit that was indeed the problem. The browser was not updated. Thank you for helping me find the solution
