### ISSUE TITLE
Prevent seeking

### ISSUE THREAD

**Issue by Aguywit** [sampotts/plyr#1078]
Is there some way to prevent seeking?

**Comment by gurupras** [comment]
There are two _resolved_ issues that are very related to this. Please look at #755 and #806.

**Comment by friday** [comment]
Thanks @gurupras!

I'll close the issue.

**Comment by Aguywit** [comment]
Thanks for pointing me in the right direction, I only searched issues for "seeking" and couldn't find anything in that direction.
thanks ;)
