### ISSUE TITLE
Multiple audio players on same page how?

### ISSUE THREAD

**Issue by mistincat** [sampotts/plyr#1089]
*Please _use this issue template_ as it makes replicating and fixing the issue easier for us. If you decide not to use it or you are vague your issue may be close instantly.*

### Environment

- Browser: Chrome
- Version: Version 67.0.3396.99 (Official Build) (32-bit)
- Operating System: Windows
- Version: 10

### Steps to reproduce I have duplicated two players on my page, changing only the ID for the second player using the floowing code:

`<audio id="player2" controls>
                      <source src="/path/to/.mp3" type="audio/mp3">
                      <source src="/path/to/audio.ogg" type="audio/ogg">
                  </audio>`
-

and i added this at the bottom of my page 

`<script>const player = new Plyr('#player2');</script>`

The second player just defaults to the standard browser player, what am i doing wrong please?

**Comment by sampotts** [comment]
It's worth reading the docs... 
https://github.com/sampotts/plyr#setting-up-multiple-players
