### ISSUE TITLE
M3u8 Videos Streaming

### ISSUE THREAD

**Issue by Cavain** [sampotts/plyr#1097]
*Please _use this issue template_ as it makes replicating and fixing the issue easier for us. If you decide not to use it or you are vague your issue may be close instantly.*

### Expected behaviour
I want to use this plugin only for m3u8 videos will this work?
### Environment

- Browser: Chrome
- Version:
- Operating System:
- Version:

### Steps to reproduce
-

**Comment by friday** [comment]
Use hls.js for streaming hls video. See the example codepen in the documentation.

**Comment by chovy** [comment]
i don't see it in the readme. can you point us to where?

**Comment by friday** [comment]
Search for streaming or HLS @chovy
