### ISSUE TITLE
ratio doesn't work

### ISSUE THREAD

**Issue by sunweijieMJ** [sampotts/plyr#1099]
If the type is video/mp4, the ratio attribute will not work

**Comment by friday** [comment]
"doesn't work" is not a valid description of a problem.

Please read the contributions guidelines and use the issue template or don't bother at all.

Also, it's not supposed to. It's for "embedded players" (YouTube and Vimeo).

**Comment by sampotts** [comment]
The `ratio` config option (and also a new setter) will now work for all video types.
