### ISSUE TITLE
Plyr youtube video inside web component and shadow DOM 

### ISSUE THREAD

**Issue by sebastien-yoobic** [sampotts/plyr#1106]
Hi, I'm trying to create a web component with a VideoPlayer in it based on plyr. My component in encapsulated in shadow DOM and I can not load youtube videos. It works fine with mp4 video and a url. 
### Do you know if youtube videos can be load inside the shadow DOM using YoutubeAPI ? 
I am using [StencilJS](https://stenciljs.com) to create my web component. 
I had the exact same behaviour trying to make the video player with videojs and videojs-youtube.

**Comment by friday** [comment]
[This isn't really the right place](https://github.com/sampotts/plyr/blob/master/CONTRIBUTING.md#reporting-issues), but good luck!
