### ISSUE TITLE
Unresponsive Controls on iPad after seeking

### ISSUE THREAD

**Issue by RedFu01** [sampotts/plyr#1109]
*Please _use this issue template_ as it makes replicating and fixing the issue easier for us. If you decide not to use it or you are vague your issue may be close instantly.*

### Expected behaviour
The Controls should respond also after using the seekbar

### Actual behaviour
If you use the seekbar of the video a few times on iPad it happens, that all other controls (Play, fullscreen, ...) do not respond on clicks anymore.

### Environment

- Browser: Safari
- Version: 11.0
- Operating System: iOS (iPad 6th Gen)
- Version: 11.4

### Steps to reproduce
- Open the plyr demo page on an iPad and use the seekbar a few times
- Click on the video to bring up the controlbar again
- Click on the play/pause or fullscreen button

**Comment by friday** [comment]
Seems similar and possibly related to #1101

**Comment by MBWebTechMariusz** [comment]
Hi,
could you have a look into this already? Seems to be a problem on some integrations.

**Comment by friday** [comment]
@MBWebTechMariusz Anyone is welcome to help out. There's no reason to expect us to fix everything, or giving us orders. I don't even have an iPad btw.

There's a handful of known serious issues right now. We're aware of it, but we're just unpaid private persons helping out in our spare time.

**Comment by sampotts** [comment]
This should now be resolved. It was a very weird bug. It seems iOS requires the input to be redrawn after you interact with it. Don't ask me why... It seems to be ok for me now but please report back if not. I'll close this for now.
