### ISSUE TITLE
Can't change Youtube video quality

### ISSUE THREAD

**Issue by Scrity1976** [sampotts/plyr#1110]
### Expected behaviour
Quality should change.

### Actual behaviour
It is impossible to change Youtube video quality with Plyr settings button. For example, if current quality is 1080p and then I want to change it to 720p, nothing happens, quality remains 1080p even after reloading page.

### Environment

- Browser: Chrome 67.0.3396.99 64 bit.
- Version: v.3.3.22
- Operating System: Windows 10 64 bit.

### Steps to reproduce
- Go to [https://plyr.io/#youtube](https://plyr.io/#youtube) and play video
- Try to change quality

**Comment by friday** [comment]
It's because YouTube removed this feature.

The current behavior is a bug imo. We should remove the controls since it's not working

**Comment by sampotts** [comment]
We've decided to remove support for YouTube quality control as the API was becoming less and less useful to the point where it didn't work 99% of the time. I'll write some documentation on this shortly.
