### ISSUE TITLE
clickToPlay is disabled on the demo

### ISSUE THREAD

**Issue by friday** [sampotts/plyr#1111]
Seems like this slipped in by mistake in https://github.com/sampotts/plyr/commit/c99607c85a293a565aa4110a69d04a9e8e9450b6#diff-247427e898ec319ee10df747286f65e4, or was this intentional?

**Comment by sampotts** [comment]
This is sorted now 👍

**Comment by ctf0** [comment]
the demo still doesnt have it
chrome v69
