### ISSUE TITLE
Player throws errors on andoid then setting player.source

### ISSUE THREAD

**Issue by MindScriptAct** [sampotts/plyr#1114]
Hello,
 Have 2 errors on android, while trying to change player.source
Works fine on PC.
Android chrome also shows existing video without problems. Only changing source throws errors.

### Expected behaviour
No errors.
### Actual behaviour
2 Errors thrown:
ReferenceError: controller is not defined     -   plyr.js:4576:34
TypeError: Cannot read property 'match' of undefined    - plyr.js:4576:34
### Environment

- Browser: Android chrome
- Version: 67
- Operating System: Android 7 (Moto g5)
- Version: 7

### Steps to reproduce
```html
<video controls poster="Images/VideoTest_First_Frame.png" id="player">
    <source src="Videos/storyVid1.mp4" type="video/mp4">
</video>
```

```js
const player = new Plyr('#player');

function TestSourceChange(){
    player.source = {
        type: 'video',
        title: 'Example title',
        sources: [
            {
                src: '/Videos/storyVid1.mp4',
                type: 'video/mp4',
            },
        ],
        poster: '/Images/clipThumb1.jpg',
        tracks: [
        ],
    };
}
```

Edit by @friday: Fixed code formatting

**Comment by friday** [comment]
Are you sure you are using the latest Plyr version and not adding anything custom to the build? The word `controller` doesn't exist anywhere is the current Plyr source code or build (except as a comment), and the word `match` is only used as a property for YouTube and Vimeo (and your example is for HTML5).

**Comment by friday** [comment]
Closing since this information doesn't add up. Comment with more info to have it reopened.
