### ISSUE TITLE
Feature: Hide controls until playback starts

### ISSUE THREAD

**Issue by daslicht** [sampotts/plyr#1115]
Hi, 
is theer a way to show the controls only after pressing playback, please?
The default seams to be that the controlas are shown anytime

Cheers Marc

**Comment by sampotts** [comment]
Not sure what you mean? Default is they hide while playing as per https://plyr.io. It's the same on YouTube, Vimeo, just about any player...

**Comment by daslicht** [comment]
Plyr defualt if not playing right after loading teh page:

![](http://prntscr.com/k9wjg0)

Youtube:
![](https://i.imgur.com/LDsGQWj.png)

**Comment by Joeao** [comment]
By looking at the docs, the easiest way I could think to do it would be:

```javascript
const player = new Plyr('#player');

player.toggleControls(false)

player.on('play', event => {
     player.toggleControls(true);
});
```

However I tried on Codepen and it doesn't actually work. You could workaround with CSS, showing controls on the play event.

I achieved this functionality by making my own play button and backdrop image and initialising Plyr when clicking the button, but it may be overkill for just hiding the controls.

**Comment by friday** [comment]
You need to disable hideControls too, and then add your own events for autohiding if you want that.

https://codepen.io/fullkornslimpa/pen/EpmKga?editors=1010

**Comment by daslicht** [comment]
AWESOME , thank you !

**Comment by friday** [comment]
If you want the same behavior with hideControls enabled:
https://codepen.io/fullkornslimpa/pen/oMomEm

Note that this won't show the controls when you start playing. You have to trigger some event for that I guess.

**Comment by daslicht** [comment]
Thats even less js ! Thank you
