### ISSUE TITLE
Event on ID3 timed metadata over HLS

### ISSUE THREAD

**Issue by BrightSoul** [sampotts/plyr#1116]
Hi, I'm evaluating Plyr as a substitute to JWPlayer but I absolutely need to be notified when ID3 metadata arrive with the HLS stream (typically the streaming server sends one metadata packet every 2 seconds). Does Plyr have an event for this? I couldn't find it in the documentation.

See the equivalent documentation page in JWPlayer's website.
[https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/#jwplayeronmeta](https://developer.jwplayer.com/jw-player/docs/javascript-api-reference/#jwplayeronmeta)

**Comment by friday** [comment]
Plyr doesn't handle streams. You can handle streams with Plyr and other libraries which have events for these things.

https://github.com/sampotts/plyr/wiki/FAQ#1-does-plyr-work-with--

**Comment by BrightSoul** [comment]
Understood, thank you!

**Comment by friday** [comment]
jwplayer probably handles this aspect better. Plyr works with captions for dash.js and hls.js (not Shaka Player). Quality switching isn't implemented yet. Plyr is also not well tested, and doesn't have the same resources, so I would expect jwplayer to be more stable if the price and licence works for you.
