### ISSUE TITLE
How to post multiple video quality HLS Livestream

### ISSUE THREAD

**Issue by skpbteam** [sampotts/plyr#1118]
Hi,
I am using this template for HLS Livestream: https://codepen.io/pen?template=oyLKQb
and this template for DASH: https://codepen.io/pen?template=zaBgBy
I do not know how to add other quality and how to play DASH on IOS.

Thanks.

**Comment by friday** [comment]
It's not yet supported. There are blockers keeping us from fixing this quickly.

**Comment by oixan** [comment]
is there any update on this feature?

**Comment by sampotts** [comment]
Waiting on pull requests 👍

**Comment by ahmadshc** [comment]
> Switching quality with the Plyr settings and streaming libraries is not yet supported. There are blockers keeping us from fixing this quickly.
> 
> It's a shame, since it makes more sense with these libraries than plain video files.
> 
> Dash on ios is not a question for Plyr https://github.com/sampotts/plyr/wiki/FAQ#1-does-plyr-work-with--

hello
this has already been done by a large company before!
please see below link:
https://github.com/sampotts/plyr/issues/1249
I hope to see this feature as soon as possible
thank you

**Comment by sebastiantoro** [comment]
Any plans for updating this feature?

**Comment by reinierkors** [comment]
Any updates?

**Comment by sampotts** [comment]
I'm ready to look at PRs 👍

**Comment by iraniamir** [comment]
?? not yet ?

**Comment by efriandika** [comment]
What do u mean @iraniamir ? would u like to give as a complete code ?

**Comment by lxr9161** [comment]
@iraniamir I need  you help . can I see your code ?

**Comment by Benny739** [comment]
Anyone figured out how to do this?

**Comment by sampotts** [comment]
Please use https://github.com/sampotts/plyr/issues/1741.
