### ISSUE TITLE
Multiple players Fail on XHTML

### ISSUE THREAD

**Issue by dreasn** [sampotts/plyr#1121]
*Please _use this issue template_ as it makes replicating and fixing the issue easier for us. If you decide not to use it or you are vague your issue may be close instantly.*

### Environment

- Browser: chrome
- Version: 67.0.3396.99
- Operating System: ms Windows
- Version: 10 Pro

### Steps to reproduce
- Create a valid xhtml valid document:

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
    <meta charset="utf-8" />
    <title>Plyr - A simple, customizable HTML5 Video, Audio, YouTube and Vimeo player</title>
    <meta name="description" property="og:description" content="A simple HTML5 media player with custom controls and WebVTT captions."/>
    <meta name="author" content="Sam Potts"/>
	<meta name="viewport" content="width=768,height=1024" />
	
	<link href="THE_PATH_TO_IT/plyr.css" rel="stylesheet" type="text/css" />
</head>
<body style="width:768px;height:1024px">
	<video class="myclass" controls="controls" poster="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.jpg" id="player">
		
		<source src="pk.mp4" type="video/mp4"/>

		
		<p>video not supported</p>
	</video>

    
    <script src="THE_PATH_TO_IT/plyr.js" ></script>

	
	<script crossorigin="anonymous">const players = Array.from(document.querySelectorAll('.myclass')).map(p => new Plyr(p));</script>
</body>
</html>

**Comment by sampotts** [comment]
HTML5 video is surprisingly only supported on... you guessed it... HTML5 😂

**Comment by dreasn** [comment]
alas..
