### ISSUE TITLE
plyr not able to play video in ios 11.4

### ISSUE THREAD

**Issue by santoshkumar1292** [sampotts/plyr#1125]
*Please _use this issue template_ as it makes replicating and fixing the issue easier for us. If you decide not to use it or you are vague your issue may be close instantly.*

### Environment

- Browser:
- Version:
- Operating System:
- Version:

### Steps to reproduce
-

**Comment by sampotts** [comment]
> Please use this issue template as it makes replicating and fixing the issue easier for us. If you decide not to use it or you are vague your issue may be close instantly.
