### ISSUE TITLE
iosNative fullscreen not working on stopped video

### ISSUE THREAD

**Issue by jamesoflol** [sampotts/plyr#1133]
Hi folks. First up, thanks for the great player.

### Expected behaviour

Clicking fullscreen button on stopped video results in fullscreen appearing

### Actual behaviour

Clicking fullscreen button on stopped video does nothing at all. It works when video is already playing

### Steps to reproduce

 - Add following code to the stock demo `, { fullscreen: { enabled: true, fallback: true, iosNative: true } }`
 - Tap fullscreen button

### Environment

- Browser: both safari and chrome
- Version: latest
- Operating System: ios iphone
- Version: latest

### Link to where the bug is happening

https://codepen.io/anon/pen/vaWWbZ. This is just Sam's codepen with iosNative set to true

### Suspected cause:

fullscreen.js:180:

    if (this.player.playing) {

There's no code path for !this.player.playing.

Can you remember the reason for requiring the video to be playing? I did a quick dirty check by taking out that condition ([link](https://s3-ap-southeast-2.amazonaws.com/jameslol-test/dist/index.html)) and it worked fine on my iphone 8. Would you like me to do the edit properly and submit a pull request?

**Comment by friday** [comment]
I've also been confused about that line. Could you test that removing it works, even *before* playing the first time, and then make the PR? :)

**Comment by sampotts** [comment]
Your change is now merged in v3.4.0! Cheers dude 👍
