### ISSUE TITLE
Disable double click to prevent fullscreen mode.

### ISSUE THREAD

**Issue by daranaveen007** [sampotts/plyr#1144]
Hello dear, sampotts.
Please let me know that I want to block Fullscreen mode in all the possible ways, including double clicking on the video.
So, is there any option to block double click to prevent fullscreen mode?
Thanks. 

Note: I have already blocking fullscreen button through Options. But I can,t make my users to STOP go for fullscreen through double clicking on the video.

**Comment by friday** [comment]
```js
const player = new Plyr(element, {fullscreen: {enabled: false}});
```

Please read the documentation and issue templates next time.

**Comment by daranaveen007** [comment]
And also in Firefox (Latest version), controls buttons are not visible because of SVG thing. Please help me in these. it'll be very great if you do.

**Comment by sampotts** [comment]
Are you seeing these on https://plyr.io? I can't replicate either. It works fine for me on IE11 and Firefox. 99 times out of a 100 this is due to an issue with implementation. Possibly due to polyfills. Is there a public page I can see?

**Comment by Monkey1GIt** [comment]
I find two ways to disable toggle fullscreen when double click.
Method 1, using listeners, construct vplyr like this:

```javascript
const vPlyr = new Plyr("#videoPlayer", {
    fullscreen: { enabled: true },
    listeners: {
        fullscreen() {
            return false;
        }
    },
});
```

Method 2, modify source code:
the code of dbclick is

<img width="1600" height="693" alt="Image" src="https://github.com/user-attachments/assets/b1ea4343-67d2-4b8e-9633-076115726daa" />

just remove the code in plyr.polyfilled.js of 3.7.8 version, if you don't use anymore, which is:
```javascript
J.call(this.player,this.player.elements.container,"dblclick",(e=>{A.element(this.player.elements.controls)&&this.player.elements.controls.contains(e.target)||this.player.listeners.proxy(e,this.toggle,"fullscreen")}))
```
