### ISSUE TITLE
Plyr is not working in IE 11.0.60

### ISSUE THREAD

**Issue by daranaveen007** [sampotts/plyr#1145]
I tried to get it worked in IE, but it is not.
But in Edge it is working fine.

Please fix these: 1. In Firefox controls are not visible.
2. In IE Plyr not working anymore.

Thanks.

**Comment by sampotts** [comment]
Why have you opened another issue? And ignored the template. As I replied already. It works fine in those browsers on the demo - https//plyr.io. Good luck fixing it your end.

**Comment by daranaveen007** [comment]
Yup!!! Sorry. But really it is not working.
![image](https://user-images.githubusercontent.com/23257694/43519093-bae5ac82-95ab-11e8-98f2-5317378cef91.png)

**Comment by sampotts** [comment]
Did you test https://plyr.io? It’s working fine. Good luck fixing your implementation. 

Sam

**Comment by daranaveen007** [comment]
Yes.. I checked out. it is working the demo. but when integrating it to my project something is missing. I'm trying to trace out it.

**Comment by sampotts** [comment]
As I said before. Probably polyfills. Try reading the docs as a starter. 

Sam

**Comment by daranaveen007** [comment]
Yes.. I tried that also. added Polyfills. even though it's not working. Anyhow, thanks for the time for commenting.
Thank's a lot.
