### ISSUE TITLE
Cannot select quality on Youtube videos

### ISSUE THREAD

**Issue by davyk7** [sampotts/plyr#1149]
Hi everyone !

First thank you  for your great job !

I think found an issue in the player behaviour because I just cain't select quality playing YT videos. 
When the video is stopped (at the beginning) I can just select the speed. The quality doesn't appear.
Then, when the video is played, the qulity setting appear but choosing an other one doesn't change anything.

Tested on Chrome & Firefox browsers.

Thanks for fixing it.

Regards,

vYk

**Comment by sampotts** [comment]
This is a limitation of the YouTube API. Feel free to raise a bug over there. I’ve tried and failed. They only make the quality levels available via API after playback has begun. Also when you “request” a quality level change via the API, you may not even get it. I’m thinking about removing the quality support for YouTube completely to be honest, given it’s uselessness. 

Sam

**Comment by tocsinDE** [comment]
This is a known problem with no real solution in sight as YouTube ignores it, see https://github.com/sampotts/plyr/issues/965

**Comment by davyk7** [comment]
It's a shame that YT doesn't do anything. Thanks for replying !

vYk

**Comment by leonardobcastro** [comment]
Good morning! Would like to know why in codepen the quality works and on my site it does not. Is it something tied to the domain?

codepen example: https://codepen.io/anon/pen/xJabdz

**Comment by sampotts** [comment]
> Would probably be a good idea to follow that by documenting provider support for various features, like captions and quality selection in the docs and FAQ

Good idea! I'll create a matrix in the docs and wiki

**Comment by sampotts** [comment]
We've decided to remove support for YouTube quality control as the API was becoming less and less useful to the point where it didn't work 99% of the time. I'll write some documentation on this shortly.
