### ISSUE TITLE
support.check "ui is not defined" 

### ISSUE THREAD

**Issue by foxock** [sampotts/plyr#1150]
![tim 20180806111835](https://user-images.githubusercontent.com/28373975/43695309-86f9c5c6-996a-11e8-8068-16739cd7eae9.png)
![tim 20180806112205](https://user-images.githubusercontent.com/28373975/43695452-5bd7b6ea-996b-11e8-8ccc-5e714c392032.png)

Console: ui.js:38 Basic support only for html5 video

OS: Windows10
Browser: Chrome (latest)
Recurring: DevTools > Disable cache
probability: 100%

**Comment by foxock** [comment]
The first visit may also trigger this issue, and the problem disappears after the page is refreshed

**Comment by sampotts** [comment]
Firstly, thanks for using the issue template 👌

Are you able to replicate this on https://plyr.io? I'm not able to replicate on Chrome + Windows 10. It's also strange as even in your screenshot I can see it defined above 😂

**Comment by foxock** [comment]
Thanks : )
 this looks like my problem, I will leave a message here after the solution.
