### ISSUE TITLE
Add Ted Talks

### ISSUE THREAD

**Issue by DenislavParvanov** [sampotts/plyr#1151]
Add Ted Talks embeded videos as provider.

**Comment by friday** [comment]
Plyr needs to control the playback of the iframe in order to work. For that to be possible the provider must have an SDK (ex: https://developers.google.com/youtube/iframe_api_reference or https://github.com/vimeo/player.js). Ted Talks doesn't have this.

**Comment by friday** [comment]
Also: Their talks seems to be on YouTube anyway? They put them up there: https://www.youtube.com/user/TEDtalksDirector/videos

**Comment by DenislavParvanov** [comment]
The problem with the YouTube version is that the subs are only in only in english.
