### ISSUE TITLE
bug in caption.language initialization

### ISSUE THREAD

**Issue by Ariex** [sampotts/plyr#1153]
### Expected behaviour
`player.captions.language` should be `en`

### Actual behaviour
`player.captions.language` is `e`

### Steps to reproduce
update the browser setting, make sure `navigator.languages || navigator.language || navigator.userLanguage` return a string instead of an array, which is what i got from IE10 in Win7

### Environment

- Browser:
Internet Explorer
- Version:
11
- Operating System:
Windows
- Version:
7

there is a problem in this code: https://github.com/sampotts/plyr/blob/master/src/js/captions.js#L87, it assume `navigator.languages || navigator.language || navigator.userLanguage` always return an array of strings but it is not, when `navigator.languages` is empty it returns a string then with `Array.from` it becomes array of characters.
It could be `Array.from([...(navigator.languages || []), navigator.language, navigator.userLanguage]).map(language => language.split('-')[0])` to avoid this issue.

**Comment by friday** [comment]
Thanks! This one is on me. I thought `Array.from()` worked differently.
