### ISSUE TITLE
Change Readme to include IE10/11 alternatives to arrow functions

### ISSUE THREAD

**Issue by xichro** [sampotts/plyr#1154]
I've integrated the plugin successfully within my project. IE10/11 however do not accept [arrow functions](https://caniuse.com/#search=arrow%20functions).

Please can you update the documentation to include an alternative, for instance:
**IE10/11:**
```
player.on('ready', function(event) {});
```
```
element.addEventListener('ready', function(event) {});
```

**All other browsers:**
```
player.on('ready', event => {});
```
```
element.addEventListener('ready', event => {});
```

Thanks.

**Comment by sampotts** [comment]
It's kinda expected that you'd understand what ES6 vs ES5 to use a library like this.
