### ISSUE TITLE
[accessibility] [tab] Enter to player by tab don't highlights play / settings button

### ISSUE THREAD

**Issue by INFJakZda** [sampotts/plyr#1156]
### Expected behaviour
When enter by tab key to the audio player by tab key "Play" should be highlighted.
When enter by shift+tab key to the audio player "Settings" should be highlighted.
### Actual behaviour
Play & settings aren't highlighted when enter by tab key.
### Steps to reproduce
press the "tab" button after get to https://plyr.io/#audio
### Environment
- Browser: Google Chrome
- Version:  68.0.3440.75 64-bit
- Operating System: Fedora
- Version: 28

### Link to where the bug is happening
https://plyr.io/#audio

**Comment by sampotts** [comment]
@INFJakZda This should be resolved in the latest version? let me know if not
