### ISSUE TITLE
Video not playing due to CORS issue

### ISSUE THREAD

**Issue by mlearncore2018** [sampotts/plyr#1164]
I am playing a video using Plyr and getting this issue-

Failed to load http://--video url --: Redirect from 'http://--video url --' to 'https://--video url --' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://admin.lc' is therefore not allowed access.

One the frontend, I am using BackboneJS and CoffeeScript. Any idea how to fix that?

**Comment by sampotts** [comment]
That’s nothing to do with Plyr. That’s an issue with your server configuration. You only need the `crossorigin` attribute if you’re hosting captions on a different origin. 

Sam

**Comment by AlizerUncaged** [comment]
is there a way to bypass this?
