### ISSUE TITLE
player.play() doesn't work

### ISSUE THREAD

**Issue by aariacarterweir** [sampotts/plyr#1166]
Hi I'm noticing that none of the API methods on the player object seem to be working. player.playing always returns false, player.pause() does nothing, etc etc. I have instantiated the player properly afaik and it is working fine apart from that. Anyone run into this issue before?

**Comment by sampotts** [comment]
Are you exposing player correctly? E.g. `const player = new Plyr('#player', options);` ?

**Comment by friday** [comment]
`Plyr` (uppercase P) is a class. You need to create an instance of it to use it. In the documentation and examples `player` with lowercase P refers to the instance. You cannot call methods of `Plyr` directly on the class.

`const player = new Plyr('#player', options);` is an *example* of how to do this. It does not matter if you use `const`, `let` or `var`, the instance doesn't need to be accessible in the global scope and it doesn't have to be named `player`.

In your case it sounds like you are are creating the instance and assigning it to a property. This is not a problem, but then you should not be using `player.play()`. You should be using `module.player.play()` (assuming your module is named `module` and your property is named `player`).

Try the [codepen templates](https://github.com/sampotts/plyr#try-plyr-online) if you need help getting started, and follow [this guide](https://github.com/sampotts/plyr/wiki/Writing-helpful-issue-descriptions) if you still have this problem and want to report it. This issue description doesn't have the details needed to understand the problem.

**Comment by aariacarterweir** [comment]
Hi @friday, thanks for getting back to me. I was aware of this but checking over my code let me find a bug - I was double instantiating the instance without doing a proper .destroy() call :)
