### ISSUE TITLE
YouTube source doesn't play on Microsoft Lumia 650 Edge

### ISSUE THREAD

**Issue by damianprzygodzki** [sampotts/plyr#1171]
### Actual behaviour
YouTube video doesn't play on Edge Mobile
### Steps to reproduce
https://codepen.io/dprzygodzki/pen/YOPBJM
### Environment
- Plyr version: 3.4.3
- Browser: Edge Mobile
- Version:  42.17134.1.0
- Operating System: Windows 10

### Console errors (if any)
In debug mode we can see, that there is lack of 'playing' event. 

Edit: in farther debugging i've found out that youtube iframe embedded by Plyr is working in itself.

**Comment by cadavre** [comment]
More input:

* Playback works with `.mp4` movie files server statically.
* Networking tab communicates YT and receives `200` responses.
* You can seek the movie and see frames changing, it simply doesn't "play".

Can be reproduced on Windows 10, Edge browser, "Nokia Lumia 650" emulation enabled.

**Comment by damianprzygodzki** [comment]
I started diggin on my own. And what i've found was that the problem is with buffering of Youtube Iframe Api. It stops on getVideoLoadedFraction() value ~0.023 and goes to Unstarted event.

**Comment by sampotts** [comment]
There *is* another way. You can use the `<div>` placeholder that even their own API and documentation supports. It won't make any difference to the playback though as either way require user input to begin playback. Don't always trust the YouTube API docs. They document the ability to request a change in quality but it actually does sod all 😂

**Comment by damianprzygodzki** [comment]
Thanks. Anyway, it would be great to somehow underline that for other lost devs :D Closing this one.

**Comment by deepansh96** [comment]
I have the same exact issue. I've been scratching my head since 2 days. How did you solve it @damianprzygodzki? I've been facing this issue in a lot of mobile browsers. Video files served with a `<video>` tag and an `.mp4` source work perfectly.
