### ISSUE TITLE
help me i need Change Quality in flie demo 

### ISSUE THREAD

**Issue by Nuttibat** [sampotts/plyr#1176]
I try to put it code. 

Quality default
    quality: {
        default: 576,
        options: [4320, 2880, 2160, 1440, 1080, 720, 576, 480, 360, 240],
    }

It does not show me
please help me

**Comment by sampotts** [comment]
Reading the docs would be a good start. I presume you've generated the quality levels you want? Plyr doesn't do it for you. It's only a client side library.
