### ISSUE TITLE
[mobile] control auto hide while changing the settings when the video is playing

### ISSUE THREAD

**Issue by sooxiaotong** [sampotts/plyr#1177]
I think it affects all versions of plyr.
![plyr](https://user-images.githubusercontent.com/13378059/44682105-1715cb80-aa75-11e8-81da-400173802afc.gif)

> pls wait for the gif to load

**Comment by sampotts** [comment]
Please use the template.

**Comment by sooxiaotong** [comment]
@sampotts what template did you mean? https://codepen.io/pen?template=GGqbbJ also have this same issue, i change settings while video is playing(in mobile) will trigger `hide control`

**Comment by sampotts** [comment]
When you create an issue, there's a template for what browser, Plyr version etc. You must have deleted it but it helps us work out the issue. I suspect this isn't an issue with the latest version for example.

**Comment by sampotts** [comment]
Yeah not sure how you update unpkg but they're pointing to an old version.

**Comment by sooxiaotong** [comment]
@sampotts after some testing it happens in [Touch simulated]Google Chrome Version 68.0.3440.106 (Official Build) (64-bit) & Android Chrome Version 68.0.3440.91

**Comment by sampotts** [comment]
Please update to the latest version. Thanks.

**Comment by sooxiaotong** [comment]
@sampotts https://codepen.io/fullkornslimpa/pen/oMomEm this pen is using the latest plyr also have this issue

**Comment by sampotts** [comment]
No. It's not. As I stated (maybe read my replies if you want help?) it's loading an older version:
https://unpkg.com/plyr@3.3.23/dist/plyr.min.js

The latest is *3.4.3*. You're using *3.3.23*. So that's definitely **not latest** 👍

**Comment by sooxiaotong** [comment]
@sampotts the latest 3.4.3 broke the touch control, so last time i force to rollback the old one
