### ISSUE TITLE
[IphoneX] can't get fullscreen while playing

### ISSUE THREAD

**Issue by sooxiaotong** [sampotts/plyr#1178]
![image](https://user-images.githubusercontent.com/13378059/44695251-e6e62100-aaa4-11e8-8b56-02ba4fbbf84e.png)

**Comment by sampotts** [comment]
FFS.

# PLEASE USE THE TEMPLATE 

https://github.com/sampotts/plyr/issues/new?template=bug.md

**Comment by sampotts** [comment]
Also. It's not something Plyr can really fix unless we can somehow inject/remove the viewport change on enter/exit fullscreen ... https://webkit.org/blog/7929/designing-websites-for-iphone-x/
