### ISSUE TITLE
https://vimeo.com/api/v2/video/{id}.json not found

### ISSUE THREAD

**Issue by stanvanheumen** [sampotts/plyr#1181]
### Expected behaviour

No error logged in the console.

### Actual behaviour

An error is displayed in the console with a response of "{id} not found."

### Steps to reproduce

Follow the Vimeo steps and embed a video.

### Environment

- Browser: Chrome
- Version: 68
- Operating System: MacOS
- Version: 10.13.6

**Comment by sampotts** [comment]
Do you see this on https://plyr.io/#vimeo ? I can't seem to replicate.

**Comment by Joeao** [comment]
Sounds like you're passing in `{id}` rather than an actual Vimeo ID.

**Comment by Joeao** [comment]
@stanvanheumen On the page you linked I'm not getting the error

**Comment by houke** [comment]
Got the same issue (also getting it on https://media-evolution.firebaseapp.com/watch?v=34), with the same environment specs.

**Comment by gurupras** [comment]
Does the video load and play? I've had issues where the vimeo video has refused to load accompanied by the same error you're having.

**Comment by stanvanheumen** [comment]
@Joeao I'm still receiving the error.
@gurupras Yes, the video does load and play.

The library seems to request this url: [https://vimeo.com/api/v2/video/286759118.json](https://vimeo.com/api/v2/video/286759118.json). In can see in the Chrome network tab that the browser is receiving a `404 Not Found` error. 

The response from the Vimeo API:
`286759118 not found.`

**Comment by danaburger** [comment]
@stanvanheumen Your request is utilizing Vimeo's deprecated Simple API- `https://vimeo.com/api/v2/video/286759118.json 
`
The Simple API can only retrieve metadata for videos public on vimeo.com. Your video at https://vimeo.com/286759118 is not public, can cannot be retrieved using the Simple API.

To get metadata on private videos, use the latest version of Vimeo's API: https://developer.vimeo.com/api/start

**Comment by stanvanheumen** [comment]
@danaburger Thanks for your response.

Isn't the library the one making this HTTP call?

**Comment by Brianvdb** [comment]
Any update on this? This is a library issue.

**Comment by sampotts** [comment]
I'm not really too sure what to do about this. I can't prevent that error in the console and let's be honest, it does no harm other than effect logs if you log to Sentry or similar. It's a 404 at Vimeo's end. We can't use the new API as you'd need to specify an API access token which is a bit of effort for some. I could probably add an option to load the poster image or not (that's what the call is for) if the console message is causing a problem.

**Comment by 19peaches** [comment]
Can we get this resolved please? This issue has been open for months.

**Comment by sampotts** [comment]
I’m dreadfully sorry I’m not meeting your SLAs with this free software! 

Feel free to open a PR.

**Comment by jolic** [comment]
Still open?

**Comment by sampotts** [comment]
> Still open?
> ![image](https://user-images.githubusercontent.com/476477/80909227-011adc80-8d27-11ea-9f48-1abf2a397f6c.png)

Still not read the thread? https://github.com/sampotts/plyr/issues/1181#issuecomment-427282584

**Comment by jolic** [comment]
Sorry

**Comment by jolic** [comment]
I'll make a PR later this week

**Comment by jaysunwalter123** [comment]
@jolic Did you find a fix for this? I spent hours to narrow the issue I'm having down to this - my private Vimeo video container displays on my Production site, but asks for a password. It works on my staging domain though. It's very odd to me.

**Comment by msahajwani** [comment]
No, I moved to a different player.

**Comment by johanjanssens** [comment]
Have the same issue but it doesn't interfere with plyr working in my case. After a bit of testing it seems that the error happens when you set the video to `Who can watch: People with the private link`If you made the vid to `Anyone`. The error doesn't happen.  Hope this is helpful. 

@sampotts Thanks for making plyr!

**Comment by johanjanssens** [comment]
Further info, the problem can be solved by using the oembed endpoint provided by Vimeo instead of the /api endpoint. See: https://developer.vimeo.com/api/oembed/videos

The url would be `https://vimeo.com/api/oembed.json?url=https%3A//vimeo.com/[id]`

Here `[id]`is the vimeo video id, for videos that are set to private linking only the id has an extra key in the form of: `[id]/[key]`. If you provide the full id you can get the oembed metadata which includes two urls that can be used for the poster image:

- `thumbnail_url`
- `thumbnail_url_with_play_button`

The second one has a play button overlay

**Comment by omenking** [comment]
Awaiting to see #1181 merged so I can finally reduce the noise my error tracking software

**Comment by sampotts** [comment]
This is released in v3.6.3. Again, sorry for the delay. I've been moving house, busy with work, blah blah. Thanks for the PR.
