### ISSUE TITLE
enterfullscreen/exitfullscreen events not firing (3.4.3)

### ISSUE THREAD

**Issue by xxx** [sampotts/plyr#1182]
Hi,

This looks to be the same issue as the now-closed #493, happening in the current version.

### Expected behaviour

When entering or exiting fullscreen, the appropriately named event would fire any attached handlers.

### Actual behaviour

Handlers do not fire.

### Steps to reproduce

Set up handlers for `enterfullscreen` and/or `exitfullscreen`. Enter/exit full screen in the player. Handlers will not be run.

### Environment

- Browser: Chrome
- Version: 68.0.3440.106
- Operating System: Ubuntu Linux
- Version: 18.04

### Console errors (if any)

none

### Link to where the bug is happening

I created at a fiddle at https://jsfiddle.net/r9wpkxyq/11/ that demonstrates the problem.

**Comment by sampotts** [comment]
Hmm I need to check where the event is being fired as your code *should* work. In the meantime you can always use the `on` method for that instance to check for events. e.g. 

```javascript
const player = new Plyr('#plyr-video', {
  controls: ['play', 'progress', 'current-time', 'mute', 'volume', 'fullscreen'],
  autoplay: true,
  loop: { active: true },
  invertTime: false,
  volume: 0,
  muted: true
});

player.on('timeupdate enterfullscreen exitfullscreen', event => console.log(event.type));
```

https://jsfiddle.net/h82L5x7f/

**Comment by sampotts** [comment]
Should be resolved in v3.5.0 👍

**Comment by davekobrenski** [comment]
for anyone who is curious, these events won’t fire on iOS Safari as of this writing (no fault of the developer’s…that’s just how it works in iOS currently.)

For anyone who needs to listen for iOS native full screen changes, add event listeners for the webkit properties ‘webkitbeginfullscreen' and ‘webkitendfullscreen.’ I banged my head around on this for a while until I understood that.

Using plyr version 3.6.4, iOS 14.4

**Comment by Elvincth** [comment]
> for anyone who is curious, these events won’t fire on iOS Safari as of this writing (no fault of the developer’s…that’s just how it works in iOS currently.)
> 
> For anyone who needs to listen for iOS native full screen changes, add event listeners for the webkit properties ‘webkitbeginfullscreen' and ‘webkitendfullscreen.’ I banged my head around on this for a while until I understood that.
> 
> Using plyr version 3.6.4, iOS 14.4

No even in chrome the event didn't fire

**Comment by spreaone** [comment]
Like Elvincth, I tried but didn't manage to make 'webkitendfullscreen' fire. 

@davekobrenski , could you kindly send your code to check how you did it work ?
