### ISSUE TITLE
 Download button for local media

### ISSUE THREAD

**Issue by groupunknown** [sampotts/plyr#1183]
first of all I would like to to thank all the team that is behind this fantastic design, and to the collaborators that help the project.

I have read several topics on the subject, and in some I saw that this feature was discontinued due to legal issues, which could violate youtube laws, vimeo ...

However, it would be great if you had the option to download the local media, for contents that do not have altorais rights, type video lessons, tutorials ...

I read the documentation and found in no way to implement the download button.

Maybe this question may have already been solved in other post, however in particularly I did not find.

**Comment by jamesoflol** [comment]
Duplicate issue: https://github.com/sampotts/plyr/issues/193

I'm still planning to do this when I've got time.

**Comment by sampotts** [comment]
Closing in favour of #193
