### ISSUE TITLE
[Question] Is that WordPress Plugin abandoned?

### ISSUE THREAD

**Issue by deblynprado** [sampotts/plyr#1187]
Checking WordPress.org plugins page I can see that the last update was 2yrs ago.

Also @xDae Github's profile seems to be inactive

**Comment by xDae** [comment]
I meant that the react plyr plugin is not abandoned as @deblynprado suggests :)

**Comment by deblynprado** [comment]
I've mentioned the wrong guy, sorry.
It wasn't my intention request anything.

I just tried to use this https://wordpress.org/plugins/plyr/ and saw that last update was 2 years ago. So I thought to clone and maintain that working, that's why my question.

Thank you for your time and efforts in this project, it's amazing! :D

**Comment by sampotts** [comment]
Closing in favour of #1127
