### ISSUE TITLE
can i use my custom ads?

### ISSUE THREAD

**Issue by CatsPlugins** [sampotts/plyr#1188]
hello,

can i use Plyr ads feature with my own ads?like inject while playing video and turn off after 12s?

thank you

**Comment by sampotts** [comment]
Only through Vi currently.

**Comment by arunkumartdr** [comment]
How about in 2021? How we can use custom ads?

**Comment by sampotts** [comment]
Sarcasm aside, it was possible in what, 2019 I think? Have a search.
