### ISSUE TITLE
Plyr will not show anything with <div> tag

### ISSUE THREAD

**Issue by Droobledores** [sampotts/plyr#1189]
### Expected behavior
Playing the video
### Actual behavior
Blank Page when using ```<div>```
### Steps to reproduce
https://codepen.io/anon/pen/eLPyLQ
### Environment

- Browser: Google Chrome
- Version: 68.0.3440.118
- Operating System: Chrome OS
- Version: 68.0.3440.118

### Link to where the bug is happening
http://phproxy-brownterrie910431.codeanyapp.com/

At first, when I used the YouTube embed link, it would just show the normal YouTube embed player, but then when I used the other method, everything disappeared completely.

**Comment by friday** [comment]
You have duplicate id's breaking the selector method. Remove `id="player"` from the wrapper.

**Comment by Droobledores** [comment]
It still won't work when I remove ```id="player"``` from the wrapper.

**Comment by Droobledores** [comment]
I ended up just using the template. Sorry.

**Comment by ivanjaros** [comment]
div is not working for me either
