### ISSUE TITLE
Player icons not showing in Safari 9.1

### ISSUE THREAD

**Issue by verde-io** [sampotts/plyr#1191]
Appreciate this is an old browser but a client pointed out the icons are not visibile in Safari 9.1 (it's the only 9 version I was able to test in BrowserStack, seems fine in 10). Same thing seems to happen on Plyr.io, so it's not my setup.

Can you think of a quick fix for this? Tried a couple of possible fixes but they didn't work, I would need to do more research on the matter.

Thanks!

<img width="1318" alt="screenshot 2018-09-24 16 52 45" src="https://user-images.githubusercontent.com/1122671/45963664-89011680-c01b-11e8-9ffd-478879c2e4bb.png">

**Comment by verde-io** [comment]
This might be related to #460.

**Comment by sampotts** [comment]
This is a hard one to test since I can't easily go back that far. I've signed up to BrowserStack and awaiting their approval as an open source project. Will get back once I've had a play.

**Comment by jwoertink** [comment]
I'm also in need of this. I think it's because the SVG uses `<use href=` which didn't seem to come out until a little later. 

```
<svg role="presentation" focusable="false">
  <use href="#plyr-play"></use>
</svg>
```

I'm not totally sure, but I think updating it to just be `xlink:href` instead might work. https://stackoverflow.com/a/43754117/1308979
