### ISSUE TITLE
youtube & vimeo Embed + vi ads

### ISSUE THREAD

**Issue by aufderbuehne** [sampotts/plyr#1198]
Hello!

I have a joomla based website. When I use the embed code for youtube or vimeo on my website it works:

<iframe src="https://www.youtube.com/embed/bTqVqk7FSmY?origin=https://plyr.io&amp;iv_load_policy=3&amp;modestbranding=1&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;enablejsapi=1" allowfullscreen allowtransparency allow="autoplay"></iframe>

How can I add to this code the vi.ai pre-roll ads? I am already registred on vi.ai and have a publisherId (XXXXXXXXX). I don't know where or how exactly I have to insert the following part inside the code above:

ads { enabled: true, publisherId: 'XXXXXXXXX' }

Thanks a lot!

Poy

**Comment by friday** [comment]
You can't. It violates YouTube's and Vimeo's terms, so this is intentionally unsupported. If you want to earn money from video content, you can self-host it.
