### ISSUE TITLE
The right-click context menu does not let show 'Save video as' option.

### ISSUE THREAD

**Issue by mlearncore2018** [sampotts/plyr#1203]
### Environment

- Browser:
- Version:
- Operating System:
- Version:

**Comment by mlearncore2018** [comment]
Expected behaviour: After enabling context menu, right click on vide should show option like 'Save video as'

Actual behaviour: The option I see is Save as html or webpage

**Comment by sampotts** [comment]
We don’t control the actual context menu but feel free to raise this with the browser vendor. Good luck!
