### ISSUE TITLE
Change theme color other than blue

### ISSUE THREAD

**Issue by jtaalmasco** [sampotts/plyr#1206]
The only way to change theme is via hard coded styling via CSS.

**Comment by sampotts** [comment]
Use SASS. Boom!

**Comment by aristizabal95** [comment]
> Use SASS. Boom!
> 
> https://github.com/sampotts/plyr#sass

The file indicated under that url (`bundle.scss`) is missing, and apparently trying to use all the sass files inside the `/src/scss` folder causes errors ( #1601 ).
