### ISSUE TITLE
Volume control disappears shortly after initializing

### ISSUE THREAD

**Issue by fiveDust** [sampotts/plyr#1208]
with the default setup, even the official codepen demo, the volume control disappears ( the progress bar extending over the freed space ) shortly after the player is fully initialized. You can see it, then it just disappears. No matter what other controls config and no matter if autoplay or not.  Weirdly it is fine in Firefox

Problem occurs under 
Win 10 pro 64bit

Opera 56.0.3051.36
Chrome 69.0.3497.100 64bit
Chrome 71.0.3577.0 canary 32bit

works in 
Firefox 62.0.3 64bit
Ms Edge  42.17134.1.0

**Comment by fiveDust** [comment]
anyone else experiencing the same issue?

**Comment by sampotts** [comment]
Hey, the CodePen demo was using an outdated version. I've updated it to use latest (v3.4.5) and it now functions correctly: https://codepen.io/sampotts/pen/jARJYp

**Comment by hoangdangduy** [comment]
@sampotts I am using ver 3.5.2 and still appear issue. Please my gif below.

![plyr](https://user-images.githubusercontent.com/8912039/54869081-5bc4d380-4dc6-11e9-9404-02412069a542.gif)

**Comment by hoangdangduy** [comment]
Add information. I am using Google Chrome version 73.0.3683.86. However it still run correct with Edge.

**Comment by sampotts** [comment]
The logic here is that we check for audio tracks before showing the volume control. It was raised as a bug previously that the volume control showed up for videos without audio tracks so I added some logic in. Essentially when the [`canplay` or `loadeddata` event](https://github.com/sampotts/plyr/blob/master/src/js/listeners.js#L387) occurs, I toggle the visibility of the volume input based on a [`hasAudio` getter](https://github.com/sampotts/plyr/blob/master/src/js/plyr.js#L626). I'll take another look. It could well be the video is cached and these two events do not fire as a result. That seems the most logical explanation. Media events can be flaky at best.

**Comment by poohitan** [comment]
Hi, any news on this issue?

**Comment by poohitan** [comment]
For anyone else wondering, there is a workaround:
`player.on('loadeddata', () => { player.currentTime = player.currentTime; });`

**Comment by sampotts** [comment]
This will be fixed in the next release (in a day or two).

**Comment by bhayward93** [comment]
Hey @sampotts, I'm still experiencing this issue using 3.5.6. Did you release that change?

https://gitlab.com/minds/video-player/issues/1

**Comment by sampotts** [comment]
This should be fixed in v3.5.7 👍
