### ISSUE TITLE
[Feature] Allow fallback-Fullscreen to be used as default

### ISSUE THREAD

**Issue by hawkeye64** [sampotts/plyr#1210]
Even though a browser may support the Fullscreen API, there may be instances where using the fallback full-window may be more desireable.
Currently, there is no option for this.
The fullscreen option currently consistes of:
```
{ enabled: true, fallback: true, iosNative: false }
```
Proposed functionality:
```
{ enabled: true, fallback: true, default: fullwindow, iosNative: false }
```
Where default has these options: `[fullscreen, fullwindow]` (default: fullscreen)

**Comment by hawkeye64** [comment]
Thank you!

**Comment by RayPS** [comment]
Is this option already implemented? We need this.

**Comment by sampotts** [comment]
This has now been released. It was released a few versions ago but I forgot to report back, sorry. 

You can now pass 'force' as a value for the `fallback` property of the `fullscreen` config.
