### ISSUE TITLE
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause()

### ISSUE THREAD

**Issue by mlearncore2018** [sampotts/plyr#1216]
### Expected behaviour
I'm using the 3.4.3 version of the player. At some places in the code, the player is initiated as seen in the screenshot. And I get the error mentioned in the title.

### Actual behaviour
The player should load properly.

### Environment

- Browser: Chrome, Firefox, Safari 
- Version: Latest versions
- Operating System: Mac OS- High Sierra
- Version:

### Console errors (if any)
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause()

**Comment by sampotts** [comment]
Will take a look but this is a minor bug as really all it does is log a message in the console. It doesn't actually effect functionality.

**Comment by mlearncore2018** [comment]
<img width="1669" alt="screen shot 2018-10-15 at 8 12 47 pm" src="https://user-images.githubusercontent.com/39502900/46986934-8c863b80-d0b7-11e8-8ff7-7733e10b8cf7.png">
This is what I see

**Comment by alejandroiglesias** [comment]
@sampotts I am having an issue in which the play is interrupted when I use the `plyrInstance.source` method while playing a file. Is it possible that such method is not handling the play/pause correctly?

**Comment by friday** [comment]
> This is what I see

That's because you don't have the css. Completely unrelated.

**Comment by sampotts** [comment]
This can be safely ignored. Closing this one 👍
