### ISSUE TITLE
Forward and rewind not working

### ISSUE THREAD

**Issue by tifDev** [sampotts/plyr#1227]
### Expected behaviour
When i pass the rewind and fastForward options to plyr initialization, i expect to get two buttons for each action:

```
    this.kplayer = new Plyr( pDivPlayer, {

        invertTime: false,

        // Localisation

        i18n: {

            rewind: 'Rewind 5s',

            fastForward: 'Forward 5s',

        },

    } );
```

### Actual behaviour
But the player is not adding a button for _Forward_ and other for _Rewind_

### Environment

- Browser: Chrome
- Version: 
- Operating System: Ubuntu 18.04
- Version:

**So what can i do to make those buttons appear to easily forward and rewind 5 seconds?  [*Something like this*](https://codepen.io/sampotts/pen/jARJYp) but with those buttons integrated with the original ones from plyr

**Comment by sampotts** [comment]
Reading the docs would be a good start. Have a look at the options section 👍

**Comment by tifDev** [comment]
OK thanks, now the buttons are appearing but they are using the default time that is 10 seconds and i want to be 5 seconds. **I've changed the values accordingly to the docs but still going forward 10 seconds. Here is my code**:

```
    //initialize plyr

    let player = new Plyr( pDivPlayer, {

    invertTime: false,
    i18n: {

    rewind: 'Rewind 5s',

    fastForward: 'Forward 5s',

    },

    controls: [

    'play-large', // The large play button in the center

    'restart', // Restart playback

    'rewind', // Rewind by the seek time (default 10 seconds)

    'play', // Play/pause playback

    'fast-forward', // Fast forward by the seek time (default 10 seconds)

    'progress', // The progress bar and scrubber for playback and buffering

    'current-time', // The current time of playback

    'mute', // Toggle mute

    'volume', // Volume control

    'captions', // Toggle captions

    'settings', // Settings menu

    'fullscreen', // Toggle fullscreen

    ]

    } ); 
```

**Comment by sampotts** [comment]
Ok so read some more of the docs. `seekTime` Is what you’re looking for. It might be worth reading the docs again?
