### ISSUE TITLE
Seems plyr ignores params with iframe youtube embed?!

### ISSUE THREAD

**Issue by nicmare** [sampotts/plyr#1228]
i embedded your great plyr script in my site as you can see here:
https://dashcamtest.de/dashcams/im-test-low-budget-fullhd-dashcam-von-suaoki/#mediagallery

I am happy with the integration. Thank you Sam! Only thing i wonder is why the player shows so much infos when pausing the playback:
![screenshot 2018-10-23 18 46 25](https://user-images.githubusercontent.com/898582/47376989-5fa7d900-d6f4-11e8-8cbc-539308c689bc.png)
Is this normal or did i miss something? is there any option to hide all these items? If this is normal then sorry for the title of this issue ;-)

**Comment by nicmare** [comment]
alright seems there was an update to showinfo and rel parameters in september this year: https://stackoverflow.com/questions/52886853/youtube-embed-showinfo-has-been-deprecated
damn it!

**Comment by nicmare** [comment]
or here: https://www.linkedin.com/pulse/truth-september-25th-youtube-change-jay-allred

**Comment by sampotts** [comment]
See closed issues
