### ISSUE TITLE
Pause using the mouse click stopped working from version 3.4.5

### ISSUE THREAD

**Issue by lgmnemesis** [sampotts/plyr#1230]
### Environment

- Browser: chrome
- Version: 69
- Operating System:
- Version: windows 10

### Link to where the bug is happening
Tested on chrome 69 and firefox 62

**Comment by sampotts** [comment]
Please be less vague.

**Comment by lgmnemesis** [comment]
Updated the bug description:

Expected behaviour:
1. clicking on the PLAY large button starts the video playing.
2. while video is playing, clicking on the video frame/div, the video should pause.

Actual behaviour:
1. clicking on the PLAY large button starts the video playing.
2. while video is playing, clicking on the video frame/div has no effect. the video is still playing.

**Comment by sampotts** [comment]
Sorry, I can’t replicate this on MacOS or Windows 10 on Chrome or Firefox. Are you seeing that on https://plyr.io?

**Comment by lgmnemesis** [comment]
Yes, also on plyr.io site.
I can only click directly on the PLAY button to active the player, and after that  i can not pause it clicking on the video.

**Comment by lgmnemesis** [comment]
Using firefox version 63

**Comment by sampotts** [comment]
I've tested on 62, 63, and 64.0b3 and still can't replicate. I hope you find the cause your end. Good luck!

**Comment by lgmnemesis** [comment]
I'll try. thanks for your help!
