### ISSUE TITLE
How to change youtube video ID on click with playlist

### ISSUE THREAD

**Issue by worksfather** [sampotts/plyr#1235]
Hello, 
I would like to integrate Plyr players into a site I am currently developing. I tried to integrate the video player for Youtube embed. And I would like to add a feature.
I created a playlist of youtube videos. And I wrote an onclick script that allows to change the ID of the video during playback, when yhe user click. This worked well with the normal Youtube embed player. But with Plyr, it doesn't work.

Is there a way to do it?

Here is the html
`
<div class="plyr__video-embed" id="player">
	<iframe id="youtube" src="https://www.youtube.com/embed/ZiqJC_l24mg?origin=https://plyr.io&amp;iv_load_policy=3&amp;modestbranding=1&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;enablejsapi=1" allowfullscreen allowtransparency allow="autoplay"></iframe>
</div>

<div id="clips">
	<div class="clip">
		<div onclick="changeVideo('QNGmpBhZ3rk');" class="videothumbnail">
		</div>
	</div>
	<div class="clip">
		<div onclick="changeVideo('8stwmQX3EVw');" class="videothumbnail">
		</div>
	</div>
</div>
`

And Here is the script

`
function changeVideo(IdVideo) {
    var ytbUrl = "https://www.youtube.com/embed/" + IdVideo + "?origin=https://plyr.io&amp;iv_load_policy=3&amp;modestbranding=1&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;enablejsapi=1";
    document.getElementById('youtube').src = ytbUrl;
}
`

Help me please
Thank you

**Comment by sampotts** [comment]
You're looking for the `[source](https://github.com/sampotts/plyr#methods)` API method. An example is here:
https://github.com/sampotts/plyr/blob/master/demo/src/js/demo.js
