### ISSUE TITLE
HTML5 video default quality needs solution

### ISSUE THREAD

**Issue by vdyrda** [sampotts/plyr#1236]
### Expected behaviour
loading first of <source> inside <video> as default HTML5 video behavior

### Actual behaviour
loading a <source> with the least 'size' attribute value (and adding it to <video> 'src' attribute)

### Steps to reproduce
add some sources with different "size" attribute

### Environment
- Browser: Chrome
- Version: 70
- Operating System: Microsoft Windows
- Version: 10

### Link to where the bug is happening
your own test case (HTML5 video) with replaced 1 and 2 sources: https://codepen.io/vladimir_dy/pen/wYZmwx
http://prntscr.com/lbujv4
http://prntscr.com/lbunbt

**Comment by Platon79** [comment]
I faced this problem recently and found solution in defining default quality in creating new Plyr Object. Like this:
`
player = new Plyr('#homepage-bg-video', {
        settings: ['quality'],
        quality: {
          default: '1080'
        }
})
`
In html template I have this:
`
<video id="homepage-bg-video" muted poster="/images/mural_1500x400.jpg">
        <source src="/video/ChristNarrowWay_1920.mp4" type="video/mp4" size="1080">
        <source src="/video/ChristNarrowWay1024.mp4" type="video/mp4" size="720">
</video>
`
But the problem for me is that I can't take quality value by getter player.quality. It is undefined :(

**Comment by vdyrda** [comment]
Thank you, Platon79, but it doesn't work - both for GET request and default quality:
http://prntscr.com/ldfr9e

**Comment by MichaGue** [comment]
I use `"quality": { "default": 720 }` and it works. The defaullt quality is selected and the user can change it if necessary through the menu.

```
<video class="js-player" poster="poster.jpg" controls playsinline preload="none" id="player1" data-plyr-config='{"volume": 0.3, "resetOnEnd": true, "enabled": true, "storage": { "enabled": false }, "quality": { "default": 720 } }'>
<source src="video_360p.mp4" type="video/mp4" size="360">	
<source src="video_720p.mp4" type="video/mp4" size="720">
<source src="video_1080p.mp4" type="video/mp4" size="1080">
</video>
```

**Comment by vdyrda** [comment]
Thank you, @MichaGue 
Everything is working perfect, 
may be the case is using inline parameters in <video> tag instead of setting them in javascript

**Comment by Lalmi-Issam** [comment]
Thank you, **@MichaGue**
