### ISSUE TITLE
Is playlist functional?

### ISSUE THREAD

**Issue by gborgonovo** [sampotts/plyr#1239]
Thank you for this great little player!
I don't understand if the playlist feature is ready in version 3, and, if so, how I can use it.
Can you provide an example, please?
G.

**Comment by sampotts** [comment]
Not yet. There's a (very old) issue that's tracking this but it's not something I've started on yet.

**Comment by vesper8** [comment]
@gborgonovo check this out ;) https://github.com/sampotts/plyr/issues/1276
