### ISSUE TITLE
[Solved] About the ERROR event

### ISSUE THREAD

**Issue by ahu** [sampotts/plyr#1241]
### Expected behaviour

When the audio/video source return 404,fire the error event.

### Actual behaviour

nothing happened which mean that the error event not fired.

### Steps to reproduce
```
const player = new Plyr('#player',...);

player.source = {
   type: 'audio',
   title: title,
   sources: [
      {
        src: path+'music.mp3',
        type: 'audio/mp3',
      },
    ],
};

player.on('error',function(){
   console.log('404 error');
})
```
### Environment

- Browser: Chrome 
- Version: 70.0.3538.77
- Operating System: masOS 
- Version: mojave

### Console errors (if any)

nothing :(

### How I solve this problem

I'm inspired by this post: 
https://stackoverflow.com/questions/23231404/detecting-html5-audio-element-file-not-found-error

So I change the player source setting code to

```
player.source = {
   type: 'audio',
   title: title,
   sources: [
      {
        src: path+'music.mp3',
        type: 'audio/mp3',
        onerror: error(),
      },
    ],
};
```

and the error function
```
function error() {
  blablabla...
}
```

It works then!

**Comment by sampotts** [comment]
See #1231. Do a search next time 👍

**Comment by ahu** [comment]
Yes I did but find no OBVIOUS answer. 
I just want to provide an answer for those people who like me :) 
sorry for my issues.

**Comment by sampotts** [comment]
No need for the caps - I can read. Yes, that's because it's not fixed yet, otherwise you'd see the issue closed. It's being worked on, be patient. Your solution is a hack and only works for HTML5 anyway.

**Comment by jRexhmati** [comment]
Still waiting for that "OBVIOUS" solution...
