### ISSUE TITLE
Does plyr changes YouTube view counts?

### ISSUE THREAD

**Issue by LittleHamster** [sampotts/plyr#1244]
So if you embed YouTube videos using YouTube's embed codes, the play counts are counted towards the view count and are displayed in total number of views. Now using Plyr, I am wondering if that is changed. 

@sampotts do you know if plyr is causing an issue with the view counts? because I embedded a video  using plyr and I only have certain number of views which I think should be higher. 

Thanks

**Comment by sampotts** [comment]
I get asked this a lot. Embed views count as views as far as I’m aware but feel free to test it out and report back. Our implementation of YouTube just uses the same code as their embedded player so I can’t see why it wouldn’t unless they ignore embedded players.

**Comment by sampotts** [comment]
I would say contact them and raise it as a bug but you'll be lucky if they actually fix it... 😂

**Comment by sampotts** [comment]
https://www.quora.com/Does-YouTube-count-views-if-the-video-is-posted-to-Facebook-and-viewed-from-there

**Comment by sampotts** [comment]
Plyr isn't customizing their code at all though. It's just using their embed API... 
https://developers.google.com/youtube/iframe_api_reference

**Comment by michelstomp** [comment]
Yes, I understand. But would the view perhaps only be counted when a user actually engages the video through an user initiated (click/tap) event and not counted when (play) event is fired by JS?

**Comment by gehaktmolen** [comment]
Michel ouwe baas! :D <- Arthur.

**Comment by sampotts** [comment]
I've no idea. I don't think anyone has solid evidence to point either way but it certainly seems strange to me that they wouldn't count views of embedded videos given how widely they are used. We're already using their API so I'm not sure there's anything else that can be done if in fact they aren't being counted. They aren't the most responsive either when it comes to fixing issues...

**Comment by gehaktmolen** [comment]
From what i remember only native clicks on Youtube play buttons would register a "view". Probably due to revenue allocation based on view count and the possibilities to just abuse the view count with your own solutions. 

I miss the sudden guitar jams and fuss-ball sessions! :D Anyway gl.

**Comment by michelstomp** [comment]
DUUUUDE!

**Comment by sampotts** [comment]
OK I guess that's a no then. I'll add a note in the docs. Do you have any source for that @gehaktmolen

**Comment by gehaktmolen** [comment]
Based on this document we could already assume that they would not allow it due to possible abuse:
https://support.google.com/youtube/answer/2991785?hl=en

Then there is this old post:
https://stackoverflow.com/questions/13456288/does-youtube-api-play-function-trigger-a-view-count/13459944#13459944

It has been a while since that post of course, but i can't find anything about Youtube enabling it. I even assume they have some captcha solution on their own play button :D If not, then i am going to quit my job and setup a bot to spam click Pewdiepie his youtube videos and ask money for it.
