### ISSUE TITLE
Problem load player controls after change svg and blank file urls

### ISSUE THREAD

**Issue by ahmadshc** [sampotts/plyr#1245]
Hello and thank you for perfect video framework
I use plyr for html5 audio and video player in my website and work correctly and beautifully
i upload 2 file for play my video and audio (plyr.js and plyr.css)
and upload plyr.svg and blank.mp4 files to my website host
and edit plyr.js file for change plyr.svg and blank.mp4 file addresses in 3195 and 3197 lines for load plyr.svg and blank.mp4 files from my website hosting for speedy load and faster ping in my country
but after change, player controls not show and Hides! and only show controls and work corrently when plyr.svg and blank.mp4 with default addresses in plyr.js file!
please help me for solve this problem
thank you very much

**Comment by sampotts** [comment]
You don't need to hack the source code to change those two paths. Check the docs for how to change them via config. https://github.com/sampotts/plyr#options

For the issue of your sprite not loading, make sure you have the correct mime type set in your server config.

Good luck! 👍

**Comment by ahmadshc** [comment]
> You don't need to hack the source code to change those two paths. Check the docs for how to change them via config. https://github.com/sampotts/plyr#options
> 
> For the issue of your sprite not loading, make sure you have the correct mime type set in your server config.
> 
> Good luck! 👍

than you
if i set mime type on my server, enough upload 2 files (blank.mp4 and plyr.svg) or need upload all .svg files in (sprite) folder downloaded from githup? 
If I do this, how should I call them?

my new question for this, is did you really need to design controls like that? and not another way?
my problem is that my distance to you is high
in my place ping cdn.plyr.io - pingtime average is 107ms
and that makes that this makes the controls loaded slower

If there was a way up files
blank.mp4 and plyr.svg
Designed otherwise
Or, it did not require special and difficult settings to transfer it to another server

your player is best web player in the world, beautifull and blue color for player and quility selector are very great. thank you for

**Comment by sampotts** [comment]
It's easy to use another server for those files. You need to change the `iconUrl` to your new URL and then the `blankVideo` option to your new URL. 

The mime types for the files should be 

| File | Type |
| --- | --- |
| blank.mp4 | `video/mp4` |
| plyr.svg | `image/svg+xml` |

It's strange though as the files are served via Fastly's very fast CDN which is globally distributed.

**Comment by sampotts** [comment]
It really depends on the server you're using. I'd just Google it myself and get an example.

**Comment by ahmadshc** [comment]
> It really depends on the server you're using. I'd just Google it myself and get an example.

thank you
i now new set below mime type on my host, is it correct?
![mimetype](https://user-images.githubusercontent.com/44749793/47971742-74e41680-e0a9-11e8-99c2-76004367f73a.png)
unfortunately, it still does not work
thank you

**Comment by sampotts** [comment]
Please post the code you're using on jsfiddle.net or codepen.io
