### ISSUE TITLE
Add an option to remove rounded corners

### ISSUE THREAD

**Issue by gradosevic** [sampotts/plyr#1250]
Is there a way to remove rounded corners inside the video? I couldn't find any settings for this and couldn't figure out what CSS to use

![rc](https://user-images.githubusercontent.com/10562516/48272020-b6304980-e44e-11e8-989a-a423cd85401f.jpeg)

**Comment by gurupras** [comment]
There are no rounded corners. Something in your CSS is causing this. Possibly styling on the container element. Here's a [pen](https://codepen.io/anon/pen/qQNxLe) that proves this.

**Comment by sampotts** [comment]
That’s just CSS in the demo. If you actually implement it yourself, there’s no radius.
