### ISSUE TITLE
Playing a video on AWS S3 doesn't work because of CORS

### ISSUE THREAD

**Issue by ugochirico** [sampotts/plyr#1255]
I'm using Plyr to play some videos stored on AWS S3 / CloudFront but the videos doesn't play because of CORS. 
I get the error: <video url> has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Is there a way to play a video that is on AWS S3?
Becasue it is S3 I cannot change the server configuration

**Comment by sampotts** [comment]
You can remove the `crossorigin` attribute if you have that added as I'm fairly certain it's only the `.vtt` files that require that attribute plus CORS to be implemented on the server. Failing that CORS is very easy to setup on S3/CF. That's how plyr.io is hosted.
