### ISSUE TITLE
Force FullScreen when Hitting Play

### ISSUE THREAD

**Issue by sparkktv** [sampotts/plyr#1256]
I was just wondering if there is a way to force full screen when hitting the play button. This is using the Youtube within Plyr if that changes the way to do it at all?

**Comment by friday** [comment]
You can add a custom event for the play button and toggle fullscreen (see the docs). That's how the fullscreen button works to begin with. It has to be a real user interaction though.

It shouldn't matter if it's YouTube or HTML5 since fullscreen works on the main container element.
