### ISSUE TITLE
Can you add theatre option to this player (plyr) ?

### ISSUE THREAD

**Issue by ahmadshc** [sampotts/plyr#1260]
Hello and thank you for your great player in the world
Can you add theatre option to this player?
Theatre like fluid player, videojs, youtube player, jw player and etc
Im use plyr.io becuse plyr has beautiful ux/ui, simple to use and modern player
But really the empty this feature in your plyr, i hope to see
For better send my information, i attached a pictures below, please see
![plyr_theatre](https://user-images.githubusercontent.com/44749793/48660788-d11d4200-ea7c-11e8-9243-4073b7c9b95a.png)

**Comment by sampotts** [comment]
The theatre mode really changes The container or page that the player is in. This isn’t something that would be feasibly built into the player but perhaps a method to add custom buttons would help, with a callback to resize the container.

**Comment by mayeaux** [comment]
I have the same question. Really all I would need is a way to add the icon and then hook into that event. Maybe I can just do it manually, but was this ticket closed because it's implemented or due to inactivity?

**Comment by sampotts** [comment]
Closed because it's not something that should be done inside the player. There's been requests to add options to the controls but this will be tackled when I find time to get started on v4.
