### ISSUE TITLE
Share button for plyr

### ISSUE THREAD

**Issue by ahmadshc** [sampotts/plyr#1263]
Hello
Can design and add social share button for your player?

The sharing button can have several different modes:

1. share link (url) of page video in
2. share link (url) of page video in, with picture of page and few description
3. share embedable video code

Every one that you run is great
Thank you

**Comment by sampotts** [comment]
I’m not sure this is something that is best built into the player. Another candidate for the ability to add custom buttons perhaps.

**Comment by ahmadshc** [comment]
> I’m not sure this is something that is best built into the player. Another candidate for the ability to add custom buttons perhaps.
> […](#)
> On 18 Nov 2018, at 8:29 pm, ahmadshc ***@***.***> wrote: Hello Can design and add social share button for your player? The sharing button can have several different modes: share link (url) of page video in share link (url) of page video in, with picture of page and few description share embedable video code Whichever one you implement is great Thank you — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Thank you for reply.

**Comment by filips123** [comment]
This should be added as plugin (see #1242).

**Comment by sampotts** [comment]
I'd say there wouldn't be a requirement for this. The sharing should be done on the parent _page_ rather than built into the player itself. Remember we want to keep the player as _small_ as possible in terms of file size. The ability to add custom buttons (with a callback) is what's required for this.
