### ISSUE TITLE
Really need a dailymotion support

### ISSUE THREAD

**Issue by xMyThoLoGyx** [sampotts/plyr#1272]
Hi, i'd really like a dailymotion support, most of my videos get blocked on youtube, so I use dailymotion, the plyr skin looks way better than the default dailymotion skin. Please add this plugin !!

**Comment by fongfan999** [comment]
👍

**Comment by sampotts** [comment]
Please search next time... 
https://github.com/sampotts/plyr/issues/682

Feel free to PR it
