### ISSUE TITLE
plyr + hls

### ISSUE THREAD

**Issue by apt425410** [sampotts/plyr#1279]
i got code from codepen 

> `    <script>
   
  var video = document.querySelector('#player');

  if (Hls.isSupported()) {
    var hls = new Hls();
    hls.loadSource('https://content.jwplatform.com/manifests/yp34SRmf.m3u8');
    hls.attachMedia(video);
    hls.on(Hls.Events.MANIFEST_PARSED,function() {
      video.play();
    });
    
  }
  
  plyr.setup(video);
</script>`

how can i get selection quality

**Comment by zacksiri** [comment]
there is an issue open for this https://github.com/sampotts/plyr/issues/652

**Comment by sampotts** [comment]
Closing in favour of #652
