### ISSUE TITLE
Fullscreen ratio problem on 21:9 screen

### ISSUE THREAD

**Issue by dacostafilipe** [sampotts/plyr#1281]
### Expected behaviour

A 16:9 video should have black bars on on both sides. 

![screenshot 2018-11-30 at 17 29 38](https://user-images.githubusercontent.com/922998/49302011-32ee9a80-f4c6-11e8-813a-67d1f5313f16.png)

### Actual behaviour

Youtube/Vimeo video shows with 100% width and the top/bottom part are cut.

![screenshot 2018-11-30 at 17 30 12](https://user-images.githubusercontent.com/922998/49301751-a47a1900-f4c5-11e8-9adf-695a368a2e86.png)

### Steps to reproduce

On plyr.io play the youtube/vimeo version and press "Enter Fullscreen" button.

### Environment

- Browser: Chrome / Firefox
- Version: 70.0.3538.110 / 63.0.3
- Operating System: macOS 
- Version: 10.14.1

### Link to where the bug is happening

https://plyr.io/#youtube
https://plyr.io/#vimeo

**Comment by dacostafilipe** [comment]
If I add 

```sass
&.plyr--youtube .plyr__video-wrapper{
        padding-bottom: 0 !important;
    }
```

to the `plyr-fullscreen-active` mixin, it solves the issue for youtube.

**Comment by jgelens** [comment]
I'm having the same issue. The inline padding-bottom is calculated incorrectly.

**Comment by dacostafilipe** [comment]
I have a fork for the change if you want to test : https://github.com/dacostafilipe/plyr/tree/yt-fullscreen-fix

**Comment by sampotts** [comment]
Are you both using the latest version? 

Sam

**Comment by dacostafilipe** [comment]
Did not test it since I opened this issue. Will give it a try again today.

**Comment by sampotts** [comment]
Cool. Let me me know. I rewrote a lot of the fullscreen logic for the embedded players so it _should_ be ok now. 

Sam

**Comment by jgelens** [comment]
I'm on 3.5.2. It's occurs on https://simulationthemovie.com/ when clicking on "watch trailer".

**Comment by dacostafilipe** [comment]
Just tested on master and tag v3.5.2 and issue seems fixed. Tested Chrome 72.0.3626.121, Firefox 65.0.1, Safari 12.0.3.

But I do have the issue on @jgelens's url.

**Comment by sampotts** [comment]
Cool site @jgelens - I'd say the issue might be elsewhere there though?

**Comment by sampotts** [comment]
Please try the latest version as I made a few changes which may help? I can't replicate.

**Comment by dacostafilipe** [comment]
I can confirm that the issue seems to be fixed on my side.

Tested it on https://plyr.io/#youtube and on a clients page: https://www.bcee.lu/fr/private-banking-conseil-gestion-de-fortune/activinvest/#c1719
