### ISSUE TITLE
Standard Media Events - volumechange not changing on mute

### ISSUE THREAD

**Issue by MADPT** [sampotts/plyr#1286]
Hello,

When I change the volume on the slider, I get the correct values.
However, when I toggle the `data-plyr="mute"` button, I always get the value before muting.

### Expected behaviour
Initial state - Volume: 1
On mute - Volume 0
On unmute - Volume 1

### Actual behaviour
Initial state - Volume: 1
On mute - Volume 1
On unmute - Volume 1

### Steps to reproduce
Toggle `data-plyr="mute"` button
`player.on('volumechange', event => { console.log(player.volume); });`

### Environment

- Browser: Chrome
- Version: 70.0.3538.110 (Official Build) (64-bit)
- Operating System: macOS High Sierra 
- Version: 10.13.6

Thank you in advance.

**Comment by sampotts** [comment]
The volume isn't technically 0 when the media is muted though. Perhaps you're looking for the `muted` boolean getter?

**Comment by MADPT** [comment]
Oh ok, now I get it. On the `volumechange` event, the `muted` getter returns `true || false` according to the mute state.

Thank you @sampotts.
