### ISSUE TITLE
Can not resize svg symbols

### ISSUE THREAD

**Issue by muuvmuuv** [sampotts/plyr#1287]
### Expected behaviour

I want to make the symbols a little bit smaller for our project UI

### Actual behaviour

The icons partly disappear

### Steps to reproduce

Set `.plyr__control svg` width and height to something smaller e.g. `10px`

### Environment

- Browser: FF
- Version: latest
- Operating System: macOS
- Version: 10.14.1

### Console errors (if any)

none

### Link to where the bug is happening

Every instance.

**Comment by sampotts** [comment]
Not really a bug is it? Edit the CSS.

**Comment by muuvmuuv** [comment]
@sampotts could you please reopen this because it is still not working or tell we which part of the CSS I need to edit to archive a resize of the SVG icons.
