### ISSUE TITLE
progress not mobile-friendly

### ISSUE THREAD

**Issue by Nomia** [sampotts/plyr#1288]
plyr's UI is pretty, both on the pc and mobile device. But I found that, when I drag the `progress` at the button, it's very sluggish.

the `progress`:
![image](https://user-images.githubusercontent.com/1707818/49723697-70abaa00-fca2-11e8-892d-32db33530118.png)

**Comment by sampotts** [comment]
What device? Seems fine to me on Android and iOS.

**Comment by Nomia** [comment]
IOS and android

**Comment by Nomia** [comment]
I removed the `progress` because of the sluggish

**Comment by sampotts** [comment]
It's fine here on an iPhone 8 and iPhone XS, both running iOS 12. I'll dig out my Android phone to test but it's always been fine in testing and the logic for that hasn't changed.

**Comment by sampotts** [comment]
I can't replicate this.

**Comment by Nomia** [comment]
I just tried your codepen demo on safari, the `progress` is truely sluggish or just cannot be moved. 
here is the link: 
https://codepen.io/sampotts/full/jARJYp

the offcial demo is good. So I think you might did some optimization on your offcial website.

**Comment by sampotts** [comment]
You're probably looking for this then...
https://github.com/sampotts/plyr#rangetouch
