### ISSUE TITLE
Is there a download button? If so, how to enable it (code)?

### ISSUE THREAD

**Issue by ferdiamg** [sampotts/plyr#1289]
I tried it adding it in the config:
```
%audio#testplayer{controls: "", "data-plyr-config" => "{ \"download\": true  }"}
  %source{ src: "https://www.link.to/xyz.mp3", type: "audio/mp3"}
```
I tried it with :controls "download", I tried it with JS, no download button appearing... No idea if there still is a download available or how to activate it, sadly theres nothing on it in the docs except for Issue#193 on here.

Thanks in advance!

**Comment by friday** [comment]
You can set `controls` to an array. Ex:

```js
const player = new Plyr('video', {controls: ['play-large', 'play', 'progress', 'current-time', 'mute', 'volume', 'captions', 'settings', 'download', 'pip', 'airplay', 'fullscreen']});
```
How you adapt that to your template language is your concern.

Seems like this is missing from the `controls` documentation, so please leave this open.

**Comment by friday** [comment]
My bad. It was only missing from the main page. It's documented [here](https://github.com/sampotts/plyr/blob/master/controls.md#using-default-controls).
