### ISSUE TITLE
Vimeo API failed to load TypeError

### ISSUE THREAD

**Issue by linhndbiz** [sampotts/plyr#1296]
I'm trying to setting up a basic player for vimeo, but it didn't work any more. Just loaded the poster and can't not playing (trigger or autoplay as well) or showing controls.

### Environment

- Browser: Chrome 
- Version: 71.0.3578.98 
- Operating System: Mac
- Version: Mojave

What i got in the content:
<img width="316" alt="screen shot 2018-12-21 at 3 09 28 pm" src="https://user-images.githubusercontent.com/45127121/50331783-7e7aee00-0532-11e9-9659-dbfc41e23a58.png">

The error message in console:
<img width="804" alt="screen shot 2018-12-21 at 3 04 38 pm" src="https://user-images.githubusercontent.com/45127121/50331732-4d022280-0532-11e9-9795-15aeaa20f8aa.png">

The simple code like this:
```
<link rel="stylesheet" href="https://cdn.plyr.io/3.4.7/plyr.css">
<script src="https://cdn.plyr.io/3.4.7/plyr.polyfilled.js"></script>

<div id="player" data-plyr-provider="vimeo" data-plyr-embed-id="76979871"></div>

<script>
const player = new Plyr('#player', {
debug: true,
});
player.play();
</script>
```

**Comment by linhndbiz** [comment]
Closed !!! I think it's conflicting with one of some my libs using in my project

**Comment by linhndbiz** [comment]
@friday could you pls have a look :)

**Comment by sampotts** [comment]
I doubt @friday will get time as he's stepped back a little. I'll try to when I can. Do you get this on https://plyr.io ?

**Comment by linhndbiz** [comment]
It works fine on https://plyr.io. You can have a quick look on my codepen: https://codepen.io/linhndbiz/pen/JwWRjW

**Comment by friday** [comment]
There is/was a similar older issue. Vimeos SDK link doesn't work with our SDK loader when requirejs is used. Hard to fix on our side, but we could perhaps overload module.exports.

And yeah, Sam is the creator and maintainer of Plyr. I helped out for a while but I hsve stepped back.

**Comment by Fabicon83** [comment]
Try this:

**Comment by linhndbiz** [comment]
Hi @Fabicon83 , where is _injectScript defined? doestn't existing on utils? or maybe you are using the older version?

**Comment by Fabicon83** [comment]
Yes, sorry i have improved this issue in plyr version 3.0.2.  Now i check the newest version of plyr's library.

**Comment by linhndbiz** [comment]
This code below seem works fine !!! Thanks for you suggestion @Fabicon83 

```
if (!is.object(window.Vimeo)) {
        loadScript(this.config.urls.vimeo.sdk);
        var vimeoTimer = window.setInterval(function () {
            if (is.object(window.Vimeo)) {
                window.clearInterval(vimeoTimer);
                vimeo.ready.call(_this);
            } else if ("function" == typeof define && define.amd) {
                require([_this.config.urls.vimeo.sdk], function (player) {
                    window.Vimeo = { Player: player };
                    vimeo.ready.call(_this);
                });
                window.clearInterval(vimeoTimer);
            }
        }, 50);
      }
```

**Comment by Fabicon83** [comment]
Oh good! :) Very nice then!
