### ISSUE TITLE
How to set up multiple players on same page? 

### ISSUE THREAD

**Issue by alongcamerissa** [sampotts/plyr#1301]
Hi,

I would greatly appreciate some help here, I am just starting out with very limited beginner's knowledge of JavaScript and need to know precisely a step-by-step of how to make multiple video players on the same page, each with a different video source file and poster image.

Thank you so much in advance,
Rissa

### Expected behaviour: Multiple players on one page of different video files, currently using this script to activate the player:

<div class="container">												
<video poster="posterfile.jpg" id="player" playsinline controls>
<source src="sourcefile1.mp4" type="video/mp4">
<source src="sourcefile1.webm" type="video/webm"></video></div>

### Actual behaviour

I add the same script again further down the page with a different source file and poster image, and the second player does not appear on the page.

### Steps to reproduce

Default FTP upload install of Plyr, have 1 working player 
### Environment

- Browser: Chrome
- Version: 71.0.3578.98
- Operating System: Windows
- Version: 10

### Link to where the bug is happening
http://www.rogerhodgson.com/epk/documents/spotsNEW.html

**Comment by sampotts** [comment]
Check the docs 👍 

https://github.com/sampotts/plyr#setting-up-multiple-players

**Comment by alongcamerissa** [comment]
Is it possible to have a demo page for help?

**Comment by JFSilvaBr** [comment]
@alongcamerissa demo video for your issue [Plyr Video Demo issue 1301](https://youtu.be/MTezfkE2KpE)
