### ISSUE TITLE
RTMP Support

### ISSUE THREAD

**Issue by ismhdez** [sampotts/plyr#1309]
It’s possible to use a RTMP streaming? from url rtmp://XXXXXXXXX/app

**Comment by abishekrsrikaanth** [comment]
Any plans on supporting this?

**Comment by abishekrsrikaanth** [comment]
@ismhdez @sampotts any reason why this was closed? Is there going to RTMP support?

**Comment by ismhdez** [comment]
You actually have it, just use another plugin with plyr.

**Comment by abishekrsrikaanth** [comment]
@ismhdez, can you please clarify this. I am not sure what plugin you are referring to?

**Comment by ismhdez** [comment]
Search for HLS or something and include it on Plyr player
