### ISSUE TITLE
A little improvement of events for video analytics

### ISSUE THREAD

**Issue by levi0214** [sampotts/plyr#1313]
I want to analyze the playback of each video, **including which parts were played and which parts were skipped.** But I found it a bit difficult.

The current situation is that when the user clicks on the progress bar, a 'pause' event is triggered, followed by a 'play' event. In other words, the following two cases trigger same events:

> 1. The user directly clicks the progress bar to jump to 10:00
> 2. The user normally plays to 10:00, pauses for a while, and then resumes playback.

Both of these situations trigger a pause event (at 10:00) and a play event(at 10:00).

Here's my suggestion and a small change can meet my needs: 

When the user jumps from 5:00 to 10:00
Current events:                _Pause **(at 10:00)** + Play (at 10:00)_    
My suggestion:    _Pause **(at 5:00)** + Play (at 10:00)_

**Comment by levi0214** [comment]
`seeking` and `seeked` can't solve the problem.
When the user jumps from 5:00 to 10:00, these events are triggered:

`pause` (at 10:00)
`play` (at 10:00)
`seeking` (at 10:00)
`seeked` (at 10:00)

I still can't figure out which part the user viewed or skipped

**Comment by sampotts** [comment]
Sure you can. Why can't you do something like this? 

```javascript
const player = new Plyr();
let lastTime = player.currentTime;

player.on('timeupdate', () => { 
    lastTime = player.currentTime;
});

player.on('seeked', () => {
    console.log(lastTime, player.currentTime);
});
```

**Comment by levi0214** [comment]
Oh, it's a good idea 💯 Thank you!

Btw, do you have any suggestions for detecting a unique played event? 

I use the `play` events to calculate video played times. But the `play` event will trigger many times during video playback, so I have to calculate the unique played times. A better way I can think of is to send data to my server only when the `play` event is triggered for the first time. 

Is there a better way?

**Comment by levi0214** [comment]
> Sure you can. Why can't you do something like this?
> 
> ```js
> const player = new Plyr('video');
> let lastTime = player.currentTime;
> 
> player.on('timeupdate', () => { 
>     lastTime = player.currentTime;
> });
> 
> player.on('seeked', () => {
>     console.log(lastTime, player.currentTime);
> });
> ```

Maybe you can put some similar code snippets together in the wiki, just like best practices. It's helpful to developers.

**Comment by sampotts** [comment]
Thanks I'll do that. I'm going to close this one 👍
