### ISSUE TITLE
Allow to customize Vimeo URL params

### ISSUE THREAD

**Issue by ilearnio** [sampotts/plyr#1316]
I need to get rid of the default blue background that vimeo iframe has. By default Vimeo's embedded iframe is transparent, so I can set any custom background behind it, but in Plyr there is a hardcoded URL parameter `&transparent=0` which I can't modify without touching Plyr's core. It adds this blue background. Could you please provide a way to override this options object https://github.com/sampotts/plyr/blob/a19ad6903855d1bb9585c0e8e4b97e65eff2c85a/src/js/plugins/vimeo.js#L99

**Comment by sampotts** [comment]
As of v3.5.0 this is now possible 👍
