### ISSUE TITLE
Vi - cannot load script of ads

### ISSUE THREAD

**Issue by codevirtuel** [sampotts/plyr#1323]
### Expected behaviour
Expected viewing an ad on the video player

### Actual behaviour
The video start without loading an ad and showing errors in the console

### Steps to reproduce
1. Go the the web-page link below
2. Open browser console
3. Play the video
4. View errors in the console

### Environment

- Browser: Firefox
- Version: 64.0.2 (64 bits)
- Operating System: Windows 10
- Version: 1803

### Console errors (if any)
![vi](https://user-images.githubusercontent.com/12038808/51785805-f359cd00-215b-11e9-988f-87ff171f92b9.PNG)

### Link to where the bug is happening
Web page that user plyr with vi : https://osureplayviewer.xyz/view.php?id=5c460feb1fa96

**Comment by sampotts** [comment]
I've pointed the VI guys to this. It looks like the ads on https://plyr.io have stopped working too.

**Comment by codevirtuel** [comment]
Okay, thx for the reply 😄

**Comment by codevirtuel** [comment]
Now the request is showed on vi.ai and the ad seem to load on the website but It failed (like in the first screen)

**Comment by MrDuckBoy** [comment]
The same here, not using any adblocker, console says "URI invalid Failed to load the media resource"

**Comment by sampotts** [comment]
Your site needs to be approved by Vi guys. It's not an issue with Plyr. Please contact Vi and they will be happy to assist. 👍
