### ISSUE TITLE
safari "This site will not work without camera/microphone access."

### ISSUE THREAD

**Issue by hktalent** [sampotts/plyr#1332]
mac os safari
display:
"This site will not work without camera/microphone access."
can not work,why?
![image](https://user-images.githubusercontent.com/18223385/52161530-1d356580-2701-11e9-96e7-ade937073eb0.png)
![image](https://user-images.githubusercontent.com/18223385/52161532-27effa80-2701-11e9-818d-b423a794efc8.png)

**Comment by sampotts** [comment]
No idea but it’s nothing to do with Plyr. We don’t request access to that. Hope you find the cause.
