### ISSUE TITLE
Pure CSS icons

### ISSUE THREAD

**Issue by doublex** [sampotts/plyr#1333]
Replace SVG sprites with pure CSS icons:
https://saeedalipoor.github.io/icono/
https://viglino.github.io/iconicss/?icon=home&page=icons

**Comment by sampotts** [comment]
Explain the benefits and I might consider it but SVGs are designed for the job.

**Comment by doublex** [comment]
It is quite simple to add (only a few CSS rules are required).
I love CSS icons (where possible) - but from a perspective point there is no benefit.

**Comment by sampotts** [comment]
That settles that then 👍
