### ISSUE TITLE
Use i.ytimg.com instead of img.youtube.com

### ISSUE THREAD

**Issue by theel0ja** [sampotts/plyr#1335]
`img.youtube.com` sends third-party cookies.

![](https://user-images.githubusercontent.com/5832930/52378607-0c1d8900-2a60-11e9-8a12-a87268a686f8.png)

**Comment by sampotts** [comment]
Happy to accept a PR for this.

**Comment by sampotts** [comment]
This is in `develop` now. I'll release shortly once I fix a few small bugs.

**Comment by sampotts** [comment]
Fixed in v3.5.3 👍
