### ISSUE TITLE
Not show quality selector with hls

### ISSUE THREAD

**Issue by tamdao** [sampotts/plyr#1339]
I have tried to use your player into my project. It's worked well. But I have an issue with hls, when I tried to load the hls file like the example here https://codepen.io/pen?template=oyLKQb

The player can play the hls, but the quality settings is not show. How can I config for show the quality selector?

Thanks

**Comment by tamdao** [comment]
@sampotts

**Comment by sampotts** [comment]
Duplicate of https://github.com/sampotts/plyr/issues/1118 - Please search next time 👍
