### ISSUE TITLE
Ads do not play audio

### ISSUE THREAD

**Issue by brandonlui19** [sampotts/plyr#1348]
### Expected behaviour
The ad plays with audio or has a unmute button
### Actual behaviour
The ad plays muted, when you inspect element and get the actual mp4 file and open it, it has audio
### Steps to reproduce
Refresh the official demo Plyr.io page https://plyr.io without an adblocker until you get an ad
### Environment

- Browser:Safari
- Version: 12.0.3
- Operating System: macOS Mojave
- Version:10.14.3 (18D109)

**Comment by sampotts** [comment]
Yep. This is expected behaviour and is controlled by Vi. Cheers 👍

**Comment by brandonlui19** [comment]
> Yep. This is expected behaviour and is controlled by Vi. Cheers 👍

Maybe in a future version, but is there a way to implement a unmute button like on the demo vi.ai page? 
http://demo.vi.ai/BBCSportDemo1.html
https://imgur.com/a/mpJgzg2

**Comment by sampotts** [comment]
You'd have to ask them. I've suggested it but they wanted muted ads. Up to them really.
