### ISSUE TITLE
3.5.0 Cannot set captions active on start

### ISSUE THREAD

**Issue by Rafostar** [sampotts/plyr#1352]
On latest 3.5.0 version captions are not automatically enabled on player load after setting below player args.
```
captions: { active: true, language: 'auto', update: false }
```

Tested on both Chrome 72 and Firefox 63 on Linux

Can be observed on this demo:
* HTML5 video: https://codepen.io/pen?template=bKeqpr

UPDATE: It seems browser cache is involved. When you visit player web page in "incognito" captions are always disabled. When visiting through normal browsing session captions are set to the last state they were set previously on that website (instead of being forced to active).

**Comment by sharq1** [comment]
Same here, Plyr 3.4.7, tested on Chrome on Windows. Tried different approaches, none worked.

**Comment by sampotts** [comment]
Check your local storage. The users config takes preference over the player config - i.e. if they disable captions then the local storage stores that state. It looks fine for me on https://plyr.io where the captions are active by default.

**Comment by sharq1** [comment]
Thanks for reply @sampotts 
I think that's the problem - is it possible to make the config override users local storage setting?

**Comment by Rafostar** [comment]
> The users config takes preference over the player config

Is this behaviour new in 3.5 series? In 3.4 player config was taking preference over local settings.
I tried testing on other linux PC and have the same problem (even when running OS from live iso).
On [https://plyr.io](https://plyr.io) subs are always disabled for me (after enabling them and refreshing page they are disabled again). In my case this problem happens on linux (have not tested on win or mac).

Is it possible that local storage misbehaves on linux systems?

**Comment by sampotts** [comment]
@sharq1 That would make the user config a bit superfluous if we ignored it. It is possible to disable it though if you wanted to do that. 

@Rafostar It's been like this since v2 or maybe even earlier. I'll check on linux and see.

**Comment by Rafostar** [comment]
I tested it today on latest fedora linux and the issue no longer happens. I still have it on few of my own PCs (all old install) but it doesn't happen on fresh installations of newest distros. Do not know what the cause is (clearing cache does not work and happens on multiple browsers), but if it no longer happens on fresh installs, I will mark this as solved and you @sampotts do not have to waste your time testing it.

> That would make the user config a bit superfluous if we ignored it. It is possible to disable it though if you wanted to do that.
> It's been like this since v2 or maybe even earlier. I'll check on linux and see.

Thanks for the tip, and clearing this up.

BTW: Awesome job with creating Plyr. I am using it for media streaming linux extension and it works great. Thank You!

**Comment by daymien** [comment]
Hey @sampotts, fyi this issue remains if storage is disabled `{ enabled: false, key: 'plyr' }` caption jumps back to disabled after selection. Tested on plyr v3.7.3
