### ISSUE TITLE
3.5.0 fails minification with uglify-js (ES6 symbols)

### ISSUE THREAD

**Issue by c0bra** [sampotts/plyr#1353]
### Expected behaviour

Successful minification

### Actual behaviour

Broken minification

### Steps to reproduce

```
npm install -g uglify-js
npm install plyr@3.5.0
cd node_modules/plyr/dist
uglifyjs plyr.min.js
```

### Console errors (if any)

```
Parse error at plyr.min.js:1,1390
w new TypeError("Invalid attempt to spread non-iterable instance")}()}const o={a
                                                                      ^
ERROR: Unexpected token: keyword (const)
```

It looks like starting with v3.5.0 ES6 symbols like `const` are showing up in the output. This is causing our build process to fail as it uses uglify-js which can't handle ES6. 

Is this intended? I guess maybe I need to manually use the polyfilled output instead?

**Comment by sampotts** [comment]
I'd recommend using [terser](https://github.com/terser-js/terser) these days but this looks to be a genuine issue. Babel doesn't seem to be transpiling the `const` to `var` for whatever reason. I had a very quick look but couldn't find anything obvious. Will have another look later.

**Comment by sampotts** [comment]
Also, I would use the unminified version if you want to minify it yourself - `plyr.js`.

**Comment by electerious** [comment]
The dist JS contains ES6+ features. This wasn't the case before and is a breaking change for most workflows.

The package `main` entry should probably link to a < ES6 version while the `jsnext:main` should link to the version containing: https://github.com/sampotts/plyr/blob/master/package.json#L9

**Comment by c0bra** [comment]
@sampotts yea I would use something modern for minification but unfortunately it's an old project and the building tooling will take more time to upgrade than we can afford atm.

I'll try importing `plyr.js` explicitly.

**Comment by sampotts** [comment]
Yep this is a bug as I’ve said. Any help is appreciated. I’ve taken a quick look and there wasn’t a quick fix. I’ll look again when I get some time. Probably this weekend.

**Comment by sampotts** [comment]
This should now be resolved. It was due to `node_modules` being excluded from the Babel process and a dependency using ES6 syntax.
