### ISSUE TITLE
Poster is loaded twice

### ISSUE THREAD

**Issue by levi0214** [sampotts/plyr#1355]
Just open the official demo [https://plyr.io](https://plyr.io/), and you'll find **the poster image loaded twice as below**. I am not sure if this is necessary?

![screenshot](https://user-images.githubusercontent.com/5380149/53243740-cdd0cc80-36e3-11e9-8828-d4c8ace32e10.png)

**Comment by sampotts** [comment]
Yep it is unfortunately as we display it in a custom element. The only other solution would involve removing the progressive enhancement. I don’t think removing the `poster` attribute with JavaScript would abort the initial load. I doubt it.

**Comment by levi0214** [comment]
Haha, OK, thank you.

**Comment by dev7ch** [comment]
maybe you could append the image to the custom element from media element maybe with sth like

```
let sourceImage = document.createElement('img'),
     imgContainer = document.getElementById("custom-element");
 sourceImage.src = "[some img url or cloning loaded poster img]";
 imgContainer.appendChild(sourceImage);

 function cloneImg(){
     imgContainer.appendChild(sourceImage.cloneNode(true));
 }

```

not tested ;)

**Comment by sampotts** [comment]
If we had access to the shadow DOM then we could clone the contents yep but its not possible.

**Comment by sampotts** [comment]
Closing this one for now as there's not much we can do.
