### ISSUE TITLE
3.5.1 Video Caption & Selector not working

### ISSUE THREAD

**Issue by lyricsbd** [sampotts/plyr#1357]
Please Solve this issue,

**Comment by sampotts** [comment]
Please give more details then?

**Comment by sampotts** [comment]
Re-open using the template

**Comment by lyricsbd** [comment]
sorry i am not mentioned YouTube dear,
here a link work video quality selector https://xdae.github.io/react-plyr/?selectedKind=React%20Plyr&selectedStory=Video%20with%20all%20Controls&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel

but its old version can you fix this latest version

**Comment by sampotts** [comment]
Wrong repo. I don’t work on that one.

**Comment by lyricsbd** [comment]
but he used your plyr script to , view source can u fix that yours @sampotts
