### ISSUE TITLE
3.5.1 youtube Video Caption & quality Selector not working 

### ISSUE THREAD

**Issue by lyricsbd** [sampotts/plyr#1358]
hello dear,
here a link work video quality selector https://xdae.github.io/react-plyr/?selectedKind=React%20Plyr&selectedStory=Video%20with%20all%20Controls&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel

but its old version can you fix this latest version

**Comment by lyricsbd** [comment]
I have also found version a 3.2.4 work youtube quality selector smoothly, then why you remove that update version 3.5.1

link:  https://codepen.io/GiovannaVillanuevaRodriguez/pen/djwOaE

**Comment by sampotts** [comment]
The selection was removed for YouTube. The API never worked correctly (a bug at YouTube end) so it was removed.

**Comment by lyricsbd** [comment]
see this demo its working bro old version https://codepen.io/GiovannaVillanuevaRodriguez/pen/djwOaE
