### ISSUE TITLE
Plyr ratio with Vimeo videos

### ISSUE THREAD

**Issue by meinhard-meintjes** [sampotts/plyr#1366]
Hi guys,

I'm not sure if this is a bug or if I just don't understand what ratio should be doing exactly and whether I'm using it in the correct way. For me the ratio config option isn't respected with Vimeo, or at least initially, but then it seems to be recalculated after certain events. Behaviour explained below. I've also tried multiple older versions of the plugin. I would appreciate any help. Thank you!
 
### Expected behaviour
A Vimeo video within a container that applies the given ratio e.g 16:5, vertically centered.

### Actual behaviour
A container that eventually fits the original Vimeo videos aspect ratio, instead of the one given in the config.

### Steps to reproduce
Initialise a minimalist plyr instance with an embedded vimeo video, add any ratio config that's not 16:9.
The player initially takes on the ratio, but then reloads with its original aspect ratio after certain events.
Events I've observed that change the ratio: ratechange and timeupdate.
Youtube videos seem to work.

### Environment

- Browser: Chrome
- Version: 72
- Operating System: Windows
- Version: 10

### Console errors (if any)
-

### Link to where the bug is happening
http://jsfiddle.net/b3a0tewr/4/

**Comment by sampotts** [comment]
I've made some changes in 3.5.3 where the `ratio` option, if specified, will take priority over the ratio information provided from the Vimeo SDK. It also allows you to fix the ratio for HTML5 videos too. 

https://github.com/sampotts/plyr/#options

There's also a getter (and setter) which means you can update the ratio after the initial setup.

**Comment by samhibberd** [comment]
@sampotts i'm still running into issue with 3.5.3, see:

https://jsfiddle.net/samhibberd/zgx9rdvn/2/

https://github.com/sampotts/plyr/issues/339#issuecomment-484069735

**Comment by samhibberd** [comment]
@sampotts Any thoughts on this? Or a point in the right direction if I am missing something obvious?
