### ISSUE TITLE
hls.s quality switcher manually

### ISSUE THREAD

**Issue by Ali-Talib-jabar** [sampotts/plyr#1372]
Hi guys, I have three links, the first is 360-720, the second is 360 and the third is 720, how can I switch between them?

The first link Auto-quality: http://192.168.120.230:1935/bein1/2_adaptive.m3u8

The second link is in 360 quality: http://192.168.120.230:1935/bein1/2_sd.m3u8

The third link with 720 quality: http://192.168.120.230:1935/bein1/2_hd.m3u8

I use this code 
```
const auto  = `http://${this.channel.server}:${this.channel.hlsport}/${this.channel.app}/${this.channel.streamname}${this.channel.adaptive}.m3u8`;
const sd    = `http://${this.channel.server}:${this.channel.hlsport}/${this.channel.app}/${this.channel.streamname}_sd.m3u8`;
const hd    = `http://${this.channel.server}:${this.channel.hlsport}/${this.channel.app}/${this.channel.streamname}_hd.m3u8`;

const video = document.querySelector('video');

// For more options see: https://github.com/sampotts/plyr/#options
// captions.update is required for captions to work with hls.js
const player = new TVPlayer(video, {
    settings: ['quality', 'speed', 'loop'],
    controls: [ 'play-large', 'restart', 'rewind', 'play', 'fast-forward',  'progress',  'current-time', 'duration', 'mute', 'volume',  'settings', 'pip', 'airplay', 'fullscreen',],
    storage:{
        enabled: true,
        key: 'plyr'
    },
    tooltips: {
        controls: true,
        seek: true
    },
    i18n: {
        restart: 'أعادة تشغيل',
        rewind: 'تراجع {seektime} ثواني',
        play: 'تشغيل',
        pause: 'إيقاف',
        fastForward: 'تقدم {seektime} ثواني',
        seek: 'طلب',
        played: 'قيد التشغيل',
        buffered: 'مخزنة',
        currentTime: 'الوقت الحالي',
        duration: 'المدة الزمنية',
        volume: 'الصوت',
        mute: 'كتم',
        unmute: 'إالغاء الكتم',
        enableCaptions: 'تشغيل الترجمة',
        disableCaptions: 'تعطيل الترجمة',
        enterFullscreen: 'ملئ الشاشة',
        exitFullscreen: 'الخروج من وضع ملئ الشاشة',
        frameTitle: 'مشاهدة {title}',
        captions: 'الرجمة',
        settings: 'الأعدادات',
        speed: 'السرعة',
        normal: 'طبيعي',
        quality: 'الجودة',
        pip: 'التشغيل خارج المتصفح',
        download: 'تحميل الفيلم',
        loop: 'تكرار',
        start: 'بدء',
        end: 'النهاية',
        all: 'الكل',
        reset: 'أعاد التشغيل',
        disabled: 'معطل',
        advertisement: 'اعلان',
    },
    iconUrl: require('plyr/dist/plyr.svg'),
    disableContextMenu: true,
    enabled: true,
    debug:false,
});


if (!Hls.isSupported()) {
    video.src = auto;
} else {
    // For more Hls.js options, see https://github.com/dailymotion/hls.js
    const hls = new Hls();
    hls.loadSource(auto);
    hls.attachMedia(video);
    window.hls = hls;

}

// Expose player so it can be used from the console
window.player = player;
```

  It's a success with me, but I can not switch between them. I checked this source (https://github.com/video-dev/hls.js/blob/master/docs/API.md#quality-switch-control-api) but did not I could find a solution. Please Help

**Comment by sampotts** [comment]
There are other issues raised related to this. Please search next time. 

Sam

**Comment by Ali-Talib-jabar** [comment]
> There are other issues raised related to this. Please search next time. Sam
> […](#)
> On 6 Mar 2019, at 2:59 am, Ali Talib ***@***.***> wrote: Hi guys, I have three links, the first is 360-720, the second is 360 and the third is 720, how can I switch between them? The first link Auto-quality: http://192.168.120.230:1935/bein1/2_adaptive.m3u8 The second link is in 360 quality: http://192.168.120.230:1935/bein1/2_sd.m3u8 The third link with 720 quality: http://192.168.120.230:1935/bein1/2_hd.m3u8 I use this code const auto = `http://${this.channel.server}:${this.channel.hlsport}/${this.channel.app}/${this.channel.streamname}${this.channel.adaptive}.m3u8`; const sd = `http://${this.channel.server}:${this.channel.hlsport}/${this.channel.app}/${this.channel.streamname}${this.channel.adaptive}.m3u8`; const hd = `http://${this.channel.server}:${this.channel.hlsport}/${this.channel.app}/${this.channel.streamname}.m3u8`; const video = document.querySelector('video'); // For more options see: https://github.com/sampotts/plyr/#options // captions.update is required for captions to work with hls.js const player = new TVPlayer(video, { settings: ['quality', 'speed', 'loop'], controls: [ 'play-large', // The large play button in the center http://ubox.alitralib.com/storage/files/movies/movies/foreign/Mary_Poppins_Returns_19010904.mp4 'restart', // Restart playback 'rewind', // Rewind by the seek time (default 10 seconds) 'play', // Play/pause playback 'fast-forward', // Fast forward by the seek time (default 10 seconds) 'progress', // The progress bar and scrubber for playback and buffering 'current-time', // The current time of playback 'duration', // The full duration of the media 'mute', // Toggle mute 'volume', // Volume control 'settings', // Settings menu 'pip', // Picture-in-picture (currently Safari only) 'airplay', // Airplay (currently Safari only) 'fullscreen', // Toggle fullscreen ], storage:{ enabled: true, key: 'plyr' }, captions: { active: true, language: "ar", }, tooltips: { controls: true, seek: true }, i18n: { restart: 'أعادة تشغيل', rewind: 'تراجع {seektime} ثواني', play: 'تشغيل', pause: 'إيقاف', fastForward: 'تقدم {seektime} ثواني', seek: 'طلب', played: 'قيد التشغيل', buffered: 'مخزنة', currentTime: 'الوقت الحالي', duration: 'المدة الزمنية', volume: 'الصوت', mute: 'كتم', unmute: 'إالغاء الكتم', enableCaptions: 'تشغيل الترجمة', disableCaptions: 'تعطيل الترجمة', enterFullscreen: 'ملئ الشاشة', exitFullscreen: 'الخروج من وضع ملئ الشاشة', frameTitle: 'مشاهدة {title}', captions: 'الرجمة', settings: 'الأعدادات', speed: 'السرعة', normal: 'طبيعي', quality: 'الجودة', pip: 'التشغيل خارج المتصفح', download: 'تحميل الفيلم', loop: 'تكرار', start: 'بدء', end: 'النهاية', all: 'الكل', reset: 'أعاد التشغيل', disabled: 'معطل', advertisement: 'اعلان', }, iconUrl: require('plyr/dist/plyr.svg'), disableContextMenu: true, enabled: true, debug:false, }); if (!Hls.isSupported()) { video.src = auto; } else { // For more Hls.js options, see https://github.com/dailymotion/hls.js const hls = new Hls(); hls.loadSource(auto); hls.attachMedia(video); window.hls = hls; } // Expose player so it can be used from the console window.player = player; It's a success with me, but I can not switch between them. I checked this source (https://github.com/video-dev/hls.js/blob/master/docs/API.md#quality-switch-control-api) but did not I could find a solution. Please Help — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Ali-Talib-jabar** [comment]
@sampotts This means that there is no solution and I have to replace the video player, or is there another way

**Comment by sampotts** [comment]
Please use https://github.com/sampotts/plyr/issues/1741
