### ISSUE TITLE
Player loads the browser default until you refresh.

### ISSUE THREAD

**Issue by mehrdadema** [sampotts/plyr#1373]
### Environment

- Browser:
- Version:
- Operating System:
- Version:

**Comment by mehrdadema** [comment]
The issue is that when I implement the player, it works and everything but at first load of the page it is not active. You have to refresh once to see the new player otherwise it only loads the browser default. I made sure JS codes load before the player but still the same behaviour. Not sure what's happening. Thanks

**Comment by sampotts** [comment]
This is an issue outside of Plyr. See the docs and examples for the correct implementation. 👍
