### ISSUE TITLE
Possible to remove existing video player controls on any site and replace with Plyr?

### ISSUE THREAD

**Issue by wpatter6** [sampotts/plyr#1378]
I'm building a chrome extension that will help with accessibility on pages, and the part that's relevant to you is that I'm using plyr to try to have consistent, accessible video controls on every web page.  However, when I do this, for example on Hulu, their custom controls are displayed along with the plyr controls.

I'm wondering, would it be possible to remove all custom video controls, including even another instance of plyr (I see similar behavior from my extension on plyr.io), from _any_ website and replace them with plyr? I know this is likely not possible because there's no standard way of setting up custom controls (one of the problems I'm trying to solve with my extension!) but I figured I'd see if there was some option I was missing.

Thanks.

**Comment by sampotts** [comment]
It would be pretty tricky as you'd need to know the structure of a third party player to know which DOM elements to remove. Not sure I can help with this one, sorry.

**Comment by WatchSoMuch** [comment]
Or you can just convert the html videos that has controls enabled and do not touch the others with custom players (custom players have the video controls off)
