### ISSUE TITLE
player.seeking is false when seeked

### ISSUE THREAD

**Issue by uzervlad** [sampotts/plyr#1379]
### Expected behaviour

When the music is seeked, `pause` event is emitted but `player.seeking` is `false`

### Actual behaviour

`player.seeking` should be true

### Environment

- Electron 4.0.7
- Version: latest
- Operating System: Windows 8.1

```js
player.on('pause', event => {
    console.log(player.seeking); // returns false even if seeking
});
```

**Comment by sampotts** [comment]
Is this an issue with native HTML5 player too? What media type did you see this issue with?

**Comment by uzervlad** [comment]
No, native player returns `true` in `.seeking`. I used `mp3` in both cases.

**Comment by sampotts** [comment]
Hard to believe. For HTML5 we’re simply passing the value of `media.seeking` on. You can check the source.

**Comment by sampotts** [comment]
Still can't replicate. I've [created a demo](https://jsfiddle.net/L0176ags/3/). As you can see, both return `true` while seeking.
