### ISSUE TITLE
Prevent videos from pre-loading until inside the viewport

### ISSUE THREAD

**Issue by ableslayer** [sampotts/plyr#1381]
I have several videos on my page and I'm using [Preloadme](https://github.com/niklausgerber/PreLoadMe) to preload my content. The problem is the page takes a while to load since it seems that it's preloading the videos in the background (saw it via chrome dev tools under Network). The landing page itself (the first section on top) doesn't have any videos. It's the section after that.

Is there a way to stop the videos from preloading so that the page starts fast? and then when you are in the viewport and you play the video, that's the only time it loads. My videos are very small in size, it's just that there's a lot of them in the page (7 in total) making my page loads slow initially.

Btw, I tried it with and without `preload `and `preload="auto"`. Same thing happens.

**Comment by sampotts** [comment]
Try `preload="none"` - [preload attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-preload) 👍
