### ISSUE TITLE
play api on Safari (mac) not play

### ISSUE THREAD

**Issue by electroheadfx** [sampotts/plyr#1385]
### Expected behaviour
Auto play on plyr creation when it is ready

### Actual behaviour
See error bellow.
The video is not played, I need to click for play.

### Steps to reproduce

HTML:
<div id="plyr-instance-1" data-plyr-provider="vimeo" data-plyr-embed-id="321528476"></div>

JS:
     options = {
                 fullscreen: {
                    enabled: fullscreen
                 }
      };
              players = Plyr.setup('#plyr-instance-1', options);
              if ( players[0] !== undefined ) {
                  players[0].on('ready', function(event) {
                    var video = event.detail.plyr;
                    video.play();
               });
        }

### Environment
- Browser: Safari
- Version: 12.0.3
- Operating System: macOS
- Version: 10.12.6

### Console errors (if any)
Unhandled Promise Rejection: PlayInterrupted: The play() request was interrupted by a call to pause()

### Link to where the bug is happening
local for now

**Comment by electroheadfx** [comment]
The plyr play work when the page was already loaded. It doesn't play when page open directly the video for play. Its like an auto play So I guess Apple block that ? I thought it was just for iOS devices.

**Comment by electroheadfx** [comment]
need Investigating more before to report ...

**Comment by while0pass** [comment]
The same issue for Safari 11.1.2.

**Comment by while0pass** [comment]
https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/
