### ISSUE TITLE
Demo app - UWP JavaScript (WebView/Edge) - fails for YouTube and Vimeo

### ISSUE THREAD

**Issue by mediabuff** [sampotts/plyr#1386]
Create a javascript UWP app in Visual Studio. HTML5 and Audio works. Clicking on youtube or vimeo does not play.

**Comment by sampotts** [comment]
I wouldn't even know where to start on this one.

**Comment by mediabuff** [comment]
do you have Visual Studio ? or any tool set that let you build Windows 10 Javascript apps ?

**Comment by mediabuff** [comment]
![windows10JSapp](https://user-images.githubusercontent.com/5080114/54574694-b4136400-49c7-11e9-8e24-812e2ab17a23.PNG)

**Comment by mediabuff** [comment]
When I click youtube or vimeo, that's what I get

**Comment by jonhue** [comment]
Most likely because these sources aren't allowed origins...

**Comment by mediabuff** [comment]
how would you fix it ? Works in regular Edge browser.

**Comment by mediabuff** [comment]
You may be right. Let me try based on pointers here: 

https://deletethis.net/dave/
https://deletethis.net/dave/2017-06/Application+Content+URI+Rule+effects

**Comment by sampotts** [comment]
I don't think this is an issue with Plyr itself and not sure I can offer any support fixing it. Good luck with it!
