### ISSUE TITLE
Just play button

### ISSUE THREAD

**Issue by ponzo-oh** [sampotts/plyr#1388]
Dear Community,

i am very new to plyr and coding but i apprecheate this topic.
This might be a very simple question to you, but I already worked 2h on it:

**I just want to embed a youtube- or vimeo video link and just show a play button, nothing else.
Didnt manage to find the right way to write it.**

(Additional: In original vimeo embed options there is a possibility to make the size "responsive". Would be great if the code has this as well, but no must.)

Thank you for help!

**Comment by GalacticSun** [comment]
+1

**Comment by julmot** [comment]
`player.play()` also didn't work for me.

**Comment by julmot** [comment]
@sampotts Do you know a working demo with play action using the YouTube iframe embed approach?

This demo doesn't work: https://jsfiddle.net/ktdhxvj9/1/

**Comment by sampotts** [comment]
@julmot Totally the wrong place to bring up your issue - I've removed your comments.

**Comment by sampotts** [comment]
This is possible. Just specify the controls option as follows:

```javascript
const player = new Plyr(selector, {
    controls: ['play-large'],
});
```
