### ISSUE TITLE
Audio - Play from where you left off

### ISSUE THREAD

**Issue by msahajwani** [sampotts/plyr#1389]
Is there a way for the player to remember where a user left off, so that I can pause the audio which I was listing to and come back to it to continue at the same point where I had left it.

**Comment by sampotts** [comment]
Not built into the player but you could use local storage outside of the player to store a value on the `progress` event and then restore that next time.

**Comment by sampotts** [comment]
Thinking about this more I think it'd be pretty tricky to build into the player itself and probably something that should be built into the application _including_ the player.
