### ISSUE TITLE
Unable to use autoplay for YouTube

### ISSUE THREAD

**Issue by joedawson** [sampotts/plyr#1390]
### Expected behaviour

YouTube video to autoplay

### Actual behaviour

YouTube video does not autoplay

### Steps to reproduce

I have recently attempted to upgrade from version 2.0.18 of Plyr to 3.5.1 since I'm a little behind. I have followed the documentation but haven't had much luck.

My previous version had autoplay functionality and is quite crucial to keep that functionality.

Documentation highlights that when using the `autoplay` query parameter (for YouTube) it will be mapped automatically to config however when I debug I see the autoplay option is set to `false` in the console.

I've tried various ways of trying to autoplay, using the progressively enhanced method first:

```html
<div class="plyr__video-embed" id="player">
    <iframe src="https://www.youtube.com/embed/GLdF0r5STf8?origin=https://urbanforefront.valet&amp;iv_load_policy=3&amp;modestbranding=1&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;enablejsapi=1&amp;autoplay=1"
        allowfullscreen
        allowtransparency
        allow="autoplay"
    ></iframe>
</div>
```
```js
const player = new Plyr('#player', {
    debug: true
});
```

I've also tried to set the option when creating a new Plyr.

```js
const player = new Plyr('#player', {
    autoplay: true,
    debug: true
});
```

This unfortunately doesn't work either.

Any ideas? I'd love to update to take advantage of all the improvements that's been made since the version I'm currently on but have hit a wall.

### Environment

- Browser: Chrome
- Version: 73.0.3683.86
- Operating System: macOS
- Version: 10.14.3

### Link to where the bug is happening

https://codepen.io/anon/pen/QozZGp

**Comment by muuvmuuv** [comment]
Same issue. I've also tried ` youtube.autoplay: true`. Website is allowed to autoplay via Browser settings.

**Comment by jmverges** [comment]
Same here

**Comment by jmverges** [comment]
https://github.com/sampotts/plyr/issues/955

**Comment by JoeDawson** [comment]
Whilst #955 may be somewhat true, I don't think it is the cause. I am using an older version of Plyr on my website that autoplays YouTube videos absolutely fine (2.0.18).

**Comment by sampotts** [comment]
Closing this - will manage it in https://github.com/sampotts/plyr/issues/1185
