### ISSUE TITLE
Size of frame video was change and appear effect stretch when change poster and source url

### ISSUE THREAD

**Issue by hoangdangduy** [sampotts/plyr#1391]
Version plyr use is 3.5.2

When I click a image on right panel, source and poster of plyr video will change but size of frame video also change and appear effect stretch image to height (see gif was attached)

I only use this code to change source and poster, and don't use css.

```
initPlayer: function (data) {
	this.player.source = {
		type: 'video',
		title: 'Example title',
		sources: [
			{
				src: data.googleVideoUrl,
				type: 'video/mp4',
				size: 480,
			},
			{
				src: data.googleVideoUrl,
				type: 'video/mp4',
				size: 720,
			}
		],
		poster: data.googleVideoThumbnail,
		hideControls: true,
		blankVideo: 'https://cdn.plyr.io/static/blank.mp4',
		quality: { default: 480, options: [720, 480] },
		loop:{ active: false },
		ads: { enabled: false, publisherId: '' }
	};
},
```

html code

```
<video id="player" playsinline controls>
</video>
```

code to init player plyr run once

`this.player = new Plyr('#player', {});`

![plyr](https://user-images.githubusercontent.com/8912039/54867683-996d3080-4db5-11e9-86f1-a7fb2a8783c1.gif)

**Comment by sampotts** [comment]
You can now fix the ratio of the player which should solve this. 
https://github.com/sampotts/plyr/#options
There's also a getter (and setter) which means you can update the ratio after the initial setup.
