### ISSUE TITLE
Disable audio download button

### ISSUE THREAD

**Issue by Generalomosco** [sampotts/plyr#1392]
Is there any option i can disable the download button from the audio player menu??

**Comment by sampotts** [comment]
It's not enabled by default (presuming you mean the `'download'` option in the controls array?). Do you have a codepen, codesandbox, or just somewhere I can debug. I'm working blind 👍

**Comment by Generalomosco** [comment]
Thanks, I disabled it by with ` controlsList="nodownload"` attribute

**Comment by garbinmarcelo** [comment]
> It's not enabled by default (presuming you mean the `'download'` option in the controls array?). Do you have a codepen, codesandbox, or just somewhere I can debug. I'm working blind 👍

Sorry to answer this old post, but a question arose that I couldn't solve.

I defined the download button in the settings, however at some point I would like to hide that button. 
Would it be possible to do this via HTML? or I would have to have for example two separate codes, 1 with the download option and one without.

If you have any code on this issue could you show? 

Thank you

P.S.:
Example, showing the download button in the player when the urls is set.
```html
<audio id="player" class="js-player" controls data-plyr-config='{ "urls": {"download": "test.mp3"}}'>
     <source type="audio/mp3" src="https://cdn.plyr.io/static/demo/Kishi_Bashi_-_It_All_Began_With_a_Burst.mp3" />
     <source type="audio/ogg" src="https://cdn.plyr.io/static/demo/Kishi_Bashi_-_It_All_Began_With_a_Burst.ogg" >
</audio>
```

**Comment by naonvl** [comment]
How to prevent audio from downloading? everytime i hit play it always downloading
