### ISSUE TITLE
Unable to dynamically update poster 

### ISSUE THREAD

**Issue by slashwhatever** [sampotts/plyr#1395]
### Expected behaviour
When updating the poster attribute, plyr component should reflect those changes

### Actual behaviour
Poster fails to update

### Steps to reproduce
Note that this test case is a simplification of how we are using Plyr. Our real implementation allows users to use a slider to update the thumbnail time of the video. When they update the slider, the poster url gets regenerated and the Plyr video component should update the poster.

### Environment

- Browser: Chrome 
- Version: 73
- Operating System: macOS

### Console errors (if any)
None

### Link to where the bug is happening
https://jsfiddle.net/slashwhatever/5ujdn41g/31/

**Comment by sampotts** [comment]
Setting the `poster` attribute in this way on the `<video>` element won't work. We don't have a `MutationObserver` in place to check for mutations of attributes. We could add it though. Changing the poster programmatically _is_ supported via the [`poster` setter](https://github.com/sampotts/plyr#getters-and-setters) though.

**Comment by slashwhatever** [comment]
Aaaah - that's helpful! Thanks :)

I've updated the test fiddle in case anyone would like to refer to a possible solution in the future: https://jsfiddle.net/slashwhatever/5ujdn41g/39/

**Comment by twistedpixel** [comment]
Aha, this must be why I was having trouble yesterday loading Plyr on the fly with no “src” attribute on the video element. I was adding it in via javascript when the user triggers an event and Plyr didn’t seem to “notice”. I didn’t realize the source setter must be used instead.

**Comment by sampotts** [comment]
Closing this as I think it's resolved. Will consider adding the mutation observer later.
