### ISSUE TITLE
Updating download button URL not working

### ISSUE THREAD

**Issue by hatsumatsu** [sampotts/plyr#1398]
Not sure if this is possible with Vimeo’s APIs but could the download button in the player controls automatically link to the MP4 source of the video if the video is from Vimeo and the video settings allow downloading the source files?

**Comment by sampotts** [comment]
It’s possible if their SDK has a method to retrieve it but I really doubt it does.

**Comment by hatsumatsu** [comment]
I just tried a workaround fetching the video's info via the Vimeo API (you need to have an Pro/Business account and generate an acces token first): https://developer.vimeo.com/api/reference/videos#get_video

Once I got the download URLs I tried updating the player's config but `instance.config.urls.download = 'my_download_url'` doesn't change the button's target. Looks like we can't overwrite the download URL for vimeo videos?

**Comment by hatsumatsu** [comment]
Looks like setting the download URL some time after the player's `ready` event does not update the button (like in a callback or timeout)?

Reduced test case: https://codepen.io/superstructure-net/pen/WmqmLG

**Comment by hatsumatsu** [comment]
@sampotts Just wanted to check if you could reproduce this behavior. Here is an even simpler demo showing that the download button's URL is not updated:

https://s.codepen.io/superstructure-net/debug/VNPrKW

**Comment by sampotts** [comment]
I'll add a setter for `download` to set the URL for the button 👍

**Comment by sampotts** [comment]
A `download` setter has been added in [`v3.5.4`](https://github.com/sampotts/plyr/releases/tag/v3.5.4) 👍
