### ISSUE TITLE
Screen goes to sleep on android

### ISSUE THREAD

**Issue by GINCHER** [sampotts/plyr#1403]
### Expected behaviour
Full screen on android will remove the screen buttons (homescreen, go back and all apps), and won't go to sleep until the end of the video.

### Actual behaviour
The screen buttons appear, so the video can't play on the entire screen and moves sideways. Wide videos will have black bars. Also, after 30 seconds the screen goes to sleep and it pasues the video.

### Steps to reproduce
Open the video in full screen on an android device

### Environment

- Browser: Google chrome for android
- Version: latest
- Operating System: Android on Samsung s8
- Version:  Android 9

### Link to where the bug is happening
https://plyr.io/

**Comment by sampotts** [comment]
I’m not even sure the browser has control over this behavior?

**Comment by twistedpixel** [comment]
That’s what I was going to say. I’m pretty sure all mobile browsers use their native player for full screen mode so Plyr would not be the reason for this behavior.

Sounds like something wrong with the OS and/or browser.

**Comment by GINCHER** [comment]
Is there a way to disable plyr in fullscreen automatically so it will show the native player? Because I'm pretty sure a lot of users have the bug.

**Comment by gurupras** [comment]
I just tested this out with a 7 minute HLS video and didn't have the screen turn off during the video. The on-screen buttons do appear as the OP pointed out, but I'm not sure about  whether they should/shouldn't.

Regardless, It sounds like you're using it for simple mp4/webm videos. You can override the fullscreen listener and run your own logic. That way, you could add the default controls when entering fullscreen and remove them when exiting.

**Comment by pau1phi11ips** [comment]
I see this bug is still here in 2021 on https://plyr.io/.
Did anyone find a solution?
