### ISSUE TITLE
Failed HTML Vaidation due to Multiple instances of id="player"

### ISSUE THREAD

**Issue by cognicademy** [sampotts/plyr#1405]
Please forgive me if this inappropriate. I have never submitted such a post before.
When placing multiple players on a single page, the W3 HTML Validator fails because of repeat instances of id="player".

Is there a way to correct this.

Many thanks.

**Comment by sampotts** [comment]
Hey there, 

This isn’t an issue with Plyr as such. If you’re setting up multiple players, you could use a className (such as `js-player`) or different IDs (such as `player1`, `player2`, etc).

**Comment by cognicademy** [comment]
Oh great. So I can change id="player" without breaking anything then.
Thank you!

**Comment by sampotts** [comment]
Well it depends how you have you me JavaScript setup. You will need to change the selector you pass to the constructor...

`new Plyr(‘.js-player’)` for example.
