### ISSUE TITLE
Setting initial speed via config not working

### ISSUE THREAD

**Issue by SrdSrd** [sampotts/plyr#1408]
Cant get it to work. Nothing happens when i change "selected:1". I need it to play at 1.1x at default... but no luck.

**Comment by sampotts** [comment]
I've found a fix for this. Should go in the next release. Probably this weekend.

**Comment by SrdSrd** [comment]
Can i have the fix? It is really important to me. :)

**Comment by sampotts** [comment]
As soon as I finish another change you’ll have it, yes.

**Comment by sampotts** [comment]
Fixed in [`v3.5.4`](https://github.com/sampotts/plyr/releases/tag/v3.5.4) 👍
