### ISSUE TITLE
Settings menu is not showing up when clicked

### ISSUE THREAD

**Issue by eberc** [sampotts/plyr#1409]
when i click on the settings icon, the whole video window goes up and settings don't show up, idk if it's a css or js bug

in fullscreen it's working well, can you help me?  thanks

**Comment by sampotts** [comment]
Some info to help reproduce such as a codepen, jsfiddle, codesandbox will help. Currently I'm working blind. Sounds like external CSS crashing the party but I have no idea.

**Comment by eberc** [comment]
my project is using a materialize css, i can't remember the version, i will check it today and run some tests later

**Comment by eberc** [comment]
i think it's a conflict with materialize css/js https://codepen.io/eberc/pen/EJmrQp

**Comment by sampotts** [comment]
Have you found out what the cause is yet? Not sure this is something we can fix our side.

**Comment by eberc** [comment]
@sampotts I put the element outside the container and it worked

**Comment by sampotts** [comment]
Great. So can we close this?

**Comment by eberc** [comment]
@sampotts yeah, thanks!
