### ISSUE TITLE
[Feature Request] Rearrange controls

### ISSUE THREAD

**Issue by mnervik** [sampotts/plyr#1411]
Ability to change to order of the controls. Example, if you want the current-time indicator on the left-side of the progress bar...like this
![bilde](https://user-images.githubusercontent.com/15329600/56038867-41ca4100-5d33-11e9-9b05-5f3d50d89045.png)

**Comment by friday** [comment]
Already supported: https://github.com/sampotts/plyr/blob/master/controls.md

**Comment by sampotts** [comment]
@friday I think he means to set the _order_ which isn't possible. I had a TODO in there and I've already made a start on it but styling is the issue that I'm finalizing currently.

**Comment by friday** [comment]
I've been away too long. Sorry mnervik!

**Comment by jamesoflol** [comment]
You can set the controls to display:flex, and then give them all an ‘order’
attribute

**Comment by sampotts** [comment]
Yeah that's possible I guess. The controls container already uses flex. 

I'm almost done making the controls order relative to the order of the array. It just requires some styling changes and might be breaking for some people so I'll probably have to bump the major version as a result.

**Comment by sampotts** [comment]
This is now possible in [`v3.5.4`](https://github.com/sampotts/plyr/releases/tag/v3.5.4) 👍 It will now take the order of your controls array as the order to display them in. I'll check I've updated the docs but will do if I've not done so already.
