### ISSUE TITLE
Videos with m3u8 extension do not appear through ajax

### ISSUE THREAD

**Issue by Reqrefusion** [sampotts/plyr#1412]
I made a system that opens in the plyr player by sending the id of the videos, this system works in normal mp4, but when I do it with hls.js, I get the video:
`<video poster="" id="player" playsinline="" update:="" false=""></video>`
However, when I open the page on chrome, the player is running. It also works when I open the page in iframe.
The codes I use in Ajax are:
```
<?php
$output .= '<div class="plyr">
        <video poster="'.$thum.'" id="player" playsinline update: false controls></video>
		<script src="https://cdn.rawgit.com/video-dev/hls.js/18bb552/dist/hls.min.js"></script>
		'.
		"<script>
		document.addEventListener('DOMContentLoaded', () => {
	const source = '".$videoLink."';
	const video = document.querySelector('video');

// For more options see: https://github.com/sampotts/plyr/#options
	// captions.update is required for captions to work with hls.js
	
	if (!Hls.isSupported()) {
		video.src = source;
	} else {
		// For more Hls.js options, see https://github.com/dailymotion/hls.js
		const hls = new Hls();
		hls.loadSource(source);
		hls.attachMedia(video);
		window.hls = hls;
		
		// Handle changing captions
		player.on('languagechange', () => {
			// Caption support is still flaky. See: https://github.com/sampotts/plyr/issues/994
			setTimeout(() => hls.subtitleTrack = player.currentTrack, 50);
		});
	}
	
	// Expose player so it can be used from the console
	window.player = player;
});</script>"; ?>
```
In order to solve this situation, I paste this code to another page and from there, I get ajax as iframe, But this solution is temporary.

### Expected behaviour
`<video poster="" id="player" playsinline="" update:="" false="" src="blob:https://example.com/d581bd72-a34d-40e7-b238-1ea3ac7425c2"></video>`
### Actual behaviour
`<video poster="" id="player" playsinline="" update:="" false=""></video>`
### Environment

- Browser: All
- Version: 3.5.3
- Operating System: Windows
- Version: 10

**Comment by sampotts** [comment]
I don't think this is an issue with Plyr itself by the sound of things. We don't maintain hls.js. You do have some issues with your markup though:

```html
<video poster="'.$thum.'" id="player" playsinline update: false controls></video>
``` 

Should be 

```html
<video poster="'.$thum.'" id="player" playsinline controls></video>
``` 

Also, you open a `<div>` and don't close it.

**Comment by Reqrefusion** [comment]
You're right hls.js doesn't work when the data is on the page that is sent as ajax, but it works when the data is on the sending page. Thanks for the code correction. :D
I solved the problem.

**Comment by Reqrefusion** [comment]
You're right hls.js doesn't work when the data is on the page that is sent as ajax, but it works when the data is on the sending page. Thanks for the code correction. :D
I solved the problem
The problem is happening in some trials but it is totally caused by hls.js.

**Comment by sampotts** [comment]
Awesome 👍
