### ISSUE TITLE
Plyr doesn't work in shadowDOM

### ISSUE THREAD

**Issue by emielbeinema** [sampotts/plyr#1415]
### Expected behaviour
Including Plyr in a WebComponent should work just as it does in normal DOM.

### Actual behaviour
Inside a shadowDOM, the menu closes whenever you click on an item.

### Steps to reproduce
1. Go to below example on codesandbox.io
2. Open the menu
3. Click on one of the items

### Environment

- Browser: Google Chrome
- Version: 75
- Operating System: Ubuntu
- Version: 18.10

### Link to where the bug is happening

https://codesandbox.io/embed/zlkl31j05p

**Comment by sampotts** [comment]
Merged your changes apart for the change to the `matches` method as I think it was a mistake 👍
