### ISSUE TITLE
plyr 3.5.3 Encountered error fullscreen in mobile

### ISSUE THREAD

**Issue by jacksonit** [sampotts/plyr#1421]
I've just upgraded **plyr 3.5.2**  to **plyr 3.5.3** for the project [102tube](https://102tube.tv) and have discovered a bug fullscreen in mobile error.

And this error causes from the Plyr JS Library when manually adding
`padding-bottom: 216.533%`
 In div class: .plyr__video-wrapper, .plyr__video-embed

And the way I can fix that is to add to this CSS snippet     
`.plyr__video-wrapper, .plyr__video-embed { 
      padding-bottom: 56.25% !important;
}`

Video bug : [https://www.youtube.com/watch?v=zS584wonJDk](https://www.youtube.com/watch?v=zS584wonJDk)

If anybody is being like me or referencing Nhé, and am looking forward to plyr sharing fix this error because Plyr is an amazing library!

**Comment by sampotts** [comment]
I've got a fix lined up for this. I can probably deploy later today or tomorrow.

**Comment by sampotts** [comment]
Fixed in `[v3.5.4](https://github.com/sampotts/plyr/releases/tag/v3.5.4)` 👍

**Comment by th-santos** [comment]
> 
> 
> Fixed in [`v3.5.4`](https://github.com/sampotts/plyr/releases/tag/v3.5.4) 👍

Awesome! Please update readme file to use version 3.5.4.

**Comment by sampotts** [comment]
> Awesome! Please update readme file to use version 3.5.4.

Good point. That's supposed to be automated. Whoops 🤦‍♂️
