### ISSUE TITLE
Video from Youtube does not start automatically on mobile and tablets

### ISSUE THREAD

**Issue by hostbox2** [sampotts/plyr#1422]
### Expected behaviour
1) When I open page (https://fmhit.ru) with a plir player, the video should be played automatically on mobile, tablet and PC.
The option "autoplay: true" is actual.

2) The function "player.play()" should start playing video.

### Actual behaviour
1) The video is automatically played on the PC.
And automatically does not play on mobile, tablets.
To start playback, you need to click the "play" button.

2) The "player.play()" function does not work.

### Steps to reproduce
1) Go to page https://fmhit.ru from a mobile or tablet. In Chrome console select function "Toggle device toolbar" and select "iPad" or "iPhone" device.

OR

2) Go to page https://codepen.io/pen?template=GGqbbJ from a mobile or tablet. In Chrome console select function "Toggle device toolbar" and select "iPad" or "iPhone" device. To write option "autoplay: true".

### Environment

- Browser: Google Chrome
- Version: 73.0.3683.103 (Official Build) (64-bit)
- Operating System: Windows 10
- Version: 10.0.14393 build 14393

### Console errors (if any)
No errors

### Link to where the bug is happening
https://fmhit.ru
https://codepen.io/pen?template=GGqbbJ (if write option "autoplay: true")

**Comment by hostbox2** [comment]
In real Android device Xiaomi Redmi Note 4X the same behaviour.
OS:

**Comment by sampotts** [comment]
Auto play is blocked in some browsers and there’s nothing we can do to change that unfortunately

**Comment by hostbox2** [comment]
Include this behavior in the readme.md for option "autoplay: true"

**Comment by sampotts** [comment]
Sure. It's been a thing for a while though...

https://webkit.org/blog/6784/new-video-policies-for-ios/
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
https://googlechrome.github.io/samples/muted-autoplay/

And more recently... 

https://hacks.mozilla.org/2019/02/firefox-66-to-block-automatically-playing-audible-video-and-audio/

**Comment by sampotts** [comment]
Added some notes in [`v3.5.4`](https://github.com/sampotts/plyr/releases/tag/v3.5.4) 👍
