### ISSUE TITLE
player.currentTime not setting

### ISSUE THREAD

**Issue by bjm1** [sampotts/plyr#1427]
Setting currentTime does not work as expected. 

Upon pressing play (from default controls) video starts playing from beginning, instead of "40 second mark".

const player = new Plyr('video', {captions: {active: true}});

player.currentTime = 40; // doesn't work
player.volume = 0.5; // works

**Comment by tocsinde** [comment]
Try it like this:

```
player.on("ready", function() {
    player.currentTime = 40;
}
```

**Comment by sampotts** [comment]
As above. You need to wait for the ready event before you can use the API. I’ll make sure this is clearer in the docs.

**Comment by bjm1** [comment]
Still no luck using the ready event. 

It seems the default play buttons ignore the newly set currentTime and the video always starts playing from beginning.

**Comment by bjm1** [comment]
Update: here's the fix!

player.on('canplay', event => {
  player.currentTime = 40;
});

The player waits until enough video buffers, then jumps to the correct location :)

Shouldn't "ready" work too?

**Comment by sampotts** [comment]
`ready` is just that Plyr has finished initializing and is ready for API calls but at that point the media won't be loaded so we won't know the duration to be able to set the current time.

**Comment by bitsbybob** [comment]
When I tried the "canplay" it would hit an endless loop and wouldn't allow the user to play the video (I assume because 'canplay' kept firing -- no idea) I found this somewhere yesterday and it worked for me.  It waits for the media to be loaded past the time requested so it can then play ...

===
player.on("loadeddata", onDataLoaded);

var time= 34;  // the seconds you want to jump to

function onDataLoaded() {
      if(time<=player.duration){}
      player.off("loadeddata",onDataLoaded);
      player.currentTime = time;
}
===

**Comment by bjm1** [comment]
player.currentTime doesn't seem to work with youtube videos.  Should it?

**Comment by bjm1** [comment]
Regarding bitsbybob, this code prevents loop you encountered.

`if (player.playing !== true) {
 player.once('canplay', event => {
   player.currentTime = 34; 
 });
}`

**Comment by bjm1** [comment]
Update: In YouTube's case "ready" will SET currentTime, but HTML5 needs "canplay". 

YouTube
```
player.once('ready', event => {
   player.currentTime = 34;
});
```
HTML5
```
player.once('canplay', event => {
   player.currentTime = 34;
});
```

**Comment by banagale** [comment]
In case someone comes across this:

I was having some trouble getting the `currentTime` setter to work on mp3 audio playback. 

First, `.once()` vs `.on` listens for a single event. `.on()` will just keep the playback stuck at whatever you set.

If your playback time is dependent on network access, you may have an async retrieval necessary. Be sure you await resolution of the value you're setting to or it may not be available in time.

For example, you might have a class method that gets the time to resume from and then sets it using `this.player.currentTime = await getResumeTime(someId);`

```
this.player.once('canplay', _ => {
  this.setPlaybackTime().error(console.error);
});
```

**Comment by ponkojr1998** [comment]
Best way:


var previous_duration=50;
var previousTimeSetter = setInterval(function(){
  if (player.playing !== true && player.currentTime != previous_duration) {
    player.currentTime = previous_duration;
  }else{
    clearInterval(previousTimeSetter);
  }
}, 800);

**Comment by amouchaldev** [comment]
I try all the solution in the comments above no one worked for me, I came up with a solution it work will
function setPlayerCurrentTime(currentTime) {
    setTimeout(() => {
        player.currentTime = currentTime; 
        player.play()
      }, 2000)
  }

**Comment by banagale** [comment]
@amouchaldev what browser(s) are you testing on?

**Comment by TuannTran04** [comment]
let player;
  useEffect(() => {
    const setupPlyr = async () => {
      // console.log("movie", movie);
      // console.log("movie subtitles", movie.subtitles);

      // Chuyển đổi dữ liệu phụ đề thành định dạng Plyr
      if (Object.keys(movie).length > 0) {
        const plyrTracks = movie.subtitles?.map((subtitle, index) => ({
          kind: "captions",
          label: `${subtitle.langSubtitle} captions`,
          srcLang: subtitle.langSubtitle,
          src: `${process.env.NEXT_PUBLIC_URL}/subtitles/${subtitle.subtitle}?specificFolder=${movie.folderOnFirebase}`,
          default: index === 0, // Đánh dấu phụ đề đầu tiên là mặc định
        }));
        // console.log(plyrTracks);

        const plyrSources = movie.sources?.map((video, index) => ({
          src: `${process.env.NEXT_PUBLIC_URL}/video/${video.srcVideo}?specificFolder=${movie.folderOnFirebase}`,
          type: video.typeVideo,
          size: video.sizeVideo,
        }));

        // Khởi tạo Ply
        if (refVideo.current) {
          player = new Plyr(refVideo.current, {
            title: "Example Title",
            controls: [
              "play-large", // The large play button in the center
              "restart", // Restart playback
              "rewind", // Rewind by the seek time (default 10 seconds)
              "play", // Play/pause playback
              "fast-forward", // Fast forward by the seek time (default 10 seconds)
              "progress", // The progress bar and scrubber for playback and buffering
              "current-time", // The current time of playback
              "duration", // The full duration of the media
              "mute", // Toggle mute
              "volume", // Volume control
              "captions", // Toggle captions
              "settings", // Settings menu
              "pip", // Picture-in-picture (currently Safari only)
              "airplay", // Airplay (currently Safari only)
              "fullscreen", // Toggle fullscreen
            ],
            settings: ["captions", "quality", "speed", "loop"],
            quality: {
              default: 576,
              options: [4320, 2880, 2160, 1440, 1080, 720, 576, 480, 360, 240],
            },
          });
        }
        // Đặt sự kiện cho Plyr khi video được play
        // player.on("play", () => {
        //   console.log("Video is playing");
        //   player.muted = false;
        //   // handleVideoPlay();
        // });

        player.on("timeupdate", (e) => {
          console.log("Video is timeupdate");
          let currentTime = player.currentTime;
          // const currentTimee = event.detail.plyr.currentTime;
          const duration = player.duration;

          // const newVideoState = {
          //   ...videoState,
          //   currentTime: currentTime,
          //   videoId: movie._id,
          // };
          // console.log("newVideoState", newVideoState);
          // setVideoState(newVideoState);
          // console.log("handleVideoTimeUpdate", duration);

          // Thời gian hiện tại gần cuối video (1 giây trước khi kết thúc)
          if (duration && duration - currentTime < 1) {
            console.log("Video đã xem xong");
            // Thực hiện các tác vụ khi video kết thúc hoặc đã xem xong
            localStorage.removeItem(`${movie?._id}`);
          }

          // handleVideoTimeUpdate(currentTime, duration);

          if (
            currentTime &&
            currentTime > 0 &&
            duration &&
            duration - currentTime > 1
          ) {
            console.log("sett", {
              currentTime: currentTime,
              videoId: movie._id,
            });
            localStorage.setItem(
              `${movie?._id}`,
              JSON.stringify({
                currentTime: currentTime,
                videoId: movie._id,
              })
            );
          }
        });

        // Kiểm tra nếu có trạng thái xem video trong Local Storage
        const savedPlaybackTime = JSON.parse(
          localStorage.getItem(`${movie?._id}`)
        );
        const currTimeLocal = savedPlaybackTime?.currentTime;
        const videoIdLocal = savedPlaybackTime?.videoId;

        console.log("savedPlaybackTime.videoId ", videoIdLocal);
        console.log(" movie._id", movie._id);
        console.log(
          "savedPlaybackTime.videoId == movie._id",
          videoIdLocal == movie._id
        );

        if (player.playing == false) {
          player.once("canplay", () => {
            // player.currentTime = 50;
            if (
              currTimeLocal &&
              currTimeLocal > 0 &&
              videoIdLocal == movie._id
            ) {
              console.log("savedPlaybackTime canplay");

              const setPlayerCurrentTime = (currentTime) => {
                setTimeout(() => {
                  const minutes = Math.floor(currentTime / 60);
                  const seconds = Math.round(currentTime % 60);
                  if (
                    window.confirm(
                      `Bạn có muốn xem tiếp video từ ${minutes}p${seconds}s không ?`
                    )
                  ) {
                    console.log("continue");
                    player.muted = true;
                    player.currentTime = currentTime;
                    player.play();
                  } else {
                    console.log("begin");
                    player.muted = true;
                    player.currentTime = 0;
                    player.play();
                  }
                }, 2000);
              };
              setPlayerCurrentTime(currTimeLocal);
            }
          });
        }

        // player.on("ended", () => {
        //   console.log("Video is ended");
        //   handleVideoEnded();
        // });

        // Thiết lập tracks cho Plyr
        player.source = {
          type: "video",
          title: "Example title",
          sources: plyrSources,
          tracks: plyrTracks,
        };
      }
    };
    setupPlyr();
  }, [refVideo.current]);
  
  -Help me. Why first run "player.currentTime = currentTime;" it doesn't work. the page must be reloaded for it to work, even though the first time "currentTime" was saved in localStorage

**Comment by banagale** [comment]
> -Help me. Why first run "player.currentTime = currentTime;" it doesn't work. the page must be reloaded for it to work, even though the first time "currentTime" was saved in localStorage

My experience was that the behavior can change between browsers. Have you tested in multiple browser types, Safari, mobile Safari, Chrome, Firefox to see if it is the same in each?

Be sure you're clearing the cache when testing code you're change.

**Comment by TuannTran04** [comment]
useEffect(() => {
    const setupPlyrWithSubtitles = async () => {
      console.log("movie", movie);
      // console.log("movie subtitles", movie.subtitles);
      // Lấy dữ liệu phụ đề từ API
      // const subtitlesData = await fetchSubtitlesFromAPI();

      // Chuyển đổi dữ liệu phụ đề thành định dạng Plyr
      let plyrSources;
      let plyrTracks;
      if (Object.keys(movie).length > 0) {
        

        plyrTracks = movie.subtitles?.map((sub, index) => ({
          kind: "captions",
          label: `${sub.langSubtitle} captions`,
          srcLang: sub.langSubtitle,
          src: `${process.env.NEXT_PUBLIC_URL}/subtitles/${sub.subtitle}?specificFolder=${specificFolder}`,
          default: index === 0, // Đánh dấu phụ đề đầu tiên là mặc định
        }));
        console.log("plyrTracks", plyrTracks);

        // Khởi tạo Plyr
        const player = new Plyr(refVideo.current, {
          settings: ["captions", "quality", "speed", "loop"],
          captions: { active: true, update: true }, // Thiết lập hiển thị phụ đề
        });

        // Thiết lập tracks cho Plyr
        player.source = {
          type: "video",
          sources: [
            {
              // src: `${process.env.NEXT_PUBLIC_URL}/video/${video.srcVideo}?specificFolder=${specificFolder}`,
              src: `${process.env.NEXT_PUBLIC_URL}/video/neudanhmatem.mp4?specificFolder=neudanhmatem_2023-9-6_22:36:28`,
              type: "video/mp4",
              size: 720,
            },
          ],
          tracks: plyrTracks,
        };

        player.once("canplay", () => {
          console.log("savedPlaybackTime canplay");
          const setPlayerCurrentTime = (currentTime) => {
            setTimeout(() => {
              player.muted = true;
              player.currentTime = currentTime;
              player.play();
            }, 2000);
          };
          setPlayerCurrentTime(300);
        });
      }
    };

    setupPlyrWithSubtitles();
  });
  
  - I have shortened the code to test but when I run the page for the first time, the currentTime is still not set. I still have to reload the page for currentTime to be set successfully. I tested on chrome, edge is the same

**Comment by banagale** [comment]
> I tested on chrome, edge is the same

Edge uses chromium as the rendering engine, be sure to try in Safari desktop at least which has a bigger share than edge anyway.
