### ISSUE TITLE
Add support for multiple tracks

### ISSUE THREAD

**Issue by gurupras** [sampotts/plyr#143]
Currently, although most of the code is in place to add multiple track elements, `_setupCaptions()` only chooses the first one.

This would also require new CSS for a tiny pop-up menu showing available captions and JS updates to figure out the currently selected one and update the underlying track element.

I'd be happy to work on this if you can write up the CSS part of it.

**Comment by SamPotts** [comment]
Definitely mate :+1: I've been planning on adding this in at some point. I'll work on the UI when I get some spare time.

**Comment by haarts** [comment]
I'd love to see this happen: https://www.bountysource.com/issues/29869063-add-support-for-multiple-tracks

**Comment by gurupras** [comment]
Would you like something like this?
https://jsfiddle.net/gurupras/7oy55wuy/

**Comment by gurupras** [comment]
Would you like something like [this](https://jsfiddle.net/gurupras/7oy55wuy/)

Let me know what you guys think and I'll create a PR accordingly

**Comment by SamPotts** [comment]
I've already started work on it. I can't see any UI changes in your fiddle there that would facilitate the functionality. I've been working on a settings menu for captions, speed and quality and working on them simultaneously so will finish that.  

<img width="221" alt="screenshot 2017-01-06 09 18 14" src="https://cloud.githubusercontent.com/assets/719092/21699728/2cbc391c-d3f1-11e6-8bbb-6916ce09f15b.png">

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by haarts** [comment]
Some one should claim the bounty!
