### ISSUE TITLE
Ratio not available in ready event?

### ISSUE THREAD

**Issue by samhibberd** [sampotts/plyr#1433]
We are getting a `null` value for the ratio getter when called in the ready function.

```
player.on('ready', function(event) {
    var instance = event.detail.plyr;
    console.log(instance.ratio); // returns null
});
```
See console: https://codepen.io/samhibberd/pen/VNOaxw

**Comment by pknijff** [comment]
@samhibberd, did you manage to find a solution to this? I am having the same problem when accessing the duration property.

**Comment by samhibberd** [comment]
Sadly not, I think I ended up with a bit of a hack involving a `setTimeout()` in the ready event, giving a chance for the ratio to be set.

**Comment by pknijff** [comment]
I managed to get the duration of the song (audio player) hooking into the `loadeddata` event. Btw. it's being used within a VueJs application.

**Comment by michaelpumo** [comment]
This is still an issue for me even when using a setTimeout hack. player.ratio returns null. However, even if I log player, I can see the ratio property. This isn't making sense to me.

**Comment by philipmarnef** [comment]
I had the same issue but since I was autoplaying the video I solved it by using the `.once('playing',...)` event where `e.detail.plyr.ratio` is available.
