### ISSUE TITLE
Progress bar width is very small

### ISSUE THREAD

**Issue by yassinebridi** [sampotts/plyr#1438]
## Expected behaviour
The progressbar to be full width
### Actual behaviour
The progress bar width is smaller then expected, as show in the 

![picture](https://i.imgur.com/Iq8I7rG.png)

### Environment

- Browser: Google Chrome
- Version: 74.0.3729.131
- Operating System: Ubuntu Budgie
- Version: 19.04

## Important Thing to keep in mind
i'm using Plyr Through a React component 
https://github.com/xDae/react-plyr

**Comment by sampotts** [comment]
Likely a CSS issue not related to Plyr itself. Unless of course you're seeing this issue on https://plyr.io

**Comment by yassinebridi** [comment]
Yeah, even the examples provided by the react-plyr repo, doesn't have that problem.

**Comment by tdimnet** [comment]
@yassinebridi: and you cannot overwrite the css of Plyr?
I thinking of something like that:

`
.plyr__progress {
    bottom: 0px;
    position: absolute;
    width: 95%; /* what lets you expand the progres bar */
  }
`

By the way, beware with using react-plyr: the library is not up to date and seems to be no longer maintained.

**Comment by yassinebridi** [comment]
I've been playing with the css all night with no desired results,
the only thing that worked is using a fixed width, which is pretty bad.

but after i downgraded to the the previous version 3.5.3 it worked perfectly.
for both the npm package and the CDN, the same problem.

**Comment by sampotts** [comment]
The latest version requires the CSS to also be updated as some changes were made to mark up. It was mentioned in the release notes.

**Comment by yassinebridi** [comment]
> The latest version requires the CSS to also be updated as some changes were made to mark up. It was mentioned in the release notes.

That worked perfectly, thanks sam.

**Comment by sampotts** [comment]
Good to hear. Enjoy 👍

**Comment by ElisDN** [comment]
For older wrappers:

```js
.plyr__progress__container {
  flex-grow: 2;
}
```
