### ISSUE TITLE
How to removeEventListener ‎timeupdate?

### ISSUE THREAD

**Issue by jasonz18** [sampotts/plyr#1441]
How to remove the listener in Plyr player?

`el.removeEventListener('timeupdate', event => {
console.log("remove");
});`

**Comment by sampotts** [comment]
Use `.on()` `.off()` and `.once()`:
https://github.com/sampotts/plyr#api

**Comment by jasonz18** [comment]
> Use `.on()` `.off()` and `.once()`:
> https://github.com/sampotts/plyr#api

Thanks! But I got the error when I used `.off()`
[Vue warn]: Error in v-on handler: "TypeError: el.off is not a function"

**Comment by sampotts** [comment]
What's `el` ? It needs to be an instance of `Plyr`.

**Comment by jasonz18** [comment]
> What's `el` ? It needs to be an instance of `Plyr`.

Below is my code, but it doesn't word...
`//todo removeListener
let player = new Plyr(el);
player.off('timeupdate', event => {
    console.log("removeListener");
})`

**Comment by rohitcoder** [comment]
Hi @sampotts I don't know why but `off` isn't removing `timeupdate` event. Can you please help us with that  and take a look at this issue https://github.com/sampotts/plyr/issues/2249
