### ISSUE TITLE
Video Streaming (HLS) quality level selector for hls m3u8 source

### ISSUE THREAD

**Issue by ncc0706** [sampotts/plyr#1446]
same issues  like https://github.com/sampotts/plyr/issues/947

my playlist like this

![image](https://user-images.githubusercontent.com/11310593/57910733-9162d600-78b8-11e9-9c4d-97a8365e52fc.png)

**m3u8**
``` javascript
 if (Hls.isSupported()) {

                const config = {
                    debug: false,
                    autoStartLoad: true
                }

                var hls = new Hls(config);

                //https://pcvideohwyun.titan.mgtv.com/c1/2019/05/15_0/8E1979DD5B612B80F5E475E9FD534B7E_20190515_1_1_769_mp4/0F9A0D9375492B15D04E9BDB3F35470A.m3u8?arange=130&pm=f3WvFr6HO34CfXR~1twkDKWWnPCsH~5U5_OFFnhFhaZsVBLz~JStW5FVlgdtFEVOogg4FPAJRvX89CYDn9aqPDN3A2s00Qy_k1r~~kT0Pn3yr4E~7tYC~AkAC6rftV9SeMYCGkqS~arBmjHnQibc~nlNKz6~ZWif7DBR~rxzqn5CmbYLB7yxzB1aIxzOP5TuKVqH2zgqJTkgklraR5O8RwnSzkWdDWu5EZlC95OfaNwvOGh53VoDotW1WL6WgY7aXPLGpbbbsFGkL5NcdVeHKm7Iydj6VIA1ZjPLO0lkZpxVD4FiBiJ2vTwnlleUadxXDPa14JTEh8vHAUVYo1n2d_l_hLCVC4nLbE5c9no9kMbXTuGuInf3zvDgjmUYG2BNmyH7hWD4j7Nw4ykMEnwBTL1bfYMYRddv9VMyDELAU8ooFzrS7KXYS_Vqer4zO2JEsy0Tl_BUyts5bJgmPQDTVGGNZtqEKXdSpo1_E0a7nC3zPTLjsXFjsdHmr9ocp6ZvK02VJm4uQeM-&did=4a7b9b11-7867-11e9-891f-4f986fb7ca3c&mr=UNWpKyZ2oQBTmT9GYY0yppNfftercrPJo8I0jOitgVkXSk~J&vcdn=0&scid=25041
                hls.loadSource('https://pcvideoyf.titan.mgtv.com/c1/2018/08/08_0/C09A93D3488790D557A2D13497AB3AA9_20180808_1_1_1039_mp4/CFC32FCF230C4FA4F67C18EEAEE33A94.m3u8?arange=0&pm=UvdKLm7RuYh1o~iSUmRv3A0HSQCXIj94xlnboXtLQ8Z4ANTCrgb0n8XL5B7gRNaKSVc_Mcrn0YIbpUbw~0rk17AR2~MrsoR4O5Ggde~StE4K_VnmYnZuI7sDKdpnxlg4XtwKfhfRyzEey2CJH~eUqr5rFmF1BqSbpe8h29lK2Sr1w9bLfmrGppJt_dNGSRJZu3H6C4RKBw60ULHKd9hyAq0mcPxwSBEwtOsChz5hZUPeLa9Uoki4RQNhCQzKYH2w7ETk6CwlhVGIElLH~VrPl~kN0lheWqPOVd40ukyqXF6hTZa6XomgLCyncmxc1Kurb_JFJCnSG_fpQimxIE2w~lR1TZvKw1y78IicGfzzks_FLc9mv4UjKKhilNIDPGkJC7b3SEUpBIVLRML7yOtB8_XzlA3YIENmgLIn7UC~1D3h4sC6qDAsyhLCaPbzdwgMC~tHXOBHnKwXQVtzbPSrXKnVpMVAU0h8GQkrwpUFEWPa4jbL~8hkJ_R5Fj9pAfWTysmbLzXFfdw-&did=4cf5c931-786f-11e9-9fe3-b9d4acab6db2&mr=cVZIPnQrKRURD6d2Ez4G~5LY9F~RWzn7LtIfx6w64trqlFMzo1cpv1bKSa767SF2&vcdn=0&scid=25022');
                hls.attachMedia(video);
                hls.on(Hls.Events.MANIFEST_PARSED, function () {
                    video.stop();
                });

                console.log(hls)
                console.log(hls.levels)
                console.log(Hls.DefaultConfig)
                console.log(Hls.DefaultConfig.debug)
                console.log(Hls.version)
                console.log(hls.currentLevel)
            }
```
**mp4**
``` javascript
player.source = {
                type: 'video',
                sources: [{
                    src: 'https://pcvideohwyun.titan.mgtv.com/c1/2019/04/16_0/4DD0F6618D403F857DAD0E152B379A50_20190416_1_1_393_mp4/F92D225DA3359EDEFFAF735E474D01BC.m3u8?arange=0&pm=OCC7Qg9ySzfnl0~WAr1BEH~8AhCTsT~1RVNs90LAOrcaoyvcgu81qrWu7dRR2ozWbxFU0Ai1HJSgz6EOa9FvkOxqMjX5SEbTqr5OiAMihLCXCScdrBH3ByE7qwDfgb~s6aRCi78XQw2ZeRfrBlmgEj~Mqz7eQXbwnV6G80nVYiQRrXu7C_9jUYH1_abMUpBbI3wmXGpvNXwg_09VRrMYYEEXXWVmZjnbp0IDEEDG5OIZC5HwSskAL0jQfxrjkrF9cG0jnk~CLXDk7wkL0FIqn3BgOswi9Jr1XsJUDTddiPloHXfE2MZ5HkkBB5FmUx4sCKLYClGBKViZNPZLsaaxM9bq0SIBRaNRXhAneB4ZHKprigDIRYo0zEyyc9j7cxRM09PtezUvobvWPzV2pEY1Xn91af8EPeZNwNCchyT115T_eQYDbtbr3XRrDTuKEEGhF2ocO2AHaHWlAZvEGjW4eAXos6_JbhmwjP_uF7kKPXtg8S8cpW~g6kxKZLfgMmqQ~hShE1vxid0-&did=241120c1-77e1-11e9-8ad7-238c34dbbff6&mr=ALBzE4NFaLnfiyOZcqxNuwRyP7K18f~bvFrvDZa1Ts3kRNGZqYIY2A--&vcdn=0&scid=25041',
                    type: 'video/mp4',
                    size: 1080
                },
                    {
                        src: 'data/output.mp4',
                        type: 'video/mp4',
                        size: 720
                    }],

                // 字幕
                tracks: [{
                    kind: 'captions',
                    label: 'English',
                    srclang: 'en',
                    src: 'data/sample-en.vtt',
                    default: true,
                }, {
                    kind: 'captions',
                    label: 'German',
                    srclang: 'de',
                    src: 'data/sample-de.vtt',
                }, {
                    kind: 'captions',
                    label: '中文简体',
                    srclang: 'zh',
                    src: 'data/sample-zh.vtt',
                }
                ],
            };
```

**Comment by IT-Pony** [comment]
Add the following code in the `<head>`

    <script src="https://cdn.plyr.io/3.5.10/plyr.polyfilled.js"></script>
    <script src="https://cdn.dashjs.org/latest/dash.all.min.js"></script>
    <link rel="stylesheet" href="https://cdn.plyr.io/3.5.10/plyr.css" />

Add the following code in the <script>
   
    // Here is the data format
    var data = [
        {
            src: 'https://bitmovin-a.akamaihd.net/content/sintel/sintel.mpd',
            size: 720,
            mode: 'mpd',// How to analyze
        },
        {
            // Resource address
            src: 'https://vod02.cdn.web.tv/am/8c/am8cvvsejym_,240,360,480,720,1080,.mp4.urlset/master.m3u8',
            size: 1080,// Definition
            mode: 'hls'// How to analyze
        },
    ];

    player.source = {
        // type: 'audio',
        type: 'video',
        title: '新播放',
        sources: data,
    };

    player.on('qualitychange', event => {
        $.each(data, function () {
            initData();
        })
    });

    function initData () {
        const video = document.querySelector('video');
        $.each(data, function () {
            // hls Adaptation
            if (this.mode === 'hls' && this.size === player.config.quality.selected) {
                // For more options see: https://github.com/sampotts/plyr/#options
                // captions.update is required for captions to work with hls.js
                if (!Hls.isSupported()) {
                    video.src = this.src;
                } else {
                    const hls = new Hls();
                    hls.loadSource(this.src);
                    hls.attachMedia(video);
                    window.hls = hls;
                    // Handle changing captions
                    player.on('languagechange', () => {
                        // Caption support is still flaky. See: https://github.com/sampotts/plyr/issues/994
                        setTimeout(() => hls.subtitleTrack = player.currentTrack, 50);
                    });
                }

                // Expose player so it can be used from the console
                window.player = player;
                return false;
            }
            // dash Adaptation
            if (this.mode === 'mpd' && this.size === player.config.quality.selected) {
                // For more dash options, see https://github.com/Dash-Industry-Forum/dash.js
                const dash = dashjs.MediaPlayer().create();
                dash.initialize(video, this.src, true);
                // Expose player and dash so they can be used from the console
                window.player = player;
                window.dash = dash;
            }
        })
    }
    initData();

Then you can run your code to see how it works. If you have any questions, please consult support@junfei.ma

**Comment by ncc0706** [comment]
@IT-Pony Thanks
