### ISSUE TITLE
Prevent Tracking From Third Parties

### ISSUE THREAD

**Issue by trymeouteh** [sampotts/plyr#1448]
I am not sure if this is a thing but if Plyr tracks its users when watching a video using Plyr weather the video is from YouTube, Vimeo or using the vi.ai ads system. But if Plyr does allow these third parties to track users maybe some improvements can be done to disable the tracking or at least have an option for the web developer when using Plyr to disable third party tracking for privacy.

**Comment by sampotts** [comment]
There’s no tracking. Ads can be enabled and can use vi.ai but are disabled by default.

**Comment by sampotts** [comment]
I am already out of pocket for cost of the current infrastructure for the CDN, I’m hardly going to add tracking 😂
