### ISSUE TITLE
Default quality for youtube videos ? 

### ISSUE THREAD

**Issue by CyrilBlankaert** [sampotts/plyr#1460]
I would like to set default quality for youtube videos, but it seems to be impossible ? 
I just want that all videos are on 720 or 1080p, how to do it ? 
Thank you ! :)

**Comment by sampotts** [comment]
Unfortunately impossible. YouTube has an API method in their SDK but it's effectively useless as you "suggest" the quality you'd like and 99.99% of the time it's ignored. I removed it because of this.
