### ISSUE TITLE
m3u8播放错误

### ISSUE THREAD

**Issue by 1265578519** [sampotts/plyr#1466]
例如url:
http://7xlv47.com1.z0.glb.clouddn.com/xxx004.m3u8

#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=200000
/Jh8rYx351Yrg7hBKrIKNdclqxLs=/lv1f9Ik9kERn5N3rjg2jVbH_nrF5/0
#EXT-X-STREAM-INF:BANDWIDTH=800000
/Jh8rYx351Yrg7hBKrIKNdclqxLs=/lv1f9Ik9kERn5N3rjg2jVbH_nrF5/1
#EXT-X-STREAM-INF:BANDWIDTH=1700000
/Jh8rYx351Yrg7hBKrIKNdclqxLs=/lv1f9Ik9kERn5N3rjg2jVbH_nrF5/2
#EXT-X-STREAM-INF:BANDWIDTH=2400000
/Jh8rYx351Yrg7hBKrIKNdclqxLs=/lv1f9Ik9kERn5N3rjg2jVbH_nrF5/3

这是一个前端配置文件问题？
~~~
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>demo</title>
</head>
<body>
<link rel="stylesheet" href="https://cdn.plyr.io/3.5.4/plyr.css">
<script src="https://cdn.plyr.io/3.5.4/plyr.js"></script>
<script src="https://cdn.plyr.io/3.5.4/plyr.svg"></script>
<script>
document.addEventListener('DOMContentLoaded', () => {const player = new Plyr('#player');});
</script>
<div class="plyr__video-wrapper plyr__video-wrapper--fixed-ratio">
    <video id="player" x5-video-player-type style="width: 100%;">
        <source src="http://7xlv47.com1.z0.glb.clouddn.com/xxx004.m3u8">
    </video>
</div>
<p>测试播放</p>
</body>
</html>
~~~

**Comment by sampotts** [comment]
Please submit in English.
