### ISSUE TITLE
Fullscreen with HTML5 video broken

### ISSUE THREAD

**Issue by philipgiuliani** [sampotts/plyr#1468]
### Expected behaviour
When I watch a movie 16:9 in fullscreen on a 21:9 display, there should be a black bar on the left and right side.

### Actual behaviour
No black bars, and the video is cut-off at the bottom
![Bildschirmfoto 2019-06-17 um 15 47 33](https://user-images.githubusercontent.com/5446019/59609203-45a18780-9117-11e9-8525-eb0de7c09519.png)

### Steps to reproduce
1. Go to https://plyr.io/
2. Click on the fullscreen icon

### Environment
- Browser: Google Chrome
- Version: 75
- Operating System: macOS
- Version: Mojave

Worked fine with 3.5.2

**Comment by philipgiuliani** [comment]
Fixed with 3.5.5 :) Thanks @sampotts !

**Comment by sampotts** [comment]
Great! Thanks for closing this 👍
