### ISSUE TITLE
Plyr is not adapted to work without Internet!

### ISSUE THREAD

**Issue by HayGT** [sampotts/plyr#1471]
### Expected behaviour
Plyr should work autonomously without Internet,
### Actual behaviour
In fact, the icons are loaded from CDN!
### Environment

- Browser: Chrome
- Version: 74.0.3729.169
- Operating System: W10 1903 pro
- Version: 3.5.2

### Console errors (if any)
`plyr.min.js: 1 GET https://cdn.plyr.io/3.5.4/plyr.svg net :: ERR_INTERNET_DISCONNECTED`

For example in **node_modules \plyr\dist\plyr.js** there is such a line: iconUrl: "https://cdn.plyr.io/3.5.2/plyr.svg"

So what should I do? And are you going to fix it?

https://imgur.com/Q3WBB7v

**Comment by sampotts** [comment]
No ones forcing you to use the CDN. It’s the default to make it easier for most users. If you read the docs you can serve your own icon sprite. There’s nothing to “fix”, just some reading for you to do 👍
