### ISSUE TITLE
Incomplete display

### ISSUE THREAD

**Issue by zz1616611** [sampotts/plyr#1473]
I hope you delete not safe, XMLHttpRequest Web Sockets 
![aiss](https://user-images.githubusercontent.com/44898919/59958704-2458e680-94dd-11e9-8fda-07743da637f2.JPG)

**Comment by sampotts** [comment]
I’m not sure what the issue is. Please elaborate

**Comment by zz1616611** [comment]
> I’m not sure what the issue is. Please elaborate

I use expansion become like this Block XMLHttpRequest Web Sockets  
https://chrome.google.com/webstore/detail/gpgbpgdfipppcelfbdlbkhmibofknppj

**Comment by zz1616611** [comment]
@sampotts  I use expansion Become like this Block XMLHttpRequest Web Sockets  
https://chrome.google.com/webstore/detail/gpgbpgdfipppcelfbdlbkhmibofknppj

**Comment by sampotts** [comment]
Sounds like a terrible extension. I'm not sure what you think Plyr needs to do to "fix" this. You just need to disable the extension. Blocking XHR will break half of the internet for you.
