### ISSUE TITLE
when Download button is press it only shows the file

### ISSUE THREAD

**Issue by parknenok** [sampotts/plyr#1478]
When you try to click the download button it shows the mp3 file to download on a separate sceen than open the file location on where to save it, you have to download the file again or save source as..

**Comment by Code1110** [comment]
This can be fixed by adding the HTML5 attribute `download` to the download link. Example:
`<a href="28_47.mp3" download="mymp.mp3">Get Audio</a>`.

Sadly I don't have time to fix it myself.

**Comment by parknenok** [comment]
Thanks

**Comment by sampotts** [comment]
Cheers @Code1110 👍 We did have the `download` attribute at some point but it must have been a regression as part of a refactor I guess.
