### ISSUE TITLE
PIP on VIMEO iframe

### ISSUE THREAD

**Issue by KrisMerckx** [sampotts/plyr#1480]
How can I activate a "pip"-button on a VIMEO-iframe?

**Comment by sampotts** [comment]
Until it's supported via [player.js](https://github.com/vimeo/player.js/) it's not possible...

**Comment by StephanLuis** [comment]
Looks like Vimeo's player.js does now support pip!  A couple links about that are the [player.js github page](https://github.com/vimeo/player.js/) and their [demo player page](https://player.vimeo.com/api/demo/357274789).  

What is the best route to have this feature 'ported' to Plyr as quickly as possible?
