### ISSUE TITLE
Only remove controls from video

### ISSUE THREAD

**Issue by myin142** [sampotts/plyr#1482]
I am building a browser extension where I can add the plyr controls to an existing video. This works fine but I have difficulties to remove the controls again.

Currently it is only possible to destroy the controls along with the video. Would it be possible to just remove the controls and the events attached to the video?

**Comment by Hanchengluo** [comment]
.plyr__controls{display:none}

**Comment by myin142** [comment]
This only hides the controls. I want to remove everything from plyr but keep the video.
I already have a workaround that somehow works. But I do not think it removes everything, especially the events listeners.

**Comment by ritz078** [comment]
The `destroy` function should not remove the `video` element.

**Comment by myin142** [comment]
Yes this seems to restore the original `video` element again. But for my use case, it is still not an option. It does not keep the current playtime and on Youtube it will create a second `video` element. I assume because Youtube thinks the original is not valid anymore.
But I already found a solution that works since my last comment, so I will close this issue.
