### ISSUE TITLE
Doc on listeners not clear about return value

### ISSUE THREAD

**Issue by antonyoneill** [sampotts/plyr#1492]
I found the doc a little misleading for the listeners object. I initially added some analytical tracking to some of the buttons, `rewind`, `fast-forward`, `mute` but each of these stopped working.

For example:
```typescript
plyr = new Plyr("video", {
  listeners: {
    mute: event => {
      MyAnalytics.record('mute');
    },
  }
});
```

Only after I looked in the `listeners.js` file did I realise that my event listener had to return a true value.
https://github.com/sampotts/plyr/blob/7c442c93571fb5d75f96bff710e310d00e1289e9/src/js/listeners.js#L511-L518

Also happy to fix this doc issue, just keeping a track of all of these small things and I'll resolve them in one swoop.

**Comment by sampotts** [comment]
That looks like a bug for sure. Wouldn't you might be better off using events for analytics rather than the event listeners though?

**Comment by taion** [comment]
@sampotts We got bit by the same thing. This logic actually looks wrong, though. It looks like this is trying to mimic the browser behavior of preventing defaults when event handlers return `false`, in which case the check should be `returned !== false`, not just `returned`. Not returning a truthy value from a custom event handler should not block the default.

**Comment by sampotts** [comment]
> Not returning a truthy value from a custom event handler should not block the default.

Yep, for sure. Hence:

> That looks like a bug for sure. 

It's on my TODO list but happy to look at PRs to fix it if you're in a rush.

**Comment by taion** [comment]
We can close this out now.
