### ISSUE TITLE
Ajax load post list, the old audio will be reset

### ISSUE THREAD

**Issue by 0x0233** [sampotts/plyr#1503]
**ajax load post list , old video is ok.
the old audio will be reset.**

![3658508B4B50A4FA7D85CD8D57120915](https://user-images.githubusercontent.com/46622287/61444793-acb49500-a97e-11e9-919e-720ac9e46159.jpg)

**Comment by sampotts** [comment]
Please use the template and perhaps add a test case. This makes no sense at all.
