### ISSUE TITLE
Import module successfully but does not work

### ISSUE THREAD

**Issue by kien5436** [sampotts/plyr#1520]
I imported `plyr` like the documentation and webpack said it had compiled but nothing worked! All of my code had been broken after import it.

Here not working code: 
```
node_modules
  plyr
...
src
  js
    myfile.js
```

```js
import 'plyr'; // or import Plyr from 'plyr'

window.addEventListener('load', function(e) {
  
  console.log('loaded');

  Plyr.setup('.player', {
    debug: true,
  });
}, false);
```
Nothing shown, even the `log` command.

Then I copied `plyr.js` file into my `src/js` folder and it worked:
```
...
src
  js
    plyr.js
    myfile.js
```

```js
import Plyr from './plyr'

window.addEventListener('load', function(e) {
  
  console.log('loaded');

  Plyr.setup('.player', {
    debug: true,
  });
}, false);
```

**Comment by StephanLuis** [comment]
I had a similar problem see [css issue with images ](https://github.com/sampotts/plyr/issues/2149) Sounds like you may need to import css.  That step is not clear on documentation.  Solve your problem?

**Comment by kien5436** [comment]
> I had a similar problem see [css issue with images ](https://github.com/sampotts/plyr/issues/2149) Sounds like you may need to import css. That step is not clear on documentation. Solve your problem?

Thank you but it's not related to css. The last time I try it works as expected, so I close this
