### ISSUE TITLE
Want Audio Player Settings Off

### ISSUE THREAD

**Issue by SukhmanpreetSingh** [sampotts/plyr#1524]
I want to hide this settings (speed option) in my audio player ... How can i do this please help
![Screenshot_20190807_155030](https://user-images.githubusercontent.com/33250386/62615707-6c1bbc00-b92b-11e9-9d95-a1fcaf0107c9.JPG)

**Comment by joanroig** [comment]
@SukhmanpreetSingh how did you hide that?

**Comment by SukhmanpreetSingh** [comment]
> @SukhmanpreetSingh how did you hide that?

By hiding the css elements

**Comment by trijammer** [comment]
I've managed to remove it with an empty array in the player speed options:
``speed: { selected: 1, options: [] }``
