### ISSUE TITLE
The poster file gets downloaded several times

### ISSUE THREAD

**Issue by tobireif** [sampotts/plyr#1531]
The poster file gets downloaded three times.

Here's a screenshot (Chrome):

<img width="1238" alt="screenshot" src="https://user-images.githubusercontent.com/80411/62861689-8deab980-bd04-11e9-85af-8ee80d29b523.png">

I had found the ticket https://github.com/sampotts/plyr/issues/1355 "Poster is loaded twice", but in this case here it gets downloaded three times.

The page is password-protected, but I can answer any questions regarding my Plyr setup.

Here's the code:

HTML:
```
<video playsinline="playsinline" muted="muted"
  poster="images/video_cover.png">
  <source src="the_video.mp4" type="video/mp4"/>
</video>
```
JS:
```
function initPlayer() {
  var player = new Plyr("video", {
    iconUrl: "../../vendor/plyr/plyr.svg",
    controls: ["play-large", "play", "progress", "current-time"],
    blankVideo: "../../vendor/plyr/blank.mp4",
    fullscreen: {enabled: false},
    hideControls: false,
    storage: {enabled: false}
  });
}

window.addEventListener("load", initPlayer);
```
  It would be great if the poster file would get downloaded only once, max twice, but not three times and one after the other (see the screenshot).

**Comment by tobireif** [comment]
Perhaps Plyr could detect whether it already got loaded, and in that case not download it again?

**Comment by tobireif** [comment]
It would be great if the poster file would get downloaded only once.

**Comment by edeis53** [comment]
I am seeing this three times as well. 

I wonder what is the benefit of the progressive enhancement to have the poster set as a DIV in addition to on the video element?

**Comment by tobireif** [comment]
... and could there be an option for disabling anything that causes the additional downloads? (I also have a hosted video scenario.)

**Comment by tobireif** [comment]
It would be great if this could get fixed.

**Comment by sampotts** [comment]
This should be fixed in v3.5.7 but report back if not 👍

**Comment by tobireif** [comment]
I tried v3.5.7, but there were two issues:

The poster file gets downloaded two times. That's better than three times (thanks!), but one time would be better. Please re-open this ticket - it should stay open until the poster file gets downloaded only once.

The other issue: The player at https://tobireif.com/posts/layout_fun_with_css_grid/ gets destroyed.

Before:

<img width="792" alt="screenshot_before" src="https://user-images.githubusercontent.com/80411/74137835-d1a97780-4bf0-11ea-9c02-128449029ad3.png">

With v3.5.7:

<img width="790" alt="screenshot_after" src="https://user-images.githubusercontent.com/80411/74137847-d5d59500-4bf0-11ea-8e83-56b8d2a7c346.png">

It would be really great if you could ensure that updates don't break things 😀

The release notes contain this text: "This update contains CSS changes." I'd rather be able to update Plyr without having to dig through all the CSS changes and adapt my CSS.

Also reported at https://github.com/sampotts/plyr/issues/1680 .

**Comment by sampotts** [comment]
It gets loaded once for me on https://plyr.io/ - anyone else seeing issues? If they are then I'll re-open the issue. Feel free to dig into the code to take a look. 

![image](https://user-images.githubusercontent.com/719092/74142986-e0dcf500-4bf1-11ea-88f0-bc5bec25441c.png)

**Comment by tobireif** [comment]
Chrome screenshot of https://tobireif.com/posts/layout_fun_with_css_grid/ :

<img width="949" alt="screenshot" src="https://user-images.githubusercontent.com/80411/74150732-d4b16180-4c0a-11ea-81ae-e66806c25df2.png">
 
Chrome screenshot of https://plyr.io/ :

<img width="1043" alt="screenshot_2" src="https://user-images.githubusercontent.com/80411/74150587-8308d700-4c0a-11ea-85a8-2ba984171793.png">

**Comment by tobireif** [comment]
Firefox downloads it just once. I'll report the Chrome issue.

**Comment by sampotts** [comment]
It may be something else. I’ll check Chrome.

**Comment by tobireif** [comment]
If you find anything (eg a Plyr fix for the issue observed in Chrome), please also post the info at https://bugs.chromium.org/p/chromium/issues/detail?id=1050569 , so that they can close their ticket if it is/was a Plyr-issue and not a Chrome-issue.

**Comment by tobireif** [comment]
At https://bugs.chromium.org/p/chromium/issues/detail?id=1050569 they requested a network log capture ( https://www.chromium.org/for-testers/providing-network-details ), and then wrote "That log only shows it being downloaded once".
