### ISSUE TITLE
TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by eliezerfot123** [sampotts/plyr#1549]
Hi boys, For this moment I'm call to plry and execute the next errors.

TypeError: URL is not a constructor with 
const players = Array.from(document.querySelectorAll('audio')).map(player => new Plyr(player));

**Comment by sampotts** [comment]
You need a [polyfill](https://github.com/sampotts/plyr#polyfills) for [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL) then.
