### ISSUE TITLE
Caption from blob

### ISSUE THREAD

**Issue by kakaska** [sampotts/plyr#155]
Currently when I add a `<track>` with blob source like this:

```
blob:http%3A//www.domain.com/b1ffc6de-8aa0-46c5-8e5f-ba59a8d475dc
```

the player doesn't show the caption.

Debug message:

```
Caption track found; URI: blob:http%3A//www.domain.com/b1ffc6de-8aa0-46c5-8e5f-ba59a8d475dc
plyr.js:1 Detected unsupported browser for HTML5 captions - using fallback
plyr.js:1 TextTracks not supported so rendering captions manually
plyr.js:1 Successfully loaded the caption file via AJAX
```

Btw I don't understand the debug message because I use Chrome 48 and that supports textTracks

**Comment by SamPotts** [comment]
I will take a look. There were several bugs with VTT captions and WebKit browsers, hence rendering using the in built engine instead. I will have a look and see if things have changed though.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
