### ISSUE TITLE
Vi configuration

### ISSUE THREAD

**Issue by SoftCreatR** [sampotts/plyr#1551]
On Vi.ai, i can set options like IAB category and language. Checking Plyr's source revealed this:

```
        var params = {
          AV_PUBLISHERID: '58c25bb0073ef448b1087ad6',
          AV_CHANNELID: '5a0458dc28a06145e4519d21',
          AV_URL: window.location.hostname,
          cb: Date.now(),
          AV_WIDTH: 640,
          AV_HEIGHT: 480,
          AV_CDIM2: this.publisherId
        };
        var base = 'https://go.aniview.com/api/adserver6/vast/';
        return "".concat(base, "?").concat(buildUrlParams(params));
```

1. What exactly does that do?
2. Is it possible to improve the vi.ai configuration? English ads are not really interesting for my users. Also ads which are completely off topic.

**Comment by sampotts** [comment]
That configuration is for the demo. It's expected that you configure ads with Vi and then use the `publisherId` supplied for the ads configuration within Plyr as per the docs.
