### ISSUE TITLE
Cannot use Data URI for source (Chrome, Opera, maybe more)

### ISSUE THREAD

**Issue by calvintam236** [sampotts/plyr#157]
On v1.5.10, I can no longer user data uri for source. I got this error when calling plyr.source(datauri).
`Uncaught TypeError: Cannot use 'in' operator to search for 'sources' in datauri`

You can get a data uri file sample at issue #89 as that issue is not solved.

**Comment by SamPotts** [comment]
Please check the docs. v1.5 had breaking changes to the `source` api method.

**Comment by calvintam236** [comment]
@SamPotts You should update the API doc in the table. I didn't notice you wrote another section for source as in the API table it is showing the old method..

**Comment by SamPotts** [comment]
Just noticed that and edited :+1: Apologies for the confusion. I think it was a merge with the new get function of the `source` method.

**Comment by calvintam236** [comment]
I still get error message after switched to new source method..
```Uncaught TypeError: Cannot use 'in' operator to search for 'type' in d```

I used this: (String is allowed for sources)
```
player.source({
            type: 'video',
            sources: datauri
});
```

**Comment by SamPotts** [comment]
OK will give it a test...

**Comment by calvintam236** [comment]
So I figure it out..
Somehow the ```sources``` is not accepting string as expected. Plyr will work when using this: ```sources: [{src: datauri}]```, but not ```sources: datauri```...

**Comment by SamPotts** [comment]
Oh sorry yeah, I already updated the docs to mention that it needs to be an array of objects. I assumed you'd seen that part...

**Comment by calvintam236** [comment]
In the table before events states it can accept string for ```sources```.. Is that an error?

**Comment by SamPotts** [comment]
Yes, that was _before _ v1.5. An array is now required. I updated the docs after your initial comment: [#issuecomment-179611449]()

**Comment by SamPotts** [comment]
There's also a whole section dedicated to it now:
https://github.com/Selz/plyr#source-method

**Comment by calvintam236** [comment]
I am referring to this section
![screen shot 2016-02-08 at 7 41 28 pm](https://cloud.githubusercontent.com/assets/6436149/12907082/00c5c45a-ce9c-11e5-97aa-8d91af4d9e7b.png)

**Comment by SamPotts** [comment]
Ah yes, that needs updating, clearly.

**Comment by calvintam236** [comment]
@SamPotts I just updated the code with your new version, and source using data URI stuck at forever loading status. There is no error message under `plyr.media.error`, and empty `src` at `plyr.media.src`. Confirmed that data URI is entered into `source()` inside an array in `sources`.

My repo: https://github.com/calvintam236/media-plyr

**Comment by SamPotts** [comment]
I have looked in this again and just can't understand why it doesn't work using the `source` API. Using the exact same string on initial load is fine but dynamically adding it to the DOM means it just permanently loads. 

I don't really understand the benefit of using Base64 for something like this given the downsides of memory usage, increased bandwidth (base64 generally increases file size) and not being able to cache the content anyway.

**Comment by calvintam236** [comment]
There are use cases:
1. you want to embed to short video or audio files (e.g. less than 100k) in order to reduce several page requests for small files
2. You want to play the media using file upload without hosting a server. (File protocol would not work, so base64 is the only way to archive that

Have you add exclusion on data URI validation? I know there is one.

**Comment by SamPotts** [comment]
Not sure what you mean about the exclusion? Do you have a link? 

The odd thing is that loading a Data URI on initial load is fine, it's when a source is dynamically added that it just doesn't work. I verified the string is identical too, so it's very weird.

**Comment by calvintam236** [comment]
Actually the second paragraph is referring #165. I got mixed up as it was so long time ago.

I think the bug is caused by `source` API change before it wasn't the before that. (Still working around v1.3.2)

**Comment by SamPotts** [comment]
Well nothing changed regarding adding the source elements to the dom. It basically takes whatever 'src' attribute is specified, adds it to the element, injects it to the DOM.

**Comment by calvintam236** [comment]
Tested v1.6.8, and it works on Firefox. Chrome and Opera are not working. While debugging, I check the ```media.networkState``` value, and I get ```3```. Maybe it is an issue on webkit core?

**Comment by calvintam236** [comment]
Last checked on v2.0.7. Chromium core e.g. Chrome, Opera is not working. Safari & FF is working.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by aodinok** [comment]
This issue still there on latest version. Works in Safari, but infinite loading in Chrome.
