### ISSUE TITLE
Title: "Title to show" is not showing in Plyr 

### ISSUE THREAD

**Issue by musarano** [sampotts/plyr#1578]
Hi.

HLS.js Latest version
Plyr Versions:     3.5.6/plyr.min.js & 3.5.6/plyr.js

I have tried different approaches, but title is not showing in player.
Do i need to included in a very specific way?

Im using the example for HLS that shows under demo on Plyr.io and also using the suggestion:

Const player = new Plyr(video, { title: 'Testing Text', captions: {.....

Hope this helps!

Thank You

**Comment by sampotts** [comment]
It's used for accessibility currently. Later I'll display it in the UI. 

It's in the docs but should probably be in the options section:
https://github.com/sampotts/plyr#the-source-setter
