### ISSUE TITLE
cookie cross site resources

### ISSUE THREAD

**Issue by ericlaaper** [sampotts/plyr#1586]
Since today i got this error massage in chrome

A cookie associated with a cross-site resource at https://vimeo.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Hope you van find something to this.

Cheers,

Eric

**Comment by CloudyChris** [comment]
Same issue for YouTube.

**Comment by sampotts** [comment]
Not sure Plyr can do anything here. It's going to be a big issue when this hits. I suspect functionality will still work but feel free to contact YouTube and Vimeo and report back 👍
