### ISSUE TITLE
Title not displaying on video player in v3.5.4

### ISSUE THREAD

**Issue by NvVijayakumara** [sampotts/plyr#1587]
Hi, I'm using latest plyr.js (v3.5.4), I need to show title on video player, using code as below, but title not showing. Is it library bug or problem with my code?

HTML code..
``````
<video id="player"
               crossorigin="crossorigin"
               autoplay
               controls
               playsinline></video>
``````

JS code..
``````
const pr = new Plyr('#player', {
				title: 'Sample title'
			});
            plyr.setup(pr);
``````

Thanks..

**Comment by sampotts** [comment]
The title is currently only used for accessibility. I'll probably display it in the UI eventually. 

It mentions in the docs but probably needs to be in the options section also.
https://github.com/sampotts/plyr#the-source-setter
