### ISSUE TITLE
Hide controls on mouseover and focus

### ISSUE THREAD

**Issue by harispepic** [sampotts/plyr#1588]
Hi 🙂

Could you please make an option to hide the controls on mouse or focus movement when the video is paused or stopped?

Regards

**Comment by TheLoneUs** [comment]
You might be able to use the classes to hide controls when you want to:
You can do this for paused,stopped, etc.
```
.plyr.plyr--paused .plyr__controls {
  display: none;
}
```

**Comment by harispepic** [comment]
Many thanks! It worked for me 👍
