### ISSUE TITLE
Support for video-streaming?

### ISSUE THREAD

**Issue by babielmg** [sampotts/plyr#159]
Hello,

my agency http://babiel.com/en/sites/babiel/home.html is working for the German Federal Ministry for Economic Cooperation and Development (http://www.bmz.de/en/). They are very interested in using your videoplayer on their website, because of the great accessibility-support. Unfortunately your player does not support streaming of videos yet. Is this a future-issue for you? Do you have plans to implement such a feature?

I'm looking forward for your answer

best regards

Michael Gampe

**Comment by SamPotts** [comment]
Hey Michael, 

This is definitely on the cards. Currently the player only supports the standard progressive download which as you know, isn't ideal. I'm just weighing up the possible solutions at the moment. It seems Safari only supports HLS and everything else supports Media Source Extensions (to a mixed degree). Dash.js is a nice library that wraps MSE and seems to standardise it but still that leaves HLS. It's definitely the next big feature as the demand is there (I keep getting tweets about it too!) 

:+1:

**Comment by SamPotts** [comment]
There's another related issue, #39

**Comment by babielmg** [comment]
Sounds good! Thanks for your reply.

**Comment by AnthyG** [comment]
I have not used it yet, but maybe this could be used as a base for streaming media: https://webtorrent.io/

**Comment by friday** [comment]
Closing since streaming is possible and [documented](https://github.com/sampotts/plyr/#streaming) now. For more specific issues of support like handling captions or switching quality, see the current github issues, or create a new one if none of the current describes your problem.

For built in support see #289
