### ISSUE TITLE
SASS not working correctly, docs not correct either

### ISSUE THREAD

**Issue by dmcgrew** [sampotts/plyr#1601]
I am trying to import the Plyr SASS and I'm running into some issues with it. I took the src/sass folder and placed it into my project. I renamed that sass folder to "plyr." In my main SASS file I am importing the Plyr sass with `@import "plyr/plyr`

When I compile my SASS I get the following error.. 

`Error: no mixin named plyr-font-smoothing on line 7 of assets/styles/scss/plyr/base.scss`

That's weird because there's obviously a mixin with that name in mixins.scss which is imported before base.scss. If I go into mixins.scss and put a simple style in there like `body {background-color: red` it works, so its not like the mixins.scss file isn't being imported. 

Also, the SASS section in the docs says to import a file named bundle.scss but that file does not exist in the plyr project.

**Comment by DanielHuntleySBG** [comment]
Also having the same issue, was a solution provided?? Thanks!

**Comment by aristizabal95** [comment]
Haven't tried using the sass files on /src, but the `bundle.scss` file is indeed missing. So for now there's no easy ways to change the styles other than hardcoding each element?

**Comment by DanielHuntleySBG** [comment]
Sorry for the late reply but to resolve it in my sass file I imported the following.

```
$plyr-color-main: $green;

@import "~plyr/src/sass/plyr";
```
