### ISSUE TITLE
Can't detect "enterfullscreen" when "iosNative" is true.

### ISSUE THREAD

**Issue by Shaker-Hamdi** [sampotts/plyr#1604]
When I set `iosNative: true` I can't detect the event `enterfullscreen` on IOS, no matter what I do, even the event `webkitfullscreenchange` doesn't work.

Is there any way to detect if the video is full screen on IOS with `iosNative: true`?

I need this so that I can give a class to the player to set `::-webkit-media-text-track-container` to `block` so that the native caption/subtitle can be visible.

**Comment by sampotts** [comment]
I don't think there's a way to do this but I'll do some digging.

**Comment by sampotts** [comment]
I think the only way this can be done is to _assume_ a `play` event is an `enterfullscreen` event.

**Comment by Shaker-Hamdi** [comment]
@sampotts Thanks for the effort, I'll try that solution.

**Comment by spreaone** [comment]
I've tried different test to fire the exit fullscreen event on IOS but didn't manage too..

 @sampotts, could you confirm neither the plyr event "exitfullscreen" , or the "webkitendfullscreen" can't work on a IOS native=true fullscreen ? or by listening to fullscreen.active?   If not possible, is it a restriction from IOS ?  I want to simulate a btn return clic on exit fullscreen . but this event doesn't fire.
