### ISSUE TITLE
play-function iOS

### ISSUE THREAD

**Issue by Ninos** [sampotts/plyr#1619]
Hey there,

I'm using following function:
```javascript
player = new Plyr(jQuery(video).find('.video-player').get(0), {
    iconUrl: jQuery(video).data('icon'),
    fullscreen: {
        enabled: true,
        fallback: true,
        iosNative: true
    }
});

player.on('ready', function () {
    player.play();
});
```

On firefox.. all's working fine (video is playing after loading. On iOS (iphone) the video is not playing after running the .play()-function. Is this a bug or restriction by iphone?

Kindest regards

**Comment by sampotts** [comment]
Play must be triggered by a user event on iOS. It looks like you're trying to do autoplay (which is an option btw). It _should_ be possible with the video muted to autoplay though.

**Comment by Thandohimself** [comment]
@sampotts [https://plyr.io/#youtube](url) does not play on iOS, is this also true on your side?
