### ISSUE TITLE
Wrong version in JS files

### ISSUE THREAD

**Issue by laukstein** [sampotts/plyr#1622]
**/dist** js files having `version: "3.1.3"` while currently expected to be 3.5.6

https://github.com/sampotts/plyr/blob/74e3990604698b1f2af3ed51e65b0ca820c1d624/dist/plyr.polyfilled.mjs#L250

**Comment by sampotts** [comment]
That version is unrelated to Plyr, it's from a polyfill. Thanks for checking though.

**Comment by laukstein** [comment]
@sampotts, are you saying Plyr code doesn't mention its version?
