### ISSUE TITLE
React Player GitHub is a broken link in readme.md

### ISSUE THREAD

**Issue by thatrobotdev** [sampotts/plyr#1624]
Hello!
In the readme.md, under **Plugins and Components,** there is a link to a react repo https://github.com/xDae/react-plyr, but it is a broken link. @xDae, are you still working on this project? Do you know where it is located?

[There are a couple of alternatives too](https://github.com/search?q=react+plyr) if we are looking to replace the link with a new one.

**Comment by sampotts** [comment]
Feel free to PR with an updated link 👍

**Comment by chintan9** [comment]
You can try this one.

https://github.com/chintan9/plyr-react

**Comment by thatrobotdev** [comment]
Fixed in #1654

**Comment by sampotts** [comment]
Cheers, as per the other issue, I'll get a new version out soon.
