### ISSUE TITLE
Demo video for Vimeo is promoting their web player

### ISSUE THREAD

**Issue by thatrobotdev** [sampotts/plyr#1626]
Hello!
I was looking at the [site's Vimeo demo](https://plyr.io/#vimeo), and it highlights a video talking about Vimeo's player, which I thought was weird to advertise because it seems to be a different product to the plyr media player.

**Comment by sampotts** [comment]
If you could find another video on Vimeo that has captions, I'd happily swap it out 👍

**Comment by thatrobotdev** [comment]
Awesome! Fixed in #1653.

**Comment by sampotts** [comment]
Cheers! I'll get a new version out soon with a load of fixes in, including this one.

**Comment by thatrobotdev** [comment]
Thanks! 😁
