### ISSUE TITLE
Fitting video within container

### ISSUE THREAD

**Issue by shravan2x** [sampotts/plyr#1634]
Plyr seems to have an issue where the video height often overflows the height of the container. Other users have reported this in issues like #611.

This seems to be because Plyr sets a `height: auto` on the `<video>` element at https://github.com/sampotts/plyr/blob/master/src/sass/base.scss#L24. So the video always fits the full width of the container causing the height to overflow when the aspect ratio of the container is higher than that of the video.

In my brief testing, it seems this could be resolved by changing the height to `100%`. This way, the video responsively fits within the container it's given.

Is there some other purpose that setting height to auto has?

**EDIT**: It seems that https://github.com/sampotts/plyr/blob/master/src/js/plugins/preview-thumbnails.js#L628 also assumes black bars above and below. This is only the case for horizontal videos. Vertical videos have these bars on the left and right causing the scrubbing thumbnails to be stretched a lot.

**EDIT 2**: I've made a few changes (~5 pieces of code) to the library on my local setup and it supports a "responsive" mode correctly i.e. the video *contains* itself within in the bounds of the plyr container. It resizes when the container size changes and so do the thumbnail, scrubber and poster. I could possibly create a PR for it.

**Comment by AkgunFatih** [comment]
create a pr i cant fix it

**Comment by shravan2x** [comment]
@AkgunFatih I made a PR with my changes. I'd appreciate help testing it if you can.

**Comment by sampotts** [comment]
This should be fixed in v3.5.7 👍
