### ISSUE TITLE
Youtube demo no-longer loads on chrome

### ISSUE THREAD

**Issue by isholaomotayo** [sampotts/plyr#1638]
### Expected behaviour
When you download the code and try the demo on Google chrome the youtube player should work as expected and load the video
### Actual behaviour
The Video loads partially and the controls do not show up
### Steps to reproduce
Fork Plyr, and create a new branch in your fork, based on the develop branch

To test locally, you can use the demo. First make sure you have installed the dependencies with npm install or yarn. Run gulp to build while you are working, and run a local server from the repository root directory. If you have Python installed, this command should work: python -m SimpleHTTPServer 8080. Then go to http://localhost:8080/demo/

Click on the youtube link, while using google chrome

Video does not load completely stops at ``` event: canplaythrough```

```event: ready``` never fires 
### Environment

- Browser: Google Chrome
- Version: Version 79.0.3945.79 (Official Build) (64-bit)
- Operating System: Mac OSx Catalina
- Version: 10.15.2

### Link to where the bug is happening

https://plyr.io/#youtube

**Comment by isholaomotayo** [comment]
Hey, found the problem, an ad blocker was blocking the ads SDK and this prevented the player from working.

Everything is fine

**Comment by TroyWolf** [comment]
Maybe not the same thing, but I find the supplied codepen Youtube demo does not work in Chrome. Works in Firefox. In Chrome, the player loads and initial frame, but it won't play. 
https://codepen.io/pen?template=GGqbbJ
