### ISSUE TITLE
how can I let user change the quality of the video without uploading the video in other qualities!?

### ISSUE THREAD

**Issue by HaliAlduhoky** [sampotts/plyr#1640]
I have a lot of videos as 1080p so after installing this script.
how can I let user change the quality of the video without uploading the video in other qualities!?

**Comment by Wykerd** [comment]
I don't think that is possible. I would use something like ffmpeg to convert the video to the other resolutions.

**Comment by sampotts** [comment]
There's no way to do it client side plus it'd make no sense anyway given they'd have to download the largest quality to downscale which would be a waste...
