### ISSUE TITLE
cdn.plyr.io lacks IPv6 support

### ISSUE THREAD

**Issue by ikomwrestling** [sampotts/plyr#1641]
cdn.plyr.io lacks IPv6 addresses and thus resources (JavaScript) from it can't be received using IPv6.

Since the CDN seems to be served by Fastly, which has great IPv6 support, it should hopefully be a simple fix by asking Fastly support to enable IPv6 on the map, as per their [IPv6 documentation](https://docs.fastly.com/en/guides/ipv6-support).

Thank you.

**Comment by sampotts** [comment]
I've spoken with Fastly and have enabled IPv6 but it'll take a while for DNS to update of course. I'll report back once it's updated 👍

**Comment by sampotts** [comment]
https://dnschecker.org/#AAAA/cdn.plyr.io

**Comment by sampotts** [comment]
I'm closing this one now as it looks like it's working with IPv6

```bash
% dig cdn.plyr.io AAAA +short
dualstack.plyr.map.fastly.net.
2a04:4e42:f::442
```

**Comment by ikomwrestling** [comment]
cdn.plyr.io is working over IPv6 now. Thanks.
