### ISSUE TITLE
add & remove an event listener for the `timeupdate` event

### ISSUE THREAD

**Issue by jasonz18** [sampotts/plyr#1644]
Hello,

How to add & remove an event listener for the `timeupdate` event.

Thanks!

**Comment by sampotts** [comment]
Hey there,

You can use `player.on('timeupdate', handler)` where `player` is a reference to the Plyr instance and `handler` is a reference to the handler you want to fire. There's also `.off` to remove the listener. The events also bubble so you can use `addEventListener` on a parent of the player.

**Comment by sampotts** [comment]
https://github.com/sampotts/plyr#methods
