### ISSUE TITLE
Captions where VTT is hosted on another site

### ISSUE THREAD

**Issue by robgalvinco** [sampotts/plyr#1664]
I know this is really not your issue, but am wondering if you have suggestions. My VTT caption file is stored on amazon CDN andmy video is playing from my website (different domain).

So when the video tries to load I get

Unsafe attempt to load URL https://s3.amazonaws.com/blahblah/file_uploads/242683/attachments/5a2/2fe/5f3/Attention.txt from frame with URL https://mydomain.com/. Domains, protocols and ports must match.

Is there any other option to pass in the VTT text?

**Comment by sampotts** [comment]
Hey, you need to add the `crossorigin` attribute. Also, the VTT files require the `.vtt` extension and `text/vtt` mime-type.

**Comment by SwhiteMHC** [comment]
Where do you ad the crossorigin attribute when using the Plyr?
