### ISSUE TITLE
Can't resolve 'jquery' with es6 and webpack, but not using jquery at all

### ISSUE THREAD

**Issue by marioloncarek** [sampotts/plyr#1682]
### Expected behaviour
Init of plyr

### Actual behaviour
Im getting error that im missing jquery, im not using jquery on project, and really dont want to, thats why i used plyr, but cant get it to work:

`bundle.js?ver=1:15865 Uncaught Error: Cannot find module 'jquery'
    at webpackMissingModule (bundle.js?ver=1:15865)
    at Object../node_modules/plyr/dist/plyr.min.js (bundle.js?ver=1:15865)
    at __webpack_require__ (bootstrap:19)
    at Module../static/js/components/VideoPlayer.js`

### Steps to reproduce

I copied the code from docs:

`import Plyr from "plyr";

export default class VideoPLayer {

    constructor() {
        this.init();
    }

    init() {
        const players = Array.from(document.querySelectorAll(".js-player")).map(p => new Plyr(p));
    }

}`

### Environment

- Browser: All
- Version: Latest from npm
- Operating System: OSX
- Version: Latest

### Console errors (if any)
check actual behaviour

### Link to where the bug is happening
local

**Comment by marioloncarek** [comment]
also i tried all version available inside dist and src folder

**Comment by sampotts** [comment]
Not sure with this one. There's only one reference to jQuery here:
https://github.com/sampotts/plyr/blob/master/src/js/plyr.js#L59

**Comment by marioloncarek** [comment]
@sampotts my webpack config was the issue, thanks for your time!
