### ISSUE TITLE
The target origin provided does not match the recipient window's origin

### ISSUE THREAD

**Issue by oguilleux** [sampotts/plyr#1689]
I'm working locally : "http://locahost/myproject". Since updating from 3.5.6 to 3.5.8, I get this error and it completely fails to init plyr :

www-widgetapi.js:159 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost').

Any idea on how to solve this ? Thanks !

**Comment by sampotts** [comment]
Any other errors? That error is unrelated and can be safely ignored

**Comment by oguilleux** [comment]
You're right I had that error before just never noticed it.

It seems to a css problem :

This rule seems to overriden (videos.scss line 15)
``` 
.plyr__video-wrapper {
  height:100%;
} 
```

by this rule (videos.scss line 26)

``` 
.plyr__video-embed, .plyr__video-wrapper--fixed-ratio {
  height:0;
} 
```

**Comment by oguilleux** [comment]
Confirmed. It was that css problem. Solved it by overriding that rule with my own css.

**Comment by sampotts** [comment]
Hmm if that's an issue for you, it may also be for others. That deceleration is in there to allow the player to calculate the ratio (using the `padding-bottom` trick) based on the size of the video (if using YouTube or Vimeo).
