### ISSUE TITLE
Width problem for full page videos

### ISSUE THREAD

**Issue by Reqrefusion** [sampotts/plyr#1719]
I wrote a code to send the m3u8 links to a page by using the get method to watch the video as a full page. However, the new update does not appear as a full page. Although it covers the entire height, its width does not cover the page. I was leaving the sample link below. Normally I would think that such a thing was my fault, but as I said, this corruption happened with the new version.

[Example](https://fullhdcizgifilmizle.com/iframe_m3u8.php?url=https://vod02.cdn.web.tv/am/8c/am8cvvsejym_,240,360,480,720,1080,.mp4.urlset/master.m3u8)

**Comment by sampotts** [comment]
I think it's because you have the player within an element with the`plyr` classname. Removing the `plyr` class from the parent `<div>` fixes it for me... 

![image](https://user-images.githubusercontent.com/719092/75600131-da121580-5aff-11ea-92af-f5a2144bc507.png)

**Comment by 20040714Mike** [comment]
Removing that div doesn't help at all. The width is still 100% to screen.
