### ISSUE TITLE
Ads only using vi.ai ?

### ISSUE THREAD

**Issue by kfe908** [sampotts/plyr#1726]
Am I able to use my own ad videos before the main video or is there only a vi.ai support (this would be horrible)? I cannot find anything regarding own content in the documentation.

**Comment by Steejo** [comment]
Hey kfe908, the player also accepts VAST/VMAP tags.

`	ads: {
      enabled: true,
      tagUrl: ''
    }`

**Comment by sampotts** [comment]
As above, use the `tagUrl` option. https://github.com/sampotts/plyr#options
