### ISSUE TITLE
YouTube requires no simultaneous playing of videos

### ISSUE THREAD

**Issue by chovy** [sampotts/plyr#1735]
Is there a way to make only one video play at a time?

YouTube terms require it and I have a page with multiple videos.

**Comment by sampotts** [comment]
I've replied in Slack, this is possible as per this demo:
https://jsfiddle.net/zkn8yhba/2/

**Comment by chovy** [comment]
I'm getting this errorr when I try to implement your code.


`www-widgetapi.js:221 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://127.0.0.1:8080').`

**Comment by chovy** [comment]
I got it working.
