### ISSUE TITLE
Preview Thumbails / vtt shows one big image

### ISSUE THREAD

**Issue by tolew1** [sampotts/plyr#1740]
### Expected behaviour
Show the preview thumbnails using vtt
### Actual behaviour
It shows the entire image at the beginning and empty the remainder of the time
### Environment

- Browser: Chrome
- Version: 80
- Operating System: Windows 
- Version: 10

### Link to where the bug is happening

What's wrong with this vtt. Here is part of it

```
WEBVTT

00:00:00.000 --> 00:00:05.000
https://omcdndev.example.net/vthumbs/686zkxq4ihj/5e736ff2e57e6/sprite.jpg#xywh=0,0,120,60

00:00:05.000 --> 00:00:10.000
https://omcdndev.example.net/vthumbs/686zkxq4ihj/5e736ff2e57e6/sprite.jpg#xywh=120,0,120,60

00:00:10.000 --> 00:00:15.000
https://omcdndev.example.net/vthumbs/686zkxq4ihj/5e736ff2e57e6/sprite.jpg#xywh=240,0,120,60

00:00:15.000 --> 00:00:20.000
https://omcdndev.example.net/vthumbs/686zkxq4ihj/5e736ff2e57e6/sprite.jpg#xywh=360,0,120,60


```

**Comment by sampotts** [comment]
Please create a codesandbox / jsfiddle / codepen for us to test this. As you'll see on the demo site, it can work fine if setup correctly.

**Comment by tolew1** [comment]
@sampotts  thanks for suggestion. Not sure how I can do that because it's using HLS from my server.  I've been struggling with this for hours now. It works perfect on videojs which I switched from to this nice player.

There is one difference I just noticed on your webvtt files on your demo is they are numbered.  1,2,3 4, etc Could that cause it not to parse correctly? My webvtt is made by a php library and have worked fine before now. 

```
WEBVTT

1
00:00:00.000 --> 00:00:01.000
100p-00001.jpg#xywh=0,0,178,100

2
00:00:01.000 --> 00:00:02.000
100p-00001.jpg#xywh=178,0,178,100

3
00:00:02.000 --> 00:00:03.000
100p-00001.jpg#xywh=356,0,178,100

4
00:00:03.000 --> 00:00:04.000
100p-00001.jpg#xywh=534,0,178,100
```

**Comment by tolew1** [comment]
Seems like there is something weird on the page. There is some conflict because on a new page it seems to work.

**Comment by jackguoAtJogg** [comment]
@tolew1 How did you get it to work with hls video? Is not working for me for mp4 or hls video.

**Comment by tolew1** [comment]
> @tolew1 How did you get it to work with hls video? Is not working for me for mp4 or hls video.

@jackguoAtJogg Honestly I didn't get it working. I switched to videojs and have been using that ever since.

**Comment by jackguoAtJogg** [comment]
@tolew1 I see, thank you for the response.
