### ISSUE TITLE
YouTube videos do not show the quality selector

### ISSUE THREAD

**Issue by leovicio** [sampotts/plyr#1742]
tested with html5 is ok but with youtube it only shows the speed selector

**Comment by sampotts** [comment]
This is expected. Have a search through the issues and you'll see why it was removed. It's flaky. The YouTube API exposes a method to allow quality selection but it's merely a suggestion and 99% of the time it's ignored, rendering the feature useless and as such it was removed.

**Comment by shivamkb17** [comment]
Is there any way to add quality selector for youtube and vimeo in plyr. 
I am dispretevely searching about this.

**Comment by sampotts** [comment]
> Is there any way to add quality selector for youtube and vimeo in plyr.
> I am dispretevely searching about this.

As above, search issues, I have covered this several times. It's possible to add to Vimeo now as they've added support but it's yet to be added to Plyr.
