### ISSUE TITLE
Prevent HTML5 video from being downloaded

### ISSUE THREAD

**Issue by MykolaPasiuk** [sampotts/plyr#1751]
It`s will be a very good feature for web sites with not free content

**Comment by jaapmarcus** [comment]
The only way to implement this with some kind of DRM license and stream it with HLS or Dash.

The file still needs to be downloaded to the browser to be viewable by the user and the source files can still be accessed by the viewer.

**Comment by sampotts** [comment]
As above. All you can do is make it mildly more difficult by disabling the context menu (which is done by default) but any competent developer could find the source URL. HLS or Dash are your friend here.
