### ISSUE TITLE
How can I activate a "pip"-button on a youtube-iframe?

### ISSUE THREAD

**Issue by jenrrycordero** [sampotts/plyr#1765]

**Comment by sampotts** [comment]
Unfortunately not supported via the YouTube API.

**Comment by jiri-thiemel-te** [comment]
Hi,

I have an idea. Something I've seen several players, especially on news portals. It's similar to the YouTube miniplayer they've recently introduced. This could be handled as  "fallback PiP" in a case when the provider's API doesn't support native PiP (like in the case of YouTube). Similar approach as the fallback for the fullscreen. With option to configure it a bit (disable or enforce this PiP). Do you already have something like this on your (presumably already long) list?

Thanks!
