### ISSUE TITLE
How to play your own video with local file?

### ISSUE THREAD

**Issue by Karkoliv** [sampotts/plyr#1766]
It works fine as long as i don't change the src of the video to "video.mp4" when I do that I always get an error "Access to video at 'file:///C:/Users/user/Desktop/video-player/video.mp4' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.". What can I against this error?

**Comment by jaapmarcus** [comment]
Easiest way/100% fail save to is to install an Apache / Nginx server look up some tutoruials on the internet.

**Comment by sampotts** [comment]
If you clone the repo locally, you can run `yarn` or `npm install` to install the packages and then `gulp` and it'll open a browser window. You can then add an `mp4` in the demo folder, and reference it in the HTML. Failing that, you can do as above.
