### ISSUE TITLE
pause on minized

### ISSUE THREAD

**Issue by ajoykarmakar459** [sampotts/plyr#1774]
I am playing a youtube video. Everything works perfectly but when I minimized the browser it's paused the audio and I have to play the video manually with the media notification button. can we resolve the problem? I mean when I minimized the browser still it will play the audio and don't let the player pause the media.

Plyr version is - 3.5.10

**Comment by sampotts** [comment]
As far as I'm aware, it's not possible to detect when the browser is minimized. You could write your own code to detect when the page loses focus perhaps but it's not something I'd want to build into the player at this point.
