### ISSUE TITLE
Poster not showing for Audio HLS Streaming

### ISSUE THREAD

**Issue by mksasi** [sampotts/plyr#1775]
We are using HLS stream and when the stream contains only audio, the player is not displaying the poster and instead white page is being displayed. 

When inspecting the poster element exist in the dom but are not getting displayed.
<div class="plyr__poster" style="background-image: url('https://www.example.com/thumb.png')" style="width:100%;"></div>

When playing the audio, the white page is displayed above the video controls. Can you please look into this and provide a fix? Thanks

**Comment by sampotts** [comment]
This is a duplicate. It’s worth searching for existing issues next time. I’ll get to the issue ASAP.
