### ISSUE TITLE
Fast forwarding 10 sec

### ISSUE THREAD

**Issue by suryansh55** [sampotts/plyr#1777]
Is there a way to fast forward or rewind 10 sec or more in video in mobile devices s by double tapping the screen like in youtube ?

**Comment by transiscodev** [comment]
There isn't a native function for that but I actually found this issue request when looking up a premade way to do that, so I will try something in my project and get back to you with that

**Comment by transiscodev** [comment]
`function up(sec){
    player.currentTime = player.currentTime + sec
}`
Here it is as a function. You can bind it to an event or button.
**player** is the variable for the player element.
**sec** is the time in seconds that the track will advance or back up. Positive numbers will move it forward, negative numbers will move it back. I will see about making a pull request to add them as UI buttons.

**Comment by transiscodev** [comment]
Oops there was actually button controls in the API already, however I'll look into the double tap thing

**Comment by suryansh55** [comment]
> 
> 
> Oops there was actually button controls in the API already, however I'll look into the double tap thing



> 
> 
> `function up(sec){ player.currentTime = player.currentTime + sec }`
> Here it is as a function. You can bind it to an event or button.
> **player** is the variable for the player element.
> **sec** is the time in seconds that the track will advance or back up. Positive numbers will move it forward, negative numbers will move it back. I will see about making a pull request to add them as UI buttons.

Hi sorry for the late reply , unfortunately I'm not that well equipped with javascript and html coding can you drop a codepen link to a code ? It would really be helpful .
Thank you

**Comment by transiscodev** [comment]
It's hard baked into my service but I'll continue to try to make a working codepen

**Comment by transiscodev** [comment]
Here is a completed [https://codepen.io/transiscodev/pen/JjYZvYb](CodePen). There is a few things to note.

- Different JS Source
I'm using a CDN version of my own fork of plyr that is nearly identical but removes one function that reserves double clicking/tapping for full screen. You can find it at https://github.com/transiscodev/plyr

I know the codepen is a bit messy and I could stand to document it a little more but that's what I have for the moment. I hope that's useful to you, I'll try to update it more this week.

That said, it's production ready and already fully implemented on my service. I need to also credit [this blog](https://sadesmith.com/2019/01/12/blog/replicating-youtube-apps-double-tap-to-seek-feature) for the original source code that I modified for use with plyr.io

-

**Comment by suryansh55** [comment]
> 
> 
> Here is a completed [https://codepen.io/transiscodev/pen/JjYZvYb](CodePen). There is a few things to note.
> ## Different JS Source
> 
> I'm using a CDN version of my own fork of plyr that is nearly identical but removes one function that reserves double clicking/tapping for full screen. You can find it at https://github.com/transiscodev/plyr
> 
> I know the codepen is a bit messy and I could stand to document it a little more but that's what I have for the moment. I hope that's useful to you, I'll try to update it more this week.
> 
> That said, it's production ready and already fully implemented on my service. I need to also credit [this blog](https://sadesmith.com/2019/01/12/blog/replicating-youtube-apps-double-tap-to-seek-feature) for the original source code that I modified for use with plyr.io

Thank you so much dude this is very helpful I really required it for my site but wasn't able to solve this problem . I will surely mention you in my site 
Thanks again

**Comment by transiscodev** [comment]
Of course! I'd love to check it out, is there a repo or website?

**Comment by suryansh55** [comment]
> 
> 
> Of course! I'd love to check it out, is there a repo or website?

It is a website but NSFW so I won't be posting it here but if github has a private message options
Again thanks a lot

**Comment by transiscodev** [comment]
> > Of course! I'd love to check it out, is there a repo or website?
> 
> It is a website but NSFW so I won't be posting it here but if github has a private message options
> Again thanks a lot

There is no such feature, just shoot me an email

**Comment by transiscodev** [comment]
> > Of course! I'd love to check it out, is there a repo or website?
> 
> It is a website but NSFW so I won't be posting it here but if github has a private message options
> Again thanks a lot

Email me, [github@yallinthehall.33mail.com](mailto:github@yallinthehall.33mail.com)

**Comment by transiscodev** [comment]
> > Of course! I'd love to check it out, is there a repo or website?
> 
> It is a website but NSFW so I won't be posting it here but if github has a private message options
> Again thanks a lot

Email me, github@yallinthehall.33mail.com

**Comment by transiscodev** [comment]
Email me, github@yallinthehall.33mail.com

**Comment by suryansh55** [comment]
hey there , thanks again for your help but unfortunately I was not able to implement your code and rather went on and developed my own piece of app . Still thanks a ton I guess I will be closing this thread now
