### ISSUE TITLE
Adding Quality Selector to plyr when using HLS Stream

### ISSUE THREAD

**Issue by rahulrsingh09** [sampotts/plyr#1780]
I was looking at a lot of PR's if this feature is supported but came across a lot where  it is closed and the implementation or the CRUX is not shared. 
In one such PR is saw CRUX implementation , and tried to use it along with plyr and Hls, but seems like it dosent work can you please shed some light, if this feature is supported or not. 

I have added this code but the selector fails to add the details from the manifest to the plyr controls..

```
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <title>HLS Demo</title>
      <link rel="stylesheet" href="https://cdn.plyr.io/3.5.10/plyr.css" />
      <style>
         body {
         max-width: 1024px;
         }
      </style>
   </head>
   <body>
      <video preload="none" id="player" autoplay controls crossorigin></video>
      <script src="https://cdn.plyr.io/3.5.10/plyr.js"></script>
      <script src="https://cdn.jsdelivr.net/hls.js/latest/hls.js"></script>
      <script>
         (function () {
         	var video = document.querySelector('#player');
         	var playerOptions= {
         		quality: {
         			default: '720',
         			options: ['720']
         		}
         	};
         	var player;
         	 player = new Plyr(video,playerOptions);
         	if (Hls.isSupported()) {
         		var hls = new Hls();
         		hls.loadSource('https://content.jwplatform.com/manifests/vM7nH0Kl.m3u8');
         				//hls.loadSource('https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8');
         	hls.attachMedia(video);
         	hls.on(Hls.Events.MANIFEST_PARSED,function(event,data) {
  
 // uncomment to see data here 
//                   		console.log('levels', hls.levels);  we get data here but not able to see in settings . 
          
         		playerOptions.quality = {
         			default: hls.levels[hls.levels.length - 1].height,
         			options: hls.levels.map((level) => level.height),
         			forced: true,
             // Manage quality changes
             onChange: (quality) => {
             	console.log('changes',quality);
             	hls.levels.forEach((level, levelIndex) => {
             		if (level.height === quality) {
             			hls.currentLevel = levelIndex;
             		}
             	});
             }
         };
        });
       }
         
          // Start HLS load on play event
          player.on('play', () => hls.startLoad());
         
          // Handle HLS quality changes
          player.on('qualitychange', () => {
          	console.log('changed');
          	if (player.currentTime !== 0) {
          		hls.startLoad();
          	}
          });
         })();
         
      </script>
   </body>
</html>
```

**Comment by sampotts** [comment]
Can you please use the existing issue for this.

**Comment by sampotts** [comment]
https://github.com/sampotts/plyr/issues/1741

**Comment by rahulrsingh09** [comment]
@sampotts But most of the issues are not tracked , can you please shed some light , i will add my findings in the comment in #1741

**Comment by sampotts** [comment]
They are tracked but I get very little time to look at issues. My job gets more painful when there's 5 issues for the same thing because people are too lazy to use the search... 

I have a life, family and a full time job so as you can imagine I have to prioritise where I spend the *little* time I have. For me at the moment the next big thing will be making a v4 that can handle plug-ins so it's easier for other developers to write add-ons such as HLS quality options. 

I don't know a huge amount about HLS so I can't help but the best place to discuss this is in *one issue* rather than spread across multiple issues.

**Comment by rahulrsingh09** [comment]
@sampotts i really appreciate the help you are giving to the community and having such a library that helps a hell lot of devs and keeping all of them happy is really difficult task, unfortunately i was able to search all the issues but die to no outcome in them i thought of raising another but now i have added my findings there in #1741 . Looking forward to a solve .

**Comment by sampotts** [comment]
I'll have a read through when I get a chance. HLS obviously seems very popular in recent times so I'm keen to get up to speed on it and hopefully get some features out for it.
