### ISSUE TITLE
Customize the scrubber handle

### ISSUE THREAD

**Issue by h08831n** [sampotts/plyr#1784]
I want to change progress bar's style it's means i want change handlare and heaight and width of progress bar how to do this?

**Comment by iSpongee** [comment]
.dz-progress {
    height: --px; // in pixels
    width: --; // in pixels
}

**Comment by sampotts** [comment]
> .dz-progress {
> height: --px; // in pixels
> width: --; // in pixels
> }

Totally wrong but thanks for responding.

**Comment by sampotts** [comment]
This will be possible in a future update using CSS Custom Properties. For now you can build your own version of the SASS or write some CSS to overpower the default CSS but I'd just wait. That sort of change wouldn't be desperate anyway.

**Comment by sampotts** [comment]
See the latest version:
https://github.com/sampotts/plyr#customizing-the-css
