### ISSUE TITLE
jQuery and Webpack clash

### ISSUE THREAD

**Issue by bhavin-nakrani** [sampotts/plyr#1792]
### Expected behaviour
This package must work without Jquery. As mentioned in ReamMe
***No frameworks - written in "vanilla" ES6 JavaScript, no jQuery required***

### Actual behaviour
Jquery is undefined while we build using webpack

### Steps to reproduce
Remove Jquery from package.json and run webpack build

### Link to where the bug is happening
https://github.com/sampotts/plyr/blob/master/src/js/plyr.js#L59

```
if ((window.jQuery && this.media instanceof jQuery) || is.nodeList(this.media) || is.array(this.media)) {
            // eslint-disable-next-line
            this.media = this.media[0];
        }
```
This code should like below:
```
if ((this.media instanceof jQuery) || is.nodeList(this.media) || is.array(this.media)) {
            // eslint-disable-next-line
            this.media = this.media[0];
        }
```

**Comment by sampotts** [comment]
jQuery isn't a requirement, that's correct. It seems like the issue isn't with Plyr but your own code? This is the first time this has ever been reported.
