### ISSUE TITLE
[Accessibility] Multiple issues causing poor accessibility user experience.

### ISSUE THREAD

**Issue by johnnguyen0215** [sampotts/plyr#1794]
My team’s application needs to be WCAG compliant and we are using the Plyr library to meet various accessibility requirements for our audio player. Since the adoption of Plyr in our app, there have been several reviews on it from accessibility experts and a few concerns have been raised. I’d like to give these concerns some visibility and provide suggestions to get them addressed. I apologize if there is some overlap here with other issues, I did look through the other accessibility related ones and was not able to find any others that have the same needs as us. Although there may be a few conflicts with: https://github.com/sampotts/plyr/issues/905

Some additional background info on our app:
- It is expected to be accessible on Chrome and Firefox using the JAWS screen reader tool which is only available on Windows.
- Our application has more fine-tuned accessibility requirements in the sense that our users are more sensitive to information overload, many of them are children. 

### Audio Player Progress Bar Slider

1 - The issue we are facing with the audio progress slider is: When the audio is playing and the progress slider is tab-focused or focused with the virtual cursor, the current time is being constantly announced to the screenreader user. This is a problem for us because it is overloading the user with information that they do not want to hear continuously. 

![Screen Recording 2020-04-23 at 01 39 AM](https://user-images.githubusercontent.com/7530508/80080329-5294c180-8506-11ea-91bc-bdb27c2b3a7f.gif)

Proposed Solutions: 
- Adding a single flag to make the `aria-valuenow`, `aria-valuemax`, `aria-valuenow`, and `aria-valuetext` conditional or a flag for each one?
- Have the attributes get updated/announced in set intervals, the interval being passed in as a prop.

I understand that the default screenreader behavior for this scenario is to constantly announce the elapsed time and that this requirement is something that is specific to our needs, but would like to know whether you are open to these changes to avoid forking.

2 - The aria-valuemax attribute is being read out by the screenreader as a large number since this value is the total duration in seconds. If we can implement the conditional property defined in 1) then this would be resolved. Right now we are deleting this attribute on load, but this is not an ideal solution.

### Audio Player Current Time
The Current Time text is being read as 3 o’clock for an innerText value of 3:00. In order to fix this, we would most likely need to add some visually hidden text with the numbers separated by commas then add an aria-hidden to the element, much like what is being done here https://github.com/bbc/simorgh/issues/2996

<img width="467" alt="Screen Shot 2020-04-23 at 2 03 00 AM" src="https://user-images.githubusercontent.com/7530508/80080621-b919df80-8506-11ea-9d77-1c35b403b5a6.png">

**Comment by nehaabrol87** [comment]
Following.

**Comment by brennanyoung** [comment]
Just want to add that it's relatively to hack plyr 'from the outside' - I mean, you can, with a short, independent javascript, set an aria-label into plyr's timecode element, which may perform any clever string substitutions, and keep those substitutions in sync with plyr's on-screen timecode using (e.g.) timeout or setinterval, without plyr breaking down. One of the many reasons I like plyr is that it is so tolerant of hacks like these, and that's mainly because plyr

But again, please study the caveats in my previous post before you do this!
