### ISSUE TITLE
Cors GoogleCloud Webvtt

### ISSUE THREAD

**Issue by vitorhugosg** [sampotts/plyr#1797]
Hi.

I have one problem.

![image](https://user-images.githubusercontent.com/17458174/80151174-fd9d8d80-858f-11ea-9aa5-ad161331b225.png)

I input webvtt with images in google cloud:
![image](https://user-images.githubusercontent.com/17458174/80151269-23c32d80-8590-11ea-9c5c-cf734d06d5d2.png)

but, i have problem with cors in google chrome.

How can I solve this problem?

Very thanks

**Comment by sampotts** [comment]
Google would need to enable CORS on that resource which I can't see happening?
