### ISSUE TITLE
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN"

### ISSUE THREAD

**Issue by afuno** [sampotts/plyr#1816]
There is a chance that this problem is directly related to your library (primary source: https://github.com/redxtech/vue-plyr/issues/171).

I tried to abandon the VuePlyr library, but the problem persisted.

If I change only the version from `^3.6.1` to `~3.5.10`, then everything is deploying successfully.

**Comment by julmot** [comment]
I have exactly the same problem:

```
JisonParserError: Parse error on line 1:
...ar(--plyr-control-padding,calc(var(--plyr-control-spacing,10px)*0.7))) - (var(-...
------------------------------------------------------------------------^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN"
```

@sampotts

**Comment by p4rse** [comment]
Same issue here!

Thanks guys for the trick!
Downgraded to `3.5.10` and it worked.

**Comment by julmot** [comment]
The issue is caused when usign `postcss-calc`, respectively I'm using `postcss-preset-env` which seems to embed it.

**Comment by francowhyline** [comment]
Same here.
If I downgrade to 3.5.10 It compiles, but if the video is a vimeo one, it throw an error (using with ngx-plyr).

**Comment by francowhyline** [comment]
> Hmm I guess this is a change as a result of the CSS Custom Properties. Any more info on how I can reproduce this locally? How are you including the CSS?
> 
> I _might_ be able to do a CSS build without the custom properties stuff in.

I am building an angular application with "node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --configuration=develop"

**Comment by KristianJohansenVakwerk** [comment]
I just tried to downgrade but get a error when I run npm install saying there is No matching version found for vue-plyr@~3.5.10? 

Anyone gets the same error?

**Comment by gorelegacy** [comment]
same issue using node v12.16.2 (npm v6.14.4)

**Comment by p4rse** [comment]
@sampotts 
> ... How are you including the CSS?

```
@import '../../node_modules/plyr/dist/plyr.css';
```

`3.5.10` works fine!

**Comment by Ka1ki** [comment]
Same issue.

**Comment by janein** [comment]
Would be nice if this would be fixed soon, as this release contains some nice and important bugfixes! :)

**Comment by sampotts** [comment]
Will the two PRs above fix this? It's hard for me to test...

**Comment by mesopa** [comment]
Same problem with Gatsby when running gatsby build.

```sh
Generating JavaScript bundles failed

Parse error on line 1:
...r(--plyr-control-padding,calc(var(--plyr-control-spacing,10px) * .7))) - (var(-...
------------------------------------------------------------------------^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN"
```

**Comment by janein** [comment]
@sampotts I tested it and the build runs through with these changes. :+1:

**Comment by sampotts** [comment]
> @sampotts I tested it and the build runs through with these changes. 👍

Awesome, cheers. I'll get a build out shortly 👍

**Comment by sampotts** [comment]
Can you folks give v3.6.2 a go? https://github.com/sampotts/plyr/releases/tag/v3.6.2

**Comment by afuno** [comment]
@sampotts I checked. Everything is fine. Thanks.

**Comment by sampotts** [comment]
Excellent 👍 Thanks goes to @Bashev 👍

**Comment by davidfilat** [comment]
Works fine on in my project too! Thank you @sampotts !

**Comment by mesopa** [comment]
Works perfectly with Gatsby, thank you very much.
