### ISSUE TITLE
the issue about the playing block

### ISSUE THREAD

**Issue by olevod** [sampotts/plyr#1817]
### Environment

- Browser: google chrome
- Version:81.0.4044.113
- Operating System: windows
- Version: windows 10 business

**Comment by sampotts** [comment]
Too vague.

**Comment by olevod** [comment]
hi
thank you for your response. please check the playing url:
https://europe.olevod.eu/vod/20200317/ynviyAId/mp4/ynviyAId.mp4/master.m3u8
when we play or seek, it is always blocked and stop playing there

Sam Potts <notifications@github.com> 于2020年4月30日周四 下午12:17写道：
