### ISSUE TITLE
How does customization work?

### ISSUE THREAD

**Issue by afuno** [sampotts/plyr#1827]
The documentation says that the main color is in this variable:

```scss
--plyr-color-main
```

But updating the value for this variable doesn't help. The update is present in CSS, but it is ignored.

<img width="242" alt="Снимок экрана 2020-05-08 в 16 17 07" src="https://user-images.githubusercontent.com/2853419/81409257-75021e00-9147-11ea-8d4a-f30c8860a941.png">

That is, this method doesn't work.

In the file settings/colors.scss there is this line:

```scss
$plyr-color-main: var(--plyr-color-main, hsl(198, 100%, 50%)) !default;
```

Manipulations with this line also lead to nothing. Plus, the need for the `$plyr-color-main` variable in the code is very doubtful.

Please tell me what I need to do so that the main color in all places of the player is changed?

**Comment by afuno** [comment]
And tell me, please, why does it work this way?

<img width="300" alt="Снимок экрана 2020-05-08 в 16 24 10" src="https://user-images.githubusercontent.com/2853419/81409820-7849d980-9148-11ea-9d8a-54974822577c.png"><img width="300" alt="Снимок экрана 2020-05-08 в 16 24 18" src="https://user-images.githubusercontent.com/2853419/81409835-7d0e8d80-9148-11ea-803e-07652a365f41.png">

**Comment by sampotts** [comment]
Are you using the latest CSS? You need to use the latest version for this support. It does work. You can try it on https://plyr.io. You can also use the CDN CSS... https://cdn.plyr.io/3.6.2/plyr.css

![image](https://user-images.githubusercontent.com/719092/81410844-c1b81a00-9184-11ea-9cba-f4a85fa032ff.png)

**Comment by afuno** [comment]
@sampotts Yes 🤔🤔🤔

<img width="400" alt="Снимок экрана 2020-05-08 в 16 37 55" src="https://user-images.githubusercontent.com/2853419/81411015-5c473780-914a-11ea-8e48-bac55ed0a135.png">

**Comment by afuno** [comment]
@sampotts This way I connect styles for Plyr:

```scss
@import '~plyr/src/sass/plyr.scss';
```

As a result, in CSS, I see what I sent above.

**Comment by sampotts** [comment]
Try just importing the CSS then? Perhaps the SASS loader you’re using is stripping the CSS Custom Properties stuff out? Or it’s cached? I don’t know. It’s definitely not outputting the correct CSS. I kept the source as SASS so it was backwards compatible. V4 will likely be CSS only.

**Comment by afuno** [comment]
@sampotts I have everything works fine for Tailwind CSS. I can conclude that everything is configured normally. For Tailwind CSS, I use the same variables that you describe in your documentation.

**Comment by sampotts** [comment]
Did you try importing the CSS file then, rather than SASS? Tailwind doesn’t use SASS either. I’m familiar with their setup as l’ve used it myself on a few projects.

**Comment by sampotts** [comment]
```javascript
@import '~plyr/dist/plyr.css';
```

**Comment by afuno** [comment]
@sampotts It doesn't help either. I don't understand why. I have a variable from plyr in root. It is ignored in the SCSS (or CSS) plyr code that I import.

If we talk about Tailwind CSS, then in addition to their .js config, I have custom scss files.

I have a problem exclusively with your library. In other sass files, all the manipulations work for me.

**Comment by sampotts** [comment]
I’ll double check tomorrow but I think the problem lies elsewhere. As you can see in my screenshot, it works on the demo. That’s using the SASS from the package.

**Comment by afuno** [comment]
I understand, yes. But I really don't understand how this is possible. I have no super complex wrappers and settings for SCSS in my project. And in other places, such variables work without problems. And in general, the question is elementary at first glance. I don't understand why this problem occurs.

**Comment by afuno** [comment]
@sampotts I was able to solve the problem. I had the vue-plyr library installed. Although it worked with 3.6.2, it still broke everything. I don’t know all the details, but I got rid of it and reinstalled Plyr.

**Comment by aubreyz** [comment]
Like the OP here I am confused by this. I am using the most recent distro. 

Adding stuff in the HTML like

<video data-poster="assets/videos/jumbo/jumbo.jpg" class="js-playervid1sm" style="--plyr-control-icon-size: 28px;">

does absolutely nothing at all. Neither does the HTML code used in the example in the docs. 

However adding the below to my custom  css (which is loaded after the plyr.css **does** change things to green. 

:root {
  --plyr-color-main: #1ac266;
}

Using 

.js-playervid1sm {
  --plyr-color-main: #1ac266;
}

however does nothing at all, which would be the most useful thing to be able to do. 

Either I am thick or the docs need tweaking. So far only the "all players" css seems to work but not the inline css or the specific-player css. What am I missing here?
