### ISSUE TITLE
Load quality based on internet speed

### ISSUE THREAD

**Issue by akbarjoudi** [sampotts/plyr#1832]
Hi, is the video loaded based on the quality of the internet?

**Comment by sampotts** [comment]
For YouTube and Vimeo yes. For HTML5, you'd have to use something like HLS or DASH.

**Comment by akbarjoudi** [comment]
How to use HLS in plyr؟

**Comment by bekee** [comment]
Any update on updating the player current quality display when HLS changes quality?
