### ISSUE TITLE
plyr__poster does not let me to click in youtube links

### ISSUE THREAD

**Issue by amirmp3** [sampotts/plyr#1833]
Hi thanks for this fantastic player.
when I used a Youtube link to show my video I saw one issue, plyr__poster does not let to select youtube links while the Plyr is in pause situation.
When I set "disply:none" for plyr__poster I can click and it does not have any problem. 
<img src="http://bayanbox.ir/view/7350954576376359381/Screenshot-2.jpg">

**Comment by sampotts** [comment]
This is fixed in 3.6.6 👍🏼

**Comment by AlecRust** [comment]
I'm confused. I thought this was one of the main features of Plyr 😄 

I am (and I assumed many others) using Plyr to somewhat "protect" an unlisted YouTube video from being sharable.

An example is creating video course content hosted on YouTube but unlisted, and embedding with Plyr on the pages of a paid course. Although easily obtained with technical knowledge, this mask protects the paid content from being viewed directly or the link obtained for the majority of users.
