### ISSUE TITLE
Prevent events from being fired when programmatically caused

### ISSUE THREAD

**Issue by araynimax** [sampotts/plyr#1854]
For example you want to achieve the following:
If you seek on the player, you round the currentTime-property. 
For this I'm using the 'seeked' event.
But if you call the setter of `currentTime`, it will also fire the `seeked` event.

An easy solution would be to have an option: `disableEvents` which will disable every event while `true`.

**Comment by akuma06** [comment]
You could when doing your listener store the seeked time inside a variable and do nothing in your listener when it's the same time, no?
```js
let lastSeek = null;
player.on('seeked', () => {
  // do the thing you want to do in the listener...
  if (lastSeek !== player.currentTime) {  // You only change and round the currenTime if it's different from the last time the user seeked
    const timeRounded = Math.round(player.currentTime);
    lastSeek = timeRounded; // Change this before so you don't have race condition
    player.currentTime = timeRounded;
  }
});
```

**Comment by araynimax** [comment]
I think this feature is unnecessary. Sorry for bothering you.

I use this to prevent events from being fired, which is basically my mentioned solution.

```js
const skipEvent = {};

const onEvent = (eventName, handler) => {
    this.player.on(eventName, (...args) => {
        if (skipEvent[eventName] === true) {
            skipEvent[eventName] = false;
            return;
        }

        handler(...args);
    })
};

onEvent('seeked', () => {
    skipEvent.seeked = true;
    player.currentTime = Math.round(player.currentTime);
});
```
