### ISSUE TITLE
preventDefault() for events.

### ISSUE THREAD

**Issue by araynimax** [sampotts/plyr#1855]
It would be nice to have the possibility of preventing events.  (I don't mean the button events)

**Comment by gurupras** [comment]
Could you describe what you're trying to achieve? I think with the early listeners, you can prevent default behavior.

```
const plyr = new Plyr({
  listeners: {
    play () { return false }
  }
})
```

This plyr _will not play_ unless played programmatically. Here's a [pen](https://codepen.io/gurupras/pen/vYLOObe)

**Comment by araynimax** [comment]
Yes I know that but listeners dont support all events listed under https://github.com/sampotts/plyr#events
It only supports events listed here: https://github.com/sampotts/plyr/blob/master/src/js/config/defaults.js#L215

That's why i've written "preventDefault() for **events**".
