### ISSUE TITLE
'Copy Link' and 'More video' buttons not clickable for Youtube embed

### ISSUE THREAD

**Issue by mteplitski** [sampotts/plyr#1856]
### Expected behaviour

- Hovering on 'Copy link' has cursor effect, and clicking should do something
- Something should happen when clicking on thumbnails under 'More Videos'

### Actual behaviour
- Nothing happens

### Steps to reproduce
1. go to https://plyr.io/#youtube
2. hover over video and try to click anything under 'more video' or 'copy link'

### Environment

- Browser: Chrome
- Version: 83
- Operating System: macOS
- Version: Catalina

### Console errors (if any)
![image](https://user-images.githubusercontent.com/45952579/83312267-ab2f3c80-a1df-11ea-889f-6148980c8792.png)

### Link to where the bug is happening
https://plyr.io/#youtube

**Comment by sampotts** [comment]
Please search next time 👍
