### ISSUE TITLE
Possible bug in scrubber handle/thumb

### ISSUE THREAD

**Issue by aubreyz** [sampotts/plyr#1868]
In Edge (but not in chrome) the fill in the scrubber thumb is not filling. This is at least on Windows 10, current version of Edge and Chrome

You can see the problem by looking at this 
https://codepen.io/sampotts/pen/YzwXOoP

On Chrome there is a nice scrubber blob
On Edge, the blob is there but only the border and shadow are present not the fill (you cant see them against this particular background but they are there). I have tried adding a fill with Custom css

--plyr-range-thumb-height: 30px;
--plyr-range-thumb-background: #ff00ee;

This makes the thumb bigger in both browsers but the fill only happens in Chrome. It's not a codepen issue. 

Some screenshots from the above codepen in the respective browsers
![scrubber issue](https://user-images.githubusercontent.com/25100168/84390528-a448f680-abef-11ea-95d2-9d9e991d336c.png)

**Comment by sampotts** [comment]
The same bug has been raised just 2 below yours in the list. Please search next time 👍 

https://github.com/sampotts/plyr/issues/1865
