### ISSUE TITLE
 Multi-Audio Track selection for video player

### ISSUE THREAD

**Issue by singhcool** [sampotts/plyr#1896]
Please add a feature to add the multiple audio tracks for video player

**Comment by sampotts** [comment]
It's been added already 👍

**Comment by singhcool** [comment]
Hi @sampotts When we can expect this feature to live?

**Comment by sampotts** [comment]
When I get around to it or someone opens a PR. I can't guarantee anything. I only get to work on this in my spare time which is very limited these days.

**Comment by singhcool** [comment]
Okay, Thanks, @sampotts

**Comment by ScribbleNerd** [comment]
Any updates on this?

**Comment by andreasunterhuber** [comment]
@sampotts any update on this one?
