### ISSUE TITLE
Total Watchtime

### ISSUE THREAD

**Issue by rohitcoder** [sampotts/plyr#1901]
It would be good if you add an option to extract WatchTime of any video through plyr. It should show exactly correct watchtime (it means it should exclude all skipped part, rewind, forward parts).

For example: if a video is having length of 1:00

And i start playing from 0:00 to 00:10 and then i pause and forward to 00:20 to 1:00 then watchtime should be 50 seconds

I am trying to integrate on my side, by adding some JS between different events, still it would be good if there is a feature something like this in future.

**Comment by rohitcoder** [comment]
I managed to achieve this, just get total video duration and under timeupdate event you can calculate watch time using current video length and total video length

**Comment by seckinyavuz95** [comment]
can you share your code with us. i dont find timeupdate event.
