### ISSUE TITLE
JS and CSS files do not load with VPN on

### ISSUE THREAD

**Issue by jlebouch76** [sampotts/plyr#1905]
I'm using Glightbox which had integrated Plyr for their video player. Yesterday as i was trying to set up my lightbox on my dev site, I observed that the plyr.css and plyr.js were not loading if my NordVPN connection was on. I tried with all different VPN protocols and the result was the same. Nothing changed when trying with different browsers. 
As soon as i removed my VPN, the videos properly launched in their lightbox.

Is there something you could do?   THanks

**Comment by DELNEGEND** [comment]
Blind guessing: maybe NordVPN and/or Plyr's CDN are blocking each others ip addresses.
Try using jsDelivr or something else instead.

**Comment by sampotts** [comment]
I'm not sure there's anything we can do. It might be worth asking NordVPN to investigate?

**Comment by NJCLous** [comment]
Hi Sam and others,

I noticed the same issue and contacted NordVPN. They're looking into it and may whitelist the Plyr CDN in the near future. Other VPNs may still block cdn.plyr.io though.

A way around this is to use the Plyr files "locally", from our own server. 

For that purpose it would help me enormously if the Plyr dist folder could be made available for download again. 

Sam, I know you removed this folder deliberately and that the files can be installed using npm or similar from https://unpkg.com/browse/plyr (discussion #2094) but for people like me, with only basic JavaScript knowledge, that's a very steep learning curve. Installing npm on Windows leads to lots of warnings about "additional software" to be installed which make me feel uncomfortable. Simply downloading the files and using them from my own server, as was possible until early this year, was much easier for me.

Thanks for your time, and for Plyr in general!

Niels

**Comment by sampotts** [comment]
Hi Niels, 

I just checked on my NordVPN connection and the assets do load for me, albeit slower but that's expected due to the VPN overhead. 

As for the `dist` folder, unfortunately it just made the developer experience more painful since PRs often included the built files, making reviewing pull requests even more painful. As you've found, the best way to get the built files is via unpkg, here:
https://unpkg.com/browse/plyr@3.6.9/dist/

Cheers

**Comment by NJCLous** [comment]
Hi Sam,
Thanks for your super-fast reply!

Do you have CyberSec on with your NordVPN? I think that's where the actual blocking occurs.
I understand what you're saying about the dist folder but using unpkg gets too complicated for me. Is there another channel by which you could share the dist folder for download - for instance via the plyr.io website? The way PRs wouldn't get confused, but people with limited JavaScript knowledge could still use the scripts "in the simple way". I'm just being selfish now!
Niels

**Comment by NJCLous** [comment]
Hi Sam,

Thanks for your super-fast reply!

Do you have CyberSec on with your NordVPN? I think that’s where the actual blocking occurs.

I understand what you’re saying about the dist folder but using unpkg gets too complicated for me. Is there another channel by which you could share the dist folder for download – for instance via the plyr.io website? The way PRs wouldn’t get confused, but people with limited JavaScript knowledge could still use the scripts “in the simple way”. I’m just being selfish now!

Best regards,

Niels

**Comment by NJCLous** [comment]
Hi Sam,

NordVPN's CyberSec service has now whitelisted the Plyr CDN domain - so Plyr works without having to disable NordVPN or its "ads and malicious sites" blocker.

Thanks for looking into this issue - and glad it's now resolved!

Best regards,

Niels
