### ISSUE TITLE
Can't display mkv subtitles

### ISSUE THREAD

**Issue by lmotascp** [sampotts/plyr#1921]
I'm using plyr to reproduce a mkv file, but the mkv subtitles associated with that file don't get displayed.

I can't use `<track kind="captions" label="English captions" src="filetosubtitles.srt" srclang="en" default />` because the subtitles are inside the mkv file itself.

Is there any way to fix this?

### Expected behaviour
Display subtitles

### Actual behaviour
Only plays the video without any subtitles.

### Steps to reproduce
Just need to load a mkv file.

### Environment

- Browser: Chromium Browsers
- Version:
- Operating System: W10

**Comment by sampotts** [comment]
Yep, as per docs and HTML5, the supported format is VTT 👍

**Comment by sampotts** [comment]
Also, mkv isn't a web format. You want mp4 or webp.
