### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by TaraOShea** [sampotts/plyr#1938]
Implementing with react - using [https://github.com/chintan9/plyr-react](https://github.com/chintan9/plyr-react) as a guideline however svg icons are not appearing. Code below:

`    useEffect(() => {
        player = new Plyr('.js-plyr', { controls: [
            'play-large',
            'play',
            'progress', 
            'current-time', 
            'duration', 
            'mute',
            'volume',
        ] });
        player.source = {
            type: 'video',
            sources: [
              {
                src: props.src,
                type: 'video/mp4',
                size: 720,
              }
            ],
        }
    })
`

**Comment by sampotts** [comment]
Head on over to https://github.com/chintan9/plyr-react/issues 👍
