### ISSUE TITLE
Android rotate in fullscreen not working in combination with Vimeo

### ISSUE THREAD

**Issue by gboston** [sampotts/plyr#1940]
I'm using Plyr in combination with Vimeo and this is giving issues on Android when going fullscreen and rotating the device. It seems that the offset isn't recaculated when turning the device.

### Expected behaviour

The video should resize to the new screen rotation.

### Actual behaviour

The screen turns black.

### Steps to reproduce

1. Open https://plyr.io/#vimeo
2. Set it fullscreen
3. Rotate to landscape mode

### Environment

- Browser: Chrome
- Version: 84.0
- Operating System: Android / Mac
- Version: /

### Link to where the bug is happening

https://plyr.io/#vimeo

**Comment by sampotts** [comment]
Thanks, the PR is merged and deployed in v3.6.3 👍
