### ISSUE TITLE
Pause media when scrolled out of viewport

### ISSUE THREAD

**Issue by Hrishikesh-K** [sampotts/plyr#1980]
Hello. I'm trying to pause media when any part of it is scrolled out of viewport. I'm doing that in vanilla javascript like this:

My helper functtion to check if element is out of viewport from any side:

```JS
var isOutOfViewport = function(elem)
  {
    var bounding = elem.getBoundingClientRect();
    var out = {};
    out.top = bounding.top < 0;
    out.left = bounding.left < 0;
    out.bottom = bounding.bottom > (window.innerHeight || document.documentElement.clientHeight);
    out.right = bounding.right > (window.innerWidth || document.documentElement.clientWidth);
    out.any = out.top || out.left || out.bottom || out.right;
    out.all = out.top && out.left && out.bottom && out.right;
    return out;
  };
```

Then, in my document's load event, I do this:

```JS
var allMedia = document.querySelectorAll('video, audio');

document.addEventListener('scroll', function()
  {
    for (var i = 0; i < allMedia.length; i++)
      {
        var isMediaOut = isOutOfViewport(allMedia[i]);
        if (isMediaOut.any || isMediaOut.all)
          {
            allMedia[i].pause();
          }
      }
  });
```

This works fine for video, but, not for audio. I suspect it's because the audio element is replace by Plyr in such a way that the actual `<audio>` tag is invisible. So, the browser isn't able to detect if the element is in or out of viewport. Does anyone have a workaround?

**Comment by vincentorback** [comment]
You need to pause your Plyr instances which I guess you have somewhere in your code? Like `var player = new Plyr(); player.pause()`.

**Comment by Hrishikesh-K** [comment]
Yes, but, when I have multiple players, how do I determine which one to pause?

This is how I'm setting the players up:

```JS
var players = Plyr.setup('.js-player',
  {
    controls: ['play-large', 'play', 'progress', 'current-time', 'mute', 'volume', 'captions', 'settings', 'pip', 'fullscreen'],
    disableContextMenu: false,
    i18n:
      {
        qualityBadge:
          {
            2160: '4K',
            1440: '2K',
            1080: 'FHD',
            720: 'SHD',
            480: ''
          },
      },
    iconUrl: '/images/plyr-sptire.svg',
    iconPrefix: 'mi',
    quality:
      {
        default: 720,
        options: [2160, 1440, 1080, 720, 480, 360, 240, 144]
      },
    ratio: '16:9',
    tooltips:
      {
        controls: true,
        seek: true
      }
  });
```

and adding the class `js-player` to the audio/video players. If I use `players.pause()`, it'll pause all my players.

Is there any way to determine the correct instance?

**Comment by vincentorback** [comment]
I think you should set up each player individually and store them in an object or array. Then you can pause each when ever you want.

```
<video id="test"></video>

const players = {}
const options = {}

Array.from(document.querySelectorAll('.js-player')).forEach(el => {
    players[el.id] = new Plyr(el, { ...options })
})
```

I would also check out IntersectionObserver if your scroll performance gets bad with many players.

**Comment by Hrishikesh-K** [comment]
But the problem is not the inability to pause. I'm able to pause the media otherwise, for example, when the device loses internet connection or when tab is switched, I'm easily pausing all video and audio on the page with `pause()`. The problem is that because the `<audio>` tag gets replaced by a `<div>` and has no height of its own, the browser it not able to check for its presence in viewport. This isn't the case for videos. Videos have a height and thus, they can be checked by browser for their presence in viewport. I also can't select the `<div>` element that gets rendered by Plyr because I can't use `pause()` on that `<div>`.

**Comment by Hrishikesh-K** [comment]
But the problem is not the inability to pause. I'm able to pause the media otherwise, for example, when the device loses internet connection or when tab is switched, I'm easily pausing all video and audio on the page with `pause()`. The problem is that because the `<audio>` tag gets replaced by a `<div>` and has no height of its own, the browser it not able to check for its presence in viewport. This isn't the case for videos. Videos have a height and thus, they can be checked by browser for their presence in viewport. I also can't select the `<div>` element that gets rendered by Plyr because I can't use `pause()` on that `<div>`.

So, while the method you suggested can work to pause each media easily, I'm not sure how I can determine the element moving out of viewport. I don't think IntersectionObserver can help with 0 height elements too, but, I'll check it anyways, just to be sure.

**Comment by vincentorback** [comment]
Ah yes sorry, I should have included that you can access some Plyr elements with `player.elements`. For example I think you should look for `player.elements.container` when scrolling.

**Comment by Hrishikesh-K** [comment]
I didn't know about that. However, that gave me another idea. Instead of my code line: `var isMediaOut = isOutOfViewport(allMedia[i]);`, I now made it `var isMediaOut = isOutOfViewport(allMedia[i].parentElement);`. It works fine both for audio as well as video. I wonder why that didn't hit me before.

Thanks a lot for the help!
