### ISSUE TITLE
plyr.fullscreen.enter() nor working on safari desktop

### ISSUE THREAD

**Issue by tbntdima** [sampotts/plyr#1981]
Basically all in the title :)
I'm trying to programmatically enter fullscreen, and it works everywhere except safari.

**Comment by tbntdima** [comment]
Ended up setting:
```js
  fullscreen: {
    enabled: true,
    fallback: 'force',
  },
```
in options.

**Comment by sampotts** [comment]
It needs to be triggered by a user input/event. Just calling `plyr.fullscreen.enter()` won't work, it needs to happen in an event binding.
