### ISSUE TITLE
Setting previewThumbnails in HTML markup

### ISSUE THREAD

**Issue by Hrishikesh-K** [sampotts/plyr#1983]
Hello.

It would be great if we could set preview thumbnails for a video my specifying it in the HTML markup itself, maybe using  a custom element or a VTT track itself (for example, `<track kind = "thumbnails" src = "<url>"/>`)

The problem is, it's easy to set the thumbnails if there's just one video on a page, it can directly go inside the JS used to initialize Plyr. However, when there are multiple videos on the same page, it's probably not possible to specify it for each video if the script is added just once on the page (before `</body>`).

It can be possible by using the source setter, but then, it's probably too much juggling to see which video is being played and set the thumbnails accordingly. 

So, if there's no other way to add preview thumbnails, it'd be great if the way I suggested (or any better way) is implemented. If I had the skills, I'd have submitted a PR for review, but, I'm pretty basic at using JavaScript.

**Comment by Hrishikesh-K** [comment]
I found a workaround. I add my thumbnails in the `<video>` tag as a custom attribute, say `thumbnails = "path"`. Then, load in Plyr using `.getAttribute()` method. Seems to work for me.

**Comment by mahdiar** [comment]
Thanks!
