### ISSUE TITLE
ads tagURL conflicting with every custom URL!

### ISSUE THREAD

**Issue by kfe908** [sampotts/plyr#1990]
Setting tagURL e.g. to

"https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator="

like in the link: https://codepen.io/nightsurge/pen/NVQGyJ works fine. But changing it to a custom link (https://myurl.com/vast.xml) , the tagURL will not get loaded at all. Chrome console says: failed due to https://imasdk.googleapis.com/js/sdkloader/ima3.js
which is present in config/defaults.js

How can we overcome the problem?

**Comment by sampotts** [comment]
I'd need to see the tag url to actually debug this.

**Comment by kfe908** [comment]
I guess I got it solved due to "strict-origin-when-cross-origin". I set it in the respective nginx location and it worked. 
Thanks for your quick response.

**Comment by sampotts** [comment]
Go for it. Remember this is open source. Anyone familiar with ads should understand how it works. You have a tag URL, you pass it in as an option, you get ads. The tag defines how those ads are displayed.

**Comment by arunkumartdr** [comment]
I have seen this : https://codepen.io/nightsurge/pen/NVQGyJ  but it does't works

**Comment by sampotts** [comment]
Works for me. If you have an ad-blocker or are using Firefox (which has one built-in) then of course you won't see the ads. This is from Chrome latest on that exact URL. I had to disable my Pi Hole. 

<img width="535" alt="CleanShot 2021-09-21 at 21 40 12@2x" src="https://user-images.githubusercontent.com/719092/134164220-a6590d9e-e59d-4559-bf4c-ba12d9423ffd.png">

**Comment by arunkumartdr** [comment]
Oh soory , I have a adblock extension....
