### ISSUE TITLE
audio still playing even the modal is closed and cant play in other browsers

### ISSUE THREAD

**Issue by whoami15** [sampotts/plyr#1995]
### Expected behaviour
The audio should stop once the modal is closed, and the video can be played in browsers, see CodePen.
### Actual behaviour
The audio is still playing even if the modal was closed and the video can't be played on some browsers, even in codepen
### Steps to reproduce
Check demo here:
https://codepen.io/whoami15/pen/JjKWarv

Open the demo
Play the video
If played, close the modal
### Environment

- Browser: Google Chrome
- Version: Version 86.0.4240.111 
- Operating System: Windows 10
- Version: 20H2

### Console errors (if any)
None
### Link to where the bug is happening
https://codepen.io/whoami15/pen/JjKWarv

**Comment by sampotts** [comment]
The modal issue is something you need to solve yourself - e.g. add an event listener to when the modal closes and stop the player. It's not functionality that should be built into Plyr. 

I can see an issue in latest Chrome. It works fine outside of an iframe (see https://plyr.io) so there must be something funky going on with CodePen. I'll take a look when I get a chance.

**Comment by whoami15** [comment]
yes @sampotts , forgot to close this issue. I already solved it as I help to solve this issue #1996
