### ISSUE TITLE
Play Youtube video from external button

### ISSUE THREAD

**Issue by ninjaclan** [sampotts/plyr#1996]
Hi, I dont know if this is currently supported so Im asking if its possible to play the youtube video without clicking the current overlay button but from another button inside the main html.

For example: 
https://i.imgur.com/ATpqiE2.jpg

**Comment by whoami15** [comment]
You'll just have to add a button for that, which will trigger the `player.play()`

`<button type="button" class="btn id="watch_btn">Start Watching</button>`

```javascript
$("#watch_btn").click(function(){
        player.play();
        $('#watch_btn').hide();
});```

**Comment by ninjaclan** [comment]
Thank you so much!

**Comment by whoami15** [comment]
> Thank you so much!

my pleasure
