### ISSUE TITLE
previewThumbnails is always larger than the set thumbnail size

### ISSUE THREAD

**Issue by SS88UK** [sampotts/plyr#2001]
Apologies if I've missed something here. I did try searching everywhere for functions, methods, and previous issues.

I have a .vtt file with the sprite and it works great however, there's one problem and that's the previewThumbnail pop-up that shows is always larger than what my sprite thumbnails are, resulting in a stretched and pixilated image.

The preview thumbnail in dev. console shows it's 

`<div class="plyr__preview-thumb__image-container" style="height: 214px; width: 379px;">`

My .vtt file shows this (very first image):

`sprite.jpg#xywh=0,0,250,141`
250x141 (width x height)

It is also enlarging the sprite image size too:

`<img src="sprite.jpg" data-index="20" data-filename="sprite.jpg" style="height: 2568px; width: 4553.19px; left: -3035.46px; top: -214px;">`

The sprite.jpg file is actually 3000x1692 pixels.

Any help is appreciated.

Note: sorry I cannot show examples at the moment. It's been integrated into adult content.

**Comment by zjttfs** [comment]
I also have this problem

examples:
https://www.zhipianbang.com/video/detail-201181.html

https://res.zhipianbang.com/videos/preview/201/201181.vtt

**Comment by reza-akbari** [comment]
I tried styling the `.plyr__preview-thumb` and it worked.
