### ISSUE TITLE
Volume bar overlaps caption menu

### ISSUE THREAD

**Issue by Koenvh1** [sampotts/plyr#2005]
### Expected behaviour
The volume bar to stop before the button on the right next to it, as Chrome does:
![afbeelding](https://user-images.githubusercontent.com/5168825/98447623-8ba12600-2126-11eb-9829-c68eb1e09002.png)

### Actual behaviour
The volume bar overlaps the first button on the right next to it (either the captions button or settings button):
![afbeelding](https://user-images.githubusercontent.com/5168825/98447604-66acb300-2126-11eb-9d36-f442cc96fa4e.png)

### Environment

- Browser: Firefox
- Version: 83.0b9
- Operating System: Windows
- Version: 10

### Link to where the bug is happening
https://plyr.io

**Comment by dirkjf** [comment]
For a simple fix set the min-width of the input field to 0: 

```
.plyr__volume input{ 
    min-width: 0;
}
```

**Comment by Koenvh1** [comment]
@dirkjf That indeed seems to fix it. Out of interest, do you happen to know why that fixes it?

**Comment by dirkjf** [comment]
@Koenvh1, By default, the initial value of `min-width` is `auto`, which means it will actually use the intrinsic minimum width that is automatically defined by the browser, which in the case of Firefox is bigger than the available space. This is how I believe it works, but you could also call it a bug in Firefox 😄.

**Comment by sampotts** [comment]
I'll get the _well overdue_ next version out the door this weekend.

**Comment by ydylla** [comment]
Hi @sampotts,
I just upgraded to 3.6.3 because the changelog claimed this was fixed.
But I think it is not, you removed the fix again with https://github.com/sampotts/plyr/commit/da16c55427881411d4b9a29c7d5e6d13662d9499 so it never manged to get into master.
Was that an accident?

**Comment by sampotts** [comment]
That is the `develop` branch and that was because I moved the declaration so that all `<input type="range" />` have the fix rather than just the volume one - see here: https://github.com/sampotts/plyr/blob/master/src/sass/components/sliders.scss#L15

It is fixed but you need to update the CSS too of course. The demo (https://plyr.io) is always using the latest published version so if it's fixed there, it's fixed on npm.

**Comment by ydylla** [comment]
Thanks @sampotts,
you are right I did not apply the update correctly. The missing commit then fooled me into thinking its not my fault 🤦 
Sorry I had to bother you.

**Comment by sampotts** [comment]
No problem at all! 👍
