### ISSUE TITLE
custom ads

### ISSUE THREAD

**Issue by newonee** [sampotts/plyr#2007]
hi, i want to know , is there any way to add custom video ads before or middle videos?

**Comment by sampotts** [comment]
You need to use a VAST tag and set it via the `ads.tagUrl` [option](https://github.com/sampotts/plyr#options).

**Comment by newonee** [comment]
how can i make vast tag?

**Comment by jzvi12** [comment]
How would set VAST on the following js code I am using for multiple videos?

```
<script>
const players = Array.from(document.querySelectorAll('video')).map(p => new Plyr(p));
</script> 
```

I know from this [demo](https://codepen.io/nightsurge/pen/NVQGyJ?editors=1010) it is set like this:
```
<script>
// Change the second argument to your options:
// https://github.com/sampotts/plyr/#options
const player = new Plyr('video', {captions: {active: true}, ads: {enabled: true, tagUrl: 'https://www.videosprofitnetwork.com/watch.xml?key=3335b438aa33d6c887e79207d1bd9c53'}});

// Expose player so it can be used from the console
window.player = player;
</script>
```

**Comment by arunkumartdr** [comment]
Is there any demo or implementatons?

**Comment by sampotts** [comment]
Third reply. You don't need to reply to all ad-related issues. See my other two replies.
