### ISSUE TITLE
Flexbox Overlap on Firefox

### ISSUE THREAD

**Issue by PotatoRui** [sampotts/plyr#2019]
I tested Plyr.io on Chrome and it looks great!
![Screenshot_23](https://user-images.githubusercontent.com/49616497/99147376-7e061600-26bb-11eb-9482-109d8eabed43.png)

But when I tried it on Firefox the volume flexbox overlaps the next element.
![Screenshot_22](https://user-images.githubusercontent.com/49616497/99147390-9bd37b00-26bb-11eb-8a8c-f768e2503460.png)

Chrome version: Version 86.0.4240.198 (Official Build) (64-bit)
Firefox Version: 83.0b10 (64-bit) | Firefox Developer Browser | Up to Date

**Comment by sampotts** [comment]
Please try again. This was fixed earlier today in v3.6.3.
