### ISSUE TITLE
Double click fullscreen fail on plyr 3.6.3

### ISSUE THREAD

**Issue by sakamotodesu1** [sampotts/plyr#2024]
### Expected behaviour
Go fullscreen when double clicked

### Actual behaviour
Not go fullscreen, and throws error on console 
`Uncaught TypeError: this.enter is not a function`

### Steps to reproduce
1. go to plyr 3.6.3 player. example : [https://plyr.io](https://plyr.io)
2. double click / tap the player

### Environment
happen everywhere i can test.

- Browser: Chrome, Firefox, Edge
- Version: Latest
- Operating System: Windows, Android
- Version: 10

### Console errors (if any)
Uncaught TypeError: this.enter is not a function

### Link to where the bug is happening
https://plyr.io

not happening in previous ver.

**Comment by watzitoya** [comment]
probably related with [this PR](https://github.com/sampotts/plyr/pull/2016/commits/4d25a33cb0848a0e0ec141f05880531ae39d5a9a)

**Comment by jackguoAtJogg** [comment]
Same error for me as well.

**Comment by prajwalan364** [comment]
Same error in react, is there any way to fix this..

**Comment by sakamotodesu1** [comment]
use version (3.6.2) to avoid this issue.

**Comment by prajwalan364** [comment]
> use version (3.6.2) to avoid this issue.

Thank you, its working

**Comment by jovick-coder** [comment]
I do not notice any errors

**Comment by hasan-wajahat** [comment]
@jovick-coder Plyr throws an exception, you should be seeing that in your console. Unless you are catching that exception somwhere.

**Comment by mrleblanc101** [comment]
Is there a way to disable double-tap fullscreen? 
I don't see an option for that

**Comment by sampotts** [comment]
Sorry, this issue should now be resolved in 3.6.4.

**Comment by sampotts** [comment]
> Is there a way to disable double-tap fullscreen?
> I don't see an option for that

Not currently but it makes sense to add it.

**Comment by moelashmawy** [comment]
> Is there a way to disable double-tap fullscreen? I don't see an option for that

const player = new Plyr(element, { fullscreen: { enabled: false } } );

**Comment by moelashmawy** [comment]
> Is there a way to disable double-tap fullscreen? I don't see an option for that

const player = new Plyr(element, { fullscreen: { enabled: false } } );

but will also prevent you from adding full-screen to controls.
check [1370](https://github.com/sampotts/plyr/issues/1370)

**Comment by naittodigital** [comment]
En mi caso el inconveniente con el double-click-to-fullsceen me ocultaba los controles ( play, volume, fullscreen, etc... ), lo corregí mediante CSS asignándole:

`.plyr__video-embed iframe {
    pointer-events: none;
}`

Además agregue lo siguiente para que no resalte:

`.plyr {
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none; 
}`

Use la actual versión: plyr.js v3.7.2
