### ISSUE TITLE
ads with Youtube source

### ISSUE THREAD

**Issue by chonian** [sampotts/plyr#2025]
I have created the demo bellow:

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/plyr@3/dist/plyr.css">
    <script src="https://unpkg.com/plyr@3.6.3/dist/plyr.min.js"></script>
    <script src="https://imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=es6,Array.prototype.includes,CustomEvent,Object.entries,Object.values,URL"></script>
    <style>
        .container {
            margin: 20px auto;
            max-width: 500px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div id="player" crossorigin data-plyr-provider="youtube" data-plyr-embed-id="bTqVqk7FSmY"></div>
    </div>
    <script>
        const player = new Plyr('#player', {
            captions: {
                active: true
            },
            ads: {
                enabled: true,
                tagUrl: 'https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dskippablelinear&correlator='
            },
        });
        window.player = player;
    </script>
</body>

I observe that the ads not working when using youtube source.
Could you take a look?

Thanks in advance.

**Comment by sampotts** [comment]
That's intended as it's against the YouTube terms of service.
