### ISSUE TITLE
Player not working in Modals in React

### ISSUE THREAD

**Issue by comertcimen** [sampotts/plyr#2027]
I am using Plyr in React with MaterialUI. When i use it in normal components, it is working (not perfectly because vtt subtitles are not showing even though i validate them but this is not the important part of my problem) When i use it in modal it doesn't work. I also tried with React bootstrap and got the same result. Then I tried it with Vanilla javascript + bootstrap, it worked. React is causing the problem but couldn't figured it out why. The sample code is in the link below. It was working with plyr-react package but since it is an old copy of this project i decided not to use it.

### Expected behaviour
To work in modals

### Actual behaviour
Not working in modals

### Steps to reproduce
I don't know.

### Environment

- Browser: Google Chrome
- Version: 87
- Operating System: Windows
- Version: 10

### Console errors (if any)
None

### Link to where the bug is happening
[Codesandbox](https://codesandbox.io/s/gallant-dream-3xy1b?file=/src/App.js)

**Comment by HenrryVo** [comment]
Try this one. 
 `  useEffect(() => {
    setTimeout(function () {
      const player = new Plyr("#player");
      player.source = {
        type: "video",
        sources: [
          {
            src: "bTqVqk7FSmY",
            provider: "youtube"
          }
        ]
      };
    }, 100);
  });`

**Comment by comertcimen** [comment]
> Try this one.
> ` useEffect(() => { setTimeout(function () { const player = new Plyr("#player"); player.source = { type: "video", sources: [ { src: "bTqVqk7FSmY", provider: "youtube" } ] }; }, 100); });`
 It works, thanks.
