### ISSUE TITLE
Webm don't load on ipad/iphone

### ISSUE THREAD

**Issue by christopheSeeka** [sampotts/plyr#2036]
Hello,

I'm currently testing the playing in a webapp and it seem that webm video are loading for ever on ipad/iphone and not able to play. MP4 are working well.
Is it a known issue or there is anything that can be done to make it work? Or is it related to the webm encoding? (i see partial support on caniuse)

Thanks in advance.

**Comment by RichardGG** [comment]
iOS does not support WebM/VP8 except for WebRTC (Real-time communication/Video calls)
You can read more here: https://webkit.org/blog/8672/on-the-road-to-webrtc-1-0-including-vp8/

**Comment by christopheSeeka** [comment]
I see, thanks for the details.
