### ISSUE TITLE
Browser warning regarding comma separated options

### ISSUE THREAD

**Issue by bjarnef** [sampotts/plyr#2048]
Using Plyr v3.6.2 I am getting warning regarding the comma separated options set in e.g. Vimeo plugin, which seems to be related to these lines https://github.com/sampotts/plyr/blob/e8d883edba3ee87ff5fbef043ffa50a1a4ae391b/src/js/plugins/vimeo.js#L106-L107

https://www.chromestatus.com/feature/5740835259809792

### Expected behaviour
The attribute value `allow` should be using semicolon as separator instead as comma separator in iframe allow attribute is deprecated. Furthermore regarding the warning "Allow attribute will take precedence over 'allowfullscreen'." it seems `allowfullscreen` attribute is not necessary with value `fullscreen` in `allow` attribute.

### Actual behaviour
The browser is showing warning in the console.

### Steps to reproduce

Render a Vimeo or YouTube video:

```
<div id="player" data-plyr-provider="vimeo" data-plyr-embed-id="@videoUrl"></div>
```

```
<div id="player" data-plyr-provider="youtube" data-plyr-embed-id="@videoUrl"></div>
```

### Environment

- Browser: Chrome
- Version: 87.0.4280.88
- Operating System: Windows
- Version: 10

### Console errors (if any)

![image](https://user-images.githubusercontent.com/2919859/102318596-df9af800-3f79-11eb-9730-42dc17cf3440.png)

**Comment by krzry** [comment]
Is it possible to update the Deprecation warning directly on the Plyr cdn v3.6.2 so that we won't have to update cdn to the latest version?

**Comment by sampotts** [comment]
This should now be resolved 👍🏼
