### ISSUE TITLE
Firefox picture-inpicture (pip) issue

### ISSUE THREAD

**Issue by ndsda** [sampotts/plyr#2051]
I have a problem with the player control icons. Only affects Firefox. It's caused by picture-in-picture.

In Firefox, the pip clickable icon is placed higher up (done by the browser) and the volume bar extends over the cog icon. As shown in the screenshot:

<img src="https://i.imgur.com/ZJw5DBo.png">

Does anyone else experience this issue in Firefox?

**Comment by sampotts** [comment]
The overlap is a CSS issue. Please use the latest CSS to fix that. 

WRT to the PIP, unfortunately there's no API for that in Firefox (certainly at time of release), meaning you're stuck with that native UI.
