### ISSUE TITLE
Vimeo "Do not Track"

### ISSUE THREAD

**Issue by Nerdies24** [sampotts/plyr#2058]
Hello,

Can I include a code for Vimeo to prevent monitoring of user behavior. Could you please give me a code example?

e.g. 12345678?dnt=1

Thank you very much.
Frank

**Comment by sampotts** [comment]
Hi,

Sorry for the delay. Yep, you can try setting `dnt: true` in the config for Vimeo. For example:

```
{
  vimeo: {
    dnt: true,
  },
}
```
