### ISSUE TITLE
Can we highlight a certain time in the video in the video progress bar?

### ISSUE THREAD

**Issue by Diwpjoy** [sampotts/plyr#2073]
Hi,
Can we highlight a certain point in the video inside the video progress bar?
I made a illustration which may help to understand me.
![Capture201](https://user-images.githubusercontent.com/75944544/104821461-527ae580-583c-11eb-93fd-4973ff77d51a.png)

**Comment by Diwpjoy** [comment]
You don't need to tell me how to make it work.Please just tell me if it's possible or not in plyr. yes or no?

**Comment by sampotts** [comment]
Not easily possible currently. Can be added to the backlog though.
