### ISSUE TITLE
Youtube rel: 0 does not work

### ISSUE THREAD

**Issue by khan725** [sampotts/plyr#2074]
### Expected behaviour
setting rel: 0 for youtube options should not show related videos on video when paused
### Actual behaviour
setting rel: 0 for youtube options still shows related videos on video when paused
### Steps to reproduce
set rel to 0 for any youtube video

**Comment by sampotts** [comment]
Unfortunately YouTube no longer supports this. I'd raise it with them if you feel strongly about it.
