### ISSUE TITLE
Plyr qualities do not update on source change

### ISSUE THREAD

**Issue by amir2mi** [sampotts/plyr#2081]
Hi, it is my pleasure working with Plyr, that is totally cool!
I have worked with it nowadays and it seems there is a problem when video source tags get updated with different size attributes Plyr does not change qualities in settings.
I mean it does not work with React when I set new source tags, destroy Plyr, and recreate it still has old settings.
So is there any option to reset Plyr settings, qualities, captions...?

**Comment by paulhan221** [comment]
@amir2mi why did you close this issue? Were you able to find a solution?
