### ISSUE TITLE
*{height:100%} in site CSS messes up Plyr's buttons.

### ISSUE THREAD

**Issue by styromaniac** [sampotts/plyr#2083]
I have a site that has this bit of CSS in it. How would I prevent the buttons from becoming insanely tall? I don't actually know what it is on my site that requires this, so could I change something in plyr.css to keep the buttons the right size?

**Comment by sampotts** [comment]
That's a pretty wild CSS ruleset! 

You could try `.plyr * { height: auto; }` _before_ the main Plyr CSS file but I can't guarantee that'll fix it without trying it myself.

**Comment by styromaniac** [comment]
![Screenshot_20210125-093540](https://user-images.githubusercontent.com/43807387/105719859-c5492800-5ef0-11eb-8174-165f99bc916d.png)
The buttons are fixed, but the controls go to the bottom. I'm unsure if that's a Glightbox bug or Plyr bug now.
