### ISSUE TITLE
plyr.css is missing

### ISSUE THREAD

**Issue by joelearn** [sampotts/plyr#2100]
Our builds have started to fail with this error: 

`Error: Failed to find 'plyr/dist/plyr.css'`

I can't find the file within `node_modules/plyr` either. Please add it back in.

**Comment by sampotts** [comment]
Strange. Unpkg will basically show what's published on npm:
https://unpkg.com/browse/plyr@3.6.4/dist/

Did you try removing `node_modules` and reinstalling it?

**Comment by joelearn** [comment]
Just tried reinstalling and it's now back. Very odd, but glad it's ok now. Thank you

**Comment by sampotts** [comment]
All good. Glad you got it sorted 👍
