### ISSUE TITLE
Ratio square issue in fullscreen mode

### ISSUE THREAD

**Issue by juliengiombetti** [sampotts/plyr#2109]
I have issues with a squared ratio video from vimeo only in fullscreen mode.

### Expected behaviour
Keep the 1:1 ratio in fullscreen mode.

### Actual behaviour
The video is not centred vertically in the screen.

### Steps to reproduce
https://codepen.io/explose_agency/pen/NWbbrYo

### Environment
- Browser: Chrome
- Version: 88.0.4324.150
- Operating System: macOS
- Version: Big Sur 11.2

Do you have an idea ? Thank you in advance.

![Capture d’écran 2021-02-11 à 12 51 37](https://user-images.githubusercontent.com/32292672/107633363-2c443c00-6c68-11eb-8cfe-1f2b55011a88.png)

**Comment by szczepankosmowski** [comment]
This issue seems to affect all vimeo videos in fullscreen mode, even if they are 16:9 -- it happens in the vimeo demo at https://plyr.io/#vimeo s well.
