### ISSUE TITLE
(IE 11 & edge) Scrollbar on video when overflow auto/scroll appears

### ISSUE THREAD

**Issue by emmanuelclement** [sampotts/plyr#212]
(Relative to issue #210 and its fix #211)

On IE Edge (and IE 11 if you fix #210 with request #211), if you insert a video in a parent which is set overflow: auto/scroll, an horizontal scrollbar appears.
(try to set overflow: auto on <section> on https://plyr.io/ )

The reason is that the .plyr__tooltip (in the .plyr__controls) go over the edges of the video.
No left or right position are fixed, and the scale -50% doesn't fix the problem; the last-right tooltip (particularly this one) go over the edges.

* First easy fix: set an overflow hidden on the entier video div.plyr;
- second (more difficult but probably better) fix: not using scale to position tooltips, but adding right/left position.

**Comment by SamPotts** [comment]
Using left/right positioning wouldn't be ideal as it would mean the tips were either left or right aligned or you'd have to fix the width and use negative margins. Using `translate` (it's not `scale`) means its always center aligned based on the content. The overflow is not ideal I know and I've come up against this in full screen mode also. A possible solution might be to do custom styling for the outer tooltips on the play/pause button and fullscreen toggle to be left and right aligned respectively. I'll take a look at this one.
