### ISSUE TITLE
Disable design for embed videos because no quality switcher

### ISSUE THREAD

**Issue by darkylmnx** [sampotts/plyr#2131]
I was desperatly trying to add a quality switcher for my YouTube video, but it seems this feature was removed.
Therefore, I looked for a way to leave the default YT player but I didn't find anything.

How can a create an instance of Plyr for a YouTube video but with the native YT player?
So users can change the quality to fit their need.

**Comment by shivamkb17** [comment]
I am also searching for same.

**Comment by sampotts** [comment]
The feature was removed because YouTube's API is useless for it. The API allows you to _suggest_ a quality level which is _ignored_ 99.9% of the time, rendering the feature useless. 

Sorry, it's not documented but you can use set `customControls: false` for the YouTube and Vimeo configs. e.g.

```
{
  youtube: {
    customControls: false
  },
}
```
