### ISSUE TITLE
Release on github the 3.6.4

### ISSUE THREAD

**Issue by HenriqueMarcelo** [sampotts/plyr#2143]
There is no release for version 3.6.4 on github

https://github.com/sampotts/plyr/releases

**Comment by sampotts** [comment]
Done:
https://github.com/sampotts/plyr/releases/tag/v3.6.4

Bear in mind that the `dist` directory is no longer included in the releases. If you need it, you can get it from unpkg or similar:
https://unpkg.com/browse/plyr@3.6.4/dist/
