### ISSUE TITLE
Broken video style with React or Create React App

### ISSUE THREAD

**Issue by bargergo** [sampotts/plyr#2149]
### Expected behaviour
The video controls should appear at the bottom of the video in styled and in normal size.

### Actual behaviour
The video controls appear above and under the video as big HTML buttons.
![kép](https://user-images.githubusercontent.com/37365034/111922485-52949d00-8a9a-11eb-8064-6f6d283a59e5.png)

![kép](https://user-images.githubusercontent.com/37365034/111923090-b4a2d180-8a9d-11eb-9c37-324c4a47c263.png)

### Steps to reproduce
```
npx create-react-app my-app --template typescript
cd my-app
npm install --save plyr
```
Change the content of App.tsx to this:
```typescript
import Plyr from "plyr";
import React, { useEffect, useRef } from "react";

const App = () => {
  const video = useRef<HTMLVideoElement>(null);

  useEffect(() => {
  
    if (video.current) {

      video.current.src = "MY_VIDEO.mp4";
      const player = new Plyr(video.current);
        
    }
  }, [video]);

  return (
    <div >
      <video ref={video} controls crossOrigin="true" playsInline >
      </video>
    </div>
  );
};

export default App;
```
(Delete not used files: App.css etc.)

### Environment

- Browser: Firefox, Chrome 
- Version: Firefox 86.0.1, Chrome 89.0.4389.90
- Operating System: Windows 10 Pro
- Version: 2004

### Link to where the bug is happening
https://codesandbox.io/s/react-and-plyr-broken-video-design-9fove?file=/src/App.js

**Comment by bargergo** [comment]
@seanlangbrown Yes, you are right. I had to add this line to the imports:
```typescript
import 'plyr/dist/plyr.css';
```
Thanks for your help!

**Comment by StephanLuis** [comment]
Thanks @seanlangbrown  and @bargergo  for the import code, @sampotts  could be a little more clear in the documentation about where the css import happens.  

I'm new to modules, but docs imply that js import is all that's needed.  Guess you're thinking if two links are needed two imports are needed!

**Comment by chintan9** [comment]
use plyr-react https://github.com/chintan9/plyr-react
