### ISSUE TITLE
After pausing the video the controls are not shown same as #2018

### ISSUE THREAD

**Issue by alexvibealex** [sampotts/plyr#2153]
Since no solution provided here : https://github.com/sampotts/plyr/issues/2018 and here https://github.com/sampotts/plyr/issues/2138
opening a new issue . 
The problem in CHROME 89.0 on ANDROID  : 
after playing vimeo video controls not showing . 

Please anyone with a quick fix , our customers are suffering due to this .
,business at stake .

**Comment by sampotts** [comment]
Please use current issues. Opening more does nothing but cause annoyance. Feel free to take a look and open a PR if you're losing business as a result.  I've just started a new role at Amazon and don't have even less spare time.
