### ISSUE TITLE
how to use player with ionic 5

### ISSUE THREAD

**Issue by AnasProgrammer2** [sampotts/plyr#2157]
hello  , create app with ionic 5 , that play videos , 
but i need to use plyr with our app ,? any idea 

ionic ver : 5
anglur  ver : 10 

### Environment

- Browser:ionic 5
- Version:anglur 10
- Operating System:
- Version:

**Comment by AnasProgrammer2** [comment]
any update ?

**Comment by sampotts** [comment]
Perhaps try adding more detail to the issue, explaining the actual error or problem you're facing. It might help others debug. Currently it's pretty vague. 

Posting "any update?" does nothing but be annoying.

**Comment by ipehimanshu** [comment]
Hello all

How to use with ionic 7 ?

any example for it?

Thank you
