### ISSUE TITLE
.mkv file type support

### ISSUE THREAD

**Issue by sthakor2362** [sampotts/plyr#2158]
Hello, Please update file type support .mkv in plyr.

**Comment by anesuc** [comment]
This is mostly a wrapper of the HTML5 player. Media types support is dependant on the browser and the HTML5 standards hence no .mkv support.

**Comment by sampotts** [comment]
As above. See https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#mp4

You're best off with an mp4 at this point, possibly with a webm if you can.
