### ISSUE TITLE
Webtorrent support

### ISSUE THREAD

**Issue by Bluppie05** [sampotts/plyr#2170]
It would be really cool seeing (official) WebTorrent support in Plyr. Torrenting is being used more and more for normal streaming applications and it would be awesome to be able to play torrents inside Plyr usingWebTorrent

WebTorrent link: https://webtorrent.io/

This would also enable Plyr to play videos from for example PeerTube as their video platform is based around torrenting.

**Comment by sampotts** [comment]
See #2137. Please search next time 👍🏼
