### ISSUE TITLE
Nuxt.js (webpack) Module parse failed: Unexpected token (1:11295)

### ISSUE THREAD

**Issue by OndrejIT** [sampotts/plyr#2174]
### Expected behaviour
Plyr version v3.6.5 works fine

### Steps to reproduce
When use plyr v3.6.6 in nuxt,js

### Environment

- Browser:
- Version:
- Operating System:
- Version:

### Console errors (if any)
Module parse failed: Unexpected token (1:11295)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
### Link to where the bug is happening
https://github.com/sampotts/plyr/blob/951cccb6b0da4372db05f3696a6b558587b59d12/src/js/utils/style.js#L90

**Comment by OndrejIT** [comment]
I think problem is in "?"

**Comment by sampotts** [comment]
Likely the reference to `window`?

**Comment by OndrejIT** [comment]
I think so.

**Comment by leahfkd** [comment]
getting the same problem

**Comment by sallakos** [comment]
Same error with Gatsby.js.

**Comment by jansgescheit** [comment]
Same issue on my angular project

**Comment by sampotts** [comment]
Anyone had a crack at a fix? I'll try conditionally accessing the window and window.CSS property.

**Comment by iwasherefirst2** [comment]
I have the same problem

**Comment by sampotts** [comment]
Can you test v3.6.7?

**Comment by leahfkd** [comment]
I think this is not the only issue, after the new update. I got now this error 
`Module parse failed: Unexpected token (1:9956)`

**Comment by sampotts** [comment]
What would help here is either: 

- Someone determines the token that's causing an issue. I originally assumed it was the reference to `window` (not available in SSR of course) but that's referenced in loads of other places.
- Someone provides a reproducible example - ideally on codesandbox or similar.

**Comment by rentalhost** [comment]
@sampotts in my setup, the last patch 32444c9 have worked.

**Comment by sallakos** [comment]
I tested and 3.6.7 works just fine.

My error with 3.6.6. points to `plyr.polyfilled.mjs:4656:31`, which seems to be the `?` in the line mentioned in the opening post, and is now fixed.

**Comment by OndrejIT** [comment]
> Can you test v3.6.7?

Thanks, works fine!
