### ISSUE TITLE
vimeo video shows black screen on full screen mode. 

### ISSUE THREAD

**Issue by Hotjava** [sampotts/plyr#2175]
Found this issue after update my plyr version to v 3.6.6 and with latest Chrome Version 89.0.4389.114 (Official Build) **(32-bit)**

When the vimeo viden enter full screen mode, it only shows a back screen 

https://user-images.githubusercontent.com/3180686/115150678-5bf53300-a061-11eb-9d83-a1acba013214.mp4

**Comment by matthieua** [comment]
Yes same issue here :) It happened when upgrading to 3.6.6

**Comment by Nerdies24** [comment]
Same issue with v3.6.7

**Comment by FritzAxel** [comment]
I can see the video on full screen on the plyr website, but i can't on my website

**Comment by lvidal1** [comment]
Same issue on my site. Does anyone find the solution?

**Comment by sampotts** [comment]
Sorry, I am working on a fix. I fixed one thing, broke another. Need to write some visual tests somehow.

**Comment by lvidal1** [comment]
It seems is not working on Edge either : /
Tested on Microsoft Edge
Versión 90.0.818.51 (Official Comp) (64 bits)

**Comment by fmarsoni** [comment]
Added this css and seems to work (only tested on latest chrome)

.plyr:-webkit-full-screen.plyr--vimeo .plyr__video-wrapper {
  height: 100%;
}

.plyr:-webkit-full-screen.plyr--vimeo > .plyr__video-wrapper > .plyr__video-embed__container {
  transform: none !important;
  position: initial;
}

**Comment by Hotjava** [comment]
> Added this css and seems to work (only tested on latest chrome)
> 
> .plyr:-webkit-full-screen.plyr--vimeo .plyr__video-wrapper {
> height: 100%;
> }
> 
> .plyr:-webkit-full-screen.plyr--vimeo > .plyr__video-wrapper > .plyr__video-embed__container {
> transform: none !important;
> position: initial;
> }

Which version are you using? didn't work for me on 3.6.7

**Comment by fmarsoni** [comment]
3.6.7

[fiddle](https://jsfiddle.net/oh1q8gft/)

**Comment by inglesuniversal** [comment]
Same here.... BUT... I was playing around with the elements inside the developer's panel (chrome desktop) and one element seemed to have opacity all the way down to ZERO (0) ... I hope this helps spot the bug faster.

Good luck to you all!

**Comment by sampotts** [comment]
@inglesuniversal Check out my last message. It should now be resolved in the latest version.

**Comment by Hotjava** [comment]
@sampotts , after upgrade to 3.6.9, it works fine. Thank you!

**Comment by FritzAxel** [comment]
Hello again! i can see the video on full screen using the latest version (css file too), thank you sam!

But i have a new problem now. 😅

It doesnt center the video vertically, it leaves space only at the bottom of the video.
![image](https://user-images.githubusercontent.com/15350252/118282567-cbb1de80-b4a4-11eb-9de1-50f56677fa71.png)

Just in case, my resolution at the browser is 1680x970

Thanks!

**Comment by sampotts** [comment]
Hey @FritzAxel, 

Sorry to hear. Do you have a video I could try? Are you seeing it on plyr.io too? I tested with a 16:9, 4:3 and 1:1 videos but perhaps this is an edge case I've missed. The logic to hide the Vimeo controls is pretty complex and catches me every time I have to look at it. 

Cheers

**Comment by FritzAxel** [comment]
Mmm.. on plyr.io seems ok. The latest version is the 3.6.8 right? I am using it with npm and that's the last version it gives me. Also i downloaded the .min.css of that version.. What i am missing? 

Thanks a lot @sampotts

**Comment by FritzAxel** [comment]
Ok.. it was completely my fault! i put on my css the next property: 
```
.plyr--video {
    position: relative;
    display: block;
} 
```

That's why it was not centered.

**Comment by sampotts** [comment]
Phew. Thanks for reporting back! 👍🏼
