### ISSUE TITLE
Can't minify v3.6.7

### ISSUE THREAD

**Issue by serenaBit** [sampotts/plyr#2179]
### Expected behaviour
Correct minification
### Actual behaviour
No minification. With a previous version of the library (3.6.3) no error was showing.
### Environment

- Browser: - 
- Version: - 
- Operating System: - 
- Version: - 

### Console errors (if any)

GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: operator «>»

### Link to where the bug is happening
-

**Comment by sampotts** [comment]
Duplicate of #2174 2174
