### ISSUE TITLE
Issue with playing .ts files (via google drive index)

### ISSUE THREAD

**Issue by Rejected-Peice** [sampotts/plyr#2184]
### Expected behaviour
Play .ts files without any issues

### Actual behaviour
.ts files gives a blank screen
### Steps to reproduce
Create a drive index from https://github.com/ParveenBhadooOfficial/Google-Drive-Index
Try to play a .ts file
Get a blank screen

### Environment

- Browser: Brace, firefox
- Version: 1.23.73 , 87.0
- Operating System: Ubuntu 20.04, Windows 20H1

### Link to where the bug is happening

https://bug.rejected-peice.workers.dev/0:/
I have included sample videos here from https://filesamples.com/categories/video 

You may try downloading the video file and play it in you system. It works perfectly fine.

![image](https://user-images.githubusercontent.com/62835853/115980992-50988f00-a5ae-11eb-8dc2-4bd4e4866122.png)

**Comment by sampotts** [comment]
Hey there,

It's an unsupported HTML5 format. You want to be using mp4 for best compatibility:

https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs
