### ISSUE TITLE
iOS native fullscreen not working on iPad OS

### ISSUE THREAD

**Issue by Benny739** [sampotts/plyr#2190]
The iOS native fullscreen function is not working on iPad OS. This leads to a non functional fullscreen button in PWAs.
I could provide a PR if needed to fix this.
To Identify an iPad with iPad OS we just need to check
```
navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1;
```

**Comment by Benny739** [comment]
Added PR https://github.com/sampotts/plyr/pull/2191

**Comment by sparkktv** [comment]
Any word on a fix for this? This continues to be an issue it seems. I just tried today using latest Plyr 3.6.12 using iPadOS 15.2 and in both Safari and Firefox the full screen button does not work and it does not fall back to iOS native player either...

**Comment by sampotts** [comment]
This should now be resolved. Please report back if there's any issues.
