### ISSUE TITLE
Default blankVideo - CORS

### ISSUE THREAD

**Issue by mgzurakowski** [sampotts/plyr#2201]
(version 3.6.7, every browser)
Default blank video (https://cdn.plyr.io/static/blank.mp4) throws CORS error:

>`Access to fetch at 'https://cdn.plyr.io/static/blank.mp4' from origin 'https://example.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

**Comment by AiziChen** [comment]
In html's header, add this `<meta name="referrer" content="no-referrer" />`.

**Comment by CraftedRO** [comment]
> In html header, add this line of code: `<meta name="referrer" content="no-referrer" />`

for some reson this only works if you load the page from local, if you upload on host it won't work anymore.

**Comment by varunarora** [comment]
I resolved the problem by using a local `iconURL`

**Comment by Baldarello** [comment]
> I resolved the problem by using a local `iconURL`

can you please give the code as example on how to use that attribute? because i'm having the same problem but i can't make it works, thanks in advance
