### ISSUE TITLE
Where is the compressed version?

### ISSUE THREAD

**Issue by babakfp** [sampotts/plyr#2235]
Hello
I wasn't able to find the compressed/minified src files (JS and CSS).

**Comment by sampotts** [comment]
See https://github.com/sampotts/plyr/discussions/2094

**Comment by babakfp** [comment]
I copied the code from here
- [Javascript](https://cdn.plyr.io/3.6.8/plyr.js) or [Javascript polyfilled](https://cdn.plyr.io/3.6.8/plyr.polyfilled.js)
- [CSS](https://cdn.plyr.io/3.6.8/plyr.css)

Was there a description of it in the readme? I couldn't find it. If there was not, please add a title and description because it was so frustrating for me.
Greate library
Thanks
