### ISSUE TITLE
Cannot use fullscreen container in IE11

### ISSUE THREAD

**Issue by k-jensen** [sampotts/plyr#2252]
### Expected behaviour
Able to use ancestor element as a fullscreen container in IE11

### Actual behaviour
Throws an error when setting up fullscreen code, doesn't complete player setup

### Steps to reproduce

1. In the player options, set the fullscreen.container to an ancestor element
2. Try and load player in IE11
3. Throws a wobbly

### Environment

- Browser: IE
- Version: 11

### Console errors (if any)
`Object doesn't support property or method 'matches'`

### Link to where the bug is happening
[configuration](https://codepen.io/kimberleyJensen/pen/mdWNPxB)
But can't view codepen in IE11

In [js/utils/elements.js](https://github.com/sampotts/plyr/blob/ba236c47539c0da8084753185697a5c59ec8f761/src/js/utils/elements.js#L249)
I think
`if (matches.matches(el, selector)) return el;`
should be just
`if (matches(el, selector)) return el;`

**Comment by AIC-BV** [comment]
I guess this can be closed? **IE11** 🤭

**Comment by k-jensen** [comment]
Yep! bye bye IE11 :wave:
