### ISSUE TITLE
Can youtube and Vimeo use custom cover overly?

### ISSUE THREAD

**Issue by weilinzung** [sampotts/plyr#233]
Can youtube and Vimeo use custom cover overly? like a image on the top of the video, then click the play button, it will load and play the video.

Thanks.

**Comment by AnthyG** [comment]
If I am right, that with "custom cover overlay", you mean like a thumbnail, then have a look at this:

```
<div class="the_container">
    <img src="http://static.independent.co.uk/s3fs-public/thumbnails/image/2013/01/24/12/v2-cute-cat-picture.jpg" style="top: 0px; left: 0px; position: absolute; width: 100%; cursor: pointer;" id="bg-pic" />
    <div style="top: 0px; left: 0px; position: absolute; width: 100%; display: none;" id="fg-plyr">
        <div data-video-id="bTqVqk7FSmY" data-type="youtube"></div>
    </div>
</div>
<script>
    $(document).ready(function() {
        pic1 = $('#bg-pic');
        player1 = plyr.setup('#fg-plyr')[0];
        
        pic1.on('click', function() {
            document.getElementById("fg-plyr").style.display = "block";
            document.getElementById("bg-pic").style.display = "none";
            player1.play();
        });
    });
</script>
```

You just need to change the "src" of the "img" to your wanted image, and then change the "data-video-id" to the yt-video-id, you want to play, when you click the BG-Video.
And, of course, you need to import plyr, just check the complete thingy out here:
http://codepen.io/anthyG/pen/reEKWg

Here are the links, to the Sources I used:

1. https://github.com/Selz/plyr
2. http://www.w3schools.com/tags/tag_video.asp
3. http://www.w3schools.com/tags/tag_img.asp

You could add something like a hoverelement, that the user can see over the ```#bg-pic```.
And you may could also add a Poster for the Video e.g. http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_video_poster
But that is not yet implemented in Plyr :thought_balloon:

**Comment by DerBeni** [comment]
@AnthyG 
...your solution is not working on iPhone 6 (sorry, i just tested this one). By clicking the image the video starts to load but doesn't stop....after a while a warning "restart your device" appears. Do you have any suggestions? ...would be great to get it working :)

**Comment by AnthyG** [comment]
Well, I don't have an iPhone neither I am like "the best" programmer, so I may won't be able to help with that, but anyways..
What do you mean with "it doesn't stop"?
Do you mean that it just loads forever, or do you mean that you can't stop playback?

**Comment by DerBeni** [comment]
@AnthyG 
...me neither ;)  Maybe the developer gets attention to the bug?/problem...

...the video loads forever until a youtube warning shows up. 
In german: "Falls die Wiedergabe nicht in Kürze beginnt empfehlen wir dir, das Gerät neu zu starten"
...klicking on the video again finally starts it.

What i found out:
The **play()** method is only working for the **video element**, but it doesn't seem to work with a **youtube video**...tested on my iPhone 6.

**Comment by AnthyG** [comment]
Hmm, if you tested this on Codepen, it could may even be a bug on Codepen..
..but that is just a speculation

And I believe that it is pretty weird that the **play()** method is not working with youtube videos on the iPhone 6.

**Comment by AnthyG** [comment]
I just checked the Pen, and recognized that the Plyr version was **1.5.21**, so I just updated to **1.6.16**.. Maybe it work's now?
