### ISSUE TITLE
To detect the length of the file

### ISSUE THREAD

**Issue by emresaracoglu** [sampotts/plyr#2338]
Hello,

Is it possible to detect the length of the recorded audio file?

Thank you.

**Comment by WebLeach** [comment]
`var x = document.getElementById("myAudio").duration;`

**Comment by emresaracoglu** [comment]
> `var x = document.getElementById("myAudio").duration;`

Thank you

**Comment by WebLeach** [comment]
@emresaracoglu mind closing the issue??
