### ISSUE TITLE
Video doesn't start on Android 6, Chrome Browser

### ISSUE THREAD

**Issue by luciendub** [sampotts/plyr#238]
The video does not start in Android 6, Chrome browser on thr démo page https://plyr.io . It stays at 0:0

**Comment by wrightpt** [comment]
second this

**Comment by SamPotts** [comment]
Damn. I'm in the UK and my test Nexus 5 is back home. Tried to use a simulator but they are terrible. Not yet found a good one. iOS is way better in that department. Out of interest, if you switch source and then back to video, does it work? I'll try and find an Android device to debug on here.

**Comment by SamPotts** [comment]
Could you let me know if this is still an issue? I've just tested on a device on 6.0 with Chrome 50 and it worked ok every time.

**Comment by enda-zoo** [comment]
Same thing happening on Android 4.3 using the latest version of Chrome. (HUAWEI G6-L11)

**Comment by SamPotts** [comment]
Frustrating as I can't replicate. Any help on this is appreciated...

**Comment by enda-zoo** [comment]
Yup, I'll try to remote debug this issue tomorrow... just need to figure out how to do that first :)

**Comment by enda-zoo** [comment]
I can see that the network inspector that the MP4 from Vimeo gets cancelled...

Request URL:https://fpdl.vimeocdn.com/vimeo-prod-skyfire-std-us/01/3683/5/143418951/459135658.mp4?token=574d87b0_0x399d4a7feaf0a282880b792d9e703e06089d3579
Request Headers CAUTION: Provisional headers are shown.
Referer:https://player.vimeo.com/video/143418951?player_id=vimeo-6396&api=1&badge=0&byline=0&portrait=0&title=0
User-Agent:Mozilla/5.0 (Linux; Android 4.3; HUAWEI G6-L11 Build/HuaweiG6-L11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.114 Mobile Safari/537.36
Query String Parametersview sourceview URL encoded
token:574d87b0_0x399d4a7feaf0a282880b792d9e703e06089d3579

![inspector](https://cloud.githubusercontent.com/assets/15690337/15673347/0c822cc6-272e-11e6-8127-ebda77d19e46.jpg)

I'm guessing that doesn't narrow it down at all though...

**Comment by enda-zoo** [comment]
Seems to be happening on the Galaxy Note 4 and Nexus 6 - they were the only Android devices I had access to with my free BrowserStack trial.

**Comment by tdaines** [comment]
Works on my Moto X running Android 5.1 with Chrome 53.0.2785.124

**Comment by ttn10** [comment]
Same here, Android 6 with Chrome browser!!!!

**Comment by alejandroiglesias** [comment]
We found this issue today on an Android device with the latest Chrome version. The YouTube video stays frozen on 0:00.

**Comment by alejandroiglesias** [comment]
I fixed that issue by disabling autoplay on mobile devices. Sadly, had to implement that by user agent sniffing, but found [a way to check for autoplay on mobile](https://github.com/whatwg/html/issues/976#issuecomment-297568668) that I hadn't implemented yet.

**Comment by mbs-affiliate** [comment]
Mozilla/5.0 (Linux; Android 7.1.2; Redmi Note 5A Prime Build/N2G47H    -  I tried plyr.io demo player on page. Not loaded(   Do you support mobile devices? I mean plyr.

**Comment by alex-devPY** [comment]
Mozilla/5.0 (Linux; Android 7.1.2; Redmi Note 5A Prime Build/N2G47H - I tried plyr.io demo player on page. Not loaded( Do you support mobile devices? I mean plyr.

**Comment by friday** [comment]
@alex-devPY: Plyr is wrapping existing browser features and apis, and doesn't determine what is or isn't supported. If your browser supports html5 video and the codec, container and preset plyr should work. Disable plyr and use html5 directly. If this fixes the issue (not likely), it could be a problem with plyr.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by firescript** [comment]
@sampotts getting this error on latest android and latest chrome, seems related to this post.

**Error is:**
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.

The video won't autoplay on certain android devices. Video and script looks like this:

```
      <video  poster="@asset('images/video-thumbnail-start.jpg')" muted id="player" playsinline>
        <source src="@asset('videos/truck-intro.mp4')" type="video/mp4">
      </video>
```
```
                const player = new Plyr('#player', {
                    hideControls: true,
                    autoplay: true,
                    fullscreen: true,
                    controls: [],
                    clickToPlay: false,
                    volume: 0,
                    debug: true,
                });
```

**Comment by friday** [comment]
@firescript See https://github.com/sampotts/plyr/wiki/FAQ#5-autoplay-scripted-play-andor-the-preload-attribute-doesnt-work-in-some-browsers and #1112
