### ISSUE TITLE
Broken Styles for iPhone

### ISSUE THREAD

**Issue by gitRacoon** [sampotts/plyr#2390]
### Expected behaviour
If you open the video in full screen in a vertical position, the picture will be in the center.
### Actual behaviour
If you open the video in full screen in a vertical position, then the picture will be at the top.
### Steps to reproduce
Go to [site](https://kinderheldin.de/kursuebersicht) and open the video.
### Environment
- Browser: Safary
- Operating System: iOS
- Version: 14.8, 15.2
- Device: iPhone.
<img src="https://user-images.githubusercontent.com/64530445/147572146-1ec3a957-ac9c-456e-8755-eec310a0e3e5.jpg" width="300px" />

**Comment by gitRacoon** [comment]
I think the problem is that `margin: auto` doesn't work on **iPhone**.

**Comment by sampotts** [comment]
The problem seems to stem from your styles as the demo site works as expected. I'll do some digging.

**Comment by sampotts** [comment]
Updating to the latest styles should fix this. It looks like you're using an older version.
