### ISSUE TITLE
No audio when playing mkv files

### ISSUE THREAD

**Issue by nodirhajiev** [sampotts/plyr#2391]
If you play bigger mkv files, there is no audio. On external player like PotPlayer is working perfectly

**Comment by sampotts** [comment]
You need to use a web friendly format/container:
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers

The best support at the moment would be mp4.

**Comment by vitality82** [comment]
Is there a standard API/Util within Plyr for verifying if it will play the format with your current browser?
