### ISSUE TITLE
Audio not playing in Safari: Unhandled Promise Rejection

### ISSUE THREAD

**Issue by john777555** [sampotts/plyr#2392]
Hi,

I'm using the following code for my audio player: https://codepen.io/jmisavage/pen/WwVQoB?__cf_chl_captcha_tk__=78qICa.l.2QLWVA.tv2rCozirXFbUb.KST0o_mDZO0Y-1641286897-0-gaNycGzNB2U and it works great in all browsers except for the Safari in macOS and iOS. When trying to click on a song name, I get the following error:

```
Unhandled Promise Rejection: AbortError: The operation was aborted.
(anonymous function) rejectPromise
```

And the audio doesn't start playing. Could you please tell me if there's a workaround for this issue?

**Comment by thomascharbit** [comment]
Unfortunately Safari doesn't support ogg audio files

**Comment by john777555** [comment]
> Unfortunately Safari doesn't support ogg audio files

Thanks, that was my problem, I was actually using mp3 files without replacing the audio/ogg to audio/mp3 in JS file.
