### ISSUE TITLE
SyntaxError: invalid regexp group

### ISSUE THREAD

**Issue by nerofix** [sampotts/plyr#2396]
function **parseHash(url)** in **plyr.js**

`const regex = /^.*(?:vimeo.com\/|video\/)(?:\d+)(?:\?.*&*h=|\/)+(?<hash>[\d,a-f]+)/;`

This regex is no valid javascript in some browsers (such as PaleMoon) and causing the player not to load.
Removing this function from plyr.js will fix, but I recommend to update the regex to a more browser compatible javascript code.

Best regards.

**Comment by fekle** [comment]
I'm seeing the same issue, this seems to be caused by the use of Named Regexp Capture Groups (https://caniuse.com/mdn-javascript_builtins_regexp_named_capture_groups).
I submitted a PR in order to resolve this issue: https://github.com/sampotts/plyr/pull/2426

**Comment by sampotts** [comment]
Thanks for your work on this. It's released in v3.7.0 🎉
