### ISSUE TITLE
No CSS file included with 3.6.12

### ISSUE THREAD

**Issue by regiside** [sampotts/plyr#2411]
Just downloaded version 3.6.12 and noticed even though the documentation references plyr.css the file isn't in the package anywhere. I use Wordpress and don't have a SASS compiler setup so it would be nice to have the default css file included. 

The demo page also doesn't show up correctly cause demo.css and demo.js has been removed as well. Not a big deal but might be confusing for new users. :)

**Comment by regiside** [comment]
Okay I guess dist folder hasn't been included since v3.6.3. Obviously I can grab the .js from the cdn. is there a way to grab the css from the cdn?

**Comment by erikt9** [comment]
There is a dist if you `npm install` the package.  It contains plyr.css.

**Comment by sampotts** [comment]
The easiest is just to get it from the [CDN](https://cdn.plyr.io/3.6.12/plyr.css) or [unpkg](https://unpkg.com/plyr@3.6.12/dist/plyr.css) where you can also view the whole [dist](https://unpkg.com/browse/plyr@3.6.12/dist/) directory.
