### ISSUE TITLE
Volume control not working in ios

### ISSUE THREAD

**Issue by skngrg** [sampotts/plyr#2428]
### Expected behaviour
Mobile showing volume control
### Actual behaviour
Volume control not showing on mobile
### Steps to reproduce
open the [page](https://www.e1.ru/text/criminal/2021/07/07/70010921/) on ios, scroll to the audio and see that there is no volume control

### Environment

- Browser: any
- Operating System: IOS
- Plyr vesion ^3.5.6
### Link to where the bug is happening
https://www.e1.ru/text/criminal/2021/07/07/70010921/

**Comment by sampotts** [comment]
iOS doesn't (or didn't) support volume control for media. It's handled system-wide via the volume control on the device.

**Comment by skngrg** [comment]
ok, got it
Thanks a lot for your help!
