### ISSUE TITLE
With plyr-react useRef ref?.current?.plyr?.on is not a function

### ISSUE THREAD

**Issue by ajithofficial** [sampotts/plyr#2438]
I'm using plyr-react version 3.2.1

using useRef for Access the plyr instance

When initial render inside usEffect,  ref?.current?.plyr is {source: null}

While access to event it's throws error like below

Error: ref?.current?.plyr?.on is not a function

**NOTE** - For previous version like 3.1.0 it was working fine.

![image](https://user-images.githubusercontent.com/43783126/156451127-a2952734-6e2f-4fb3-b5ad-c73d8e37bada.png)

**Comment by sampotts** [comment]
Hey, your best bet would be to ask here:
https://github.com/chintan9/plyr-react
