### ISSUE TITLE
I have a problem with the volume control on my ipad

### ISSUE THREAD

**Issue by oNguyenTienManh** [sampotts/plyr#2471]
like the picture below, I set the volume down to 0.1, then check the value again, it's back to 1

this problem only occurs on ipad(probably ios), i tried on pc but i don't see this problem

![Screenshot from 2022-04-20 12-08-15](https://user-images.githubusercontent.com/70244770/164154981-9f49d1e3-c90c-424d-9d35-7747dcb75854.png)

please let me know how can i debug and fix this problem

**Comment by sampotts** [comment]
Volume cannot be controlled at the player level on iOS. It's handled at the system/device level.
