### ISSUE TITLE
`iconUrl` not working, even though `loadSprite` is disabled

### ISSUE THREAD

**Issue by ffxsam** [sampotts/plyr#2473]
Misunderstood the docs - my mistake! Closing.

**Comment by sampotts** [comment]
I'll edit the docs to make this clearer. It's obviously not clear enough as-is.

**Comment by ffxsam** [comment]
No worries! I misinterpreted this part:

"If false, it is assumed you are handling sprite loading yourself."

I thought it meant handling it yourself = specifying an icon URL.

**Comment by ffxsam** [comment]
BTW, in case you're curious, we're moving all Plyr-related files onto our own CDN. Sadly, I'm seeing more cases where users' privacy blockers are blocking CDNs willy-nilly, hence causing things to break.
