### ISSUE TITLE
supports('video/quicktime') returns false

### ISSUE THREAD

**Issue by ricardo17coelho** [sampotts/plyr#2478]
### Expected behaviour
supports('video/quicktime') should return true, becuse is supported

### Actual behaviour

supports('video/quicktime') returns false

https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#quicktime

**Comment by sampotts** [comment]
It'll only return `true` for Safari:

<img width="268" alt="CleanShot 2022-04-26 at 22 31 04@2x" src="https://user-images.githubusercontent.com/719092/165300345-c2918b69-29f1-40d4-bf26-cfc8fdeb725b.png">

You can also test the logic by call [canPlayType](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType) directly: 

```js
document.createElement('video').canPlayType('video/quicktime')
```

Should return `"maybe"`. 

Regardless, I'd use a more modern format as highlighted in the linked docs:

> Because QuickTime support is, for all intents and purposes, primarily available on Apple devices, it is no longer widely used on the internet. Apple itself generally now uses MP4 for video. In addition, the QuickTime framework has been deprecated on the Mac for some time, and is no longer available at all starting in macOS 10.15 Catalina.
