### ISSUE TITLE
We need Chinese doc!

### ISSUE THREAD

**Issue by JohyC** [sampotts/plyr#2479]
Come my friend! plyr this project is awesome ! I`m very love it. 
But I think we need Chinese Doc !

**Comment by fugbixer** [comment]
Calling strangers your friend is strange my friend. 
Learn English and translate. Your welcome to contribute

**Comment by sampotts** [comment]
I don't mind him calling him my friend 😄 It's quite common in other cultures and a nice touch. 

There _was_ a Chinese translation _somewhere_. I just can't remember where. Sorry! Perhaps some Googling will find it? If you do, please report back and I'll link it in the readme if it's up to date.

**Comment by JohyC** [comment]
Friend, thank you! I will find out. And I am also learning english!
I readly love [plyr](https://github.com/sampotts/plyr)!
plyr helped me a lot！

**Comment by sampotts** [comment]
Thanks, mate!

**Comment by Ray000000** [comment]
i18n: {
    restart: "重播", play: "播放", pause: "暫停",
    rewind: "倒退 {seektime} 秒", fastForward: "前進 {seektime} 秒",
    seek: "尋找",
    played: "已播放",
    buffered: "緩衝",
    currentTime: "目前時間", duration: "總共時間",
    volume: "音量", mute: "靜音", unmute: "取消靜音",
    enableCaptions: "開啟字幕", disableCaptions: "關閉字幕",
    enterFullscreen: "進入全螢幕", exitFullscreen: "退出全螢幕",
    frameTitle: "{title} 播放器",
    captions: "影片字幕",
    settings: "設定",
    speed: "播放速率", normal: "正常",
    quality: "影片畫質",
    loop: "循還播放",
    start: "開始", end: "結束",
    all: "全部",
    reset: "重置",
    disabled: "關閉",
    advertisement: "廣告",
    qualityBadge: {
      4320: "８Ｋ",
      2160: "４Ｋ",
      1440: "２Ｋ",
      1080: "ＨＤ",
      720: "ＨＤ",
      576: "ＳＤ",
      480: "ＳＤ",
    },
  },
