### ISSUE TITLE
Sprites image flashes for a split second before player renders

### ISSUE THREAD

**Issue by ffxsam** [sampotts/plyr#2485]
### Expected behaviour

I expect the video player to load without visual glitches.

### Actual behaviour

The sprites image is visible and very large just before the player renders.

### Steps to reproduce

Load page containing Plyr.

### Environment

- Browser: Chrome
- Version: 101.0.4951.54 
- Operating System: macOS
- Version: 11.6.1

### Link to where the bug is happening

https://play.reelcrafter.com/reel/example-reel

<img width="421" alt="CleanShot 2022-05-10 at 17 34 42" src="https://user-images.githubusercontent.com/12532733/167733410-9626e34a-2a4c-4fee-92fd-60e627010597.png">

**Comment by erikt9** [comment]
I believe you are loading and running the plyr javascript before loading its css.  The css should be loaded on the page before the plyr javascript runs.

**Comment by ffxsam** [comment]
@erikt9 Perfect, that did the trick. Thank you!
