### ISSUE TITLE
toggle playback

### ISSUE THREAD

**Issue by d4lv** [sampotts/plyr#2490]
the "space"  toggle playback stop working in the last version but only on browser like chrome-brave-opera etc. on firefox is ok is any fix for that??

(when i play it on my site the page is go down and in the demo https://plyr.io/ is just dont do nothing but the K is ok)

**Comment by fugbixer** [comment]
@sampotts 
please add space keyboard shortcut for pause / resume video playing

**Comment by RaSan147** [comment]
@sampotts any update??

**Comment by WebLeach** [comment]
Just use version 3.7.0 for now. 
Tried to fork and re build with older ones, but required packages weren't installing

**Comment by d4lv** [comment]
still this is not fixed on new version..

**Comment by Rishi-Bidani** [comment]
> @sampotts still this is not fixed on new version..
 I am using this as a work around till its fixed.

```
    (document.querySelector(".video__container") as HTMLDivElement).addEventListener("keydown", (e) => {
        if (e.key === " ") {
            e.preventDefault();
            (video.value as any).plyr.togglePlay();
        }
    });
```
