### ISSUE TITLE
Consider oembed for support X provider requests

### ISSUE THREAD

**Issue by drrobotnik** [sampotts/plyr#252]
Since you're using each vendors iframe and modifying through their api's. It might make it easier to maintain by using oembed to retrieve the proper iframe source. Oembed is well maintained and has many video/audio services using it. It would work well with plyr. You don't have to support every service, just use the service as the controller to make sure you're getting the services iframe correctly. You also get additional data back in a structured format which you could use to enhance the custom player ui.

Wistia for example:
https://wistia.com/doc/oembed
https://wistia.com/doc/player-api

SoundCloud:
https://developers.soundcloud.com/docs/oembed

**Comment by SamPotts** [comment]
I like the idea of not having to maintain the iframe code but an obvious downside is the slower performance of a round trip to get the HTML using AJAX prior to rendering. Will have a think about it.

**Comment by friday** [comment]
I think this only solves the easy part (getting the content). But there's no standardized oembed js API we can use to connect events from our controls to the iframe, right?

**Comment by micker** [comment]
hello i realy think oembed is a good solution to extand provider support !
https://oembed.com/ any news about this ?

**Comment by sampotts** [comment]
As @friday pointed out, the API isn’t standardized so it’s not really an option.
