### ISSUE TITLE
video does not play on mobile device 

### ISSUE THREAD

**Issue by ShoaibZhaid** [sampotts/plyr#2527]
check below link

https://drive.google.com/file/d/1k9pqH4CcgfiWnhP4Ch7mZPQtHXZwJcOT/view

**Comment by Davi-T** [comment]
I'm having the same issue. Getting > TypeError: null is not an object (evaluating 't.target.disabled') >>> plyr.polyfilled.js:2 >>> value, simulateTouchEvent, simulateMouseEvent, simulateMouseMove

**Comment by sampotts** [comment]
That file 404s for me. It seems to be working fine here on Android and iOS.
