### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by messagebeliever2022** [sampotts/plyr#2535]
1. An option or menu to add Likes Or Favourites Songs.. It has to been displayed with favourite icon?
image

![image](https://user-images.githubusercontent.com/112235944/193469218-d647aafd-b6b8-4960-9806-97db5d1e4a53.png)

2. Can the app be made as portable as well ? like other https://portableapps.com/
    Is it possible to carry the app and music in pen drive and play in any computer?

3. I have many files in .rm and .ram format (real media player formats). Is it possible to provide support for .rm and .ram files

4. An option to synchronize lyrics with an audio file. Following are working example
https://codepen.io/z-/pen/MQRGOe

**Comment by sampotts** [comment]
1. This should probably be managed outside of Plyr but is something we could consider in Vidstack (the next evolution of Plyr)
2. The nature of web video players is their content needs to be served by a web server. Perhaps INA or VLC would be better here?
3. We're limited by what formats browsers support - see https://developer.mozilla.org/en-US/docs/Web/Media/Formats.
4. Again, I would build this outside of the player itself.
