### ISSUE TITLE
Video decoder failed on mobile browser when video doesn't have audio in it 

### ISSUE THREAD

**Issue by harshilyadav223** [sampotts/plyr#2563]
Video decoder failed on mobile browser when video doesn't have audio in it 

code
:
3
message
:
"PIPELINE_ERROR_DECODE: video decoder reinitialization failed"
[[Prototype]]
:
MediaError

Steps to reproduce

provide a video url that does not have sound in it and then try to play on mobile device

**Comment by sampotts** [comment]
This would be an issue with the underlying `video` element, outside of the control of Plyr.
