### ISSUE TITLE
I need Help to add markers

### ISSUE THREAD

**Issue by gitbucket-crypto** [sampotts/plyr#2568]
I'm trying to add markes on event,

But no response the documentation doesnt mean how to work with markers,

Theres a div  it can append custom markers, but  my method never executed I'm at Babel JS maybe go to Vanilla JS

   player.on('durationchange loadeddata loadedmetadata', ()=>
        {
            //<div class="marker" style="left:92" data-time="12"><span>Obrigado</span></div>
            var p = jQuery(player.plyr__controls.plyr__progress.children_[0].el_);
            console.log(p);
 
        });

**Comment by sampotts** [comment]
I would suggest looking at the [demo code](https://github.com/sampotts/plyr/blob/master/demo/src/js/demo.js#L80) for this.
