### ISSUE TITLE
Better sizing (or even sizing at all?)

### ISSUE THREAD

**Issue by LogoJK** [sampotts/plyr#2569]
Giving the players a set size really needs to be added or at least documented.
Any try of doing a **simple** video list is an absolutely impossible with what plyr gives me.

![image](https://user-images.githubusercontent.com/86485918/201497673-57679b4e-6bf3-45c9-b673-0960ee67d3f3.png)

**Comment by sampotts** [comment]
The player is designed to be responsive by default. You can of course use CSS to set the `height` and `width` if you prefer. Or you can use the `ratio` option to force a consistent ratio for all videos.
