### ISSUE TITLE
cdn error

### ISSUE THREAD

**Issue by beijinaqie** [sampotts/plyr#2579]
![image](https://user-images.githubusercontent.com/36781262/204434796-302acf38-320f-46d3-80fd-d99b553376ec.png)

The official website cannot be opened and the cdn icon cannot be loaded

**Comment by stocksstinar0** [comment]
I had the same problem

**Comment by sampotts** [comment]
@stocksstinar0 The CDN is currently serving over 1,600 requests a second and the error rate is < 1%. I've also tested on a few connections and it seems fine here.
