### ISSUE TITLE
Vimeo player not working with airplay

### ISSUE THREAD

**Issue by gonziesc** [sampotts/plyr#2629]
### Expected behaviour

- Vimeo provider should show airplay button on Safari

### Actual behaviour

- Vimeo provider does not show airplay button on Safari

### Steps to reproduce

- Enter https://plyr.io/#vimeo on Safari
- Airplay button is not displaying

### Environment

- Browser: Safari
- Version: 16.1
- Operating System: MacOS
- Version: 13.0.1

### Console errors (if any)

- `this.media.webkitShowPlaybackTargetPicker is not a function. (In 'this.media.webkitShowPlaybackTargetPicker()', 'this.media.webkitShowPlaybackTargetPicker' is undefined)` if you manually display the button

### Link to where the bug is happening

- https://plyr.io/#vimeo

**Comment by sampotts** [comment]
Sorry, AirPlay is only supported for HTML5 video, currently. Vimeo (and YouTube) would need to add an API method for this to be possible. I'll add a note in the docs to cover this.

**Comment by bdougherty** [comment]
@sampotts we've added support for this to the Vimeo player. A `{method: 'remotePlaybackPrompt'}` message can be sent to the player to trigger it.

I'll have an update for the player api library shortly, and then I am happy to submit a pull request here to add support, if that is something you'd be open to merging.
