### ISSUE TITLE
Command failed: sh: gulp: command not found

### ISSUE THREAD

**Issue by muuvmuuv** [sampotts/plyr#2638]
Latest release causes an install error because "postinstall" cannot run.

> https://github.com/sampotts/plyr/commit/ed0b901d1175e1549324526b19ec0fac08b25fe3#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R33

```
node_modules/.pnpm/plyr@3.7.4/node_modules/plyr: Running postinstall script, failed in 293ms
.../.pnpm/plyr@3.7.4/node_modules/plyr postinstall$ pnpm build
│ > plyr@3.7.4 build /Users/marvin/Developer/xxxxx/app/node_modules/.pnpm/plyr@3.7.4/node_modules/plyr
│ > gulp build
│ sh: gulp: command not found
│  ELIFECYCLE  Command failed.
│  WARN   Local package.json exists, but node_modules missing, did you mean to install?
└─ Failed in 294ms at /Users/marvin/Developer/xxxxx/app/node_modules/.pnpm/plyr@3.7.4/node_modules/plyr
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by muuvmuuv** [comment]
@olieady I would not recommend that because e.g., Cypress needs scripts to install its binaries. Just pin the version to "3.7.3" for now.

**Comment by sampotts** [comment]
Apologies for this. I've pushed 3.7.5, which replaces references to `pnpm` with `npm` in scripts, which should resolve this issue. Report back if not.

**Comment by sampotts** [comment]
I've now completely removed the `postinstall` script in `3.7.6`
