### ISSUE TITLE
broken images on version 3.7.7

### ISSUE THREAD

**Issue by d4lv** [sampotts/plyr#2642]
i hope is only for me but the last version is broken https://prnt.sc/CQIln2z1ji4K and the console error https://prnt.sc/6FhcE8yMyevh

i use https://cdnjs.cloudflare.com/ajax/libs/plyr/3.7.7/plyr.js not local host, i clear caches but still the player is missing icons.

**Comment by sampotts** [comment]
Not sure what happened there but some purging of cache and it seems to have come good. Can you try again and report back if there's any issue? Thanks!

**Comment by d4lv** [comment]
is ok now
