### ISSUE TITLE
issues on playing on mobile phones

### ISSUE THREAD

**Issue by jelkomme** [sampotts/plyr#2653]
@sampotts 
i got some issues on smartphones with playback youtube videos. somethimes they wont play! they just show the youtube play icon when i click on that icon the loading circle is turning and turning but no playback... this happens only on smartphones. any ideas?

Thank you.

**Comment by jelkomme** [comment]
When i activate full-screen mode on my smartphone, parts of the video may get cut off because the screen stretches too much. this does not happen on regular yt-player but only on plyr-player. any help?

**Comment by sampotts** [comment]
I've commented regarding the control we have over the YouTube quality, on the other issue you commented on. Closing this one.

**Comment by jelkomme** [comment]
@sampotts
i got issues on smartphones with playback youtube videos. somethimes they wont play! they just show the youtube play icon, when i click on that icon the loading circle is turning and turning but no playback... this happens only on smartphones. any ideas?

(This has nothing to do with quality check) 

Thank you.
