### ISSUE TITLE
Contorl icons not displaying

### ISSUE THREAD

**Issue by moses-mbaga** [sampotts/plyr#2658]
Hello, 

All the control icons were previously displaying but suddenly disappeared across 2 of my sites that use your library. Can you look into it

**Comment by sampotts** [comment]
Got a link so I can check? If not, which version? The demo site looks ok but that uses latest, of course.

**Comment by CraftedRO** [comment]
same problem here, link here http://craftedro.go.ro/radio/index.html
```
cess to XMLHttpRequest at 'https://cdn.plyr.io/3.7.8/plyr.svg' from origin 'http://craftedro.go.ro' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
controls.js:53 Uncaught Error: 0
    at XMLHttpRequest.<anonymous> (controls.js:53:12)
(anonymous) @ controls.js:53
cdn.plyr.io/3.7.8/plyr.svg:1     Failed to load resource: net::ERR_FAILED
```

**Comment by CraftedRO** [comment]
related https://github.com/sampotts/plyr/issues/2201

**Comment by gamestap99** [comment]
> Got a link so I can check? If not, which version? The demo site looks ok but that uses latest, of course.

I also encountered a similar error when trying to retrieve the plyr.svg file, as it returned a 421 error network code

**Comment by Baldarello** [comment]
> > Got a link so I can check? If not, which version? The demo site looks ok but that uses latest, of course.
> 
> I also encountered a similar error when trying to retrieve the plyr.svg file, as it returned a 421 error network code

Yes same here, 
![image](https://user-images.githubusercontent.com/13116656/231413400-ccc37f77-d3cf-4947-b0d6-079bc3b99772.png)
![image](https://user-images.githubusercontent.com/13116656/231413466-ee9c2e71-3eb7-44d1-961e-9215f238b436.png)

**Comment by juji** [comment]
same here...

![Screen Shot 2023-04-12 at 17 06 42](https://user-images.githubusercontent.com/493553/231426325-e51033e1-8261-4ade-b7ac-99267491898e.png)

**Comment by sampotts** [comment]
Sorry for the delay. I'm actually on holiday with my family so couldn't fix this very quickly. 

This should be resolved now. Fastly pushed a change related to TLS validation which seemed to break everything, even though they claimed there would be no change to my account. I guess it's time to accelerate the move to R2 for object hosting. I've temporarily bypassed Fastly for now but as Cloudflare doesn't have _proper_ origin shielding (and Fastly does), my S3 bill is likely to increase substantially (with almost 500 million unique a month!) as it did last time I tried this. I hope you're all sponsoring/donating! :)

**Comment by CraftedRO** [comment]
I still get a
GET https://cdn.plyr.io/3.7.8/plyr.svg 403

**Comment by Baldarello** [comment]
> I still get a GET https://cdn.plyr.io/3.7.8/plyr.svg 403

same here...

**Comment by sampotts** [comment]
https://httpstatus.io says 200 for that URL. You may just have to wait. I'm not 100% sure how Cloudflare's "Proxied" DNS records work. 

<img width="601" alt="CleanShot 2023-04-12 at 21 04 12@2x" src="https://user-images.githubusercontent.com/719092/231438930-5607b60c-461e-4bc6-81bc-63a375faa8ec.png">

**Comment by CraftedRO** [comment]
ok now it works
