### ISSUE TITLE
Speed up loading buffering before/after playing video

### ISSUE THREAD

**Issue by pvtai** [sampotts/plyr#2688]
### Expected behaviour
Speed up loading buffering before/after playing video
I want to speed up loading like this 
![Screenshot (101)](https://github.com/sampotts/plyr/assets/4888072/6b07b119-522e-4c1e-a7e8-d1886d215dfe)

### Actual behaviour
Progress bar buffering displays very slowly

### Environment

- Browser: Chrome
- Version: 3.7.8
- Operating System: Windows
- Version: 11

### Link to where the bug is happening
My code here:
https://github.com/pvtai/player/blob/main/player.php

Thank you

**Comment by pvtai** [comment]
Hello,
Is anybody here?
@sampotts

**Comment by sampotts** [comment]
I'm not sure what problem you're having. Buffering speed is directly related to:
- whatever server is hosting your video
- the bandwidth available between the user and the server

Plyr is a wrapper for either HTML5, YouTube or Vimeo and has no control over any of the above. 

If you want a fast service to host your videos, you can look at services like:

- Cloudflare with their R2 product
- S3 and CloudFront on AWS
...plus many more. 

Hope that helps.

**Comment by sampotts** [comment]
My answer to that would be, you might want to look into upgrading your internet connection 👍🏼 If it plays fine with minimal buffering, it's not really a big problem.

**Comment by pvtai** [comment]
> My answer to that would be, you might want to look into upgrading your internet connection 👍🏼 If it plays fine with minimal buffering, it's not really a big problem.

Thank you so much, bro
