### ISSUE TITLE
Custom controls

### ISSUE THREAD

**Issue by Shuvadip-Ghosh** [sampotts/plyr#2700]
### Custom controls for hls stream
I would like to make a custom control button but do not know how to do
it should be like this codepen repo  
https://codepen.io/jwjcmw/pen/pedQRL   
  
the button should be  on the down-right corner but above the controls but doing it the way shown is not working for me 
my controls list is   
  
const controls = [
        "play-large", // The large play button in the center
        "rewind", // Rewind by the seek time (default 10 seconds)
        "play", // Play/pause playback
        "fast-forward", // Fast forward by the seek time (default 10 seconds)
        "progress", // The progress bar and scrubber for playback and buffering
        "current-time", // The current time of playback
        "duration", // The full duration of the media
        "volume", // Volume control
        "settings", // Settings menu
        "pip", // Picture-in-picture (currently Safari only)
        "fullscreen", // Toggle fullscreen
    ];

**Comment by vitordml** [comment]
You can inject the html for the custom control into the controls dom container at the initialization of the player and its controls.
Or you can have the custom html in the page, inside the player container, and you can use the js hooks for hiding and showing the controls to also hide and show your custom html controls.
