### ISSUE TITLE
TypeError: webkitEnterFullScreen is not a function (Chrome & Safari)

### ISSUE THREAD

**Issue by lf-devs** [sampotts/plyr#2701]
### Expected behaviour
It should play video in fullscreen mode in mobile devices

### Actual behaviour
When clicked on fullscreen icon, the following error appears: ` TypeError: webkitEnterFullScreen is not a function`
![image](https://github.com/sampotts/plyr/assets/82515790/68efb412-2c6f-4a92-a5ba-ccc716ae6a9f)

### Steps to reproduce
Play any youtube video on mobile and try to enter into fullscreen mode.

### Environment

- Browser: Chrome and Safari
- Version: Chrome (114.0.5735.99)
- Operating System: iPhone 11
- Version: iOS 16.5

### Console errors (if any)
![image](https://github.com/sampotts/plyr/assets/82515790/68efb412-2c6f-4a92-a5ba-ccc716ae6a9f)

**Comment by lf-devs** [comment]
@sampotts - Please review this. I'm facing this bug in iPhone 11. Please share the solution for this. I've installed the 'Plyr' dependency using `yarn` with "next": "^12.1.6".

**Comment by sampotts** [comment]
Are you able to replicate this on https://plyr.io? 

What config are you using? It'll help me to debug.

**Comment by lf-devs** [comment]
Here is the config:
`const plyr_config = {
        controls: [
          "play-large",
          "play",
          "progress",
          "duration",
          "mute",
          "volume",
          "captions",
          "fullscreen",
        ],
        width: 100,
        height: 100,
        playsinline: true,
        disableContextMenu: true,
        vimeo: { byline: false, portrait: false, title: false, speed: true, transparent: false, playsinline: true },
        youtube: { noCookie: false, rel: 0, showinfo: 0, iv_load_policy: 3, modestbranding: 1, playsinline: true },
        fullscreen: {
          enable: true,
          allowAudio: true,
          iosNative: true,
        },
        captions: { active: true, language: "auto", update: true },
        autoplay: false,
      };`

**Comment by lf-devs** [comment]
Using v3.7.3 in another project and it's working absolutely fine. However, the same version throws the error in a new project.

Both projects are in `next.js v12.1.6.`

**Comment by sampotts** [comment]
Are you using custom controls? If you're using YouTube as you've said (and the screenshot would indicate) and you've set `fullscreen.iosNative` to `true` and `playsinline` to `true`, it will play the video using the native player, because we can't programatically trigger fullscreen via the YouTube API. This is noted in the settings section of the readme:

> YouTube does not support programatically toggling the native fullscreen player via it's API. This means on iOS you have two options, neither being perfect:
> - Use the fallback/faux fullscreen option which covers the whole viewport (this is the default)
> - Set `playsinline` to `false` and/or `fullscreen.iosNative` to `true` - either option hides the fullscreen toggle in the UI (because of the above API issue) and means iOS will play the video in it's native player.

Given the config you've provided, you should not see the fullscreen toggle and I don't here using that config. 

![CleanShot 2023-06-13 at 21 37 14@2x](https://github.com/sampotts/plyr/assets/719092/3a3d7f35-d371-4a9d-9d9d-e32e5e7fd31c)

**Comment by lf-devs** [comment]
@sampotts - Thank you soo much for helping me out.

I've update the config:

```json
 const plyr_config = {
        controls: [
          "play-large",
          "play",
          "progress",
          "duration",
          "mute",
          "volume",
          "captions",
          "fullscreen",
        ],
        width: 100,
        height: 100,
        playsinline: true,
        disableContextMenu: true,
        vimeo: { byline: false, portrait: false, title: false, speed: true, transparent: false, playsinline: true },
        youtube: { noCookie: false, title: false, playsinline: true },
        fullscreen: {
          fallback: true,
          enable: true,
          allowAudio: true,
          iosNative: false,
        },
        captions: { active: true, language: "auto", update: true },
        autoplay: false,
      };
```

The youtube video fullscreen is working now.
