### ISSUE TITLE
Wrong condition that won't be satisfied

### ISSUE THREAD

**Issue by qugh** [sampotts/plyr#2730]
https://github.com/sampotts/plyr/blob/master/src/js/fullscreen.js#L280

https://github.com/sampotts/plyr/blob/master/src/js/fullscreen.js#L259

You check the !Boolean(value), and then the string for emptiness. This condition should not work.

**Comment by sampotts** [comment]
It's a valid point; the else if condition is negated by the condition above it.

**Comment by qugh** [comment]
> It's a valid point; the else if condition is negated by the condition above it.

ye. my mistake. its closed
