### ISSUE TITLE
Progress bar stands still android chrome 

### ISSUE THREAD

**Issue by sanserna** [sampotts/plyr#308]
Hi, I was testing the video player with embedded youtube video in a nexus tablet with chrome , I found that when you click the progress bar to advance vídeo playback, the progress marker moves to the position where I click and stands still and the vídeo continúe playing. If you press de play/pause button, the progress marker starts moving again from the position in which it is supposed to be.

**Comment by SamPotts** [comment]
Damn. I'll take a look. Thanks for reporting 👍

**Comment by SamPotts** [comment]
Which version of Chrome  + Android are you using? I'm struggling to replicate on Android 4.4 with latest Chrome.

**Comment by sanserna** [comment]
Im using Android 6.0 with Chrome versión 51.0, not sure if other mobile devices present the same problem, I just taste it in a nexus 7.

**Comment by SamPotts** [comment]
Is this still an issue?

**Comment by nathaliasebben** [comment]
@SamPotts Hi, I'm implementing the audio player, I tested it on other mobile devices and it worked, on Nexus 5 LG Android 6.0.1 with Chrome version 54.0 the player does not work.
![screenshot_20161201-105147-2](https://cloud.githubusercontent.com/assets/20545476/20794677/93af15da-b7b4-11e6-8aa4-02ea6027c3b4.png)

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
