### ISSUE TITLE
Problem with Fullscreen and will-change

### ISSUE THREAD

**Issue by dpschen** [sampotts/plyr#350]
I have a case where I use plyr inside an overlay that has the css will-change attribute.

If I enable full screen the overlay and plyr won't be shown and the background shines through (macOS, Chrome).
Screenshot:
(https://i.imgur.com/nEF5TW8.png)

But if I comment out the will-change everything works fine.
Screenshot:
(https://i.imgur.com/shCbM4m.png)

Test it here: https://codepen.io/dpschen/pen/PzPMdR

I'm not sure if this is a problem with plyr or more a browser bug of Chrome desktop and mobile (Opera, Safari, Firefox and Edge seem to work) and where I should report it.

**Comment by dpschen** [comment]
If I get it right, it has to do something with this:
https://bugs.chromium.org/p/chromium/issues/detail?id=582318

**Comment by SamPotts** [comment]
I think this is outside of the scope of Plyr?

**Comment by dpschen** [comment]
An overlay that uses will-change isn't uncommon. I thought there might be a way to address this in the stylesheet of plyr somehow.
Otherwise feel free to close the issue. For me the bug seems to be to complicated to solve. Do you know where else I could report the problem instead?

**Comment by SamPotts** [comment]
I'll have a look and see if I can come up with something then 👍

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
