### ISSUE TITLE
multiple play buttons/songs but only one player

### ISSUE THREAD

**Issue by anybany** [sampotts/plyr#354]
Hi, i've got some crazy idea in mind :)

I would like to build a website with one player (play/pause, progress, volume etc) fixed somewhere on the page and then multiple play-buttons spread all over the page. and each play-button starts a different song in the fixed player.

do you think something like this is possible with plyr?

nevertheless plyr looks awesome and seems to be very easy. i will try it on the weekend!

**Comment by hilburger** [comment]
Hi anybany,  have you succeeded? I need exactly the same ;)

**Comment by anybany** [comment]
Hi @hilburger 
sorry didn't had the time to try it yet. I'll let you know!

**Comment by SamPotts** [comment]
You could start by looking at the `.source()` API method I'd say?

**Comment by samuelcarreira** [comment]
Yeah you can use one player and set the source dinamically based with the clicked button. Each button can trigger a function to set the plyr source to a specific file.

**Comment by friday** [comment]
This is possible as mentioned. With v3 using [the source setter](https://github.com/sampotts/plyr/#the-source-setter)
