### ISSUE TITLE
Add Support for macOS Sierra Picture in Picture

### ISSUE THREAD

**Issue by justadaniel** [sampotts/plyr#366]
The title says it all. MacOS Sierra now has a PiP button on the native video controls. I'm pretty sure all you have to do is some research and add the button and functionality.

**Comment by SamPotts** [comment]
I've already been looking at this, just not got around to getting it into the player. It's pretty straight forward to do. Working on it 👍

**Comment by dacheezypuffs** [comment]
Alright cool, will definitely be looking forward to this in the future!

**Comment by nam-co** [comment]
Hi Sam is it possible to add airplay also? appreciate your work on the player, thanks

**Comment by nam-co** [comment]
Sorry I just saw it under "Features currently being developed", thanks

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
