### ISSUE TITLE
Player variable always undefined

### ISSUE THREAD

**Issue by joerstom** [sampotts/plyr#370]
After using var player = plyr.setup()[0]; I always receive a "TypeError: player is undefined" error when trying to destroy the instance using all variations of player.destroy(); player.plyr.destroy(); and player[0].destroy();

**Comment by dacheezypuffs** [comment]
Bump

**Comment by SamPotts** [comment]
If this was the case, https://plyr.io would not work:
https://github.com/Selz/plyr/blob/master/demo/src/js/main.js#L28

Do you have any more info on reproducing this?

**Comment by joerstom** [comment]
Perhaps I'm not approaching this in the best possible way but I'm trying to minimize load times. 

I have 8 videos I want to play within a modal. I'm binding plyr.setup into the click event for the video thumbnails, and passing the video id via data attributes. Then when the video is finished playing - a custom overlay is added on top of the video. What would be ideal is that when the modal is closed, the plyr object is destroyed.  This only works if the destroy() is called within the same function as the setup(). It would be more natural if the variable "player" was accessible globally.

Should I try setting the variable outside of my document.ready function? This is a simple version of what it looks like:

`jQuery(document).ready(function($) {
$('.episode .video-link').bind('click', function(e) {
		e.preventDefault();

		var vid = $(this).data('vid');
		var vlink = $(this).data('link');
		
		$('.modal.video').addClass('visible').find('.player-container .vimeo-player').attr("data-video-id", vid);
		$('.modal.video').find('.btn-primary').attr("href", vlink);
		
		var playermodal = plyr.setup('.modal.video')[0];

		playermodal.on('ready playing pause ended', function(event) { 
		    switch(event.type) {
		        case 'ready':
		            break;
		        case 'playing':
					console.log(playermodal.getDuration());
		            break;
		        case 'pause':
		          
		            break;
		        case 'ended':
		        	
		        	$('.modal.video .next-episode').fadeIn();
		        	
		        	break;
		    }
		});
		
		$('.close, .overlay').bind('click', function(e) {
			e.preventDefault();
			$('.modal').find('.player-container .vimeo-player').attr("data-video-id", "");
			$('.modal').find('.btn-primary').attr("href", "");
			$('.modal.video .next-episode').hide();
			playermodal.destroy();
			console.log("DESTROYED!");
		});
		
	});
});`

**Comment by gurupras** [comment]
I'm confused..Isn't your `playermodal` object is _inside_ the anonymous function that is bound to `.episode .video-link`'s `click` event? This would mean that the scope of this variable is only within this anonymous function.

In that case, if you defined `$('.close, .overlay').bind('click', function(e) {...}` _outside_ of this anonymous function, the browser is expected to complain about not finding `playermodal`.

**Comment by joerstom** [comment]
The undefined variable occurs either way. Maybe I'm not understanding how variables are declared, but it should be available to be accessed regardless of whether it's called within a function. 

I did attempt to declare the variable outside of the function, with no success. When the `destroy()` is called it returns an "undefined variable". No matter where `playermodal` is declared.

**Comment by gurupras** [comment]
Well, there is *definitely* a bug, but it is not that the player variable is undefined.
Check out this example: https://jsfiddle.net/gurupras/0wx9e754/

**Comment by zeeshanjan82** [comment]
I am also getting undefined error for player @joerstom have you managed to fix this?

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
