### ISSUE TITLE
Creating youtubes after the fact

### ISSUE THREAD

**Issue by MHenley** [sampotts/plyr#377]
I have a project where I'm creating youtubes after the page loads and for some reason I'm encountering a bug where the youtube video refuses to load again after it's already been loaded once on the page.

I can't replicate it via JSFiddle, but I did find a fix for myself.  When I change https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L1608 to plyr.embed = new window.YT.Player(container, { then the problem goes away.  Other examples that I see online uses the container and not the container.id.

I guess I'm wondering if the code on that line is correct or should you be referencing the full container object?

**Comment by SamPotts** [comment]
I'll take a look - thanks for letting me know

**Comment by joshuapease** [comment]
Howdy! Just coming by to confirm that I'm hitting the same issue too whenever I dynamically create & destroy youtube videos. Trying to integrate Plyr with a custom modal I'm building for a site. 

The video is dynamically created when a modal is opened and then destroyed when it is closed. 

I've put together a reduced test of the issue. This is roughly how I'm going about creating & destroying. I've tested with Vimeo videos and this isn't an issue.

http://codepen.io/joshuapease/pen/qaYdLR

Notice the console error after you've toggled the video twice. Seems to be coming from youtube's JS. 

![image](https://cloud.githubusercontent.com/assets/2145998/19253705/fd29cbee-8f01-11e6-8a9a-738927c22eb3.png)

PS. This is "by far" the best JS video player I've used, so great.

**Comment by SamPotts** [comment]
Thanks Josh. I'll try and fix this issue as soon as I get some time (possibly today/tomorrow).

**Comment by joshuapease** [comment]
Hey @SamPotts & @MHenley! I think I may have figured out what my issue was. 

I was calling `plyr.setup()` before I'd actually appended the DOM element to the body. So while the element did exist, it wasn't part of the actual document tree. 

Must be that Youtube and/or Plyr don't like that. I did notice that Plyr controls weren't showing up on the old demo. 

Here's a new codepen that seems to show everything working. Simply involved swapping the order of a single line of code. 

http://codepen.io/joshuapease/pen/LRALqQ

**Comment by SamPotts** [comment]
Hey @joshuapease,

Thanks for reporting back. So is there still a bug that needs fixing or are we good?

**Comment by joshuapease** [comment]
Yeah! Seems to be working well for me.

Although I'm curious if the route I took is a good way to dynamically
create Plyr instances. Is there a better way to do that programmatically?
