### ISSUE TITLE
Event callback if the plugin wasn't enabled, i.e IE browsers.

### ISSUE THREAD

**Issue by ImranBug** [sampotts/plyr#384]
Do we have or can have a callback function when custom player is not added i.e in IE browsers?

**Comment by SamPotts** [comment]
Is this any use? https://github.com/Selz/plyr#checking-for-support

**Comment by ImranBug** [comment]
I know some browsers are not supported but the video should at least play with normal UI ... I ended up using this to make sure Youtube UI is there for video:

	// Fallback if custom controls dont exist i.e IE
	setTimeout(function () {
		if(!$('.plyr__controls').get(0)){

			$('.we-video iframe').each(function () {
				var src = $(this).attr('src');
				var src = src.split('?')[0];
				$(this).attr('src', src);
			});

			$('.we-video iframe').css({
				width: '100%',
				height: '100%'
			});
		}
	}, 5000);
