### ISSUE TITLE
Adaptive streaming options.

### ISSUE THREAD

**Issue by zyxep** [sampotts/plyr#39]
Hi.

I would love to see adaptive streaming support for VOD and Live.
Read about it here: http://www.wowza.com/forums/content.php?546

**Comment by SamPotts** [comment]
Hey @zyxep , I'll look into how feasible this is and get back to you.

**Comment by guido4000** [comment]
HLS support and MPEG DASH would be great.

**Comment by ronag** [comment]
@SamPotts: We're looking into using plyr in our projects. We have no need for streaming right now but we will in the not to far future. What is your recommendation, should we use plyr and hope for HLS support or should we choose something else (e.g. clappr).

I'm not looking for any promises just want some clarification on the intentions/roadmap.

**Comment by SamPotts** [comment]
Hey @ronag , it's something I *want* to do but struggling to find the time to devote to it at the moment. I know there's dash.js but wasn't aware of hls.js. I'll take a look at that. It's hard to say when it'll be done given the nature of the project is basically whenever I get free time at the moment :-(

**Comment by friday** [comment]
Closing since streaming is possible and [documented](https://github.com/sampotts/plyr/#streaming) now. For more specific issues of support like handling captions or switching quality, see the current github issues, or create a new one if none of the current describes your problem.
