### ISSUE TITLE
Standard Volume Unit

### ISSUE THREAD

**Issue by Drulac** [sampotts/plyr#400]
Hello,
The `instance.getVolume()` method return value between 0 and 1. `instance.setVolume(vol)` need a value between 0 and 10. Why it is not the same volume unit ?

**Comment by SamPotts** [comment]
Good point. I'll fix this in the next major release (soon) with a few other new features as it would be a breaking change.

**Comment by silverwind** [comment]
I'd suggest unifiying both to a range of 0 - 1 and make the volume slider accept floating point values. If a value > 1 is encountered on setVolume, you can divide by 10 for some backwards compatibilty, if needed.

**Comment by arxpoetica** [comment]
I just discovered this discrepancy too. Looks like it's been in the pipe awhile. Any idea when it will land?

**Comment by sampotts** [comment]
It's already in v3 which I should have out soon (sorry, I keep saying that)

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
