### ISSUE TITLE
Unmute button won't work when volume sets to 0

### ISSUE THREAD

**Issue by Topski2015** [sampotts/plyr#404]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io
### Expected behaviour

Unmute button should work. Restores sound
### Actual behaviour

Won't unmute except if the volume is set from 1 - 10, but if set to 0 it won't unmute
### Environment
- Browser: Chrome, firefox, IE
- Version:  any
- Operating System: windows
- Version: 7
### Steps to reproduce
- 
### Relevant links

https://jsfiddle.net/0o3ehedp/

**Comment by SamPotts** [comment]
Thanks - what would the expected behaviour be if the user sets the volume to 0 on the slider, then mutes, then un-mutes? What value should be restored?

**Comment by Topski2015** [comment]
value should be 10 I think.

**Comment by SamPotts** [comment]
What's that based on? Perhaps we should use the `config.volume` value?

**Comment by Topski2015** [comment]
Hi. If you take a look from the sample fiddle , My default value is 0 because I thought it should represent "Mute" mode. So if user clicks the "mute" icon it should restore the sound. But the currently , if I click the "mute" button the sound won't function. I thought there is something missing on my code if you check it. What is the config.volume?

**Comment by SamPotts** [comment]
`config.volume` is the `volume` property of the initial config passed to the player. Setting it to `0` would be a pretty strange case but I guess setting it to max on un-mute makes sense in this case. YouTube doesn't restore the previous value on unmute, they just set it to max. However, the native HTML5 player does not. If you set volume to `0` and then try to unmute nothing happens. It stays muted. On Chrome at least. 

Example:
http://html5demos.com/video

**Comment by Topski2015** [comment]
alright. it makes sense now. I guess I should try this. Thanks!

**Comment by garethjohnsdesign** [comment]
Was anything resolved here, having the same issue, I basically want a video to autoplay muted then someone can hit the volume button to unmute it

**Comment by JesseHigson** [comment]
+1 for the above comment

**Comment by sampotts** [comment]
I will get this fixed up in the next major release (which I'm very close to working on). Really sorry about the delay. Being a dad hasn't left me much spare time...

**Comment by sampotts** [comment]
I think this is resolved in v3+, I just forgot to close the issue. Let me know if it's still an issue 👍

**Comment by bhayward93** [comment]
Hey @sampotts, any chance that this could be reoccurring?

Here is a quick video showing what is happening.
https://streamable.com/a1rgeg

I noticed it in v3.5.6, upgraded, and replicated in v3.6.2.

It uses ngx-plyr as a wrapper, but if it's of any use our code is here https://gitlab.com/minds/front/blob/e055ca31aa2c0210f366d6cc82433d72208c8548/src/app/modules/media/components/video-player/player.component.ts#L123

With the only difference being how Plyr is imported, and the volume option being set to true.
