### ISSUE TITLE
How to control the subtitles inside the MPD/Dash file?

### ISSUE THREAD

**Issue by KingjZhang** [sampotts/plyr#418]
- [X] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
I want to control the subtitles inside the MPD file.
### Actual behaviour
The plyr video player can't read the subtitles from Dash.js

### Environment

- Browser: Chrome 
- Version:  All
- Operating System: All
- Version: All

### Steps to reproduce 
- This is an mpd with subtitles. The plyr video player can't read the subtitles from Dash.js. 
https://vm2.dashif.org/dash/vod/testpic_2s/multi_subs.mpd

### Relevant links

**Comment by jronallo** [comment]
I've confirmed using the dash.js reference player that the manifest @KingjZhang points to does show the English captions, but does not allow for turning them on/off.

The dash.js reference player allows for turning on/off different captions/subtitles for that example.
http://dashif.org/reference/players/javascript/

**Comment by jronallo** [comment]
@KingjZhang Can you try adding the following CSS? This worked for me to show sidecar WebVTT captions in an MPD in Chrome. Note that in my case I was able to see the captions in Firefox already.

```css
.plyr video::-webkit-media-text-track-container {
    display: block;
}
```

See an example here: http://codepen.io/jronallo/pen/ENzbpe

**Comment by KingjZhang** [comment]
@jronallo 

Thanks. I just adding the CSS. It works now.

**Comment by friday** [comment]
Closing in favor of #470.
