### ISSUE TITLE
crossorigin can't work on macOS sierra Safari 10.0

### ISSUE THREAD

**Issue by amowu** [sampotts/plyr#422]
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 

Video should be work with `crossorigin` attribute

### Actual behaviour

It can't work, all `<source>` and `<track>` not be append

### Environment

- Browser: Safari
- Version: 10.0
- Operating System: macOS
- Version: Sierra

### Steps to reproduce 

- Use macOS Sierra Safari 10.0 to open https://plyr.io

### Relevant links

**Comment by SamPotts** [comment]
So this is a bug with *Safari* as opposed to Plyr? 

Probably best to raise it here:
https://webkit.org/reporting-bugs/

**Comment by amowu** [comment]
@SamPotts look like it's Plyr's bug

Because I put this code in JSBin, it can work

```
<video poster="https://cdn.selz.com/plyr/1.5/View_From_A_Blue_Moon_Trailer-HD.jpg?v1" crossorigin controls>
  <source src="https://cdn.selz.com/plyr/1.5/View_From_A_Blue_Moon_Trailer-HD.mp4" type="video/mp4">

  <!-- Text track file -->
  <track kind="captions" label="English" srclang="en" src="https://cdn.selz.com/plyr/1.5/View_From_A_Blue_Moon_Trailer-HD.en.vtt" default="">
</video>
```

**Comment by SamPotts** [comment]
So are you seeing this on https://plyr.io?

**Comment by Nadeus** [comment]
My gf has the same problem too, she cant see the player on her 2016 mac book air , this problem is very annoying :/

**Comment by SamPotts** [comment]
If you don't need the crossorigin attribute - i.e. you're not loading webvtt files from another domain, you can remove the attribute.

**Comment by amowu** [comment]
Edge 14 has the same problem too.

**Comment by friday** [comment]
Is this still happening? Seems very strange to me that only a couple of people would have these issues if it's a browser bug, rather than a browser addon, proxy issue, misconfigured server or something.

There was a related issue in iOS 10 around that time though: https://poodll.com/ios-10-and-html5-video-and-html5-audio-on-https-sites/

Anyway. I'll close this until some confirmation of the opposite (comment here).
