### ISSUE TITLE
Dynamically embedded youtube gives “cannot read property of play of undefined” error

### ISSUE THREAD

**Issue by cwaldau** [sampotts/plyr#423]
I am dynamically loading embedded youtube videos into the http://plyr.io custom player

```
  player.source({
    type:       'video',
    title:      'Example title',
    sources: [{
        src:    '5WU7oGiwiao', // youtube 11 digit id
        type:   'youtube'
    }]
```

However I am receiving the following error:

Uncaught TypeError: Cannot read property 'play' of undefined.

This error is blocking other elements of my javascript from executing but I cannot figure out why it is happening.

The error doesn't occur if I load the player statically

`<div class="plyr"><div data-type="youtube" data-video-id="5WU7oGiwiao"></div></div>`

JSFiddle: http://codepen.io/cwaldau/pen/JbXjKW

Thank you!

**Comment by javiergarciagonzalez** [comment]
Are you receiving the error on a device environment or on a desktop one? Because I'm having that error only in devices environment.

**Comment by sampotts** [comment]
Can you try this again in v3? I have a feeling this should be resolved but if not, feel free to re-open 👍

**Comment by cwaldau** [comment]
Hi! Thanks for the update but I have moved on from this project. In fact, I was testing to see the viability of using the player in another context but ended up mostly coding up my own thats specific to my purposes.

Unfortunately, I no longer have the code I was testing with and the JSFiddle linked above seems to be working even with v1.6.13, so its hard for me to confirm whether the issue still exists, sorry!

Happy to see development is still ongoing though, I may need to revisit this player for my other needs!

**Comment by sampotts** [comment]
All good - thanks for the reply 👍
