### ISSUE TITLE
Animate.css conflicting with Plyr

### ISSUE THREAD

**Issue by sohrabzia** [sampotts/plyr#429]
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behavior 
on full screen active only Plyr should be visible.

### Actual behavior
after adding animate.css some divs from page are showing on top of full screen video.
everything is fine and working as expected without animate.css

### Environment

- Browser: chrome
- Version:  
- Operating System: windows
- Version: 8.1

### Steps to reproduce 
- issue with chrome only

### Relevant links

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
