### ISSUE TITLE
Cannot set source property dynamically on an angular directive

### ISSUE THREAD

**Issue by aarjithn** [sampotts/plyr#435]
I was using plyr with angular directive as suggested in http://stackoverflow.com/a/37950692 and it works great.

Now I'm looking to switch between youtube and external video source depending upon some condition. I have removed `data-type` and `data-video-id` and trying to use source property on the instance. However I'm getting `TypeError: Cannot set property 'source' of undefined`

I've created a plnkr to demonstrate the issue. (check browser console)
https://plnkr.co/edit/pARzwIjxBv5imCjr9waA?p=preview

It works fine with template in line 10 (commented) but that in line 11 throws above error. Looks like plyr doesn't find any elements to instantiate, hence it fails. 

How to handle this case?

### Environment

- Browser: Chrome
- Version:  55
- Operating System: OSX
- Version: Sierra

**Comment by friday** [comment]
I'm closing this since it's now outdated and phrased as a question. If you still have this issue, please upgrade Plyr in the example and paste the full stack trace. Also our [slack](https://bit.ly/plyr-chat) is better for questions.
