### ISSUE TITLE
Disable double-click on progress bar

### ISSUE THREAD

**Issue by GBratsos** [sampotts/plyr#436]
- [*] Issue does not already exist
- [*] Issue observed on https://plyr.io

### Expected behaviour 
I use some code in order to disable seeking after the current progress of the video, but when i doubleclic on the progress bar the progress goes forward.
I use a native video element not embed from vimeo/YouTube

### Actual behaviour
Shouldn't update video progress when i double click on progress bar.

### Environment

- Browser: Chrome
- Version:  54
- Operating System: OS X
- Version: Sierra

### Steps to reproduce 
- Use script that on click disables seeking forward and enables seeking backwards.
- Double click forward on the unwatched progress.

### Relevant links

**Comment by friday** [comment]
Closing this as it's very old by now and I wasn't able to replicate it.

If you ask at [our slack](https://bit.ly/plyr-chat) with a link to a jsfiddle, codepen or something similar, the latest Plyr version and minimal code to reproduce your problem I will try to help you.
