### ISSUE TITLE
I change the source from the video, after i cant play it.

### ISSUE THREAD

**Issue by ghost** [sampotts/plyr#440]
Hi, there! im using the source method but before change the video y can't play the video, I lost the player object. How can i fix it?

This is my source code

` 
var rp = plyr.setup();
var player = rp[0];
player.source({
        type: 'video',
        title: 'Example title',
        sources: [{
                    src: 'ccupD_IIN1U',
                    type: 'youtube'
                     }]
});
player.play();
`

**Comment by friday** [comment]
I can't reproduce this. The creator is MIA, and the second comment has a syntax error (semi-colon after `]`).

If someone experiences a similar problem, please create a new issue.
