### ISSUE TITLE
Audio player multiple instances on running plyr.setup();

### ISSUE THREAD

**Issue by binarynos** [sampotts/plyr#442]
I have a web app which loads posts via ajax. Whenever a post has audio or video in it, plyr is initialized by running plyr.setup. This works fine for video elements but if an `<audio>` element is present on the page and plyr.setup(); is run, it creates another instance of the audio player. I am not  a coder so i might be  doing something wrong. Any ideas on how to fix this?
- Browser: Chrome
- Version:  50
### Steps to reproduce
Go to https://plyr.io/#audio and run plyr.setup(); on console
Thanks

**Comment by TrevorHinesley** [comment]
I believe you're looking for this: https://github.com/selz/plyr#initialising

**Comment by binarynos** [comment]
Yes, I found that. but running just `plyr.setup()` does not create a new plyr instance, the original one gets replaced or reset. But for audio players, on running `plyr.setup();` creates another audio player instance.
Since this does not happen with `<video>`, this is not the default behavior. If this changes, it would be great for non-coders like me 😄 . Scrrenshot: http://icecream.me/19395b6a83c4496871c4cbc766b9ba49/
BYW, plyr is great 
Thanks

**Comment by SamPotts** [comment]
Yep it seems there is a bug with `<audio>` - I'll look into it ASAP.

**Comment by angelsix** [comment]
This happens on videos too:

document.getElementById('test').innerHTML = '<video id="my-video" controls autoplay poster="..."><source src="..." type="video/mp4"></video>';

plyr.setup();

Then you get 2 videos playing. Also setting document.getElementById('test').innerHTML = '' to remove the video content doesn't stop one of the duplicates playing, its nowhere to be seen in the HTML yet there continues to be and play another video

They key is the autoplay option on the video. Remove it and problem goes away

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
