### ISSUE TITLE
Scroll gesture to change volume in fullscreen

### ISSUE THREAD

**Issue by gurinderhans** [sampotts/plyr#444]
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 
When player is in focus, (ie. full screen), scrolling on trackpad (vertically) or mouse (wheel scroll), should change player volume.

### Actual behaviour
No volume change occurs on scroll, trackpad (vertically) or mouse

### Environment

- Browser: Chrome
- Version:  55.0.2883.75 (64-bit)
- Operating System: macOS Sierra
- Version: 10.12.1

### Steps to reproduce 
- Browse to page with player, make player fullscreen, scroll vertically with trackpad

### Relevant links
N/a

**Comment by SamPotts** [comment]
This could be made into a flag for sure. Currently it only adjusts volume when you're moused over the actual control itself.

**Comment by gurinderhans** [comment]
Yes and even so, it only does if you click on the slider (ie. it's now in focus), and you are hovering over it at the same time. Having it do that (change player volume) when your mouse is anywhere and whether the volume slider element is in focus or not, would be ideal (only in full screen mode) This would not really work in non-fullscreen mode.

I can try to mess around with this and put something in a PR when I get the chance, if that's ok ?

**Comment by SamPotts** [comment]
Sounds very logical to me yeah. A PR would be really appreciated. Thanks 👍

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
