### ISSUE TITLE
Double click player to enter / exit fullscreen mode

### ISSUE THREAD

**Issue by gurinderhans** [sampotts/plyr#446]
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 
Double clicking on player when not in fullscreen should make it enter full screen mode, and when in full screen should exit full screen mode.

### Actual behaviour
Double clicking at any state, full-screen or not, the player simply pauses and plays again.

### Environment

- Browser: Chrome
- Version:  55.0.2883.75 (64-bit)
- Operating System: macOS Sierra
- Version: 10.12.1

### Steps to reproduce 
- Browse to page with player and double click the player.

### Relevant links
N/a

**Comment by mayeaux** [comment]
Any status update on this?

**Comment by ix5** [comment]
Double-click-to-fullscreen is what users have come to expect of a video player, please integrate this.

**Comment by gurinderhans** [comment]
If no-one is taking this, I might be able to take it over this weekend!

**Comment by gurinderhans** [comment]
PR is up here (https://github.com/sampotts/plyr/pull/740), comments appreciated!

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
