### ISSUE TITLE
controls.progress UI

### ISSUE THREAD

**Issue by suryaiiit** [sampotts/plyr#447]
![image](https://cloud.githubusercontent.com/assets/5886793/20887751/f9934572-bb21-11e6-9b11-52a62e12c07a.png)

When we dont have progress in controls (Option) the UI of volume and full icons are not aligned to the right, as shown in the image. I think it would be better if we always restrict them to the right most.

Thanks.

**Comment by SamPotts** [comment]
Will take a look at this 👍

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
