### ISSUE TITLE
Options in data-plyr attribute  do not work

### ISSUE THREAD

**Issue by MQTEnt** [sampotts/plyr#449]
This is my code in body tag
> <body>
	<div id="main">
		<audio data-plyr='{ autoplay: "true", volume: "10" }' controls>
			<source src="audio.mp3" type="audio/mp3">
		</audio>
	</div>
	<script src="dist/plyr.js"></script>
	<script>plyr.setup();</script>
</body>

...but in browser, the options in data-plyr attribute don't work,
what should I do?

**Comment by SamPotts** [comment]
That's not valid JSON, the keys need to be in quotes and those values don't need to be in quotes, only strings do. i.e.:

```
<audio data-plyr='{ "autoplay": true, "volume": 10 }' controls>
```

10 is the default for volume anyway btw.

**Comment by osworx** [comment]
And why do you have it here false??
https://github.com/sampotts/plyr#options 

`<video data-plyr='{ title: "testing" }'></video>`

**Comment by sampotts** [comment]
Fixed in the readme. Cheers 👍
