### ISSUE TITLE
Request a song via an xhr

### ISSUE THREAD

**Issue by BafS** [sampotts/plyr#454]
Hello,

Is it possible to pass an `xhr` callback to `.sources()` ?

I want to get a file from my server and I use JWT token but I did not see any option in the documentation.

Thanks in advance.

**Comment by SamPotts** [comment]
Not currently but you could always call `.source()` in your callback.

**Comment by BafS** [comment]
But then I need to passe the full file. I use web sockets and want to do some streaming, I guess it's not possible ?

**Comment by SamPotts** [comment]
Streaming is possible:
https://github.com/Selz/plyr#streaming

**Comment by BafS** [comment]
I need to check it again, thanks !
