### ISSUE TITLE
Second line of caption text not shown

### ISSUE THREAD

**Issue by Fosterscape** [sampotts/plyr#455]
Plyr does not show both lines of a caption when the caption is broken over two lines.

> WEBVTT
> 
> 1
> 00:00:01.000 --> 00:00:10.000
> This is the first line of text, displaying from 1-10 seconds
> 
> 2
> 00:00:15.000 --> 00:00:20.000
> And the second line of text
> separated over two lines

![vtt](https://cloud.githubusercontent.com/assets/8201555/21194367/14eb90d2-c206-11e6-9aeb-625e7595d5cf.png)

**Comment by SamPotts** [comment]
Will take a look. Maybe try a `<br>` if you need a line break for now. That *should* work.

**Comment by Fosterscape** [comment]
I did some more testing, this seems to only be a problem with Firefox (only tested with version 51.0.1)

I tested with Chrome and Edge and it works as expected in those browsers.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
