### ISSUE TITLE
hideControls event

### ISSUE THREAD

**Issue by intelligence** [sampotts/plyr#456]
Hey!

Keep coming back for more plyr, it's amazing, use it everytime I need to embed video :) 
Thanks so much!

I'm wondering about the possibility to add events for hideControls. I have some stuff outside plyr that I'd like to fade aswell if there hasn't been activity, and to show them again when activity occurs!

Cheers

**Comment by SamPotts** [comment]
Good idea 👍

**Comment by jwjcmw** [comment]
+1 for this feature.

**Comment by jwjcmw** [comment]
Just a note that I figured out my specific need for hiding some stuff using the custom html attribute...see http://codepen.io/jwjcmw/pen/pedQRL
unfortunately, it looks like using that breaks the i18n stuff, but perhaps that attribute could be looped through and replaced in the html like the id and seektime are (and might allow for having additional variables added to the i18n attribute for use in the custom html).

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
