### ISSUE TITLE
getDuration() on 'ready' always return 0 for vimeo embed

### ISSUE THREAD

**Issue by biospank** [sampotts/plyr#459]
### Expected behaviour 
On **ready** event I'm expecting to get the video duration by calling **getDuration()** on plyr instance.

### Actual behaviour
It works for youtube but not for vimeo.

### Workaround
One way I found to fix this is to add true as third parameter [here](https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L1841) and get notified when duration is available.

### Environment
Linux biospank-VGN-FE21B 4.4.0-53-generic #74~14.04.1-Ubuntu SMP Fri Dec 2 03:44:01 UTC 2016 i686 i686 i686 GNU/Linux

- Browser:
Chromium 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04
- Version:  
Chromium 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04
- Operating System:
Linux 
- Version: 
4.4.0-53-generic #74~14.04.1-Ubuntu SMP i686 GNU/Linux

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
