### ISSUE TITLE
Deprecated xlink:href

### ISSUE THREAD

**Issue by majiix** [sampotts/plyr#460]
**xlink:href**
**Deprecated since SVG 2**
This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Do not use it in old or new projects. Pages or Web apps using it may break at any time.
Note: SVG 2 removed the need for the xlink namespace, so instead of xlink:href you should use href.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

**Comment by SamPotts** [comment]
Hmm this is the first I've heard/seen of this. Strange they've not updated their own docs on the `<use>` element:
https://developer.mozilla.org/en/docs/Web/SVG/Element/use

I don't think there's an urgent need to change this just yet. Given in my quick testing, Safari seems still to require `xlink:href`, typical. 

Thanks for raising it - will keep this open.

**Comment by sampotts** [comment]
It looks like support for `href` has improved and only Safari doesn't support it - hardly a surprise... 

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href#Browser_compatibility

**Comment by sampotts** [comment]
Have added a check into v3... 

```javascript
// If the new `href` attribute is supported, use that
// https://github.com/sampotts/plyr/issues/460
// https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
if ('href' in use) {
    use.setAttribute('href', path);
} else {
    use.setAttributeNS('http://www.w3.org/1999/xlink', 'xlink:href', path);
}
```

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
