### ISSUE TITLE
Can't get replay method to work

### ISSUE THREAD

**Issue by jackiboy** [sampotts/plyr#464]
Hi. 
I am having a few issues with getting my video to restart when I click a custom button I have setup.

Here is my function:

`        function replayVideoSetup() {
            var player = plyr.get('.player');
            player[0].restart();
        };
`

I get this error

`Uncaught TypeError: Cannot read property 'restart' of undefined
    at replayVideoSetup (video:842)
    at HTMLButtonElement.onclick (VM22800 video:246)
    replayVideoSetup @ video:842
    onclick @ VM22800 video:246
`
### Environment

- Browser: Chrome
- Version:  Latest
- Operating System: OSX
- Version: El Capitan

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
