### ISSUE TITLE
Videos not playing on Safari (mac)

### ISSUE THREAD

**Issue by suryaiiit** [sampotts/plyr#465]
Videos are not playing on Safari, also the video on https://plyr.io is not playing.

**Comment by SamPotts** [comment]
They will work if you're not using the crossorigin attribute. I've not found why Safari is having this issue yet but if you don't use crossorigin, it's fine.

**Comment by SamPotts** [comment]
Doing more testing on this it seems Safari is working fine now? What OS are you on. Try and use the template as it helps debug without having to ask again...

**Comment by SamPotts** [comment]
Anyone else getting this?

**Comment by inkm** [comment]
I've got same on any device - vimeo doesn't work generally. 
`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().`

**Comment by SamPotts** [comment]
I've raised a bug with Vimeo's API related to Vimeo on iOS but I've not seen issues with Vimeo on any other platform. Anyhow, from what I can gather this issue was about Safari and HTML5 video although it's hard to tell as @suryaiiit like many others, didn't use the template I provide, for whatever reason. 

That promise exception is nothing to worry about anyway. It doesn't break functionality.

**Comment by inkm** [comment]
For me on OSX Sierra all browsers (with mobile emulation support) + xcode ios simulator - all devices - have the same issue - console shows only this bug, but even if You check another plugins for video that support not-native controls have the same issue.

**Comment by SamPotts** [comment]
That is a WebKit/Chrome bug that seems to have been introduced recently. As I say, it doesn't break functionality and happens sometimes on El Capitan (but playback still works). I know it's not nice seeing errors in the console but this isn't one to worry about. 

Here's the Chrome bug for it:
https://bugs.chromium.org/p/chromium/issues/detail?id=593273

I'll take another look at Sierra. I'll setup a VM.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
