### ISSUE TITLE
Click to video if set auto hide control not play/pause

### ISSUE THREAD

**Issue by Lang-le** [sampotts/plyr#466]
Seem `clickToPlay: true` is not working.
if i set `hideControls: true`
Maybe same thing happened on Plyr home page.

**Comment by SamPotts** [comment]
Will take a look cheers 👍

**Comment by Blucreation** [comment]
Can confirm, I am having the same issue when playing videos on mobile, clickToPlay not working when hideControls is set to true.

**Comment by friday** [comment]
@Blucreation for both play and pause? This is working now in my tests with play, but not pause  (see #968 for that one).

**Comment by friday** [comment]
Closing since I think this is the same issue as #968, which is better described. If I'm wrong about that comment here or open a new issue.
