### ISSUE TITLE
Hi, the player with streaming icecast generates double connection.

### ISSUE THREAD

**Issue by rcasunshare** [sampotts/plyr#473]
Hi, the player with streaming icecast generates double connection. When connecting a streaming with platform Icecast connects twice but the audio is listened to only one.

If you can see the image when playing live audio, it generates two connections but the audio is only one.

![baires](https://cloud.githubusercontent.com/assets/12421510/21632362/6461880a-d224-11e6-9257-033363d6b73b.png)

**Comment by sampotts** [comment]
Can you try this again in v3? I have a feeling this should be resolved but if not, feel free to re-open 👍
