### ISSUE TITLE
Seek on load is hiding the Poster & showing Loading...

### ISSUE THREAD

**Issue by suryaiiit** [sampotts/plyr#478]
When I'm trying to seek on 'ready' event the poster is hidden and Loading is being shown.

When it loads the Poster is shown fine, but when I seek the Poster image is not shown (instead Loading icon is being shown).

Example: http://codepen.io/anon/pen/PWZoNZ

Thank you.

**Comment by sampotts** [comment]
Yeah this is unavoidable - we don't have control over how the poster image is shown unfortunately. Sorry for the super late response.
