### ISSUE TITLE
Add SugarSS

### ISSUE THREAD

**Issue by kbytin** [sampotts/plyr#479]
Hi, 

we are using Plyr in our project, but we are using SugarSS for  CSS. 

What do you think about add it to the dist?  I can do PR if you agreed

**Comment by SamPotts** [comment]
I'd be hesitant at this stage as I already have to maintain both SASS and LESS separately so whenever I make a change to the LESS (primary), I have to remember to retro-fit it to the SASS and this would just add to that workload. How popular is SugarSS?

**Comment by kbytin** [comment]
It is like SASS or Stylus syntax but for PostCSS.
