### ISSUE TITLE
Support for RTSP

### ISSUE THREAD

**Issue by mburger81** [sampotts/plyr#482]
Does your great player support an RTSP or an RTSPH stream?

If not, this would be a **feature request** :) Do you think you can support something like that?

thx

**Comment by friday** [comment]
Plyr is using HTML5 video. As long as browsers don't support RTSP (which will likely never change since it's a legacy format), neither will Plyr. To support RTSP you either need to use flash, or you can convert the stream with your own server and ffmpeg.
