### ISSUE TITLE
Safari 10 transition when turn fullscreen

### ISSUE THREAD

**Issue by alexislevrai** [sampotts/plyr#484]
- [X] Issue observed on https://plyr.io demo page

### Expected behaviour 
A smooth zooming transition when I turn player full screen and a a zoom-out when I turn off the fullscreen mode.

I think it's a css transition problem, but I can't find where ! 

### Actual behaviour
Wired transition of zoom out same when I turn off full screen.

### Environment

- Browser: Safari
- Version:  10.0.2
- Operating System: macOS Sierra
- Version: 10.12.2

Players affected:
- [X] Vimeo

### Steps to reproduce 
- Turn on fullscreen

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
