### ISSUE TITLE
Add playsinline /  webkit-playsinline  property to play video inline (NOT FULLSCREEN) on mobile (ios)

### ISSUE THREAD

**Issue by gino8080** [sampotts/plyr#485]
Since now ios 10 supports the playsinline attribute
and there is already a library [iphone-inline-video](https://github.com/bfred-it/iphone-inline-video) that is used as polyfill for lower ios 8 & 9

do you think is possibile to add this as a new great feature? :)

- [x] Improvement

### Relevant links
https://webkit.org/blog/6784/new-video-policies-for-ios/
http://walterebert.com/blog/html5-video-autoplay-mobile-revisited/
http://stackoverflow.com/questions/30855662/inline-html5-video-on-iphone

**Comment by intelligence** [comment]
If I remember correctly, adding "playsinline" to the video tag works great, but the look and feel of the plyr player is not working.

**Comment by SamPotts** [comment]
I've actually added this in my changes in `develop` but everything is still WIP and the UI needs some tweaks at such a small size:

![image](https://cloud.githubusercontent.com/assets/719092/25925575/c0f50562-362c-11e7-8d8f-15873546b542.png)

**Comment by intelligence** [comment]
Awesome!

**Comment by TungXuan** [comment]
Awesome, 
So now I can use playsinline by add "playsinline" to my youtube tag.
I have tried but I think I have some mistake.
How I can add playsinline to my youtube video?

**Comment by sampotts** [comment]
Not yet. It's still in progress. I'm getting there. Good things come to those who wait 👍

**Comment by TungXuan** [comment]
Great! I 'm waiting the your awesome features 👍

**Comment by Danetag** [comment]
Nice work guys! Do you know when we'll have the ability to see the UI on iOs phones? Inline works perfectly, just missing the UI 👊 

Thanks!

**Comment by spacedawwwg** [comment]
+1

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by rgaufman** [comment]
When you say it's fixed, how would one use it today?
