### ISSUE TITLE
HLS live DVR stream seeking issue

### ISSUE THREAD

**Issue by perohu** [sampotts/plyr#486]
Hi All,

I use Plyr with Hls.js to play my live DVR stream. 
If I seek back in time and pause playing for 10-15 sec or more and then start playing and seek back to live position, then the stream freezes. Sometimes it freezes only for 5-6 secs, sometimes for 30-40 secs and sometimes forever ( or at least I can't wait the time :) )
I can reproduce this with latest Chrome and Firefox on Windows 7.

Here it is in action: http://madarles.hu/

I failed to reproduce this with HLS.js only, so it may be a Plyr bug.
Here is the Hls.js only test page:  http://infocam.hu/players/madarles-hls.js.html

BTW thanks for this great player, I just started testing/using it. It's great!
Thx!

**Comment by perohu** [comment]
I just found another seeking issue. 

To reproduce:
Let's say I have LIVE DVR stream with 1 hour long playlist. 
I start playing and after I watched 30 min, I start seek back in time. I will rich the start of the stream ( 1 hour in the past) in the middle of Plyr's seekbar, NOT on the start (left side) of Plyr's seekbar. If I seek to the fist half of plyr's seekbar, than it jumps to the live position.
Of course if I watch only 6 mins in a 1 hour long playlist, then I will reach the actual start of playlist at 10% of plyr's seekbar

This is reproducable in the Hls.js only version too. But I think that Hls.js behaves like this by design. I think that the player ( in our case Plyr ) should render seekbar correctly.
Am I right?

Thx!

**Comment by perohu** [comment]
Now I started testing Clappr, which uses Hls.js too and it does not have this problem.
The "in action" url changed from http://madarles.hu to http://infocam.hu/players/madarles-last-pryl.php

**Comment by friday** [comment]
> This is reproducable in the Hls.js only version too

This of course means it's not a Plyr issue. Since Clappr is using Hls.js it seems unlikely that it's a Hls.js issue either. Probably something you can do to avoid it in your implementation, or you should take it up with hls.js.
