### ISSUE TITLE
Feature Request: clickToPause

### ISSUE THREAD

**Issue by Tekanewa** [sampotts/plyr#489]
Similar to the already available "clickToPlay" option, the player should in my opinion also provide a "clickToPause" option, to pause the player the same way it could be started (by clicking anywhere on the video), or to simply attach such a behavior to the existing "clickToPlay" routine.

**Comment by Tekanewa** [comment]
**Update:**
Just noticed that the desired behavior already works, but only on non-touch screens. Viewing a video on my 1st desktop screen, which happens to be a touch screen as well, the player does not pause when clicking on the video. Viewing the same video on my 2nd non-touch screen, the behavior works as expected.

Maybe the check for a touch device should take screen size into account, or somehow check if a mouse is present?

**Comment by sampotts** [comment]
In v3 first tap will play, 2nd tap will show controls (including the pause button) which I think is the standard behaviour.
