### ISSUE TITLE
Volume Slider visible even if there is no audio in the video

### ISSUE THREAD

**Issue by sirx** [sampotts/plyr#491]
As the title says I experienced that the volume slider from plyr is still visible even if the video has no audio.

With plyr
![d48817cc](https://cloud.githubusercontent.com/assets/14188379/22554139/61d75464-e95f-11e6-92ba-1a7681bfca60.png)

Without plyr
![dcfb25fc](https://cloud.githubusercontent.com/assets/14188379/22554145/6d532f52-e95f-11e6-8e6f-87347b404ce8.png)

**Comment by jonnitto** [comment]
Look at the Readme in the options section: https://github.com/Selz/plyr#options There you'll find it option `controls`. Or you provide a own html: https://github.com/Selz/plyr/blob/master/controls.md

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
