### ISSUE TITLE
Fullscreen event not firing

### ISSUE THREAD

**Issue by lorengrayh** [sampotts/plyr#493]
I am using an HTML5 player and cannot get the enterfullscreen or exitfullscreen events to fire. I have tried using other events and can get all of them to work expect the fullscreen. 

My player does have custom controls and icons but I have tried using the default controls and icons and still have the same issue. There are no errors in the console. I have seen this issue in Chrome, Safari, and Firefox on a Mac. I am using the latest version of plyr.

**My setup code:**
Full JS: https://www.pastiebin.com/5894dce55f600
	
`plyr.setup('.js-player', {
		html: controls,
		//debug: true
	});`

**The event call:**
`$('.js-player').on('enterfullscreen', function(event) {
		console.log("here!");
   });`

This shows nothing in the console.

**My video HTML:**
`<video poster="images/headphones.jpg" class="js-player">
         <source src="videos/sample-video.mp4" type="video/mp4">
</video>`

**Comment by dieskim** [comment]
Same error here? It gets logged when debug is enabled but it does not bubble up to be caught once fired?

**Comment by zeeshanjan82** [comment]
@lorengrayh instead of $('.js-player') use players[0]
setup the player like this:
    var players = plyr.setup(document.querySelector('#player'), { autoplay: true, controls: ['play-large', 'play', 'progress', 'current-time', 'mute', 'volume', 'fullscreen'] });

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by xxx** [comment]
I'm seeing this behavior in 3.4.3. `cue` events attached at the same time fire as expected.

like @dieskim's case, when `debug` is enabled, I see the `enterfullscreen` and `exitfullscreen` events fire, but my handlers are never called.

the actual event is attached via:

```javascript
const video = document.getElementById('plyr-element-id')
video.addEventListener('enterfullscreen', (e) => console.log('enter the dragon'))
```

The dragon hasn't entered yet :(

**Comment by pankajkumar-patil** [comment]
use below code you will get event of full screen and exit full screen.

after initialised plyr add below lines -  (i am using same jsfiddleexample - https://jsfiddle.net/r9wpkxyq/11/)

window.plyr = new Plyr('#plyr-video', {
          controls: ['play', 'progress', 'current-time', 'mute', 'volume', 'fullscreen'],
          autoplay: true,
          loop: { active: true },
          invertTime: false,
          volume: 0,
          muted: true
        })

 window.plyr.on('enterfullscreen', (event) => {
      console.log('Entered full-screen mode');
    });

    window.plyr.on('exitfullscreen', (event) => {
      console.log('Exited full-screen mode');
    });

![Screenshot 2024-09-24 170428](https://github.com/user-attachments/assets/3844a7f2-ac1d-4392-afac-1bcaa2ce290a)
