### ISSUE TITLE
Vimeo Toolbar fails on Android 

### ISSUE THREAD

**Issue by iamrobert** [sampotts/plyr#497]
- [ x ] Issue does not already exist
- [ x ] Issue observed on https://plyr.io

### Expected behaviour 
1. Click Pause -> Pause Should Work
2. Click Full Screen -> Screen should shrink
3. Progress Bar -> can't drag
### Actual behaviour
1. Click Pause -> Pause Fails
2. Click Full Screen -> Screen stays Large
3. Progress Bar -> progress bar fails

### Environment

- Browser: Chrome 
- Version: 55.0.288
- Operating System: Android (Samsung Galaxy S6)
- Version: 6.0.1

My other developer encountered same issue on a separate phone.

 
Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [x] Vimeo

### Steps to reproduce 
1. Tap Vimeo tab
2. Click Play Button
3. Phone goes to full screenplayer
4. Touch any of the Vimeo buttons

The Vimeo default toolbar appears - and is unable to work. The plyr one when it appears works fine.

### Relevant links
https://plyr.io/#vimeo

**Comment by frazerf** [comment]
Is there any update on this one? I still can't seem to press the pause button.

**Comment by friday** [comment]
I think this has been fixed. I'm not getting this issue in Chrome on my Android, and it hasn't been brought up in quite a while now. If not, please comment and I'll reopen.
