### ISSUE TITLE
#ios first time tapping on play button, the video doesn't start

### ISSUE THREAD

**Issue by hardcorenik** [sampotts/plyr#502]
Hello, I have a problem with playing video in iOS.
I have a video with text vtt subtitles in mp4 format. My problem is that if tap the play button, the video doesn't start. If I reload the page containing the video, the play button works flawlessly.

I bet there is something related to the preloading of the video.. there is a setting that I am missing?

### Environment

- Browser: safari
- Version:  10
- Operating System: iOS
- Version: 10.1

I am hosting both player and mp4 video on AWS S3

thanks,

**Comment by sampotts** [comment]
I can't seem to replicate this on v3 so assuming it's fixed? Feel free to re-open if that's not the case 👍
