### ISSUE TITLE
I would like to see a touched event added

### ISSUE THREAD

**Issue by AlGantori** [sampotts/plyr#505]
This is a feature request
- [x] Issue does not already exist

I would like to overlay some buttons over plyr some affect the player and some other parts of the app like switching to a different view.  I would like these to eventually fade away after a timeout.

I see you already have enterfullscreen and exitfullscreen but no touched event.
I think web folks have tricks overlaying a div to intercept touch/click but I rather leave plyr relaying this information instead of me passing it down.
Another approach is a couple of events  controlsShown and controlsHid this way my apps could show and hide in sync with plyr controls.

The same also could be achieved with touched and controlshidding each conveying a specific general purpose event.

What do you suggest?

### Expected behaviour 
plyr reports touched my app shows the additional set of custom floating buttons.

- Browser: chrome
- Version:  56.0.
- Operating System:  Windows, Android, soon iOS
- Plyr Version:  1.8.12  with  ionic2/angular2  2.0.x

Players affected:
- [x] HTML5 Video
- [x] HTML5 Audio
- [x] YouTube
- [x] Vimeo

### Steps to reproduce 
-

**Comment by SamPotts** [comment]
There's been suggestions to add the `controlsshown` and `controlshidden` events so I'll add those. Touch events you can bind to the parent I'd say?

**Comment by AlGantori** [comment]
Thanks for the info I did not spot them when I searched initially.  
What does it mean to bind to parent for touch? I am new to JS can you point me to some code,
I will map it to TypeScript which is what I am learning to code with from ionic2/angular2.  
Thank you.
