### ISSUE TITLE
Missing "off" method

### ISSUE THREAD

**Issue by lbineau** [sampotts/plyr#512]
### Expected behaviour 
Since there is a "on" method to listen events there should be a "off" method to stop listening its.

### Actual behaviour
There is no "off" method.
I don't see it used in the "destroy" method neither so there are some memory leaks for sure. Even if it is not a big deal with regular pages because they are often reloaded, it is really important with SPAs.

Players affected:
- [x] HTML5 Video
- [x] HTML5 Audio
- [x] YouTube
- [x] Vimeo

**Comment by alejandroiglesias** [comment]
I stumbled upon this today and is an issue at the moment.

@sampotts I see that there's an `_off` function in the code that's commented out. Is there any chance to get this?

**Comment by sampotts** [comment]
It's coming back in v3...

**Comment by frumbert** [comment]
I also stumbled apon this in 2.0.17 in Firefox when destroying then recreating the same instance. It would be good if you could simply pass an `instance.off('eventname')` to unbind each event. Or if I could assign the event to a variable then dispose the variable - https://stackoverflow.com/a/45086170 is a neat example of this.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
