### ISSUE TITLE
Accessibility Validation Issues

### ISSUE THREAD

**Issue by aprilxu2222** [sampotts/plyr#516]
When doing an accessibility validation and HTML validation check, we found a couple issues in the HTML generated in the Javascript.  We are using an accessibility validator tool called AInspector Sidebar and the W3C validator bookmarklet.  These issues do not seem that serious, but just thought you guys might want to know.

W3C HTML Validator issues:

- Bad value presentation for attribute role on element progress
- Bad value 1 for attribute allowfullscreen on element iframe
- The frameborder attribute on the iframe element is obsolete.  Use CSS instead.

AInspector Sidebar issues:

- Each PROGRESS element must have an accessible label.
- Labels and IDs must be unique (this violation occurs when there's more than one video on a page)

### Relevant links
W3C serialized DOM bookmarklet: https://validator.w3.org/nu/about.html#extras
AInspector Sidebar: https://addons.mozilla.org/en-US/firefox/addon/ainspector-sidebar/

**Comment by sampotts** [comment]
Thanks for this. Some good points to address:

- I've already removed the presentation role on the progress elements in v3
- `allowfullscreen` is a valid attribute. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
- This may be something from v2 or perhaps the YouTube or Vimeo API. It's certainly not present in v3

Other issues:

- Will add a label for progress elements
- Will make the IDs unique per player

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
