### ISSUE TITLE
Vimeo player not loading

### ISSUE THREAD

**Issue by deepsharma** [sampotts/plyr#519]
- [ no] Issue does not already exist
- [ yes] Issue observed on https://plyr.io

### Expected behaviour 
Vimeo player should load as youtube player or other mp4 player
### Actual behaviour
vimeo player not loading , only showing blank screen as attached images
### Environment

- Browser:
- Version:  
- Operating System: Android 
- Version:  in all versions

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [yes ] Vimeo

### Steps to reproduce 
- 

### Relevant links
![453d8b54-f9ed-11e6-90d2-35f7cf1798ca](https://cloud.githubusercontent.com/assets/6744578/23293122/57cac140-fa8a-11e6-8f32-29c55f4111d9.png)
![8aa79162-f9ed-11e6-8a25-dfec0a228d3a](https://cloud.githubusercontent.com/assets/6744578/23293131/60bb3c94-fa8a-11e6-88b1-25efa5d0b299.png)

**Comment by SamPotts** [comment]
What browser and version? 

Please fill in the bug report properly...

**Comment by SamPotts** [comment]
Does this load correctly on the same device?
https://player.vimeo.com/api/demo

**Comment by deepsharma** [comment]
Yes , its working android browser (chrome) , i am using this js for cordova so i am playing both video (youtube and vimeo) but youtube is working fine but there is issue with vimeo player

**Comment by etylsarin** [comment]
Facing the same issue. Assume that this is because plyr tries to access global window.Vimeo.Player when the script's injected to the page. However, if you use AMD with your project, Vimeo won't become a global object when loaded because of the modules wrapper.

**Comment by sampotts** [comment]
Can you try this again in v3? I have a feeling this should be resolved but if not, feel free to re-open 👍
