### ISSUE TITLE
How to restrict the embed: [data-type] to only youtube/vimeo

### ISSUE THREAD

**Issue by arrowthemes** [sampotts/plyr#523]
### Actual behaviour
When integrating plyr.io with other bootstrap systems, the embed feature changes the html for any data-type e.g. any element that has data-type="comments" or data-type="button" is wrapped in the plyr divs. How can I restrict it to avoid it wrapping around all elements with data-type?

### Environment

- Browser: All browsers
- Version:  N/A
- Operating System: Mac
- Version: All versions

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
-

**Comment by SamPotts** [comment]
Sorry, this will require a code change. I'll take a look when I next get back to this but I've just a had a baby boy (well, the wife has!) so time is a bit limited...

**Comment by arrowthemes** [comment]
Ok no worries. I've had to change the embed to something like data-video-type for the time being, so all good for now. I totally understand. Everything was at a stand still when we were blest with our boy. 

Congratulations!

**Comment by arrowthemes** [comment]
*bump*

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
