### ISSUE TITLE
On ended event - restart player

### ISSUE THREAD

**Issue by frazerf** [sampotts/plyr#525]
Hi there,

I'm trying to restart the player (vimeo) when the video ends but I'm not having much luck. I'm even trying to console log a message and that's not even working. Can anyone see where I'm going wrong?

```
     if ($('.main-hero__vimeo__video').length) {
		console.log("Video player init");
		// Define the controls
		var plyr_options = {
	        autoplay: true,
			clickToPlay: true,
			showPosterOnEnd: true,
			controls: ['mute','progress','play']
	    };

		// Create the plyr instances - this defines players[0] as our primary player.
		var players =  plyr.setup(plyr_options);

		players[0].on('ended', function(event) {
		  console.log("test");
		});

	}
```

### Environment

- Browser: Chrome
- Version: 56.0
- Operating System: MacOSX
- Version: Yosemite

**Comment by alejandroiglesias** [comment]
@frazerf are you getting an instance on `players`? Is the other log appearing on your console? Can you listen to the `ready` event and see if it gets triggered?

**Comment by sampotts** [comment]
Can you try this again in v3? I have a feeling this should be resolved but if not, feel free to re-open 👍
