### ISSUE TITLE
Any idea why i see the Vimeo player control in the background?

### ISSUE THREAD

**Issue by onigetoc** [sampotts/plyr#527]
I did i simple popup to play Youtube, MP4 and Vimeo.

I created a RSS reader for Wordpress and i do show enclosure, Youtube and Vimeo in RSS FEED.

It work great for Youtube and MP4 but for Vimeo i see the vimeo control in the background of the Plyr controller.

Click the RSS link or the RED video icon.
http://altnews.top/en/rss/getrssfeeds?rssurl=vimeo.com%2Fuser10373475%2Fvideos%2Frss

**Comment by sampotts** [comment]
I can't seem to replicate this on v3 so assuming it's fixed? Feel free to re-open if that's not the case 👍
