### ISSUE TITLE
Calling toggleMute() or setVolume() on Youtube video causes an error

### ISSUE THREAD

**Issue by wujekbogdan** [sampotts/plyr#528]
### Expected behaviour 
Methods should do what they are supposed to do or notify (using console.error()) that a method is not supported (if this is a reason why they don't work - but the documentation doesn't say that these methods are not allowed for YT player).

### Actual behavior
`Uncaught TypeError: Cannot read property 'mute' of undefined`

### Environment

- Browser: Any
- Version:  Any
- Operating System: Any
- Version: Any

Players affected:
- [x] YouTube

### Steps to reproduce 
- Initialize the Youtube player
- Call `toggleMute()` or `setVolume()` on the instance. 

// EDIT:
I've just found that as a workaround these methods can be called within the `setup` or `ready` callbacks (basically, within any callback that is called after the initialization :)).

**Comment by snstar2006** [comment]
I'm getting this issue now. I try to set the video as muted by default, but it is not working and throw an exception in console: 
Uncaught TypeError: Cannot read property 'mute' of undefined
    at Object.ve [as toggleMute] (plyr.js:formatted:866)
    at (index):201

**Comment by billmn** [comment]
I have the same problem. Please fix.

**Comment by sampotts** [comment]
I can't seem to replicate this on v3 so assuming it's fixed? Feel free to re-open if that's not the case 👍
