### ISSUE TITLE
Playback speed controls

### ISSUE THREAD

**Issue by rand99** [sampotts/plyr#53]
new feature

**Comment by nathancharles** [comment]
Any update on this feature?

**Comment by SamPotts** [comment]
I'm working on this next along with loop controls for #115

**Comment by cwbmuller** [comment]
@SamPotts This would be incredible! Will the speed controls work for Vimeo videos?

Super excited to integrate this with a new solution we're building :)

**Comment by webprus** [comment]
Deal SamPotts!
Thank you for your wonderful player.
I am very much looking forward to Vimeo playback speed Control. 
I look forward to seeing when I can see the playback speed control. Thankyou!

**Comment by pplanel** [comment]
Hi @SamPotts not trying to put pressure on you.
But I really need this functionality. Maybe you can tell what status is it and maybe you can use my help to finish it.

**Comment by SamPotts** [comment]
I'm getting there slowly. It's hard with a wife who's 7 months pregnant and preparing for the little ones imminent arrival (our first). I've been trying to squeeze it in here and there. I'm keen to get it out ASAP too.

**Comment by pauliusuza** [comment]
@SamPotts I posted a 50$ bounty, I would appreciate if you could spend some time on this in the next few days. Thanks. 
https://www.bountysource.com/issues/9211745-playback-speed-controls

**Comment by SamPotts** [comment]
Yep, I saw that. Unfortunately my impending child (very soon) takes priority over this right now. I'll try my best though. 

Sam

**Comment by pauliusuza** [comment]
Congrats and thank you.

**Comment by DiasFelipe** [comment]
Looks awesome, can't wait.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
