### ISSUE TITLE
Vimeo Seek not working

### ISSUE THREAD

**Issue by frumbert** [sampotts/plyr#537]
- [ ] Seems similar to https://github.com/Selz/plyr/issues/208 (still open)

### Expected behaviour 
1. Calling `seek` on the `ready` event should set the start position to that point then start playback

### Actual behaviour
Vimeo always starts at the beginning.

### Environment

- Browser: Chrome 
- Version:  56 / 57
- Operating System: MacOS Sierra
- Version: 10.12.3

Players affected:
- [X] Vimeo

### Steps to reproduce 
- include cdn versions of plyr code.
- put ONE div on the page, pointing to a vimeo id
- var _player =plyr.setup()[0];
- _player.on("ready", function (event) { event.detail.plyr.seek(60); });

### Relevant links
Internally plyr calls the setCurrentTime() method on the vimeo player.

Vimeo documentation: https://github.com/vimeo/player.js#setcurrenttimeseconds-number-promisenumber-rangeerrorerror

Pen: https://codepen.io/frumbert/pen/Rpjypx

**Comment by weskhaled** [comment]
Try:      
  plyerplyr[0].on('playing', function (event) {
          event.detail.plyr.seek(50);
  });

**Comment by sampotts** [comment]
I can't seem to replicate this on v3 so assuming it's fixed? Feel free to re-open if that's not the case 👍
