### ISSUE TITLE
Make video only as high as its container? (without cropping width)

### ISSUE THREAD

**Issue by frumbert** [sampotts/plyr#538]
I'd like to know how to limit the height of the underlying embedded Vimeo video so that it's no higher than the controls overlay.

That is, I'd like the video never to be able to extend beyond the height of its container, nor to crop. Ideally I'd like Plyr to behave in the same way as the CSS `background-position: center; background-size: contain;`, preferably without some janky jquery hack 

I've used the

     .plyr {
         height: 100vh; min-height: 100%;
     }

hack to ensure that the *controls* glue at the bottom of the container (in this case, the body). But if you make the window wide enough but maintain the height , you'll see the video expands beyond past the controls and keeps getting bigger whereas the controls stay put at the bottom.

The hack also does not cover the YouTube play button. If your browser window is much wider than it is high before you start, you'll see both play buttons.

Vimeo example: https://codepen.io/frumbert/pen/NpwzPW
YouTube example: https://codepen.io/frumbert/pen/qrVKOo

**Comment by SamPotts** [comment]
The problem with Vimeo is that they don't actually support hiding their controls like YouTube does. So the *hack* to hide them is to make the iframe larger so they are hidden off screen. It would be possible eventually to so the height and width dynamically somehow using the API to get height and width (if it's available on load unlike the lame YouTube API). The current setup assumes 16:9 which is fine for 99.99% of videos out there. 

Are you trying to make the player full window?

**Comment by frumbert** [comment]
IN my case the player is being used within an iframe in a cms. That iframe has a fixed height by design, but a dynamic width (98%, for some ungodly reason). I can control my vimeo player code, but not the cms it's included onto. I'm trying to prevent cropping.

**Comment by frumbert** [comment]
I'm happy enough with a hack for my case, which is to first set the container width to the 16:9 ratio of its height after initialisation, then when the video resizes, calculate the height of the player based on the width of the internal video, so that the controls / captions appear in the correct spot. (assuming there's only one instance as well).

    // ensure 16:9 on resize
	(function() {
	  window.addEventListener("resize", resizeThrottler, false);
	  var resizeTimeout;
	  function resizeThrottler() {
	    if ( !resizeTimeout ) {
	      resizeTimeout = setTimeout(function() {
	        resizeTimeout = null;
	        actualResizeHandler();
	       }, 66);
	    }
	  }
	  function actualResizeHandler() {
		var e = document.querySelector(".plyr__video-wrapper"); // the video INSIDE plyr div
		if (!e) return;
		var h = e.offsetHeight;
		var w = (h * 16) / 9;
		document.querySelector("div.plyr").style.width = w + "px";
		document.querySelector("div.plyr").style.height = h + "px";
	  }
	}());

    domReady(function () {
	var _player =plyr.setup({
		keyboardShortcuts: {
			global: true
		}
	})[0];
	document.querySelector(".plyr").style.width = ((Math.max(document.documentElement.clientHeight, window.innerHeight || 0) * 16) / 9) + "px";
	_player.on("ready", function (event) {
            ... etc

obviously needs some tidying up, but for my case it's "good enough"

**Comment by aftereffectsmagic** [comment]
Any update on #538 being addressed in the next update? I'd love to have a workable solution for this, or an understanding of whether or not this will be addressed sometime soon. Vimeo videos I link to do not look like they are title-safe or action-safe (due to the offset) when playing full-screen, but they look great when not full-screen.

As an aside, @frumbert, I wasn't able to implement your solution in my setup. Did you include those functions in plyr.js or on the page that displays the iframe? With a couple of pointers I can set up a workaround until this is officially addressed. Thanks for any help you can provide!

**Comment by frumbert** [comment]
@aftereffectsmagic the code above is on the page that hosts the div that has the video id on it. That's all that's on the document body though - I've intended mine to be the only element within that page and it to (probably) be an iframe.

**Comment by frumbert** [comment]
The fitjs plugin is just what I wanted:

https://github.com/soulwire/fit.js
