### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined at NodeList.togglePlay (plyr.js:2855)

### ISSUE THREAD

**Issue by friconelli** [sampotts/plyr#540]
- [x] Issue does not already exist

### Actual behaviour
Console error on togglePlay of "play-large" button

- Browser: chrome
- Version:  v2.0.11
- Operating System: Mac OSX
- Version: 10.11.6

Players affected:
- [x] HTML5 Video

### Correction
I think you should modify this line from 2852 to 2856 with this block:

```
if (target) {
    if (target.length > 1) {
        target = target[target.length - 1];
    } else {
        target = target[0];
    }
}
```

**Comment by seanthepottingshed** [comment]
Also affects Vimeo Player.

**Comment by SamPotts** [comment]
Sorry this will be fixed in the next round of changes

**Comment by sampotts** [comment]
I can't seem to replicate this on v3 so assuming it's fixed? Feel free to re-open if that's not the case 👍
