### ISSUE TITLE
Reverse duration

### ISSUE THREAD

**Issue by MarkMurphy** [sampotts/plyr#541]
Is there a way to have the total duration displayed upfront instead of counting up to it during playback?

**Comment by jwjcmw** [comment]
I've got something that does that using the custom controls html: http://codepen.io/jwjcmw/pen/pedQRL

**Comment by SamPotts** [comment]
I'll add something built in. The custom HTML option may have to disappear with the upcoming update as it's going to become too complex with the templating required.

**Comment by jwjcmw** [comment]
perhaps the controls could follow the order that they are in the controls array.  I do like being able to include some non-standard stuff in the custom html, though.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
