### ISSUE TITLE
Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.

### ISSUE THREAD

**Issue by MarkMurphy** [sampotts/plyr#544]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io (likely)

Plyr v2.0.10

### Environment

- Browser: 

% | Browser
:--|:--
0.41%	| Chrome 56.0.2924
6.04%	| Chrome Mobile 56.0.2924
4.94%	| Chrome 55.0.2883
4.12%	| Chrome Mobile 50.0.2661
13.58%	| Chrome Mobile 51.0.2704
61.04%	| Chrome Mobile 55.0.2883
7.41%	| Chrome Mobile 44.0.2403
2.47%	| Chrome Mobile 54.0.2840

- Operating System: 

% | OS Name
:--|:--
0.27%	| Linux
99.73%	| Android

- Version: 

% | OS Version
:--|:--
4.08%	| Android 7.1.1
0.41%	| Android 4.2.2
4.35%	| Android 7.0
22.96%	| Android 6.0
68.21%	| Android 6.0.1

- Device Family: 

%	|	Device
:-- | :--
0.58%	| Samsung SM-A310F
0.14%	| LG-K100
0.43%	| Samsung SM-G935W8
0.14%	| Nexus 6
1.88%	| Samsung SM-G935Fo
0.14%	| Moto G (4)
2.60%	| Lenovo PB1-750M
0.29%	| Samsung SM-G925V
0.72%	| XT1635-01
0.58%	| Samsung SM-J106B
0.87%	| MHA-L29
1.16%	| XT1585
0.29%	| Samsung SM-G925T
1.30%	| HUAWEI VNS-L31
0.72%	| LG-H901
0.43%	| ONEPLUS A3003
1.16%	| Samsung SM-G935A
2.75%	| Samsung SM-G900A
0.58%	| EVA-L09
2.02%	| XT1068
0.29%	| LGLS775
0.87%	| Samsung SM-G920W8
3.32%	| Nexus 5X
1.01%	| Samsung SM-J700T
0.72%	| Samsung SM-G870A
1.30%	| Samsung SM-G9350
1.30%	| FRD-L09
0.72%	| Samsung SM-N910P
1.45%	| LGLS991
0.87%	| Samsung SM-J510FN
0.72%	| Samsung SM-G935Uo
0.58%	| VS990
7.95%	| HTC One A9
9.54%	| Samsung SM-G900I
0.29%	| LG-K210
1.30%	| Samsung SM-N9208
0.58%	| Samsung SM-G900T1
1.16%	| Samsung SM-G935P
1.45%	| Pixel
0.29%	| Samsung SM-G925P
0.43%	| Samsung SM-T110
4.91%	| SHIELD Tablet K1
2.02%	| Samsung SM-A500W
0.58%	| VS987
0.72%	| Samsung SM-G920V
6.79%	| LG-D855
1.01%	| LG-H811
1.01%	| XT1565
5.35%	| Samsung SM-G930P
3.61%	| Samsung SM-G930A
7.08%	| HUAWEI GRA-L09
1.16%	| Vivo 5R
2.31%	| ONE E1005
1.59%	| Samsung SM-N910A
2.17%	| Samsung SM-G550T1
2.17%	| Samsung SM-G900V
1.30%	| Samsung SM-G930V
1.30%	| Samsung SM-N915A

### Exception
**TypeError**
Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio (possibly)
- [ ] YouTube (possibly)
- [ ] Vimeo (possibly)

![screenshot 2017-03-25 00 56 59](https://cloud.githubusercontent.com/assets/873474/24319290/1dac0c8a-10f6-11e7-9c4d-0ff7ec1e4f12.png)

**Comment by paulconlin** [comment]
Seeing this one as well. Any ideas on a timeline? Could try to write up a PR

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
