### ISSUE TITLE
lazyload

### ISSUE THREAD

**Issue by mitjarobic** [sampotts/plyr#552]
is it possible to lazy load videos?

**Comment by sampotts** [comment]
Since Plyr is a wrapper for the HTML5 player it's certainly possible but not built into Plyr.

**Comment by matthewmcvickar** [comment]
In case anyone else is looking for a way to do this, here's how I'm accomplishing it.

On my site, there is an image and button that the user clicks to open a modal window with the video, which starts playing immediately. 

Here is my HTML and JavaScript. It's simplified to leave out the rest of the stuff specific to my site. (E.g., supporting multiple videos on a page.)

### HTML

Note the `defer` attribute, which prevents the source video request from happening when the page loads.

```html
<button class="video-play-button" data-video-target="video-1">Play</button>

<video id="video-1" defer>
  <source src="video_url.mp4" typr="video/mp4">
</video>
```

### JavaScript

The script reads the target element from the data attribute of the play button, initializes a new Plyr with it, and starts the video.

```js
document.querySelector('.video-play-button').addEventListener('click', function(event) {
  // Get video element to initialize.
  var videoElement = event.target.dataset.videoTarget;

  // Initialize video.
  player = new Plyr(videoElement);

  // Play video once it's ready.
  player.on('ready', () => {
    player.play();
  })
});
```

To get this to work with multiple videos on a page, you'll need to write code that attaches an event listener to each of the play buttons and move the video-initializing code into a function…

**Comment by iamrobert** [comment]
Here's my attempt for youtube:

https://codepen.io/iamrobert/pen/GRWOYNJ

It pulls the image and title from youtube, and only loads plyr on click. You'll need to add a button over the image that loads.

**Comment by ZacHiler** [comment]
@matthewmcvickar Can defer really be used this way? I thought `defer` was only usable for script tags. `preload="none"` is what I'm using for video.

**Comment by matthewmcvickar** [comment]
> @matthewmcvickar Can defer really be used this way? I thought `defer` was only usable for script tags. `preload="none"` is what I'm using for video.

You are correct. Not sure why I did that. I updated my comment accordingly.

**Comment by ZacHiler** [comment]
> You are correct. Not sure why I did that. I updated my comment accordingly.

All good. I'm an amateur at best and your comment helped me find the preload info I was looking for. Also, now that I know more about defer, I can use that too.
