### ISSUE TITLE
YouTube Video on Loop

### ISSUE THREAD

**Issue by CudaCores** [sampotts/plyr#560]
Hey guys,

I'm fairly new to this, I have the player working as I need it to however I'd like to have it running on a loop. Is there an easy way to set this in the options?

This is what I have right now before the closing <body> tag

`<script>plyr.setup({
		autoplay: ["true"],
		hidecontrols: ["true"]
	});
	</script>`

This is a YOUTUBE video

**Comment by SamPotts** [comment]
You don't need to set those values as strings in an array. Also, hidecontrols is default to `true`

Try this

```javascript
plyr.setup({ 
    autoplay: true, 
    loop: true
});
```

**Comment by CudaCores** [comment]
Thanks Sam, but unfortunately that didn't get it to loop :-(

**Comment by alejandroiglesias** [comment]
I'm also experiencing that the `loop` option doesn't work for a YouTube video. AFAIK the YouTube API doesn't provide a loop parameter, but you can achieve looping by making a playlist with only one video:

```
player.loadPlaylist(videoId);
```
The downside is that it reloads the video each time. Another possibility that I haven't explored, is to seek to position 0 (zero) and replay.

@SamPotts how is YouTube looping implemented on Plyr? Can you confirm it works?
(PS: this can be tested with this very short video: https://www.youtube.com/watch?v=tPEE9ZwTmy0)

**Comment by alejandroiglesias** [comment]
I'm trying to workaround this by doing:
```
plyr.on('ended', () => plyr.restart());
```
The event handler is executed but the video doesn't restart. This is the debug log:
```
[Plyr] event: ended Object
[Plyr] event: timeupdate 
[Plyr] event: seeking 
[Plyr] Seeking to 0.0000 seconds
[Plyr] event: statechange
```
I'm also trying to restart the playback programmatically by calling `plyr.restart()` as well as `plyr.rewind() && plyr.play()` on the browser console but nothing seems to make it play again.
```
[Plyr] event: ended
[Plyr] event: statechange
$0.plyr.restart()
[Plyr] event: timeupdate
[Plyr] event: seeking
[Plyr] Seeking to 0.0000 seconds
```
_(Notice that `$0.plyr` refers to a Plyr instance in my browser console.)_

**Comment by alejandroiglesias** [comment]
I found that in order for YouTube to replay, it needs a call to `youtubePlayer.stopVideo()` first. After that, calling `plyr.play()` works.

**Comment by alejandroiglesias** [comment]
I've opened a PR that you can test which implements loop functionality on YouTube. Beware that since it was made against the `develop` branch, it uses the new loop config structure (`config.loop.active`).

**Comment by CudaCores** [comment]
I've updated my files with the develop branch and used your code, yet I'm seeing this:

`(index):62 Uncaught TypeError: plyr.on is not a function`

**Comment by SamPotts** [comment]
Develop is *not production ready* otherwise it'd be in the master branch.

**Comment by alejandroiglesias** [comment]
@SamPotts I would suggest as an advice keeping the `develop` branch
production ready and all in-progress work to happen on a feature branch. In
that way, the latest features can be tested before they are released (as I
think @CudaCores intended).
Cheers!

**Comment by SamPotts** [comment]
I use `develop` as a feature branch for developing. Once it's production ready then I'll create a `staging` or `beta` branch that would be production ready for testing. `master` is the production branch. It's a pretty standard setup. Yours may differ of course.

**Comment by CudaCores** [comment]
Can you let me know on here when and where the updated files are ready to be tested. Thanks!

**Comment by gideonco** [comment]
Although the video looped, I didn't love the visual reset that took place in stopping the video completely. I achieved a more seamless looping effect seeking to 0 using YouTube `seekTo` method on `ended`. 

```javascript
plyr.on('ended', () => {
  plyr.getEmbed().seekTo(0);
  plyr.play();
});
```

There's still one or two frames of black, but this is pretty close to a seamless loop.

**Comment by CudaCores** [comment]
@gideonco I tried your code and it didn't do anything? No loop. 
`<script>
	plyr.setup({ 
    autoplay: true, 
    loop: true
});
	plyr.on('ended', () => {
    plyr.getEmbed().seekTo(0);
    plyr.play();
});
	</script>`

**Comment by CudaCores** [comment]
Actually I'm seeing "plyr.on is not a function" should i be downloading a new version somewhere?

**Comment by sampotts** [comment]
As I said .... 

> Develop is **not production ready** otherwise it'd be in the master branch.

**Comment by adrigm** [comment]
I solved with this code:

```js
var players = plyr.setup()[0];
players.on('ended', function(event) {
    console.log("fin");
    players.getEmbed().seekTo(0);
    players.play();
});
```

**Comment by sampotts** [comment]
Another issue has been raised for this so I'll close this one and track it in the other one... 

https://github.com/sampotts/plyr/issues/632
