### ISSUE TITLE
right-click on a youtube video (Safari)

### ISSUE THREAD

**Issue by gmzu** [sampotts/plyr#562]
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Actual behaviour
If you right-click on a youtube video you will see a menu and you can no longer make it disappear (only in Safari) with a left click. The menu disappears only if you right-click. Menu items are not selectable.
### Environment

- Browser: Safari 
- Version:  10.1 (12603.1.30.0.34)
- Operating System: macOS Sierra 
- Version: 10.12.4

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [x] YouTube
- [ ] Vimeo

### Steps to reproduce 
- right-click on a youtube video

**Comment by alejandroiglesias** [comment]
I confirm this issue.

**Comment by sampotts** [comment]
Is this still an issue?

**Comment by sampotts** [comment]
I don't think there's much that can be done about this unfortunately as YouTube controls the iframe. If you right click again it goes away which is odd.
