### ISSUE TITLE
Controls' gradient background is seen on mouseover even if no controls are enabled

### ISSUE THREAD

**Issue by alejandroiglesias** [sampotts/plyr#564]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
If no controls are enabled at all, no gradient at the bottom to be shown on mouseover.

### Actual behaviour
Even though you set no controls, there's still a gradient on the bottom of the video (where the controls should be) if you mouse over it.

### Environment

- Browser: Chrome
- Version: 57
- Operating System: macOS
- Version: 10.12.4

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [x] YouTube
- [x] Vimeo

### Steps to reproduce 
- Set `controls: []` as an option.
- Mouseover on the video.

**Comment by SamPotts** [comment]
I'll add it my current work as I'm changing the controls. 

Thanks

Sam

**Comment by sampotts** [comment]
This is a duplicate so I'll close it - will track via the other issue 👍
