### ISSUE TITLE
Mute Vimeo video not working

### ISSUE THREAD

**Issue by romain-perspective** [sampotts/plyr#569]
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
- Set Volume to 0 mutes the video

### Actual behaviour
- The video is not mute

### Environment

- Browser: Chrome
- Version:  57.0.2987
- Operating System: macOs
- Version: 10.12.3 

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [x] Vimeo

### Steps to reproduce 
- Set volume 0

**Comment by julmot** [comment]
The `mute` attribute isn't respected for me on native `<video>` tags too.

**Comment by sampotts** [comment]
There's no such attribute for `<video>` - perhaps you're thinking of `muted`?

https://developer.mozilla.org/en/docs/Web/HTML/Element/video

**Comment by julmot** [comment]
@sampotts This is what I meant, and it doesn't work for me.

**Comment by jjui** [comment]
Confirmed when embedding from Vimeo on macOS with Chromium version 61.
```
... data-plyr="{ "volume": 0}" ...
```
Cannot confirm `<video ... muted>` yet.

**Comment by sampotts** [comment]
You'd need to use 

```html
data-plyr='{ "volume": 0 }' 
```

Note the single quotes to wrap the JSON

**Comment by sampotts** [comment]
This has been raised in another issue so I'll close this one for now

**Comment by fourroses666** [comment]
doesn't work
