### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by victerryso** [sampotts/plyr#572]
Hi there,

I've been trying to disable keyboard shortcuts for a specific task and I finally found why I couldn't. The option for keyboard shortcuts is **keyboardShorcuts** oppose to **keyboardShortcuts**.

The three instances in which they appear:

- https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L52
- https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L2908
- https://github.com/Selz/plyr/blob/master/src/js/plyr.js#L2912

Thanks for the great product!

**Comment by alejandroiglesias** [comment]
@victerryso yes, that's a typo indeed.

**Comment by burakozturk16** [comment]
The document should be corrected.

**Comment by alejandroiglesias** [comment]
@burakozturk16 the typo is in the source code, not in the docs. The correct word is "shortcut".

**Comment by sampotts** [comment]
This will be fixed in v3 - as it's technically a breaking change even though it's my silly typo :)

**Comment by sampotts** [comment]
This is fixed in v3 👍
