### ISSUE TITLE
Control overlay problems Angular4

### ISSUE THREAD

**Issue by cbjerg** [sampotts/plyr#573]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

This is when playing a Youtube video after updating to Angular 4

### Expected behaviour 
The video shows up with Standard Plyr controls overlayed

### Actual behaviour
All overlays are shown underneath video in giant blocks. See 
https://www.dropbox.com/s/hdynnv4qrriyy2n/Screenshot%202017-04-26%2008.38.52.png?dl=0
### Environment

- Browser: Chrome, Firefox
- Version:  Chrome:  58.0.3029.81 
- Operating System: MacOS
- Version: Sierra

Players affected:
- [x] HTML5 Video
- [x] HTML5 Audio
- [x] YouTube
- [x ] Vimeo

### Steps to reproduce 
-

**Comment by cbjerg** [comment]
My bad. It was actually me, uglifying the css, and thus removing plyr.

**Comment by brunopiaui** [comment]
Hi @cbjerg 
Can you tell me how do you configured on the Angular???

Thanks...
