### ISSUE TITLE
Hide Controls Background Gradient

### ISSUE THREAD

**Issue by xcrap** [sampotts/plyr#583]
[X] Issue does not already exist

When using the controls: [] to hide controls, I still have the controls div showing up on page, it does not show controls icons but I see the background on hover. <div class="plyr__controls"></div>
If no controls are displayed should this div also be gone ? Because it makes that background gradient in the bottom of the video on hover and I can't see how to hide with options, of course I can force the CSS to hide but should this be automatic ? 

Sorry for my bad english.

**Comment by sampotts** [comment]
Yeah you're right - will fix this in the next major release

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
