### ISSUE TITLE
Plyr should not add non-passive event listeners

### ISSUE THREAD

**Issue by FallingSnow** [sampotts/plyr#585]
If Plyr has to be able to cancel a scroll then this issue can be ignored.

- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 
No Violation message should be displayed in chromium-dev. Plyr should start an with the passive option to allow for smoother scrolling.
### Actual behaviour
Violation message should be displayed in chromium-dev. Plyr starts an event listener without the passive option.
![screenshot from 2017-05-21 08-53-19](https://cloud.githubusercontent.com/assets/2512197/26285406/0bb2a63e-3e04-11e7-87d7-1fe454975639.png)
### Environment

- Browser: Chromium
- Version: 60.0.3100.0 (Developer Build) (64-bit)
- Operating System: Arch Linux
- Version: Rolling

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [x] YouTube
- [ ] Vimeo

Perhaps also Vimeo but not confirmed.

### Steps to reproduce 
- Enable Plyr on any video, then watch browser console for violation messages.

### Relevant links
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Parameters

**Comment by sampotts** [comment]
Hey, 

Thanks for raising this. I noticed these starting to appear in the console. It's a really new feature and passive listeners aren't widely supported but I've already added them in with part of some other work but it's not production ready yet - hopefully soon! 

https://github.com/sampotts/plyr/blob/develop/src/js/plyr.js#L730

Cheers

**Comment by FallingSnow** [comment]
Good to hear, thank you.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by jonathanlal** [comment]
This is still an issue it seems.
