### ISSUE TITLE
Blocked a frame with origin "https://youtube.com" ... Protocols, domains and ports must match.

### ISSUE THREAD

**Issue by georgegach** [sampotts/plyr#588]
I have been trying to make Plyr work on iOS 9 Safari for a while. First it had issue with SSL certificate. It needed my website to be on https. Now when I bought it origin: youtube.com bug strikes back. 

This is the error I get
> Blocked a frame with origin "https://www.youtube.com" from accessing a frame with origin "https://domain.ge". Protocols, domains, and ports must match.

I didn't get this error on my iPad. Plyrworks well there. Older iOS devices are real troublemakers. Any ideas how to fix it?

I am using Browserstack to test my website. Attaching error message screenshot with device specs. 
![18685277_125074261399618_1800161576_n](https://cloud.githubusercontent.com/assets/5983539/26442426/7bde8682-4145-11e7-93d1-51536b7911b7.jpg)
![18720872_125074268066284_1002600853_o](https://cloud.githubusercontent.com/assets/5983539/26442427/7be6a236-4145-11e7-8ab3-eef2a5a45fe1.jpg)

**Comment by stoqe** [comment]
I'm having similar problems on desktop and mobile; similar error messages. Did you find a fix @georgegach?

**Comment by stoqe** [comment]
@georgegach Update: this helped solve the problem for me --> https://github.com/sampotts/plyr/issues/597

**Comment by georgegach** [comment]
I couldn't.. In the end I switched to youtube Embed for youtube source videos.

**Comment by ewwink** [comment]
bug in iOS < 9.3, if you have `<input type="search"` change to `<input type="text"`

**Comment by syts88** [comment]
Has someone found a solution to this problem? I'm having similar problems on safari desktop and mobile.

**Comment by sampotts** [comment]
I've seen this in the console but it's never effected functionality so I've safely ignored it.

**Comment by EnziinSystem** [comment]
This error belongs to the Google Youtube API.

Inside "https://www.youtube.com/iframe_api":

```
if (!window['YT']) {
    var YT = {loading: 0, loaded: 0};
}
if (!window['YTConfig']) {
    var YTConfig = {'host': 'http://www.youtube.com'};
}
```
They use http instead of https.

We need to override the 'host' option and 'widget_referrer' same as 'origin'.

```
player = new YT.Player('player', {
          host: 'https://www.youtube.com',
          height: '390',
          width: '640',
          videoId: 'M7lc1UVf-VE'
...
          origin: "https://www.enziin.com",
          widget_referrer: "https://www.enziin.com"
}
```
Goodluck.

**Comment by sampotts** [comment]
I can't seem to get around this. I think the error is in the YouTube API.

**Comment by RathodGirish** [comment]
hello,

I am also getting the same problem in iPad Air 2 version 9.3. Is there any solution @sampotts @georgegach ?

**Comment by sampotts** [comment]
Nope. It doesn’t matter text playback and can be safely ignored.

**Comment by sampotts** [comment]
*doesn’t effect playback
