### ISSUE TITLE
Add playsinline to youtube and possibly vimeo

### ISSUE THREAD

**Issue by baberuth22** [sampotts/plyr#590]
It might be impossible with vimeo.  A workaround could be using Vimeo url in video player.
Possible with Youtube:  https://developers.google.com/youtube/player_parameters

### Expected behaviour 

Video Plays inline

### Actual behaviour

Video opens in video player popover

### Environment

- Browser:  Chrome, Safari
- Version:  
- Operating System: iOS
- Version: 10.0.2

Players affected:
- [ ] YouTube
- [ ] Vimeo

**Comment by sampotts** [comment]
Related: https://github.com/sampotts/plyr/issues/485

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
