### ISSUE TITLE
jump to a time

### ISSUE THREAD

**Issue by puppetmaster3** [sampotts/plyr#591]
how can I jump to a certain time on the video?

**Comment by sampotts** [comment]
![robert-downey-jr-rolls-eyes](https://cloud.githubusercontent.com/assets/719092/26516435/ab2238aa-42c9-11e7-83bb-e2b09ac3cca7.jpg)

Reading the docs would be a good start

**Comment by puppetmaster3** [comment]
Pardon, I was looing for a time. It's called seek.
