### ISSUE TITLE
YouTube Video Playhead Not Moving

### ISSUE THREAD

**Issue by baberuth22** [sampotts/plyr#592]
I have no idea why not. 

### Expected behaviour 
Playhead moves.

### Actual behaviour
Video plays, but playhead doesn't move and timeupdate event doesn't fire.

### Environment

- Browser: Chrome
- Operating System: OSx

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [x] YouTube
- [ ] Vimeo

**Comment by sampotts** [comment]
Are you seeing this on https://plyr.io? I'm not seeing issues on Chrome on MacOS/OSX.

**Comment by baberuth22** [comment]
You're right.  It works on https://plyr.io.   

The reason it was not working is because I change the src after load to append `&playsinline=1`
for mobile.

**Comment by sampotts** [comment]
It's going to be in the next major release along with playsinline for HTML5 video. Vimeo is not currently supported unfortunately.
