### ISSUE TITLE
0-9 key shortcuts shouldn't seek when used with a modifier key

### ISSUE THREAD

**Issue by cobbweb** [sampotts/plyr#594]
- [x] Issue does not already exist (_O.P: not that I can find_)
- [x] Issue observed on https://plyr.io

### Expected behaviour 

When pressing a modifier + any number key, I wouldn't expect the player to seek. Specifically, I expect cmd+[0-9] to switch tabs in my browser.

### Actual behaviour

When pressing cmd+[0-9], the focus players seeks instead of changing tabs

### Environment

- Browser: Google Chrome
- Version: 58.0.3029.110 (64-bit)
- Operating System: OS X
- Version: 10.11.6 (El Capitan)

Players affected:
- [x] HTML5 Video
- [ ] ~~HTML5 Audio~~
- [x] YouTube
- [ ] ~~Vimeo~~

Weird that it doesn't affect audio or vimeo 🤔 

### Steps to reproduce 

1. Go to https://plyr.io
2. Play a video or a YouTube video
3. Press cmd+[0-9]
4. Plyr seeks instead of passing pressed keys through to browser

### Relevant links
¯\\\_(ツ)\_/¯ Chrome shortcuts: https://support.google.com/chrome/answer/157179?hl=en

**Comment by sampotts** [comment]
Thanks for this. Will look into fixing it up in the next major release.

**Comment by sampotts** [comment]
I can't seem to replicate this on v3 so assuming it's fixed? Feel free to re-open if that's not the case 👍
