### ISSUE TITLE
Event timeupdate not firing on mobile

### ISSUE THREAD

**Issue by baberuth22** [sampotts/plyr#595]
- [ ] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 
Event kicked off to js when player head moves

### Actual behaviour
No event

### Environment

- Browser:  iOS
- Version:  10.0.2
- Operating System:
- Version: 

Players affected:
- [x] HTML5 Video
- [x] HTML5 Audio
- [x] YouTube
- [x] Vimeo

### Steps to reproduce 
View player on mobile.  We are playing inline trying to respond to the event. 

I am able to call players[0].getCurrentTime() using javascript.  As a workaround, I am considering using setInterval with getCurrentTime.

**Comment by sampotts** [comment]
I think there's some event issues on unsupported browsers. It'll be fixed in the next major release (which I'm working on).

**Comment by romanvbabenko** [comment]
Still here. Any chance to fix it?

**Comment by sampotts** [comment]
Have you tried v3?

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
