### ISSUE TITLE
 Can't find variable: plyr

### ISSUE THREAD

**Issue by erdinctogulga** [sampotts/plyr#597]
Hi,

I'm not familiar in js and not a coder as well :) but I made a website and add the .plyr into it. the player works fine and I really love it, but having trouble to switch video content to push on master player. I'm really stuck on this case...  I found a working code on [jsfiddle.net](https://jsfiddle.net/6okm62pf/26/) that makes reCreate video into the master player. I added into my site but .plyr variable error.  I really appreciate to solve this issue. Please help :/ 

The video is on the home screen >[hadipisir.com](http://hadipisir.com/tr)

the html
```
<div class="row">
      <ul  id="video" class="list3">
              <selection>
                 <div data-type="{{ data.datatype }}" data-video-id="{{ data.videoid }}"></div>
              </selection>
            <li class="col-lg-3 col-md-3 col-xs-6 {{ loop.index }}">
              <div class="box1">
                  <button id="btns">
                      <figure><img class="{{ data.class }}" src="{{ data.image }}"/></figure>
                 </button>
           </li>
      </ul>
</div>
```

and the js on same page 
```
ref = plyr.setup()[0].plyr;

document.querySelector("#btns").addEventListener("click", function (event) {
  ref.source({
    type:       'video',
    title:      'Memories of Paintings',
    sources: [{
        src:    '160978792',
        type:   'vimeo'
    }]
  });
});
```

### Relevant links
http://hadipisir.com/tr

**Comment by sampotts** [comment]
It should be...

```javascript
var ref = plyr.setup()[0];
```

**Comment by erdinctogulga** [comment]
thanks for the lightspeed comment but I2m having the same error on log
