### ISSUE TITLE
Feature: ES2015 support

### ISSUE THREAD

**Issue by marcobiedermann** [sampotts/plyr#598]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

How about moving your codebase to ES2015 syntax?
This would have some benefits and would make further development more easier:
* Template literals to build HTML structure in JavaScript
* `class` constructor which simplifies the structure
* split code into modular components via `import` and `export`, this way it is easier to maintain and allows treeshaking for smaller build files, if not all functions are needed
* it is the future of JavaScript

If you have any planings on implementing this, feel free to hit me up, I can help you out :)

**Comment by sampotts** [comment]
Hey @marcobiedermann, 

This is definitely on the cards. I've never been 100% happy with how the JS is structured. In the `develop` branch I've rewritten it to use a proper constructor and prototypes but moving to ES6/ES2015 would be even better. Once I've finished getting the bugs ironed out with the changes I'm working on then I'll give you a yell to give me a hand if that's ok? 

Cheers

**Comment by marcobiedermann** [comment]
@sampotts Sounds good. Yeah, sure ping me at any time :)

**Comment by ShimShamSam** [comment]
The tree-shaking aspect is exciting to me. I don't need YouTube/Vimeo/etc support and it bothers me a little bit to know that it's bundled into my build without purpose.

**Comment by sampotts** [comment]
Yeah I've always wanted to make Plyr more modular in that regard. Some may also want custom controls and not use the built in etc.

**Comment by jwjcmw** [comment]
+1 to tree-shaking and custom controls!

**Comment by sampotts** [comment]
The good news is, the way I've restructured the plugin in v3.0.0, it should make this a lot easier.

**Comment by sampotts** [comment]
Just to update you. I've re-written the whole thing in ES6 but there's still some improvement to be made in that removing Vimeo or YouTube doesn't break anything but it will come in time...

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
