### ISSUE TITLE
Issue on Fullscreen with undesirable thumb zoom

### ISSUE THREAD

**Issue by electroheadfx** [sampotts/plyr#599]
- [x] Issue observed on https://plyr.io/#vimeo

### Expected behaviour 
Go to fullscreen smoothly fitting plyr to fullscreen

### Actual behaviour
Go to fullscreen in a zoom and de-zoom with plyr small thumb image

### Environment

- Browser: Safari 
- Version:  10.1.1
- Operating System: MacOS Sierra
- Version: 10.12.5

Players affected:
- [x] Vimeo
- [x] Youtube

### Steps to reproduce 
- Install plyr with bootstrap 3 :
 HTML :
\<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
\<div class="js-media-player" >
\<div data-type="vimeo" data-video-id="34952587"

- JS :
plyr.setup();

### Relevant links, the video capture show the zoom artefact :
http://host.electroheadfx.fr/efxbox/laurent/plyr_zoom_issue.mov.zip

On old JS plyr the fullscreen was better (not zoomed thumb) :
http://josselinbillot.com/video/fiction
It could be perfect too

**Comment by sampotts** [comment]
I can't seem to replicate this on v3 so assuming it's fixed? Feel free to re-open if that's not the case 👍
