### ISSUE TITLE
Ready event fired twice with autoplay

### ISSUE THREAD

**Issue by dungphanxuan** [sampotts/plyr#600]
I set autoplay,so sound to good, two sound play.
i check debug and see two ready event.
I hander event ready for autoplay video. So app play two time.

![image](https://user-images.githubusercontent.com/10725732/26967120-43df52e6-4d27-11e7-97d2-e419e6ad2720.png)

**Comment by sampotts** [comment]
Will take a look thanks for raising it

**Comment by dungphanxuan** [comment]
Hi @sampotts , i check my app request two time, so plugin fire two time.  I have check it, so it's not bug.
