### ISSUE TITLE
Displaying duration using default options

### ISSUE THREAD

**Issue by vers-one** [sampotts/plyr#601]
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
Plyr shows actual duration of audio (or duration value passed through options) in the time label during initial load.

![expected](https://user-images.githubusercontent.com/12114169/27010835-bde733de-4eb6-11e7-9d73-ac9f4c2a6b9e.png)

### Actual behaviour
Plyr shows 00:00 in the time label during initial load.

![actual](https://user-images.githubusercontent.com/12114169/27010839-cac625c4-4eb6-11e7-9875-2b78dc3ab761.png)

### Environment

- Browser: Mozilla Firefox
- Version:  53.0.3
- Operating System: Windows
- Version: Windows 10 build 1703

Players affected:
- [ ] HTML5 Video
- [x] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
1. Use the following HTML code:
```
<audio controls crossorigin>
    <source src="https://cdn.selz.com/plyr/1.5/Kishi_Bashi_-_It_All_Began_With_a_Burst.mp3" type="audio/mp3">
</audio>
```
2. Add this JS code:
`plyr.setup();`
(or look at the Example 1 link below)

3. You will get the following result:
![result](https://user-images.githubusercontent.com/12114169/27010839-cac625c4-4eb6-11e7-9875-2b78dc3ab761.png)

### Relevant links
Example 1 (just plyr.setup() call): https://jsfiddle.net/kua4L64c/
00:00 is shown on load.

Example 2 (plyr.setup + source calls): https://jsfiddle.net/jr66ojku/
Works correctly (03:03 is shown) but requires additional setup from the JS code.

Example 3 (plyr.setup + explicit duration): https://jsfiddle.net/p4uxf2c2/
00:00 is shown on load.

Tooltip over progress bar in examples 1 and 3 shows correct values which means that plyr knows about duration but doesn't show it in the time label.

Setting preload="none" in example 3 also doesn't help (00:00 is shown).

**Comment by sampotts** [comment]
Is this for YouTube? I assume so. It's yet another limitation of their API unfortunately

**Comment by sampotts** [comment]
P.S it helps me if you use the issue template I created and you've gone ahead and deleted when creating your issue.

**Comment by versfx** [comment]
Sorry, I've updated my initial comment using the issue template.

**Comment by versfx** [comment]
So it looks like there is no way to display duration of audio with `preload` set to `"none"`.

If you do it via `plyr.setup(options)` like in this example:
```
<audio crossorigin preload="none">
    <source src="https://cdn.selz.com/plyr/1.5/Kishi_Bashi_-_It_All_Began_With_a_Burst.mp3" type="audio/mp3">
</audio>
```

`plyr.setup({duration:10});`

it doesn't work (shows 00:00).

If you do it via setting `player.source(...)` there is no way to set duration explicitly (and also no way to prevent it from requesting the audio).

So the only way to display the duration is to let Plyr to retrieve it from the audio files which is very inconvenient if you have dozens of them on the same page.

**Comment by versfx** [comment]
OK, I am going to fix it myself.

**Comment by versfx** [comment]
Please look at my pull request above.

**Comment by sampotts** [comment]
Will do thanks for that 👍
