### ISSUE TITLE
Plyr Ads | Monetize Plyr

### ISSUE THREAD

**Issue by ferdiemmen** [sampotts/plyr#605]
### Environment

- Browser: Chrome
- Version: 58.0.3029.110
- Operating System: macOS Sierra
- Version: 10.12.5

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [x] YouTube
- [x] Vimeo

### Relevant links
https://github.com/ferdiemmen/plyr-ads

**Comment by ferdiemmen** [comment]
Thank you for building Plyr! I enjoy it very much. Although it's great as it is, I missed the option to add pre-rolls. So I started to work on Plyr Ads. First I thought to extend the Plyr api and add it to the core. But on second thought I think this would be better as a separate plugin (size, external scripts). Also I saw that there is currently no way to extend the api before "setup" is fired.

Keep in mind this is a work in progress and I really would like to hear what you think about the current setup. And what you think is the best way to move forward with the plugin.

**Comment by sampotts** [comment]
It's been discussed a few times. I'll take a look it's just not something I have a huge incentive to build given I'm not a big fan of ads you can't skip.

**Comment by ferdiemmen** [comment]
Thanks for getting back to me.

Well the ad is actually skippable. By default it is set to show the ad skip button at 10 seconds. But if you set it to 0 (zero) it will immediately show.

**Comment by gehaktmolen** [comment]
Nice work, take note though that skippable ads are provided by doubleclick for example. Simply set the ads to be served as overlay ads. So no need to create your own skip button, as this would most likely result in a warning from your ad provider.

Just try some out: https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector
at: https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags

**Comment by ferdiemmen** [comment]
@gehaktmolen Thanks for the information. We are currently working on an update and I will set the ad skip button to optional instead of on by default.

**Comment by hieuhuynh93** [comment]
@ferdiemmen is it compatible with Plyr version 3 ?

**Comment by ferdiemmen** [comment]
@hieuhuynh93 Not only is it compatible it's actually integrated into Plyr version 3. Check: https://github.com/sampotts/plyr/tree/beta/src/js/plugins

**Comment by hieuhuynh93** [comment]
@ferdiemmen  oh wow, i didn't know that. It's awesome. Thank you

**Comment by sampotts** [comment]
Closing this one as I think it's baked into the latest version 👍
