### ISSUE TITLE
plyr.get('.some-player') always return empty array

### ISSUE THREAD

**Issue by Lorchelio** [sampotts/plyr#606]
I try get a plyr element with get(), but it always return [ ]

For Example:

const player = plyr.setup('.some-player')

plyr.get('.some-player') // []
plyr.get(document.getElementById('.some-player')) // []
const getPlayer = plyr.get(player) // []

In docs:

> This will return an array of all instances that were setup. Another way is to use plyr.get() to get all instances within a given container, for example:
> var players = plyr.get('.js-player');

What is the cause of the problem?

**Comment by ferdiemmen** [comment]
Hi,
I've made you a plunker to see the basic setup. Check the console to see the Array.
See: [Link to Plunker](https://plnkr.co/2J5m2EFlvcX7jink1kKF)

**Comment by Lorchelio** [comment]
Hi, ferdiemmen.
Looks like it's personal problem.This is the basic behavior for get(),but i use plyr on Twirl-template and it return empty array always. Maybe rerender is a reason, hmmm.....

**Comment by ferdiemmen** [comment]
Could you provide a plunker or a jsfiddle or a demo setup in some way so we can have a better look at your problem?

**Comment by Lorchelio** [comment]
Most likely not, because my project is big template machine :D and i have upload all template architecture.
I can try describe in words this case:
1) A user click to button for upload music
2) Music will upload
3) plyr.setup('.audio-for-uploaded-music) . Everything is OK.
4) The user does not like music and he removes it
5) I try plyr.get('.audio-for-uploaded-music'), but always have empty array . By the way - '.audio-for-uploaded-music' still in DOM, if i use plyr.get() - i'll get an array with this object.

**Comment by ferdiemmen** [comment]
Ah ok, just to be clear. What were you expecting to get after you removed it?

**Comment by Lorchelio** [comment]
In №4 case - i delete a input type="file" with uploaded music, then i try to release case №5

The function is:
            $('.delete-load-music').on('click', () => {
                $('#music_load_div').show();
                $('.delete-load-music').hide();
                $("#audioTag").attr('src', '');
                $('#add_file_input').remove();
                plyr.get().forEach((item) => { // i don't get a needed element,
                    item.destroy(); // this is the problem, i will destroy all of this now
                });

                $('.iframe-yandexMusicBox').after('<input class="hide" type="file" id="add_file_input"/>');
                    $('#add_file_input').on('change', function(event){
                        $("#music_load_div").addClass("loading");
                            var files = event.target.files;
                            var data = new FormData();
                            $.each(files, function(key, value){ data.append(key, value);});
                            ajaxFiles("@routes.MediaFileController.upload","POST",data,
                                function(response) {
                                    $("#music_load_div").removeClass("loading");
                                    $("#music_uuid").val(response);
                                    $("#audioTag").attr('src', '@routes.MediaFileController.tmpFile("")'+response);
                                    $('.delete-load-music').show();
                                    $('#music_load_div').hide();
                                    plyr.setup('#audioTag');
                        }
                    );
                });
            });

**Comment by Lorchelio** [comment]
I found the desicion!
`plyr.setup('.audio-for-uploaded-music')`
then i **must** search the element which contained '.audio-for-uploaded-music', for example
`const loadedMusic = plyr.get('.form-vertical')[0]; // get correct element`
`loadedMusic.destroy(); // success`

Docs contains not correct code-example for get()

**Comment by ferdiemmen** [comment]
Great work! I'm glad you found the problem.
