### ISSUE TITLE
Instance object returned by `get()` is equal but different reference than passed on `event.detail.plyr`

### ISSUE THREAD

**Issue by alejandroiglesias** [sampotts/plyr#608]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
```javascript
const plyrInstance = plyr.setup(element)[0];
plyr.get().forEach(p => console.log(p === plyrInstance));  // true
```
Expected the code to log `true`.

### Actual behaviour
```javascript
const plyrInstance = plyr.setup(element)[0];
plyr.get().forEach(p => console.log(p === plyrInstance));  // false
```
Actual code logs `false`.

### Environment

- Browser: Chrome
- Version:  59
- Operating System: macOS
- Version: 10.12.5

Players affected:
- [ ] HTML5 Video
- [x] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
- Check code samples on "Expected behaviour" and "Actual behaviour" sections.

### More info
This makes it difficult to implement functionality like the following without having to resort to deep object comparison, which is expensive if you have lots of players.
```javascript
function stopAllBut(instance) {
  plyr.get().forEach(player => player !== instance && player.pause());
}
```
As I said, it could be made with deep object comparison since the objects actually are equal, but this is more expensive.
```javascript
import _ from 'lodash';

function stopAllBut(instance) {
  plyr.get().forEach(player => !_.isEqual(player, instance) && player.pause());
}
```

**Comment by sampotts** [comment]
Sorry about this. I'm actually removing this in the next major release in favour of a proper constructor.

**Comment by sampotts** [comment]
This method has been removed in v3. Please upgrade to the latest version 👍
