### ISSUE TITLE
video's height is larger than the container

### ISSUE THREAD

**Issue by muzichen** [sampotts/plyr#611]
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

- Browser: Chrome
- Version:  New
- Operating System: Win10

Players affected:
- [ ] HTML5 Video

### Steps to reproduce 
- 

### Relevant links
[link](http://www.kmf.com/lesson/teacherinfo?id=106)

**Comment by sampotts** [comment]
I think this is a CSS issue that's outside of the realms of Plyr...

**Comment by muzichen** [comment]
@sampotts If the video's height is larger than the container's height. Does the video's height will overflow the container?
