### ISSUE TITLE
data-type attribute gets hijacked by plyr

### ISSUE THREAD

**Issue by owldesign** [sampotts/plyr#612]
I noticed that whenver I use `data-type="whatver"` anywhere on the page where I also have plyr scripts the `data-type` is being taken over by plyr. 

For example I have product detail page that has quantity number counter with plus and minus icons to add or remove quantity. My icons have `data-type="plus"` and 'data-type="minus"`... On the same page I also use plyr and once initialized it will wrap my icons with a div of class `plyr plyr--minus` for the minus icon. 

Thanks for the great plugin!

**Comment by sampotts** [comment]
Thanks for reporting. Will get this fixed up in `v3` which is coming soon

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
