### ISSUE TITLE
Play audio from..to

### ISSUE THREAD

**Issue by ThreadPitt** [sampotts/plyr#619]
Hi,

is there a way to play only a certain part of the audio, e.g. for standard <audio>, I can add the time parameter to the url: "http://...mp3?time=666,7550".

I saw that  there is a seek() and forward(), but how would I end at a certain point in time?

Thx

**Comment by tocsinDE** [comment]
> how would I end at a certain point in time?

Once you got the end mark in seconds (here called `end`) you could do this:

```javascript
element.on("timeupdate", function() {
    if (this.getCurrentTime() >= end) {
        this.pause();
    }
}
```

**Comment by ThreadPitt** [comment]
Yes, that works - Thanks a lot!

**Comment by sampotts** [comment]
Glad you got it sorted. I'll close this for now. Start and end times are scoped for build at some point.
