### ISSUE TITLE
Doesn't work properly on iOS

### ISSUE THREAD

**Issue by elemis** [sampotts/plyr#621]
Having issues on iOS. 

iPad: Vimeo appears with native player.
iPhone: All videos appear with native player.

Issues are observed on https://plyr.io

Only tested with the following:

- Browser: iOS Safari
- Operating System: iOS10

Are these issues fixable? If not, what is exactly the reason behind?

**Comment by sampotts** [comment]
Vimeo has issues with the API on iOS. I'm not sure why. It may be resolved. I'll need to check again. 

With iOS it's a limitation of iOS. Support for `playsinline` is being added in v3.
https://github.com/sampotts/plyr#browser-support
