### ISSUE TITLE
youtube video has no sound

### ISSUE THREAD

**Issue by jarekskuder** [sampotts/plyr#622]
I have cordova app. In android the video are just fine, but in iOS i have no sound in video.

My code 

`<div id="plyr_player" data-type="youtube" data-video-id="ZaIxLNKX11U" style="width: 100%; height: 100%"></div>`

Also i get this error, tho i don't think this is the problem

Blocked a frame with origin "https://www.youtube.com" from accessing a frame with origin "file://".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "file". Protocols must match.

**Comment by sampotts** [comment]
I don't think this is a Plyr issue but try v3 as it's a complete rewrite pretty much 👍

**Comment by jarekskuder** [comment]
@vesper8 i forgot about this problem, as @sampotts said, with v3, everything is ok for me. Try to show us the code here, maybe we can see whats the problem for you

**Comment by vesper8** [comment]
managed to get some info with the debugger, it was causing this error
```
Unable to post message to https://www.youtube.com. Recipient has origin file://
```

And I found the fix! Simply needed to add this line to the config.xml inside src-cordova
```
<!-- Add the whitelist plugin -->
<plugin name="cordova-plugin-whitelist" source="npm" spec="*"/>

<!-- White list https access to Youtube -->
<allow-navigation href="https://*youtube.com/*"/>
```
