### ISSUE TITLE
Autoplay not disable with hls

### ISSUE THREAD

**Issue by burakozturk16** [sampotts/plyr#625]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
When autoplay:false in config or autoplay="false" in >video< tag, video not need to start automatically.

### Actual behaviour
it plays auto..

### Environment

- Browser: Firefox
- Version:  54.0.1
- Operating System: macOS
- Version: 10.12.5

Players affected:
- [x] HTML5 Video (with HLS)
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

**Comment by burakozturk16** [comment]
I found a solution for this issue myself;

`player.on('ready', function(event) {
		player.stop();
	});`

I hope, it will help somes..

**Comment by friday** [comment]
`autoplay` is a boolean property, so in order to disable it you must leave it out.
