### ISSUE TITLE
SoundCloud Example

### ISSUE THREAD

**Issue by Plinpod** [sampotts/plyr#627]
Hello, 

I saw that you could play SoundCloud audio through plyr. I was wondering if someone could provide me with a working example of this. Much appreciated. Thank you!

**Comment by sampotts** [comment]
It's being removed in an upcoming release as it's only partially supported. It was meant to be experimental. It'll be re-added once we have a proper plugin framework built.

**Comment by sampotts** [comment]
Closing this for now.
