### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided

### ISSUE THREAD

**Issue by sessionstop** [sampotts/plyr#631]
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Environment

- Browser: Chrome
- Version:  60.0.3112.90
- Operating System: Mac OS
- Version: 10.12.6

Related Links for solving this issue:

**Comment by edanedison** [comment]
I'm also starting to see this error in Chrome (60.0.3112.90 (Official Build) (64-bit)). It seems to be having a fit somewhere around the _youTubeReady function.

**Comment by sampotts** [comment]
Does it actually cause any playback issues for you though? I've always seen it in the console but it's never effected playback so I've just ignored it. I assume it's an issue with YouTube's API which isn't the best.

**Comment by edanedison** [comment]
Nope, no playback issues, and no error message in other browsers as far as I can see. I personally didn't notice this at all until the recent chrome update.

**Comment by sampotts** [comment]
This is an issue with the YouTube API and nothing I try seems to fix it. Closing this one for now. Will add a note in the docs.

**Comment by jvlobo** [comment]
any news on this?? I'm getting the same error...
doesn't it happen for everyone?
any hints why does it happen?

**Comment by jvlobo** [comment]
I saw it... but the player seems so broken that I thought somebody else may have experienced this issue... and seems your last comment is from a year ago... that's why I asked.

<img width="933" alt="screenshot 2018-12-27 at 21 30 12" src="https://user-images.githubusercontent.com/5671420/50478771-c1e7c780-0a1e-11e9-9a7f-e317c0598afa.png">

**Comment by jvlobo** [comment]
My fault... I wasn't including the CSS and the player was looking super broken and I thought it was because of that error :( 
Thanks!

**Comment by haladamateusz** [comment]
> 
> 
> My fault... I wasn't including the CSS and the player was looking super broken and I thought it was because of that error :(
> Thanks!

I Had the same problem. Please create "troubleshooting" in readme or sth and mention that because I spend over 30min to figure this out. I was thinking its because of the "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided" but the real reason was not including .css

**Comment by Anand-Paul** [comment]
Am too getting this error, is there any way to resolve it?

**Comment by sampotts** [comment]
You can safely ignore it. There's no way around it. It's from the YouTube SDK.

**Comment by Anand-Paul** [comment]
OK

**Comment by tmk1991** [comment]
Found a fix for me:
Add: `<script defer src="https://www.youtube.com/iframe_api"></script>` to your main index.html
Make sure to set both youtube params: `origin: 'https://localhost/'` `widget_referrer: 'https://localhost/'`

https://developers.google.com/youtube/player_parameters

**Comment by Shuvadip-Ghosh** [comment]
I am also getting this error
but when my code is this 
```html
<div id="player" data-plyr-provider="youtube" data-plyr-embed-id="bTqVqk7FSmY"></div>
```
the video is not playing 
and when the code is this
```html
<div class="plyr__video-embed" id="player">
  <iframe
    src="https://www.youtube.com/embed/bTqVqk7FSmY?origin=https://plyr.io&amp;iv_load_policy=3&amp;modestbranding=1&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;enablejsapi=1"
    allowfullscreen
    allowtransparency
    allow="autoplay"
  ></iframe>
</div>
```
The css is not working what to do ??
