### ISSUE TITLE
Fix `loop` and `muted` options on setup

### ISSUE THREAD

**Issue by julmot** [sampotts/plyr#632]
Even I didn't understand the docs or they don't document the following case. However, sorry for asking such a trivial question.

When I initialize plyr with HTML5 videos the HTML looks like the following:

```html
<video preload="auto" muted loop controls>
  <source src="somevideo.mp4" type="video/mp4">
</video>
```

Then plyr leaves the attributes, especially `muted` and `loop`. So this works. However, I find it strange that I need to use HTML5 attributes here and that there is no option property for this, e.g.:

```javascript
let players = Plyr.setup(video, {
  muted: true,
  loop: true
});
```

And that's the problem I have now when the video is a Vimeo video. I need to also set `muted` and `loop`. Regarding `muted` I've workaround to set `player.setVolume(0)` after initialization. However, specifying `loop` on a Vimeo video wasn't successful for me.

How to define default options for HTML5 and Vimeo videos, especially `muted` and `loop`? Also I'm interested in the `playsinline` attribute, which I need for autoplaying videos on iOS?

**Comment by sampotts** [comment]
Sorry yeah I need to make this a little cleaner for sure. I'll make sure to include it in V3.

**Comment by julmot** [comment]
Thanks @sampotts. And what would be the intermediate solution?

**Comment by sampotts** [comment]
I'll have to get back to you on that...

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
