### ISSUE TITLE
Is there a way to set the cc_lang_pref in _youTubeReady()?

### ISSUE THREAD

**Issue by Hambern** [sampotts/plyr#633]
### Expected behaviour 

I want to be able to change the prefered cc language. Is this possible through the options object? In any other way that does not include messing with the source code?

### Actual behaviour

English as permanently set as the cc language

### Environment

- Browser: Google Chrome
- Version: ?
- Operating System: Mac OS
- Version: ?

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [x] YouTube
- [ ] Vimeo

### Steps to reproduce 

Play a YouTube video with captions

**Comment by sampotts** [comment]
I've added this in v3 but do you have a video with captions I could test with by any chance?

**Comment by sampotts** [comment]
I've added this to v3 (it pulls from the same language as the caption settings) so assuming it's fixed? Feel free to re-open if that's not the case 👍
