### ISSUE TITLE
Quality selection

### ISSUE THREAD

**Issue by RomanS2N** [sampotts/plyr#634]
Hello!

When will be make "quality selection"? And if it is't realized in the code  tham how to play HD quality video?

- [x ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Environment

- Browser: Opera
- Version:  last
- Operating System: Win  
- Version:  10

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [x ] YouTube
- [ x] Vimeo

**Comment by sampotts** [comment]
In progress already.

**Comment by RomanS2N** [comment]
But how can play in HD quality in tcurrently version? May I canged it in code manualy?

**Comment by sampotts** [comment]
Too hard to explain here or I’d have released the feature already?

**Comment by RomanS2N** [comment]
Ok. will be wait! Thank you for great web app!
