### ISSUE TITLE
Reference Vimeo Froogaloop API in docs

### ISSUE THREAD

**Issue by julmot** [sampotts/plyr#635]
I couldn't find any information about the API that's being used in plyr, as it's no longer supported. Why doesn't plyr use the official player API of vimeo? Please document where to find all necessary information.

**Comment by sampotts** [comment]
It doesn't use Froogaloop. They stopped supporting that a while back. It uses [player.js](https://github.com/vimeo/player.js) now but Plyr is really an abstraction for the API anyway.

**Comment by sampotts** [comment]
I've updated the docs. Sorry for the confusion.

**Comment by julmot** [comment]
Thanks @sampotts, I'll read the player.js docs of Vimeo to get started. However, I'd love to have plyr options for default HTML5 options, as I'm not sure how to define them that they also work for Vimeo (see #632).
