### ISSUE TITLE
Video recording from android phone is not displayed 

### ISSUE THREAD

**Issue by lazyboy1801** [sampotts/plyr#637]
I recorded a video on my phone. When embedded in the code below it will not run. help me !

/---------------------------------------------------------------------------------------------------------------/
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Plyr - A simple HTML5 media player</title>
        <meta name="description" content="A simple HTML5 media player with custom controls and WebVTT captions.">
        <meta name="author" content="Sam Potts">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        
        <link rel="stylesheet" href="../dist/plyr.css">

        
        <link rel="stylesheet" href="dist/demo.css">
    </head>
    <body>
        <header>
            <h1>Plyr</h1>
            <p>A simple, accessible HTML5 media player by <a href="https://twitter.com/sam_potts" target="_blank">@sam_potts</a></p>
            <nav>
                <ul>
                    <li>
                        <a href="https://github.com/sampotts/plyr" target="_blank" class="btn btn--large btn--primary" data-shr-network="github">
                            <svg class="icon"><use xlink:href="#icon-github"/></svg>Download on GitHub
                        </a>
                    </li>
                    <li>
                        <a href="https://twitter.com/intent/tweet?text=A+simple+HTML5+media+player+with+custom+controls+and+WebVTT+captions.&url=http%3A%2F%2Fplyr.io&via=Sam_Potts" target="_blank" class="btn btn--large btn--twitter" data-shr-network="twitter">
                            <svg class="icon"><use xlink:href="#icon-twitter"/></svg>Tweet
                        </a>
                    </li>
                </ul>
            </nav>
        </header>

        <main role="main" id="main">
            <nav class="btn__bar">
                <ul>
                    <li class="active">
                        <button type="button" class="btn" data-source="video">Video</button>
                    </li>
                    <li>
                        <button type="button" class="btn" data-source="audio">Audio</button>
                    </li>
                    <li>
                        <button type="button" class="btn btn--youtube" data-source="youtube"><svg class="icon"><use xlink:href="#icon-youtube"/></svg>YouTube</button>
                    </li>
                    <li>
                        <button type="button" class="btn btn--vimeo" data-source="vimeo"><svg class="icon"><use xlink:href="#icon-vimeo"/></svg>Vimeo</button>
                    </li>
                </ul>
            </nav>
            <section>
                <video poster="https://cdn.selz.com/plyr/1.5/View_From_A_Blue_Moon_Trailer-HD.jpg?v1" controls crossorigin>
                    
                    <source src="abc.mp4" type="video/mp4">
                    <source src="abc.mp4" type="video/webm">

                    
                    <track kind="captions" label="English" srclang="en" src="https://cdn.selz.com/plyr/1.5/View_From_A_Blue_Moon_Trailer-HD.en.vtt" default>

                    
                    <a href="abc.mp4" download>Download</a>
                </video>

                <ul>
                    <li class="plyr__cite plyr__cite--video"><small><a href="http://viewfromabluemoon.com/" target="_blank">View From A Blue Moon</a> &copy; Brainfarm</small></li>
                    <li class="plyr__cite plyr__cite--audio"><small><a href="http://www.kishibashi.com/" target="_blank">Kishi Bashi &ndash; &ldquo;It All Began With A Burst&rdquo;</a> &copy; Kishi Bashi</small></li>
                    <li class="plyr__cite plyr__cite--youtube"><small><a href="https://www.youtube.com/watch?v=bTqVqk7FSmY" target="_blank">View From A Blue Moon</a> on <span class="color--youtube"><svg class="icon"><use xlink:href="#icon-youtube"/></svg>YouTube</span></small></li>
                    <li class="plyr__cite plyr__cite--vimeo"><small><a href="https://vimeo.com/ondemand/viewfromabluemoon4k" target="_blank">View From A Blue Moon</a> on <span class="color--vimeo"><svg class="icon"><use xlink:href="#icon-vimeo"/></svg>Vimeo</span></small></li>
                </ul>
            </section>
        </main>

        
        <script src="../dist/plyr.js"></script>

        
        <script src="dist/demo.js"></script>

        
        <script src="https://cdn.rangetouch.com/1.0.1/rangetouch.js" async></script>

        
        <script src="https://cdn.shr.one/1.0.1/shr.js"></script>
        <script>if(window.shr) { window.shr.setup({ count: { classname: 'btn__count' } }); }</script>
    </body>
</html>

**Comment by jonnitto** [comment]
Have you tested your video without the plyr? Because plyr is just a wrapper for the `<video>` element. I think it's more an issue at Android or browser and not plyr. But the line `<source src="abc.mp4" type="video/webm">` is for sure incorrect. You have to delete this line, since you have not the video in the webm format…

**Comment by sampotts** [comment]
You need to make sure the video is a HTML5 friendly format. Closing this one as it's not really a Plyr issue.
