### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by vibhi19** [sampotts/plyr#638]
please Update Wordpress plugin 
Can You add More Site to support the player Like Vk.com, funnyordie.com,ok.ru,facebook,and google drive yandex drive onedrive basically Support all Oembed provider (if Possible) 
Add  advertisment Support Like Popup,baaner ,pre roll ,mid roll (by the way found this https://github.com/ferdiemmen/plyr-ads)
Also Give Option to upload Your own subtitle through own computer or mobile from local storage
completly Hide Youtube Logo if it possible
add Option to share video but not youtube or vimeo share link insted post link where it embedded 
add lazy load (load only a splash Image first when click then load the whole player )
Add own Logo with Link support

- [ ] Issue observed on https://plyr.io
Sometime The Play button doesn't  work in mobile device(need to click At least 3 to 4 times )'
Hide Play Button When Click on  it (youtube)

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

**Comment by sampotts** [comment]
I'll try and make sense of that:

- The WordPress plugin I don't manage or look after. Get in touch with the author for that
- In regards to "more support" - this will come later. I'm not going to go down that road but instead make Plyr work with plugins that would allow this
- Advertisements has been raised already - not a huge amount of incentive for me to do this as I don't like ads really. Only advertisers do! :) 
- Subtitles is already supported - have a read of the docs - doing something like you want has a low use case so I'd not really incorporate that but you can build it yourself pretty easily
- YouTube branding is already reduced to the minimum it can be - unfortunately they still show their logo and loader 
- Custom sharing you can build yourself 
- Logo can be added with CSS fairly easily 

Thanks for the feedback but most of what you suggested has such low general appeal that I wouldn't want to bloat Plyr even further for features that wouldn't get much use.

**Comment by vibhi19** [comment]
Well Thanks For the player and reply but what you think about these problems

Sometime The Play button doesn't work in mobile device(need to click At least 3 to 4 times )'

Hide Play Button When Click on it (youtube)

**Comment by vibhi19** [comment]
And Advertisement is the only way to survive for publisher so I think its Important

**Comment by sampotts** [comment]
Not sure on those issues as I've not experienced them myself. 

> And Advertisement is the only way to survive for publisher so I think its Important

I'm sure it is for you but this is a project for me to build in my spare time. It's meant to be fun for me. The prospect of others making money off my hard work has little appeal. Do you work for free?

**Comment by vibhi19** [comment]
Ok Thanks For the reply 

Well Plugin Author on wordpress doesn't reply on support forum
and He's also not active on the forum from at least 7 months so
Need to find another way for update 
I'll try myself LOL!
