### ISSUE TITLE
How to use this player via provided script

### ISSUE THREAD

**Issue by vibhi19** [sampotts/plyr#639]
Hi 
I tried using your player via provide script 

`<script` src="path/to/plyr.js"></script>
<script>plyr.setup();</script>
<link rel="stylesheet" ``href="path/to/plyr.css">`

I Put the code before ending of the </body> tag 
and Use<div data-type="youtube" data-video-id="bTqVqk7FSmY"></div>
and Even put the direct url but it doesnt work

Can You tell how to actully use your player ??

**Comment by sampotts** [comment]
Hey mate, all in the docs:

https://github.com/sampotts/plyr#quick-setup

**Comment by vibhi19** [comment]
Hi
In My wordpress site i put this script
```
<script` src="path/to/plyr.js"></script>
<script>plyr.setup();</script>
<link rel="stylesheet" ``href="path/to/plyr.css">
```

before Closing body tag as said in docs
after that i created a post and Put Youtube  code Like Provide in Docs
`<div data-type="youtube" data-video-id="bTqVqk7FSmY">``
But it doesnt work

**Comment by vibhi19** [comment]
and If you got time Please Check This Url In Your Phone http://newsa2.com/poster-boys-second-song-kedi-menus-released/

Play Button doesn't work  You Need To click multiple Time thenIt work

**Comment by vibhi19** [comment]
and The Upper Problem Doesn't fix yet
