### ISSUE TITLE
IE11 active plyr button shifting

### ISSUE THREAD

**Issue by julmot** [sampotts/plyr#640]
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 

When clicking on a player button, the text or icons should not move.

### Actual behaviour

In IE11, the text/icons moves when you click on a player button.

### Environment

- Browser: IE
- Version:  11
- Operating System: Windows
- Version: 10

Players affected:
- [x] HTML5 Video
- [x] HTML5 Audio
- [x] YouTube
- [x] Vimeo

### Steps to reproduce 

![plyr-button-jump-effect](https://user-images.githubusercontent.com/8310677/29605222-627e2990-87ea-11e7-9e7a-a9e304b6015d.gif)

### Relevant links

https://stackoverflow.com/a/19593629/3894981

**Comment by sampotts** [comment]
Thanks for raising this. IE has always been crap with `<button>` elements which is what drove many developers to use the horrible `<a href="javascript:void(null)">` type stuff or worse `<div>` and `<span>`.

I'd rather not add the extra `<span>`s in personally to bloat the markup. IE11 is slowly dying off anyway. Currently at 3% usage. I'll put this on the back burner.

**Comment by sampotts** [comment]
I think I'm just going to close this and not worry about it for now. IE11 is slowly dying anyway 👍
