### ISSUE TITLE
[Compatible] HTTP/1.1 302 Moved Temporarily

### ISSUE THREAD

**Issue by An0nymous0** [sampotts/plyr#642]
Video address cdn sometimes occurs  http 302 state, whether it can be compatible

**Comment by sampotts** [comment]
Whatever's compatible with the `<video>` element:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

**Comment by An0nymous0** [comment]
What can be said to be more detailed? I do not really understand. thx

**Comment by sampotts** [comment]
I'm not really too sure what the question is? Do you mean the Plyr CDN returns a 302? Or your video CDN returns a 302 and you're asking if the `<video>` element is ok with that?

**Comment by An0nymous0** [comment]
source src：http://a.xxx.com/CourseWareMp4/15bbf4d9c2f6d2a5137aef03055e5042_sd.mp4  

cdn http state 302   -->>

http://117.75.20.6/mp4files/4173000003137183/a.xxx.com/CourseWareMp4/15bbf4d9c2f6d2a5137aef03055e5042_sd.mp4


Lead to can't play.

**Comment by sampotts** [comment]
Well that last URL doesn't load for me...

![image](https://user-images.githubusercontent.com/719092/31419019-1aa863ee-ae85-11e7-8328-eb6616800ab6.png)

It doesn't seem like a Plyr issue so I'd make sure the video is in the correct format, is served with the correct content type and actually loads by itself. As I say, Plyr is just an abstraction for the `<video>` element so if it doesn't work with that, it'll not work with Plyr.

**Comment by An0nymous0** [comment]
source url can not be played when redirected,I'm not sure if it's Plry.

**Comment by sampotts** [comment]
No, it's not. Good luck fixing it! :-)
