### ISSUE TITLE
plyr.setup() adds sprite to top of page

### ISSUE THREAD

**Issue by codemonkeynorth** [sampotts/plyr#643]
plyr.setup() is adding an unhideable sprite to the top of the page or above the body

setting `display: none` does nothing

I believe this is possibly because modernizr is adding a class to the body? is plyr.setup looking for a standard class like 'video' maybe?

thanks
J

**Comment by sampotts** [comment]
Yes, the sprite is required by the controls. There's information about it in the docs on the main page. Worth a read 👍
