### ISSUE TITLE
YouTube example doesn't play on iOS 9.3.5, Chrome 60 (iPad)

### ISSUE THREAD

**Issue by codemonkeynorth** [sampotts/plyr#644]
YouTube example doesn't play. Just gets stuck loading . Is it possible to force the native UI on iOS?

My iPhone 5 works ok but the OS is newer and it's not trying to use the custom UI

Thanks
J

**Comment by codemonkeynorth** [comment]
I think it might be a 720p issue because going to the video URL directly in chrome on my ipad (original v3) it won't play either
https://m.youtube.com/watch?v=bTqVqk7FSmY

something like this does play, but it is 480p 
https://m.youtube.com/watch?v=VN-kFN3cNuc

so if youtube doesnt work directly, we can't expect plyr to work

hope this helps somebody anyway
j

**Comment by sampotts** [comment]
Closing this one for now then? Let me know if it's still an issue
