### ISSUE TITLE
How to add plyr on Dynamic element from ajax

### ISSUE THREAD

**Issue by Yugandharjaiswal** [sampotts/plyr#645]
hello i am using plyr js and it's working fine for audio and video tag which are already part of DOM whene loaded
i used 
<script>
plyr.setup();
</script>

it's working fine but whene i add new video and audio elements using ajax 
for example new chat message(Audio/video)
it's not working on new element 
so  i've to call plyr.setup() again with each element added
well that's working fine for new elements
but for old elements its creating copies of old elements
again and again on each new element added

**Comment by marcelogarbin** [comment]
+1

**Comment by friday** [comment]
You can use [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) for that
