### ISSUE TITLE
All seekbars freeze while dragging one seekbar

### ISSUE THREAD

**Issue by geomslayer** [sampotts/plyr#648]
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 
Independent volume and main seekbars.

### Actual behaviour
While dragging volume slider, the main seekbar freezes.
### Environment

- Browser: Google chrome, Version: 59.0.3071.115 (Official Build) (64-bit)
- Browser: Firefox, Version: 55.0.2 (64-bit)
- Operating System: Ubuntu, Version: 16.04 LTS

Players affected:
- [x] HTML5 Video
- [x] HTML5 Audio
- [x] YouTube
- [x] Vimeo

### Steps to reproduce 
- Start to play video
- Click on volume slider and hold it

**Comment by sampotts** [comment]
Can you fill out the rest of the bug report so I can replicate, debug and fix it? Mainly the OS and browser part...

**Comment by geomslayer** [comment]
In the code I found a condition, that do it.
There it is: https://github.com/sampotts/plyr/blob/master/src/js/plyr.js#L2385
Explain please, why do we need it.
Also thanks for the player, it's awesome!

**Comment by sampotts** [comment]
I'm not sure - I should have left a comment there. I've removed it in V3 and there doesn't seem to be an issue.

**Comment by geomslayer** [comment]
@sampotts, how soon is V3 coming?

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
