### ISSUE TITLE
Autoplay with different volume

### ISSUE THREAD

**Issue by thagxt** [sampotts/plyr#653]
Is is possible to autoplay 2 players at the same time but with different volumes?! 

Because I've noticed that it saves a global value for volume, when volume is tweaked. 

Once you refresh the page all the players start with the saved volume and not with the one specified in `plyr.setup(); `

**Comment by wngr** [comment]
just use `.setVolume` on the different instances.

**Comment by sampotts** [comment]
As above really - use `.setVolume()`
