### ISSUE TITLE
Buttons and Closed Captions not showing

### ISSUE THREAD

**Issue by kretchy** [sampotts/plyr#655]
Thank you for making plyr - it's really a great project and I love the amount of options. Facing a strange issue though:

Trying to come up with a public kiosk solution playing back a couple of silent videos with captions (wvtt) on a computer with a touchscreen attached to it. Everything works fine on the quite modern mac os x system I am using for the development. Tested it in Safari as well as Chrome with no problems.

On the small scale 32 bit based fanless computer system (Intel Atom processor, just 2GB of RAM, shared memory graphics chip) powering the touchscreen I tried it with some piece of Windows Kiosk Software (just offering Microsoft Internet Explorer as browser) as well as a USB stick bootable Porteus Kiosk Linux in its 32 bit version using Google Chrome (I guess the latest 32 bit release). In both browsers I get the plyr player and progress bar with functionality, but the buttons of the player (restart, play / pause toggle, CC) are not showing, though the area is clickable and functional. Also the captions don't show up. I wonder whether it's got something to do with SVG rendering of the plyr buttons not working properly, but I have no idea what could cause the closed captions to not show up. Any ideas?

**Comment by david-potgieter** [comment]
Regarding the missing buttons: does the kiosk have external internet connectivity? The SVG sprite is referenced from a CDN. Also facing missing captions - which led me to your issue. :)

**Comment by sampotts** [comment]
You can reference a local version of the SVG sprite instead. See the demo for an example. I'm going to close this one as it's been around a while. Feel free to re-open if you have issues 👍
