### ISSUE TITLE
.source() throws exception when used on a Vimeo video

### ISSUE THREAD

**Issue by NindroidX** [sampotts/plyr#657]
When using the .source() api method to get the video source on a Vimeo video, the browser throws an exception. 

[Codepen which displays this behaviour](https://codepen.io/anon/pen/PJwrzG)
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
The video url should be returned.
### Actual behaviour
The browser throws an exception.
### Environment

- Browser: Chrome
- Version:  60
- Operating System: OS X
- Version: 10.12.5

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [x] Vimeo

### Steps to reproduce 
- Call the .source() function on an instance of a Vimeo video

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by NindroidX** [comment]
Hey! Thanks for the work, but I think it's not fixed yet.

I updated the codepen to use v3.0.3 and it still does not log the source url for vimeo videos.

https://codepen.io/NindroidX/pen/MVpNGV

**Comment by sampotts** [comment]
Damn. I’ll take another look then.
