### ISSUE TITLE
After setting up player, play button and others not working

### ISSUE THREAD

**Issue by Moses-Bassey** [sampotts/plyr#660]
After setting up the player the control button aint working, but the player seems to be set up as it is in the demo guide

- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Environment

- Browser:
- Version:  
- Operating System:
- Version: 

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
-

**Comment by sampotts** [comment]
Could you be more vague?
