### ISSUE TITLE
REDAXO AddOn :: video adds Plyr

### ISSUE THREAD

**Issue by skerbis** [sampotts/plyr#661]
I would like to proudly announce that Plyr is now part of the REDAXO Video Addon.
Maintained by the FriendsOfREDAXO team.
It is now available in the installer.
https://github.com/FriendsOfREDAXO/video

**Comment by friday** [comment]
Looks good! If you want to be added on the [Used by](https://github.com/sampotts/plyr#used-by) section, shout out to Sam of twitter, or better yet: add a PR (not my call to make).
