### ISSUE TITLE
Force Fullscreen on play?

### ISSUE THREAD

**Issue by pablopaul** [sampotts/plyr#663]
Hey, 

is there a way to force / activate the fullscreen mode on play (started by a click)?

I found this example https://github.com/sampotts/plyr/issues/74 but I cant find the proper "plyr"-element to which I can attach the onClick handler.

Does anybody has an idea?

Thanks,
Paul

**Comment by Fanna1119** [comment]
Not sure if this is what you are looking for.

`    $(".button).on("click", function(){
    	vid.toggleFullscreen();
    	vid.play();
    });`

**Comment by sampotts** [comment]
Sorry for the delayed response - the above is correct 👍
