### ISSUE TITLE
Fullscreen is broken on Apple Safari v11 except youtube

### ISSUE THREAD

**Issue by electroheadfx** [sampotts/plyr#664]
- [X] Issue does not already exist
- [X] Issue observed on https://plyr.io

### Expected behaviour 

Full screen on totally screen

### Actual behaviour

Full screen with cropped half video on top screen

### Environment

- Browser: Safari
- Version:  11
- Operating System: macOS Sierra
- Version: 10.12.16

Players affected:
- [X] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [X] Vimeo

### Steps to reproduce 

Test on plyr.io with the environment above.

### Relevant links
https://plyr.io/#vimeo
![capture d ecran 2017-09-21 a 17 46 40](https://user-images.githubusercontent.com/1211149/30705368-8d7693fe-9ef5-11e7-81f9-dd9c94f9f7ea.png)

**Comment by electroheadfx** [comment]
Only on youtube fullscreen WORKS with Safari 11. Its broken with all others videos support (video + vimeo)

**Comment by sampotts** [comment]
This should be handled in v2.0.16. Safari, being Safari changed how they handle fullscreen elements, of course.
