### ISSUE TITLE
Creating a playlist - Need community help

### ISSUE THREAD

**Issue by onigetoc** [sampotts/plyr#665]
I am creating a playlist for Plyr, i need help with better programers than me

It should play any format audio or and video.

https://codepen.io/onigetoc/pen/VMPeNg

I really want the json to look like this for many reason

```
var myPlaylist = [
  {
    title: "Armin van Buuren live at Ultra Music Festival Miami 2017",
    artist: "Armin van Buuren",
    youtube: "cLcKew4cQq4",
    oga: "http://www.jplayer.org/audio/ogg/TSP-01-Cro_magnon_man.ogg",
    poster: "https://img.youtube.com/vi/cLcKew4cQq4/hqdefault.jpg"
  },
  {
    title: "2 hours Trance Music - Armin Van Buuren",
    artist: "Armin van Buuren",
    youtube: "https://www.youtube.com/watch?v=r6KXy0j85AM",
    poster: "https://img.youtube.com/vi/r6KXy0j85AM/hqdefault.jpg"
  }
]
```

1.  i did a lot of coding for the jPlayer playlist.
2. I did a podcast parser here: https://github.com/onigetoc/Podcast-parser-for-jPlayer

**Comment by onigetoc** [comment]
My V4 beta version with loading Youtube playlist.
https://codepen.io/onigetoc/pen/YrZzbx?editors=1010

**Comment by onigetoc** [comment]
Finally i make it work.
JSON or Youtube playlist with previous and next buttons.
https://codepen.io/onigetoc/pen/veWNbP

**Comment by qnoox** [comment]
note there is an issue same as my setup if you switch tab it won't change the song automatically and start playing it, let me know if you figure it out :) other then that awesome playlist function!

**Comment by Metalspell** [comment]
Hi guys, sorry in advance for my clumsy English - this is not my native language. So, when you click on a pause, above the control panel, a list of "other videos" appears with a preview. But it is not clickable. Is it possible to select a video from the list and open it in the player window? Or in extreme cases, remove this list.
https://codepen.io/Metalspell/pen/vbzRgg

**Comment by skerbis** [comment]
here is a working example for 3.x https://codepen.io/skibbi/pen/NWvLoRz
