### ISSUE TITLE
On iOS 11 video black screen

### ISSUE THREAD

**Issue by jarekskuder** [sampotts/plyr#668]
I have cordova app with video stream. On new iOS 11 when i come to video tab, it shows perfectly, but when i toggle view and come to video again, the sound is going but no video, only black screen.

Cordova 7.0.1
iOS 11

Code:
<video id="my-video" poster="">
<source src="http://m-1.data.lt/lietus/lietus_480p/playlist.m3u8" type="application/x-mpegURL"></video>

**Comment by sparkktv** [comment]
I have not seen this issue on iOS 11 yet myself. It works fine using Youtube & Vimeo, only issue I've seen is on iPad it won't go full screen, only fill up size of browser or app being used in. I've been using iOS 11 since Beta 1

**Comment by jarekskuder** [comment]
Well i fixed it with new plyr object creation when i come to video screen. But still happens after 6 and more times of changing screen.

**Comment by danil89** [comment]
I have the same problem on iOS11

**Comment by electroheadfx** [comment]
plyr is broken with newer version of Safari (iOS 11 and macOS safari 11 ) specially in fullscreen.

**Comment by sampotts** [comment]
There seems to be a couple of issues mentioned here. The fullscreen one should be fixed in the latest version. Safari made a change to how it handles fullscreen elements, as per usual.

**Comment by electroheadfx** [comment]
yeah thanks sampotts, it works great now, just tested. Take care.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by rquimbygh** [comment]
@sampotts what was the fix? We're running into a problem that sounds exactly the same. Is there a commit we can look? Thanks!!
