### ISSUE TITLE
Seek  via URL params instead of Byte range headers? 

### ISSUE THREAD

**Issue by fiveDust** [sampotts/plyr#675]
Not an issue, more a question.  I'm planning to give the nginx mp4 pseudo streaming module a go. Just having a look at the demo player and it uses byte range headers like, e.g. "range:bytes=45842432-" . mp4 module supports query params like http://example.com/elephants_dream.mp4?start=238.88 ... Is this possible too? If not, is there an easy way to intercept requests?

**Comment by friday** [comment]
Sounds like you were looking for HTML5 media fragments. Hope you found it. https://www.sitepoint.com/html5-video-fragments-captions-dynamic-thumbnails/
