### ISSUE TITLE
Can't load video on ipad [Youtube]

### ISSUE THREAD

**Issue by cokol5** [sampotts/plyr#677]
- Issue observed on https://plyr.io

- Browser: Google Chrome last

Players affected:
- YouTube

https://plyr.io at Youtube video tab, on iPad Pro 9.7 when clicking on Play button, player can't load the video and start playing it.

**Comment by electroheadfx** [comment]
how it works on Safari ?

**Comment by cokol5** [comment]
on Safari the same problem

**Comment by sampotts** [comment]
I can't seem to replicate this on v3 so assuming it's fixed? Feel free to re-open if that's not the case 👍
