### ISSUE TITLE
Plyr is not working properly with vimeo on mobile phones

### ISSUE THREAD

**Issue by mittalyashu** [sampotts/plyr#679]
When we click the play button on a video from the mobile phone it opens the Vimeo video link in new tab and the video plays with full screen.

Why it doesn't play in the plyr itself when we hit the play button.

**Comment by sampotts** [comment]
It's a limitation of the Vimeo API unfortunately. There's no support for `playsinline`. YouTube supports it but is coming soon to Plyr once I finish it.
