### ISSUE TITLE
Time Selection Will Not Work

### ISSUE THREAD

**Issue by mbrahimi617** [sampotts/plyr#680]
So I'm trying to create a `<video>` which is loaded from my Django backend. The video is definitely loaded properly as it begins to play starting from the beginning as expected. However when I try to skip to certain location on the video's timeline, the range selection will drop back to the very start of the video. Any ideas?

**Comment by friday** [comment]
You need to provide more details or we won't be able to help you (as instructed in the issue template). Create a codepen/jsfiddle or something with the latest Plyr version and minimal code to reproduce your problem and I will try to help you.

I'm closing the issue, but you are welcome to comment further here or ask at [our slack](https://bit.ly/plyr-chat)
