### ISSUE TITLE
Removing border on edge of video

### ISSUE THREAD

**Issue by mayeaux** [sampotts/plyr#683]
What's going on here? I can't figure out how to remove this black border from my videos, no matter what I do with the CSS it doesn't seem to fix it

**Comment by mayeaux** [comment]
![screen shot 2017-10-11 at 4 59 28 pm](https://user-images.githubusercontent.com/7200471/31472795-a62fe688-aea5-11e7-9d03-e07401fb84f9.png)
![screen shot 2017-10-11 at 4 59 14 pm](https://user-images.githubusercontent.com/7200471/31472797-a6651e34-aea5-11e7-9b0e-15bbd80794a9.png)

As you can see, there's some kind of border on the edge of the video, which makes my controls stick out further than they should and looks tacky, how can I fix this? No amount of fiddling seems to work

**Comment by sampotts** [comment]
Where can I see the code? Likely some other CSS causing issues. I'm working blind though currently...

**Comment by mayeaux** [comment]
https://pew.tube/user/EisAugen/Ywo0a4H

^ Here's the video in question

**Comment by mayeaux** [comment]
It looks like the actual video is not taking up the full video element

**Comment by sampotts** [comment]
Remove the inline styles on the `<video>` element. That's what's causing your issues.

**Comment by mayeaux** [comment]
Awesome thanks a lot, couldn't quite get it
