### ISSUE TITLE
destroy method not working as expected

### ISSUE THREAD

**Issue by casjonker** [sampotts/plyr#684]
### Expected behaviour 
Would expect plyr instances to be destroyed after calling `instances.forEach(function(instance) { instance.destroy(); }`

### Actual behaviour
Unforunately the js instances are still there, the method only destroys the DOM elements. Because of the instance still existing, the entire plyr DOM elements can still be found as detached elements in the memory.

### Environment
- Browser: Chrome
- Version: latest  
- Operating System: Windows
- Version: latest 

Players affected:
- [x] HTML5 Video
- [x] HTML5 Audio
- [x] YouTube
- [x] Vimeo

### Steps to reproduce 
Instantiate player(s), call `destroy()` method on it and then try and access the instance. For example call the `play()` method on it. Even though the initial DOM elements are destroyed, you're still able to play the audio file...

### Relevant links
https://github.com/sampotts/plyr/issues/77

**Comment by ashkanhosseini** [comment]
@sampotts it seems that this issue is with plyr.container not getting garbage collected. I've created [a PR](https://github.com/sampotts/plyr/pull/700) for this, could you please assign someone for review and get it merged if it's fine? We really need this as well for our project.

Thanks.
