### ISSUE TITLE
Strange artifact in IE11/Edge

### ISSUE THREAD

**Issue by DMShamonov** [sampotts/plyr#686]
In IE11 and Edge I have strange artifact [http://prntscr.com/gwraox](http://prntscr.com/gwraox)

**Comment by ThreadPitt** [comment]
I have the same, plus the methods like seek().. don't seem to work

**Comment by sampotts** [comment]
This will be resolved in v3

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
