### ISSUE TITLE
Event 'setup' not triggered

### ISSUE THREAD

**Issue by mizmiz** [sampotts/plyr#689]
### Steps to reproduce 
instance.on('setup', function(event) {
  console.log(event.detail.plyr);
});

**Comment by AlfaTrion36** [comment]
Yeah, I'm having the same issue on the timeupdate event.

**Comment by sampotts** [comment]
This will be removed in favour of just a `ready` event in v3

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
