### ISSUE TITLE
Plyr is breaking my video grid

### ISSUE THREAD

**Issue by DennisAdelmann** [sampotts/plyr#690]
Hey Guys,
I have a Vimeo video on my project page which runs without problems with PLYR. On the homepage I have inline HTML 5 videos, which are looping videos (gif like behaviour).For this I am using this plugin: https://github.com/wottpal/kirby-video . But as soon as I initialize the plyr plugin, my grid breaks on the homepage and the inline videos won't play anymore (this only happens to the videos on the homepage).  I'm using kirby as a cms. 

Does someone has an idea what causes this problem? 

I appreciate any help :) 

- Browser: Chrome  
- Version:  61.0.3163.100
- Operating System: macOS High Sierre
- Version: 10.13

Players affected:
- [X ] Vimeo
- [ X] HTML 5 Video Tag

**Comment by jonnitto** [comment]
Hi there, we have now a [Slack channel](https://join.slack.com/t/plyr-chat/shared_invite/enQtMjYxNDUxMzk4MDIwLThkYWMzMTkxYjk3ODU2M2QzMDY3ZGU4YzI3Y2I3OGIyMGRkNTEyNjNkZGY5MmQyNzI4Yzc3NjRiMGUxYmQ4OTk). As this is more a question, I would recommend going there…

**Comment by sampotts** [comment]
Can you try this again in v3? I have a feeling this should be resolved but if not, feel free to re-open 👍
