### ISSUE TITLE
Multiple PLYRs on same page

### ISSUE THREAD

**Issue by huglester** [sampotts/plyr#691]
Hello,

so for example I init all video fields like so:
players = plyr.setup('.players');

I can access video using: players[0], players[1]

but maybe there is a way to 'name' players or similar?
<div data-custom-slug="video1" data-type="youtube" data-video-id="6rReMbO42uE"></div>
<div data-custom-slug="uniqKey" data-type="youtube" data-video-id="6rReMzzzz2uE"></div>
and later access video like: players['video1'], players['uniqKey'] ? 

Thanks

**Comment by friday** [comment]
You could call plyr.setup() multiple times with different selectors and store in different variables, or call getMedia() to get the element from a plyr instance (and use that to get the classname or id).

**Comment by jonnitto** [comment]
We have now a [Slack channel](https://join.slack.com/t/plyr-chat/shared_invite/enQtMjYxNDUxMzk4MDIwLThkYWMzMTkxYjk3ODU2M2QzMDY3ZGU4YzI3Y2I3OGIyMGRkNTEyNjNkZGY5MmQyNzI4Yzc3NjRiMGUxYmQ4OTk)
