### ISSUE TITLE
Create a platform for questions

### ISSUE THREAD

**Issue by jonnitto** [sampotts/plyr#692]
I see that many issues are more questions than issues. Perhaps it would be better to create a platform for that. In our community, we use [slack](https://slack.com) and [discourse](https://www.discourse.org)  
Like that, @sampotts don't have to clean up all the issues all the time.  

What do you think about this?

**Comment by sampotts** [comment]
Good idea. I've created a slack... 

https://join.slack.com/t/plyr-chat/shared_invite/enQtMjYxNDUxMzk4MDIwLThkYWMzMTkxYjk3ODU2M2QzMDY3ZGU4YzI3Y2I3OGIyMGRkNTEyNjNkZGY5MmQyNzI4Yzc3NjRiMGUxYmQ4OTk

**Comment by sampotts** [comment]
Good idea. I've created a slack...

https://join.slack.com/t/plyr-chat/shared_invite/enQtMjYxNDUxMzk4MDIwLThkYWMzMTkxYjk3ODU2M2QzMDY3ZGU4YzI3Y2I3OGIyMGRkNTEyNjNkZGY5MmQyNzI4Yzc3NjRiMGUxYmQ4OTk

**Comment by jonnitto** [comment]
Great,
