### ISSUE TITLE
Input - Plyr is adding classes to input (around input)

### ISSUE THREAD

**Issue by apsolut** [sampotts/plyr#702]
- [true] Issue does not already exist
- [false] Issue observed on https://plyr.io

### Expected behaviour 
plyr should only add class to video etc. elements
### Actual behaviour
plyr (classes: plyr plyr--input plyr--is-touch) are added to every ```input``` element
```<div tabindex="0" class="plyr plyr--input plyr--is-touch">```
### Environment

- Browser: Chrome. FF. Vivaldi, Opera.. All
- Version:  All
- Operating System: Win10
- Version: Latest

Players affected:
- [true ] HTML5 Forms (font Avenir...etc style is applied)

### Steps to reproduce 
Add input filed in HTML... Plyr will add wrapper ```<div tabindex="0" class="plyr plyr--input">```

```<input placeholder="Name*" required="" type="text" data-field="f1" class=" form-control" id="f1_1" name="f1" value="" data-type="text" aria-required="true" aria-labelledby="f1Label">``` 

### Relevant links
https://codepen.io/apsolut/pen/WXvGMx

**Comment by sampotts** [comment]
I'm going to be changing all the data attribute namespacing in v3 so everything is under `data-plyr-x` so this won't be an issue any longer.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
