### ISSUE TITLE
Any plans to support aspect ratios different from 16:9?

### ISSUE THREAD

**Issue by yuriykuzin** [sampotts/plyr#707]
Hi! 
Do you plan to support other aspect ratios, like 4:3?

See example - a screenshot with original vimeo video (below) and truncated representation in plyr (above).

Thanks!

![screen shot 2017-11-06 at 12 17 05 pm](https://user-images.githubusercontent.com/1729556/32436421-b5a6fa6a-c2ec-11e7-9e35-7c960bd39746.png)

**Comment by sampotts** [comment]
Hey - funny you should mention this. It's coming in v3 - which is getting closer every day. I've been spending more and more time on it. 

For Vimeo it will be automatic as they expose API methods that mean I can grab the video dimensions and then calculate the ratio to set the frame and inner container to. YouTube I *think* forces 16:9 but I've added a config option anyway so this can be used if preferred. 

I'll let you know when this is ready for testing.

**Comment by yuriykuzin** [comment]
Sounds great! Thank you @sampotts!

One question, how are you grabbing original video dimensions for vimeo?

**Comment by sampotts** [comment]
Using their API methods...

![image](https://user-images.githubusercontent.com/719092/32438973-b68755b6-c340-11e7-8eb5-ed9487fbcbbc.png)

**Comment by yuriykuzin** [comment]
cool, thank you!

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
