### ISSUE TITLE
Option to disable autopause functionality for Vimeo.

### ISSUE THREAD

**Issue by voxellotl** [sampotts/plyr#708]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
Option in config to disable Vimeo's 'autopause' functionality. Autopause is on by default, while disabling autopause would make it possible to view multiple Vimeo video's simultaneously.

### Actual behaviour
Autopause option is not set in Vimeo configuration and thus only one video plays at a time.

### Environment

- Browser: not relevant
- Version: not relevant
- Operating System: not relevant
- Version: 2.0.17

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [x] Vimeo

### Steps to reproduce 
- Create two Vimeo video's
- Play one
- Play the other, the first one stops

### Relevant links
An example of what autopause is can be seen here (not using plyr): http://tube.merkulov.design/autopause.html

**Comment by bleepsandblops** [comment]
If that helps, I get around it with:

`var vimeoplayers = plyr.setup();
  vimeoplayers.forEach(function (player) {
    player.on('ready', function (e) {
      player.getEmbed().setAutopause(false);
    }) 
  })`

**Comment by sampotts** [comment]
This is in place in v3 which will be released soon.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
