### ISSUE TITLE
plyr, youtube links do not work

### ISSUE THREAD

**Issue by spencer237** [sampotts/plyr#711]
# Hi guys, I hope you're fine ...
I have a problem with the PLYR html reader, I installed it via Bower on my xampp server. at the beginning it worked very well but after the youtube links no longer worked and the reader remains frozen. 

Thank you for your help.

**Comment by sweethoneycode** [comment]
@spencer237 see issue here: https://github.com/sampotts/plyr/issues/709

**Comment by spencer237** [comment]
@sweethoneycode thanks

**Comment by sampotts** [comment]
Fixed in #709

**Comment by spencer237** [comment]
#709 problem solved using this method 

[https://github.com/sampotts/plyr/blob/master/src/js/plyr.js#L1771](https://github.com/sampotts/plyr/blob/master/src/js/plyr.js#L1771)
