### ISSUE TITLE
Vimeo Videos not loading plyr theme on Ipad

### ISSUE THREAD

**Issue by diegopego86** [sampotts/plyr#715]
- [x] Issue observed on https://plyr.io

### Expected behaviour 
Plyr to show the play button and options bar with its styles.

### Actual behaviour
Showing default Vimeo iFrame

### Environment
Tested it on:
- Browser: Safari / Chrome
- Version:  Safari: 9.0 / Chrome 62.0.3202
- Operating System: iOS 
- Version: 9.3.5 and 11.1

Players affected:

- [x ] Vimeo

### Steps to reproduce 
- Load the plyr.io site on any iPad and then click on the Vimeo link.

### Relevant links
https://plyr.io

**Comment by spencer237** [comment]
#709 use this methode
https://github.com/sampotts/plyr/blob/master/src/js/plyr.js#L1771

**Comment by sampotts** [comment]
I'll look into this.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
