### ISSUE TITLE
Video controls do not appear if you tap after the video starts playing

### ISSUE THREAD

**Issue by davethomasthewendysguy** [sampotts/plyr#720]
- [X] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
Video controls should show when you tap on the video in iPad.

### Actual behaviour
Controls show then hide when you tap.

### Environment
Was able to reproduce in ios10 but not ios9

- Browser: Safari
- Version: 
- Operating System: ios10
- Version: 10.1.1

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [X] YouTube
- [ ] Vimeo

### Steps to reproduce 
- Load up a page with a video initialized in Plyr and click play.

Not sure if it affects other videos but it does affect embedded Youtube videos.

**Comment by cobbweb** [comment]
Adding `playsinline` to your video _might_ help for iOS 10, but it doesn't seem to help iOS 11. Can replicate this on https://plyr.io/ with iPad Pro + iOS 11.2.5

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by cobbweb** [comment]
Yep, fixed on the new website running v3. Thanks :+1:
