### ISSUE TITLE
Allow passing existing embed <iframe> to constructor

### ISSUE THREAD

**Issue by vibhi19** [sampotts/plyr#722]
Hi Thanks for awesome Player 

Can You provide code for player automatically works on video embedded through YouTube Iframe on post

**Comment by jonnitto** [comment]
Hi @vibhi19 
We have now a [Slack channel](https://join.slack.com/t/plyr-chat/shared_invite/enQtMjYxNDUxMzk4MDIwLThkYWMzMTkxYjk3ODU2M2QzMDY3ZGU4YzI3Y2I3OGIyMGRkNTEyNjNkZGY5MmQyNzI4Yzc3NjRiMGUxYmQ4OTk). As this is more a question, I would recommend going there…

**Comment by sampotts** [comment]
I think what @vibhi19 is referring to is setting up Plyr on an already loaded embed `<iframe>`. It's something I've considered doing but won't be part of v3. I like it though as it's true progressive enhancement as the HTML5 player is.

**Comment by vibhi19** [comment]
Yes im referring to is setting up Plyr on an already loaded embed <iframe>

**Comment by vibhi19** [comment]
HEY i have a lot of video in WordPress embed through iframe can You Provide code which Will convert those iframe to Support player i really want to use this player

**Comment by sampotts** [comment]
Did you read my comment?

**Comment by vibhi19** [comment]
Hi Wordpress Plugin work But i create problem In mobile devices so Im Thinking you can provide some code like This i have one but its not working  here

`  // Iframe and find Autoplay
    $YTiframe = '/<iframe.*?(width="[0-9]*")?\.?(height="[0-9]*")?\.*?src=".*?youtube\.com\/embed\/(\w*\-?\w*).(autoplay=1)?.*?<\/iframe>/i';
    
    $YTreplace = '<div data-type="youtube" data-video-id="$3">';
    
    $content = preg_replace(
        $YTiframe, $YTreplace, $content
    `);``

**Comment by vibhi19** [comment]
can You take a look and Tell me why its not working 

```
  // Iframe and find Autoplay
    $YTiframe = '/<iframe.*?(width="[0-9]*")?\.?(height="[0-9]*")?\.*?src=".*?youtube\.com\/embed\/(\w*\-?\w*).(autoplay=1)?.*?<\/iframe>/i';
    
    $YTreplace = '<div data-type="youtube" data-video-id="$3">';
    
    $content = preg_replace(
        $YTiframe, $YTreplace, $content
    );
```

**Comment by sampotts** [comment]
I'll update once it's supported 👍

**Comment by vibhi19** [comment]
What You mean

**Comment by vibhi19** [comment]
I Tried but its not working for me

**Comment by sampotts** [comment]
Are you reading my comments or just brushing over them. 

# It's not supported yet - as in it doesn't work yet

# I will be adding it soon

# I will update this issue when it works (no firm date) 

Hope that clears it up for you

**Comment by vibhi19** [comment]
bro I read It i totally understand that you update this in next update but right now but if You can Help me Replace youtube iframe with Plyr plater That will be Helpful  Any code which can do that please
Im using wordpress

**Comment by sampotts** [comment]
You could try the WordPress plugin as listed in the docs

**Comment by vibhi19** [comment]
I did but its Play button doesnt work in Mobile device You have click on full screen then click on play

**Comment by sampotts** [comment]
That's a limitation of iOS

**Comment by vibhi19** [comment]
No im talking about android Phone i dont use ios

**Comment by vibhi19** [comment]
and if i use Script then the play button work pefectly

**Comment by vibhi19** [comment]
Well thanks for Your Time What i can do Waiting for Update

**Comment by sampotts** [comment]
I'll keep this issue open as a reference until I've added support.

**Comment by vibhi19** [comment]
Ok

**Comment by vibhi19** [comment]
Issue Solved Updated The css and Js Files in Plugin and Boom hehehe 

https://drive.google.com/open?id=16-X-79UIjzusZ1lM5vBH5Tgp7dLWO7wy

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
