### ISSUE TITLE
Question on Ads

### ISSUE THREAD

**Issue by OrtegaMichael** [sampotts/plyr#727]
Hello,

I didn't notice anything (could have missed it) about putting ads on the video. Looking to do something similar to what youtube does with preroll ads and / or running ads during the video be it a break or overlaying. Is there currently a way to do this with this player?

Thank you.

**Comment by sampotts** [comment]
Not currently but it is in development for release early next year. Will support VAST and VPAID through a recommended ad network.

**Comment by sampotts** [comment]
This is coming in v3:
https://github.com/sampotts/plyr/issues/766

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by mxmzb** [comment]
Isn't putting own ads on videos against the terms of YouTube?

**Comment by OrtegaMichael** [comment]
@mxmzb I think you are confused. I am not looking to take a YouTube video and put my own ads on it. I am putting ads on my own videos. YouTube is an example of what I am looking to do.

**Comment by sampotts** [comment]
I'm really not sure what they can do. You're showing an advert, then you're showing a YouTube embedded video - on your own website. I'm sure they'd like to cream off the top but legally I'm not sure they'd have a leg to stand on.
