### ISSUE TITLE
Cannot set property 'src' of null

### ISSUE THREAD

**Issue by musichopper** [sampotts/plyr#729]
### Environment 

- Browser:chrome
- Version:  Version 62.0.3202.94 (Official Build) (64-bit)
- Operating System: win7
- Version: ?

Players affected:
- [x ] HTML5 Video

### Steps to reproduce .... well here is code that is causing it.
function my own function(){
player[0].source({
  sources: [{
      src:    'https://www.website.com/videos/video.mp4',
      type:   'video/mp4'
  },],
});
}

//this below later on in body......
<script>
var plyr_options = {
	    disableContextMenu : true,
			clickToPlay: true,
			controls: ['mute','progress','play']
	    };

var player =  plyr.setup(plyr_options);</script>

----------------------------------
It seems that it works on the first run through, then when it runs my function another time, the error comes up. It is like it can't see your player[0] any more after I change the source in my function. 

Maybe I am over tired but I can't seem to see what is causing this odd behavior to occur.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
