### ISSUE TITLE
Video PLAY icon appears even if i set controls to an empty array

### ISSUE THREAD

**Issue by HectorLS** [sampotts/plyr#730]
in iOS the play video icon appears even if you pass the `controls: []` as an empty array

### Expected behaviour 
No icon

### Actual behaviour
Icon appears 😢 

### Environment
- Browser: Safari
- iPhone 5 y iPhone 6
- Operating System: iOS
- Plyr version: 2.0.18

Players affected:
- [ ] HTML5 Video

### Steps to reproduce 
- Check in mobile a Plyr video with no controls passed in the array

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
