### ISSUE TITLE
Wowza Live Streaming Support

### ISSUE THREAD

**Issue by csyasar** [sampotts/plyr#731]
hello;
i want to use plyr.io player for wowza live streaming. is that possible? 
(i want to play on web and mobile web)

**Comment by friday** [comment]
Plyr supports HTML5 video, which can be used for both streaming and embedding a single file depending on the source element(s) or attribute being a video file or streaming manifest.

I don't see why it wouldn't work with wowza as long as you can get the manifest from wowza. If they're hosting the player that might not be the case.

**Comment by friday** [comment]
See https://github.com/sampotts/plyr#streaming for using Plyr with streaming. The examples are outdated but it's pretty easy to update them for Plyr v3.
