### ISSUE TITLE
Issues with large play button and fullscreen option

### ISSUE THREAD

**Issue by eabigelow** [sampotts/plyr#734]
Thank you for any help on this!

- [x ] Issue does not already exist (not to my knowledge)
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
when fullscreen is toggled false, expected behavior would have a play button appear? It does not. 
### Actual behaviour
When fullscreen is toggled false, no controls appear at all. 
### Environment

- Browser: chrome
- Version:  
- Operating System: mac
- Version: 

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
-

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍

**Comment by dm-grinko** [comment]
If you are using angular 9.1.0 you should update it to the latest version. 9.1.4 in my case.

```
"@angular/animations": "~9.1.4",
"@angular/common": "~9.1.4",
"@angular/compiler": "~9.1.4",
"@angular/core": "~9.1.4",
"@angular/forms": "~9.1.4",
"@angular/platform-browser": "~9.1.4",
"@angular/platform-browser-dynamic": "~9.1.4",
"@angular/router": "~9.1.4"
```
Hope it helps someone
