### ISSUE TITLE
Play Button not working for Vimeo on devices

### ISSUE THREAD

**Issue by squareblok** [sampotts/plyr#735]
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
Play button should cause Video to play / pause

### Actual behaviour
Nothing happens when hitting play button on devices

### Environment

- Browser: Safari & Chrome
- Version:  
- Operating System: iOS
- Version: 10.1.1

Players affected:
- [ ] Vimeo

**Comment by chasegiunta** [comment]
Can’t reproduce this iOS 11.1.2 ... maybe a OS specific issue?

**Comment by sampotts** [comment]
Could you check out v3 and see if this is still an issue:
https://github.com/sampotts/plyr/issues/766

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
