### ISSUE TITLE
the player dosent work on other mp4 file

### ISSUE THREAD

**Issue by ayulayol** [sampotts/plyr#737]
the player dosent work on other mp4 file
http://streamableorigin.b-cdn.net/video/mp4/fp0rw.mp4

**Comment by jonnitto** [comment]
Hi @ayulayol 
This file doesn't work on Safari, but on Chrome it will work. This has nothing to do with the Plyr, it is more an issue from the file itself…

**Comment by vibhi19** [comment]
using streamable cdn url is not a good idea it may work for few day 
but if they update their Way to get link Then all your videos will be dead better to use their iframe

**Comment by friday** [comment]
The CDN didn't allow the resource to be embedded (no CORS header), but I think the poster just fixed this.

Nothing to do with plyr.
