### ISSUE TITLE
Unable to run the app in Android (Audio) option after the screen is locked

### ISSUE THREAD

**Issue by positivepause** [sampotts/plyr#738]
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
We would like the RADIO to be played using this app. As per the developer it is not possible today once the screen is locked ( Auto locked) but end user ..the player stops working. Can we get some type of option to keep playing and show the menu on Top of Android locked screen the play option?

### Actual behaviour
It stops.

### Environment
Android Lolipop - LG phone
- Browser:
- Version:  
- Operating System:
- Version: 

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
-

**Comment by friday** [comment]
This doesn't seem like an issue with plyr, but an issue with your phone or phones in general and how they handle video playback.

There used to be a special youtube app just to listen to yt while the screen was off, but it stopped working after a while.

Please complete the bug report by checking the checkboxes that applies. See https://help.github.com/articles/about-task-lists/#creating-task-lists for how
