### ISSUE TITLE
Redirect after play?

### ISSUE THREAD

**Issue by pedro-rivera** [sampotts/plyr#739]
Hey people. It's actually a question that I have. I need to redirect the page after the entire video is played.

Tried to compare getCurrentTime() and getDuration(), but didn't get too far.

Any ideas?

**Comment by sampotts** [comment]
You probably want to listen to the `ended` event

**Comment by pedro-rivera** [comment]
Sorry for the lack of response, Sam. Totally worked, it's a shame the project pivoted so we coudn't use Plyr :(
