### ISSUE TITLE
Can't click to pause?

### ISSUE THREAD

**Issue by YLaido** [sampotts/plyr#741]
- [ ] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 
I can click on the area above controls to pause the video.
### Actual behaviour
I failed to click to pause except clicking on the pause button. I remember that it used to be available few months ago. And I don't know if I am the only one who met this problem.
### Environment

- Browser: Chrome and Firefox
- Version:  63.0.3239.84
- Operating System: Windows 10 
- Version: x64

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
- https://plyr.io

### Relevant links

Thank you.

**Comment by omitech** [comment]
that't a known bug https://github.com/sampotts/plyr/issues/718
