### ISSUE TITLE
when will support playlist and quality switching?

### ISSUE THREAD

**Issue by argb** [sampotts/plyr#742]
when will support playlist and quality switching?
This is an awesome project, but I saw the last updating time is 2 months ago, will this project be maintained for a long time?

**Comment by sampotts** [comment]
Please see original issues - v3 is coming soon. I have a personal life as well as maintaining Plyr 👍 

For any discussion, use the Slack channel rather than GitHub issues: 
http://bit.ly/plyr-slack

**Comment by argb** [comment]
@sampotts Thank you, it's really a beautiful player, just hope it better :D

**Comment by sampotts** [comment]
v3 is a massive re-write and is way better

**Comment by argb** [comment]
https://github.com/Bilibili/flv.js/ 
this project is nice, it is used to play flv file instead of flash, it extract data from rtmp and feed it to video player, based on MSE, it seems did sth like hls.js, maybe you can think about supporting it. 
rtmp has much lower delay than hls. :D
