### ISSUE TITLE
Is it possible to defer youtube on load?

### ISSUE THREAD

**Issue by iamrobert** [sampotts/plyr#744]
Hi,

When running gtmetrix tests - youtube falls under the Render blocking javascript.

![Page Speed](https://i.imgur.com/Ac6fQBt.png)

Is there away to implement a defer method with plyr.io? 
https://varvy.com/pagespeed/defer-videos.html

![Page Speed](https://i.imgur.com/EqDjcch.png)

The code I'm using is:
`<div data-type="youtube" data-video-id="bTqVqk7FSmY" class="js-player"></div>`

Thanks

**Comment by vibhi19** [comment]
ya when this player add supports to lazy loading for youtube 
if you can add lazy load somehow than its possible

**Comment by vibhi19** [comment]
and the link you add for lazy load video that only works with iframe not with this player

**Comment by sampotts** [comment]
It's not something that needs to be added to plyr. You can handle deferring the load in your own JS however you like - either by loading the script to initialise the player with the `defer` attribute or just call setup on the `load` event on `window` or `DOMContentLoaded` on the document. 

Neither will make a huge difference to performance though.

**Comment by vibhi19** [comment]
@sampotts

can you show any example? 

tried this doesn't work 

<script>
function init() {
var vidDefer = document.getElementsByTagName('iframe');
for (var i=0; i<vidDefer.length; i++) {
if(vidDefer[i].getAttribute('data-src')) {
vidDefer[i].setAttribute('src',vidDefer[i].getAttribute('data-src'));
} } }
window.onload = init;
</script>

**Comment by iamrobert** [comment]
Here's my attempt for youtube:

https://codepen.io/iamrobert/pen/GRWOYNJ

It pulls the image and title from youtube, and only loads plyr on click. You'll need to add a button over the image that loads.

**Comment by kaquna** [comment]
> Here's my attempt for youtube:
> 
> https://codepen.io/iamrobert/pen/GRWOYNJ
> 
> It pulls the image and title from youtube, and only loads plyr on click. You'll need to add a button over the image that loads.

hi all

if youtube id starts with a number, it gets this error:
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '.player-videos[data-plyr-embed-id=8xxxxxxxxxx]' is not a valid selector.

this line...
var plyr = '.js-player[data-plyr-embed-id=' + plyr + ']';

best in this way:
var plyr = '.js-player[data-plyr-embed-id="' + plyr + '"]';

**Comment by kaquna** [comment]
> Here's my attempt for youtube:
> 
> https://codepen.io/iamrobert/pen/GRWOYNJ
> 
> It pulls the image and title from youtube, and only loads plyr on click. You'll need to add a button over the image that loads.

and I think, the section STOP other players can be simplified with
`document.querySelectorAll('.plyr__control--overlaid.plyr__control--pressed').click();`
