### ISSUE TITLE
No option for repeat videos

### ISSUE THREAD

**Issue by ishanjm** [sampotts/plyr#748]
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Environment

- Browser:
- Version:  
- Operating System:
- Version: 

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
-

**Comment by sampotts** [comment]
Duplicate of https://github.com/sampotts/plyr/issues/632 - have a search before raising issues 👍
