### ISSUE TITLE
YouTube-update(?) causes unwanted items visible

### ISSUE THREAD

**Issue by jseubring** [sampotts/plyr#749]
- [X ] Issue does not already exist
- [X ] Issue observed on https://plyr.io

### Expected behaviour 
The plyr.io-player hides all YouTube buttons, items, branding

### Actual behaviour
A title, profile picture, the view count, react count, and buttons show up underneath.

### Environment

- Browser: Safari
- Version:  11.0.2
- Operating System: MacOS X
- Version: 10.13.12

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [X ] YouTube
- [ ] Vimeo

### Steps to reproduce 
- 

### Relevant links

**Comment by sampotts** [comment]
I can't seem to replicate this on https://plyr.io - do you have a screenshot?

**Comment by jseubring** [comment]
Yes --> https://ibb.co/j4mYPw

**Comment by sampotts** [comment]
I can't replicate this still

**Comment by michaelGregoire** [comment]
A variant of this is also happening for me. YouTube center play button and logo show beneath plyr controls.

**Environment**

    Browsers: Firefox Developer Edition (v59.0b5), Safari (v11.0), Chrome (v63.0.3239.132)
    Operating System: MacOS X
    Version: 10.11.6

**Node/Webpack Based JS Setup:**
```
import Plyr from 'plyr';
window.Plyr = Plyr;
const player = new Plyr('#home-plyr');

player.source = {
  type: 'video',
  sources: [
    {
      src: 'cjgsNc6qlHE',
      provider: 'youtube'
    }
  ],
  poster: '/img/home-video-poster.jpg'
};
```

**Relevant HTML:**
`<video id="home-plyr"></video>`

** Screenshot **
<img width="596" alt="screen shot 2018-01-31 at 6 18 40 am" src="https://user-images.githubusercontent.com/1930152/35620277-ada9cb26-064e-11e8-94c3-3434e2b43381.png">

**Comment by sampotts** [comment]
Unavoidable unfortunately. There are no options that hide the logo or play button. It might be worth raising your concerns with YouTube directly but I don’t fancy your chances. I raised a bug with them about issues with duration returned by their API and they just closed it even after admitting it was an issue. We’re just using their API/SDK as-is.

**Comment by michaelGregoire** [comment]
Yeah, after I posted this I noticed that the issue exists on your website, too. Tried the YouTube api independently and saw that there's no way to avoid it. Thanks.
