### ISSUE TITLE
Fullscreen mode ios

### ISSUE THREAD

**Issue by mvdb31** [sampotts/plyr#751]
Hello Sam,

thanks to your job.

Is it possible to unforce fullscreen video on iphone ios 11.2.1 ?
On mobile android, the video start play without fullscreen mode 

### Environment

- Browser: safari/chrome
- Version:  
- Operating System: ios
- Version: 11.2.1

Players affected:
- [x] HTML5 Video

**Comment by friday** [comment]
Are you sure it isn't IOS/Safari doing that? Have you tried to disable plyr (just use html5 video)?

**Comment by friday** [comment]
https://9to5mac.com/2016/06/15/ios-10-inline-video-playback-safari/

**Comment by mvdb31** [comment]
Thanks you for the answer,
the solution is html5 video tag => playsinline

**Comment by sampotts** [comment]
I've not added full support for this in Plyr yet but v3 has it which will be in beta very soon
