### ISSUE TITLE
AMP - This plugin is not working on AMP Page

### ISSUE THREAD

**Issue by shahidmaqbool** [sampotts/plyr#753]
Plugin is amazing is there any way to add support for AMP pages for this plugin. I am having an issue on my AMP pages i am unable to show youtube videos. I have a wordpress website, and i am using wordpress plugin that auto convert all youtube video interface, but then i open amp it remove all youtube videos as well. If we dont have AMP support is there anything we can do like to keep interface changes on desktop but also keep youtube video on amp pages.

- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Environment

- Browser:
- Version:  
- Operating System:
- Version: 

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [x] YouTube
- [ ] Vimeo

### Steps to reproduce 
-

**Comment by vibhi19** [comment]
Just tried working for mehttp://xvid.ihostfull.com/test/amp/

**Comment by vibhi19** [comment]
it's working but it can also create some validation error in amp

**Comment by vibhi19** [comment]
To Make Your Video Appear in amp There is way 

Use Plyr. io Plugin it Support normal youtube links 

you need to use YouTube link 

So In main Site You can use plyr.io Player but as you using normal links It will also load in amp too as WordPress supports oembed by default but it will load youtube player not Plyr.io in amp page

**Comment by shahidmaqbool** [comment]
First thing when we add PLYR.IO plugin it support perfect on desktop version and convert all youtube likes in to amazing player but on amp pages it dont show any thing

**Comment by vibhi19** [comment]
@shahidmaqbool add Plyr Js and Css file In amp version it will Start working but it will create problems Maybe Not sure with amp validation

**Comment by shahidmaqbool** [comment]
@vibhi19 if i as js it will cause issue in validation so is there any way to stop its plugin to hide youtube iframe on amp

**Comment by vibhi19** [comment]
@shahidmaqbool well im not sure it will create problems with amp validation but it can create problems because amp has very limitations 
Please Add Js And css file in amp 
Css In head and js in Body 
and Check Your site in Amp validation tool

**Comment by vibhi19** [comment]
and i if you using Plyr plugin in wordpress than only use A YouTube Link instead of div

 here some pic [url=https://imgdrive.com/v/jEZotwZ][img]https://i.imgdrive.com/jEZotwZ.png[/img][/url]
[url=https://imgdrive.com/v/2sDAb3F][img]https://i.imgdrive.com/2sDAb3F.png[/img][/url]
[url=https://imgdrive.com/v/vj1FE6v][img]https://i.imgdrive.com/vj1FE6v.png[/img][/url]

**Comment by sampotts** [comment]
Can you try again with the v3 update?
