### ISSUE TITLE
Add beta version to npm

### ISSUE THREAD

**Issue by jimblue** [sampotts/plyr#756]
Hi,

To start testing the beta version could you add it to npm?

Would be happy to give some feedback.

BTW thank you so mutch, Plyr is fantastic 😄  !

**Comment by sampotts** [comment]
Hey, it's there as `3.0.0-beta.6` currently. I'll update as fixes come in. Please prefix any bug fixes you find with [v3] in the title so it's easy for me to manage.

**Comment by jimblue** [comment]
All right about V3 prefix and thanks again! Cheers

**Comment by sampotts** [comment]
Cool. Closing this one for now 👍
