### ISSUE TITLE
vimeo video not rendeing in windows 7 safari browser.

### ISSUE THREAD

**Issue by sateesh-fishead** [sampotts/plyr#757]
- [x] Issue observed on https://plyr.io

### Expected behaviour 
video should render with custom options
### Actual behaviour
Video not rendering in safari browser
### Environment

- Browser:Safari
- Version:  5.1.7
- Operating System: windows 7 64bit
- Version: 

Players affected:
- [x] Vimeo

### Steps to reproduce 
-

**Comment by sigfriedseldeslachts** [comment]
Browser is outdated and Safari on Windows is not being updated. You should consider updating to Google Chrome, Firefox, Edge, Opera, ....

**Comment by sampotts** [comment]
Yep. Unsupported browser (by anyone these days).
