### ISSUE TITLE
Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by kieusonlam** [sampotts/plyr#759]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
Player auto or have a function to reload resource if got this error.

### Environment

- Browser: Chrome
- Plyr version:  2.0.18
- Operating System: Windows 10

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
Sometime I got this error.

![image](https://user-images.githubusercontent.com/13093313/34903114-147b2f70-f85d-11e7-8245-f61fa34d6726.png)
the video hosting response a bit slow I quest and I have to refresh the webpage to get player to work.

Is there any solution for this one? Like a player reload function.

**Comment by sampotts** [comment]
This is a network error on your side. Plyr is merely an abstraction/wrapper for the native HTML5 player so isn't the cause of this.

**Comment by alexmanrique** [comment]
@kieusonlam did you fix this error? was a network problem? I get this error in Google Chrome but not in Firefox when I visit a website (the issue is not related with plyr but I found this conversation while searching in google) thanks

**Comment by kieusonlam** [comment]
@alexmanrique no, I didnt find anyway to fix it. And yes only chrome have this error :(

**Comment by alexmanrique** [comment]
@kieusonlam I have asked in stackoverflow https://stackoverflow.com/questions/48598766/err-spdy-protocol-error-in-chrome-when-visiting-a-website lets see if someone has an answer to it.

**Comment by friday** [comment]
There are plenty of answers to this if you just spend a short time searching. For example: https://www.reddit.com/r/chrome/comments/3ej5ua/err_spdy_protocol_error/

**Comment by yang200258** [comment]
经常会在将代码重新上传至服务器时候出现，服务器可能是因为静态资源缓存问题吧
