### ISSUE TITLE
How to fix Unable to post message to https://www.youtube.com. Recipient has origin http://x.x.x.x

### ISSUE THREAD

**Issue by arLevi** [sampotts/plyr#762]
- [X] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Actual behavior
The issue is happening only from an iPad emulator - as an app ( Ionic 2 app )
From the iPad's browser, If I browse the dev code via: http://x.x.x.x:$port - it's working fine
But the app itself, is throwing to the console tons of errors of:
```
Unable to post message to https://www.youtube.com. Recipient has origin http://x.x.x.x:8101.
```

### Environment
- Mobile: iPad
- Operating System: IOS 10.2

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [X] YouTube
- [ ] Vimeo

### Side note
When I didn't use plyr, I used to have the following settings in my `iframe` player:
```
playerVars = {
        playsinline: 0,
        fs:          0,
        controls:    1,
        showinfo:    0,
        rel:         0,
        enablejsapi: 1,        
        autoplay:    true,
        hl:          'he',
        origin:          "http://youtubekids.co.il",
        widget_referrer: "http://youtubekids.co.il"
    };
```

Maybe `origin` should be supported in the `plyr.interface.d.ts` or something here ?

**Comment by sampotts** [comment]
Even with origin set, the error is present. It’s a YouTube bug but good luck getting them to fix it. They just close bugs I’ve raised and say it’s intended. Like display incorrect duration. It’s not the best API/SDK.

Let me know how you go with raising it with them...

**Comment by arLevi** [comment]
I'm not sure I follow ... 

From the browser - plyr is fine.
Using YouTube's embeddable player inside an iPad app ( which is what I currently do ) - also works fine ...

It's something specific to plyr on iPad I believe - not a bug in YouTube ....

I'm just trying to move away from YouTube's embeddable player -> plyr because of the brand logo that is directing users back to the YouTube site and I can't catch that event ( https://stackoverflow.com/questions/48128015/how-can-i-detect-and-catch-the-allow-popups-event-inside-an-iframe ) ....

But reading https://github.com/sampotts/plyr/issues/764 make me believe that sooner or later the app will be rejected because I'm violating YouTube's terms of services - which is the only thing I wanted to gain here by using plyr :)

**Comment by sampotts** [comment]
No, it’s not violating the terms of service. The player had been like this for several years now. Other players do exactly the same thing too. 

With regards to the console message, people raise it all the time. At the end of the day, it’s thrown by the YouTube SDK not Plyr. It doesn’t effect playback, it just seems to needlessly worry developers. The message can be ignored. Or feel free to have a dig around and raise a PR against develop to fix it. 

Cheers,
Sam

**Comment by RScottLewis** [comment]
See this article for help:
https://www.html5rocks.com/en/tutorials/security/content-security-policy/

**Comment by berestovskiy** [comment]
I've been facing the same issue and it seems I found a workaround
Posting it here in case someone needs it:
It didn't work for me with youtube link that looks like this https://www.youtube.com/watch?v=XX-XXXXX&t=2348s
Then I tried embed link which worked like a charm: https://www.youtube.com/embed/XX-XXXXX

**Comment by dickyj** [comment]
I am seeing this problem in iOS 14.1 iPhone XR

**Comment by hermes2405** [comment]
Find a answer, from [https://medium.com/collaborne-engineering/who-blocks-my-youtube-embed-cordova-phonegap-45a8ec04ff72](url)
Put this to `<allow-navigation href="https://*youtube.com/*"/>` config.xml telling to whitelist that allow youtube navigation. But now I see and error when play the video, try again later.
