### ISSUE TITLE
Question: Is plyr safe to use?

### ISSUE THREAD

**Issue by fredlee0109** [sampotts/plyr#764]
plyr hides the iframe's native controls, and overlays its own controls on top of it. For vimeo, their terms of service says:
"2.2.4. You will not alter, remove, replace, or mask any aspect of the Vimeo Player (including the playbar, logo, and like, embed, and share features) without Vimeo’s prior written consent."
https://developer.vimeo.com/guidelines/terms

I wonder if plyr is safe to use despite it.

**Comment by sampotts** [comment]
It's up to you really. I assume no liability.

**Comment by fredlee0109** [comment]
So are you saying that terms of service violation's liability is on the developer who uses plyr?

**Comment by fredlee0109** [comment]
Same goes for youtube:

https://www.youtube.com/static?template=terms
General Use of the Service—Permissions and Restrictions

YouTube hereby grants you permission to access and use the Service as set forth in these Terms of Service, provided that:

...

If you use the Embeddable Player on your website, you may not modify, build upon, or block any portion or functionality of the Embeddable Player, including but not limited to links back to the YouTube website.

**Comment by sampotts** [comment]
Well YouTube allow you to hide controls and branding which is all we do 👍 Vimeo is the only grey area.

**Comment by sampotts** [comment]
Vimeo is your call yes. That's always going to be the case since it relates to the website using it.
