### ISSUE TITLE
Default controls don't include everything, rewind missing

### ISSUE THREAD

**Issue by martinwolf** [sampotts/plyr#765]
Hey,

the documentation states the following concerning the `controls` option:

> Toggle which control elements you would like to display when using the default controls html. If you specify a html option, this is redundant. **The default value is to display everything.**

I just noticed that the default is not everything. The `rewind` button is not shown but I can activate it by adding `rewind` to the `controls` option.

Cheers,
Martin

Players affected:
- [ ] HTML5 Video
- [x] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Relevant links
https://github.com/sampotts/plyr#options

**Comment by sampotts** [comment]
Thanks @martinwolf, this is updated in v3 which will be released shortly.

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
