### ISSUE TITLE
NPM Require Issue [v3]

### ISSUE THREAD

**Issue by ryanpilbeam** [sampotts/plyr#770]
Hi

I think there's a similar issue in the npm 3.0 beta release as mentioned in #151 

If I edit the package.json files main entry to point to dist/plyr.js I'm able to import the package fine.

**Comment by friday** [comment]
You can get around this by importing with a subdirectory in the meanwhile. ex `require('plyr/dist/plyr.js')`

**Comment by sampotts** [comment]
I think this should be fixed now. I've updated the `main` property as suggested.
