### ISSUE TITLE
[v3] Volume control is not visible when audio is played

### ISSUE THREAD

**Issue by anantajitjg** [sampotts/plyr#773]
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 
I have initialized Plyr with html5 audio element for a Wordpress theme made with Bootstrap 4. 
When I play the audio the volume control must be visible.

### Actual behaviour
Before playing the audio the control is visible. But after playing the audio the control is not visible.

**before playing**
![audio_01](https://user-images.githubusercontent.com/22009263/35568020-4814d58c-05ed-11e8-97d7-452c58f3df75.png)
**after playing**
![audio_02](https://user-images.githubusercontent.com/22009263/35568026-4fb29bda-05ed-11e8-8f07-bfe52fe1a6e5.png)

### Environment

- Browser: Firefox Quantum
- Version: 58.0
- Operating System: Ubuntu
- Version: 16.04 LTS

Players affected:
- [ ] HTML5 Video
- [x] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
- Initialize Plyr with html5 audio element
- Play the audio

### Relevant links
https://plyr.io/beta/#audio

**Comment by sampotts** [comment]
Thanks. This should be fixed in the latest version 👍
