### ISSUE TITLE
Plyr is not defined  (v3.0.0-beta.10)

### ISSUE THREAD

**Issue by ispal** [sampotts/plyr#775]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
When importing library from NPM using Webpack and `import Plyr from "plyr"`, I expect everything to work normally using examples on the site. It works if I include the script using script tag

### Actual behaviour
I get error in the console saying `ReferenceError: Plyr is not defined`.

Error comes from this code on dist version according Dev Tools

```
dispatchEvent: function(e, t, i, n) {
   if (e && t) {
       var s = new CustomEvent(t,{
                       bubbles: !!c.is.boolean(i) && i,
                       detail: Object.assign({}, n, {
                          plyr: this instanceof Plyr ? this : null
                       })
                    });
        e.dispatchEvent(s)
       }
 },

```
### Environment

- Browser: Chrome
- Version:  63.0.3239.132
- Operating System: MacOS 
- Version: High Sierra

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [x] YouTube
- [ ] Vimeo

### Steps to reproduce 

```
import Plyr from 'plyr';

const player = new Plyr('#player', {
    autoplay: true
});
player.source = {
    type: 'video',
    sources: [
      {
        src: 'bTqVqk7FSmY',
        provider: 'youtube'
      }
    ]
};
```

**Comment by sampotts** [comment]
This should be sorted in 3.0.0-beta.11

**Comment by Maqsyo** [comment]
Thanks for this fast fix!
