### ISSUE TITLE
Add vue-plyr to plugins section

### ISSUE THREAD

**Issue by redxtech** [sampotts/plyr#777]
I have just spent a bunch of time writing a VueJS plugin for plyr, and I would greatly appreciate it if you would include it in the plugins section of the README.

I have already made a PR for it at #769 so you could just merge that and it would be all fine.

Thanks very much \:)

**Comment by redxtech** [comment]
If you want to take a look at it before you add it you can find it here:
https://github.com/redxtech/vue-plyr

**Comment by redxtech** [comment]
It's also on NPM as vue-plyr
https://www.npmjs.com/package/vue-plyr

**Comment by sampotts** [comment]
Sure. Will do. Bear in mind that v3 is coming very soon (it's on NPM already) so will need to update when that goes to master?

**Comment by redxtech** [comment]
Yeah, I'll make sure to do that. The reason why I'm not on the V3 beta already was because when I used `import plyr from 'plyr` I received a message saying that plyr wasn't found, and when using it in a Vue component it told me that `setup()` was not a function.

**Comment by sampotts** [comment]
Ah that should be fixed now but `setup` has been removed in favour of a proper constructor...

**Comment by redxtech** [comment]
Ah ok.
Would you say that v3 is ready for a plugin yet? I can easily update mine to support it.
The constructor has changed from `let player = plyr.contructor(selector, options)` to `let player = new Plyr(selector, options)` right ?

**Comment by sampotts** [comment]
It's still in testing and the feedback has been a little slow really. I'll badger people about it. It's pretty close though I think. 

Yeah that's the change for the player. Previously the setup function would always return an `array` and now it returns a single instance. Also some of the config options have changed but not sure if that would effect your wrapper.

**Comment by redxtech** [comment]
Yeah, the config things shouldn't change anything at all. However, when I do `this.player = new Plyr(document.getElementById('js-player'))` I get no errors, `this.player` is set to the proper value, but the actual video/audio/etc element remains unchanged, even though the correct selector is being passe through.
