### ISSUE TITLE
plyr can not be used in xhtml

### ISSUE THREAD

**Issue by suvamkundu** [sampotts/plyr#783]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Expected behaviour 
It should work in xhtml as well.
### Actual behaviour
for xhtml it is not loading and giving hude console error.
### Environment

- Browser:all
- Version:  
- Operating System:windows
- Version: 

Players affected:
- [x] HTML5 Video
- [x] HTML5 Audio

### Steps to reproduce 
-

**Comment by sampotts** [comment]
It’s a HTML5 video player. There’s a bit of a hint in the name. Also, “huge error” means nothing to me.

**Comment by suvamkundu** [comment]
is there any hack or any other way to make it work in xhtml?

**Comment by sampotts** [comment]
Not really. It's a _HTML5_ media player. The elements only exist in _HTML5_ therefore it won't work with XHTML.

**Comment by friday** [comment]
There is a "hack". Change your doctype to `<!DOCTYPE html>` and you'd be using html5. XHTML has been dead for almost 10 years now so it's about time.

**Comment by sampotts** [comment]
^ This.

**Comment by suvamkundu** [comment]
Still not working.

**Comment by sampotts** [comment]
Worth a read:
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5
