### ISSUE TITLE
[V3] Volume Control on HLS Live Stream Not Showing, Works for MP4

### ISSUE THREAD

**Issue by thekendog** [sampotts/plyr#786]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io/beta

### Expected behaviour 
Volume controls show

### Actual behaviour
Volume controls are hidden

### Environment

- Browser: Chrome
- Version:  63
- Operating System: Windows
- Version: 10

Players affected:
- [x] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
- Using hls.js as in the referenced demo and a live stream from Wowza

### Relevant links
http://www.resortcams.com/plyr/test.php

**Comment by thekendog** [comment]
Nevermind on this.  Just tested it with a stream that has audio and it works.  I guess the new version can detect audio in a stream.  Brilliant!

**Comment by sampotts** [comment]
Phew. I thought I'd have to implement something custom for HLS for a minute. 

Yep, I added audioTrack detection for videos as an issue was raised for volume control being visible.

**Comment by thekendog** [comment]
Yup, that is an awesome feature.  The only other issue I see right now is that the pause button never displays in the control bar.  I can fix that with some javascript though.

**Comment by sampotts** [comment]
I have a fix coming for the pause button issue today. 👍

**Comment by sampotts** [comment]
Pushed - check `v3.0.0-beta.14`

**Comment by thekendog** [comment]
Yup, looks good!

**Comment by volkirik** [comment]
Hello,

Where is volume controller? I only get mute button with my audio stream..

**Comment by friday** [comment]
@volkirik Please read our guidelines https://github.com/sampotts/plyr/blob/master/CONTRIBUTING.md#reporting-issues
