### ISSUE TITLE
plyrjs not working with requirejs, It shows black screen.

### ISSUE THREAD

**Issue by Dhar114** [sampotts/plyr#788]
<link rel="stylesheet" href="../plyr/plyr.css" />

    <div data-type="vimeo" data-video-id="143418951"></div>

    
    <script src="../plyr/require.js"></script>
    <script type="text/javascript">
    	require(['../plyr/plyr.js'], function (plyr) {
        plyr.setup();
    });
    </script>

**Comment by friday** [comment]
Make sure you are using Plyr v2, or use the new syntax for plyr v3-beta #766

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
