### ISSUE TITLE
Videos not playing in IE or any browser on Ipad.

### ISSUE THREAD

**Issue by elliottcoe** [sampotts/plyr#790]
Plyr with hosted Ogg and Webm doesn't play back the video in IE or on any browser on an Ipad, we have it in a pop up modal. Here's the code, all of the source links are echoed without any issues.

Here's the code:

`<div id="video_popup">
			<div class="wrap">
				<div class="close">
					<span>+</span>
				</div>
				<video class="plyr" poster="<?php echo $hero_video_poster_url; ?>">
					<source src="<?php echo $hero_video_mp4_url; ?>" type="video/mp4">
					<?php if ($hero_video_ogg) : ?>
						<source src="<?php echo $hero_video_ogg; ?>" type="video/ogg">
					<?php endif; ?>
					<?php if ($hero_video_webm) : ?>
						<source src="<?php echo $hero_video_webm; ?>" type="video/webm">
					<?php endif; ?>
				</video> 
			</div>
		</div>`

The only thing that does work is the poster.

I have tried removing the poster and it still doesn't work, the only thing that happens is that the loading bar moves and that's it.

**Comment by friday** [comment]
If your videos aren't working with browsers that you want to support, it's your own responsibility to find out what codecs and format that does. Plyr doesn't handle any of this.

It's like blaming the pen for writing a typo.

**Comment by elliottcoe** [comment]
To add to this, I enabled debugging which just returned "[Plyr] event: waiting".

**Comment by friday** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility
