### ISSUE TITLE
captions not playing if track file is fetched from server.

### ISSUE THREAD

**Issue by suvamkundu** [sampotts/plyr#791]
- [ ] Issue does not already exist
- [ ] Issue observed on https://plyr.io

### Environment

- Browser:
- Version:  
- Operating System:
- Version: 

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
-

**Comment by sampotts** [comment]
Please be less vague

**Comment by suvamkundu** [comment]
the file which i am using for caption is stored in amazon s3 server.  so when i am putting the file path (
which looks like 'http://something.amazonaws.com/something/file_name.vtt' ) in src attribute of track tag it is not working. The video is playing but captions are not showing.

**Comment by sampotts** [comment]
That's exactly how the demo works (which works). You either have an issue with the MIME type or something else network related.
