### ISSUE TITLE
Space bar stops working after clicking on the play button with mouse

### ISSUE THREAD

**Issue by EvgenyOrekhov** [sampotts/plyr#796]
- [x] Issue does not already exist
- [x] Issue observed on https://plyr.io

### Expected behaviour 
Space bar should always work as play/pause.

### Actual behaviour
Space bar stops working after clicking on the play button with mouse.

### Environment

- Browser: Google Chrome
- Version:  64.0.3282.167 (Official Build) (64-bit)
- Operating System: Ubuntu
- Version: 17.10

Players affected:
- [x] HTML5 Video
- [x] HTML5 Audio
- [x] YouTube
- [x] Vimeo

### Steps to reproduce 
1. Go to https://plyr.io/
2. Click on the play button in the center of the video frame
3. Space bar stops working

**Comment by sampotts** [comment]
Can you try again? I think this is fixed in `v3`. Will close for now but feel free to re-open if it's still an issue 👍

**Comment by EvgenyOrekhov** [comment]
@sampotts It works on https://plyr.io now. Thanks!

**Comment by mhluska** [comment]
For me it seems to be the other way. Space bar doesn't control the video until after pressing play. I'm using `3.3.23`.

**Comment by friday** [comment]
@mhluska It's not happening when I test at https://plyr.io/, so it may be fixed (3.3.23 isn't the latest version) or related to your browser or setup. If you get this with the latest version (currently 3.4.3) please create a new bug report and follow the instructions in the template :+1:
