### ISSUE TITLE
Vimeo UI is not hidden by plyr when pause/play

### ISSUE THREAD

**Issue by electroheadfx** [sampotts/plyr#800]
http://pierrenogueras.com

- [X ] Issue NOT observed on https://plyr.io

### Expected behaviour 
Work without vimeo UI

### Actual behaviour
Vimeo UI show when I play and pause for some secondes.

### Environment
- Browser: Safari/chrome/firefox
- Version:  -
- Operating System: MacOS Sierra
- Version: 10.12.6

Players affected:
- [ ] HTML5 Video
- [ ] HTML5 Audio
- [X ] YouTube
- [X ] Vimeo

### Steps to reproduce 
Open http://pierrenogueras.com
and click on any thumbnail

**Comment by sampotts** [comment]
Can you try v3?

**Comment by electroheadfx** [comment]
hey sorry sampotts, where is the v3?

**Comment by friday** [comment]
See: https://github.com/sampotts/plyr/issues/766

**Comment by sampotts** [comment]
The beta branch or if you use NPM you can get it on there also. 

Sam

**Comment by sampotts** [comment]
Closing this one as I think it's fixed but feel free to re-open if not solved in v3 👍
