### ISSUE TITLE
Disable forward seek

### ISSUE THREAD

**Issue by kimlop** [sampotts/plyr#806]
It's possible to implement a features to disable the foward seek?
But leave the possibility to rewind the video.

Players affected:
- [X ] Vimeo

**Comment by gurupras** [comment]
Your requested feature can probably be accomplished once Issue #832 is resolved.
Here's a [pen](https://codepen.io/gurupras/pen/rdzBLK) showing how to accomplish it

**Comment by friday** [comment]
Closing since this should be working now. See @gurupras helpful comments in #755 and #832

If not, comment and I will reopen it.

**Comment by Sarmadjaved** [comment]
i just started using your player and it seems like either e.preventDefault() or return false not working  when i restrict forward seek..i am using "https://cdn.plyr.io/3.6.3/plyr.polyfilled.js", I have multiple videos of youtube, vimeo and local uploaded video on page . Using below code but the issue only producing when i forward and it does forward rejecting prevent default and return false;


const  playermodal = Plyr.setup('.gsplyr', { 
				captions: {active: true}, 
				tooltips: {controls: true},
				listeners: {
						seek: function customSeekBehavior(e) {
							playermodal.forEach(function (player) {
								
							  var current_time = _getCurrentTime(player, e);

							  var newTime = _getTargetTime(player, e);
							  
							  console.log("Current Time of" +player.config.vid_id+ "is" +current_time);
							  console.log("New Timeof" +player.config.vid_id+ "is" +newTime);
							  // We only want rewind functionality
							  // Therefore, disallow moving forward
								  if (parseFloat(newTime) > parseFloat(current_time)) {
									// Works if we add the following:
									// Object.defineProperty(event, "defaultPrevented", {
									//   value: event.defaultPrevented,
									//   writable: true
									// });
									// event.preventDefault = () => {
									//   event.defaultPrevented = true;
									// };
									player.currentTime = current_time;
									player.rewind(current_time)
									console.log('prevented');
									event.preventDefault();
									 return false;
									
									
								  }
							});
						}
					  },
			});
function _getTargetTime(plyr, input) {
		  if (
			typeof input === "object" &&
			(input.type === "input" || input.type === "change")
		  ) {			  
			return input.target.value / input.target.max * plyr.duration;
		  } else {
			// We're assuming its a number
			return Number(input);
		  }
		}

		function _getCurrentTime(plyr, input) {
			console.log("Curent Time" +plyr.currentTime);
		  return plyr.currentTime;
		}

**Comment by Sarmadjaved** [comment]
@friday @gurupras !!can anyone please help me here?

**Comment by Sulaimon-Abiola** [comment]
@Sarmadjaved `.plyr__progress > input` is the input responsible for seeking, you can get the value in the seek listeners and that will represent the seeked time from user, `player.currentTime` will give the current time of the player, below is what my code looks like 

`listeners: {
                seek: function (e) {
                    e.preventDefault(); // required on v2
                    // Your code here
                    let seekedTime = ($('.plyr__progress > input').val() * vdadConvertToMinSec(player.duration)) / 100;
                    let theCurrentTime = vdadConvertToMinSec(player.currentTime) * 1;
                    
                    if (seekedTime < theCurrentTime) return true;
                    
                    return false;   // required on v3
                }
            }`

**Comment by gurupras** [comment]
My pen still works with the latest versions of plyr.
If you want to stop seek, call `e.preventDefault()` and return `false`.
If you want to only stop forward seeks, conditionally call `e.preventDefault()` and return `false`.

**Comment by if-songmi** [comment]
Hello! Thank you for your code ^^

After show alert, currentTime is change.
if u have the same problem as me, Please refer to the code below.

`// get seek of moving forward in progress bar
function _getTargetTime(plyr, input) {
  if (typeof input === "object" && (input.type === "input" || input.type === "change")) {
    return input.target.value / input.target.max * plyr.duration;
  } else {
    return Number(input);
  }
}

const player = new Plyr('#player', {
  controls: ['play', 'progress', 'current-time', 'mute', 'volume', 'fullscreen'],
  invertTime: false,
  keyboard: {
    focused: false,
    global: false
  },
  listeners: {
    // disallow moving forward
    seek: function customSeekBehavior(e) {
      const current_time = player.currentTime;
      const newTime = _getTargetTime(player, e);
      if (parseFloat(newTime) > current_time) {
        e.preventDefault();
        alert('Disallow moving forward!');
        player.currentTime = current_time; // Fix wrong currentTime
        return false;
      }
    }
  }
});`

Life is short, the code is long.
Have a peaceful day!

**Comment by kotasudhakar** [comment]
This is all that is need for this to work

`const plyr = new Plyr("#player", {
  controls: [
    'progress'
  ],
  listeners: {
    seek (e) {
      e.preventDefault();
      console.log(`prevented`);
      return false;
    }
  }
})`
