### ISSUE TITLE
instance.on('progress') not working

### ISSUE THREAD

**Issue by CinKon** [sampotts/plyr#809]
- [x] Issue does not already exist
- [ ] Issue observed on https://plyr.io

I need to get the progress of an audio-instance for a custom radial progress-bar.

### Expected behaviour 
The Event `playerInstance.on('progress', (event) => { console.log(event) })` should be fired every XX seconds while playing a media-file.

### Actual behaviour
Event is fired only 2 times.

### Environment

- Browser: Chrome
- Version: 65
- Operating System: macOS
- Version: 10.13.3

Players affected:
- [ ] HTML5 Video
- [x] HTML5 Audio
- [ ] YouTube
- [ ] Vimeo

### Steps to reproduce 
- See codepen

### Relevant links
https://codepen.io/CinKon/pen/mxEQPJ

**Comment by CinKon** [comment]
Also I'd prefer a `getCurrentProgress` method :)

**Comment by friday** [comment]
You probably meant to use timeupdate https://developer.mozilla.org/en-US/docs/Web/Events/timeupdate

Also, adding event listeners with a generic event listener method such as `on` is pretty much the gold standard of event listening, and a lot more efficient than your suggestion.

**Comment by CinKon** [comment]
Yeah, that's how i do it now. But since plyr offered this event in the docs, i thought it might be a good idea to use this in the first place ;)

**Comment by sampotts** [comment]
Events like `progress` are merely re-dispatched and set to bubble (media events don't by default) so if it fires twice, that's because it's only fired twice on the underlying media element. Are you on a fast connection or have the file cached? The spec says:

> While the load is not suspended (see below), every 350ms (±200ms) or for every byte received, whichever is least frequent, queue a task to fire a simple event named progress at the element.

Anyway, you should try v3 as it's way better than v2. I'm about to merge to master but you can grab it from the beta branch or npm. 

I can add a progress getter on the instance which I guess would return between 0 and 1 (for percentage).

**Comment by CinKon** [comment]
OK, should've read the description more accurate... My bad

**Comment by friday** [comment]
It happens to the best of us!

**Comment by Spongman** [comment]
i read this wrong the first time, too.

> progress...  Sent periodically to inform...

was enough to confuse me.

**Comment by sampotts** [comment]
> was enough to confuse me.

It's literally "borrowed" from:
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Media_events
