### ISSUE TITLE
Plyr.css not working in v3

### ISSUE THREAD

**Issue by majamee** [sampotts/plyr#810]
### Expected behaviour
Include post.css to apply theme.

### Actual behaviour
Theme is not getting applied. Fallback to browser default. In the shown demo on plyr.io the post.css is also not used at all, but instead the demo.css

### Environment

- Browser:
- Version:
- Operating System:
- Version:

### Steps to reproduce
-

**Comment by friday** [comment]
It's because it's failing to initialize (javascript). Please read the Plyr 3 documentation for how to use Plyr 3. The api has changed.

If the javascript works but not the css the result would look very broken and not at all browser default.

**Comment by sampotts** [comment]
As above, read the docs

**Comment by majamee** [comment]
thank you, fixed it
