### ISSUE TITLE
Controls documentation

### ISSUE THREAD

**Issue by koyin** [sampotts/plyr#812]
I am customizing my player layout in v2 using the html option, but it seem the documentation is still in v2 that I cant apply on v3. Will there be a full html example with all controls for v3?

**Comment by sampotts** [comment]
Yep, sorry I need to do this. Will get it updated ASAP.

**Comment by jamesgillispie** [comment]
How does one hide controls?

**Comment by tocsinDE** [comment]
@jamesgillispie `toggleControls` could be helpful for you: https://github.com/sampotts/plyr#methods

**Comment by 1057641912** [comment]
@tocsinDE Do you how to use the toggleControls()?

**Comment by sampotts** [comment]
Just pushed an update to the docs. Let me know if it's not clear 👍
