### ISSUE TITLE
provider getAvailablePlaybackRates

### ISSUE THREAD

**Issue by Feverqwe** [sampotts/plyr#817]
getAvailablePlaybackRates response array of number, here is check for object

https://github.com/sampotts/plyr/blob/bb7eea27e513bf33dd4a4d846b3234b37a5be48d/dist/plyr.js#L3429

**Comment by sampotts** [comment]
Nice find 👍 Will get that fixed up

**Comment by sampotts** [comment]
Pushed a fix for this
