### ISSUE TITLE
Stop not working

### ISSUE THREAD

**Issue by Antonio-Laguna** [sampotts/plyr#819]
### Expected behaviour

`stop()` method should work in all browsers.

### Actual behaviour

`stop()` method not working on Chrome.

### Environment

- Browser: Chrome
- Version: 64
- Operating System: macOs
- Version: 10.13.3

### Steps to reproduce
- Go to the demo. Play the video and in the terminal write `window.player.stop();` 
Video will restart.

Only happens in Chrome AFAIK

**Comment by sampotts** [comment]
Pushed a fix - will release a new version shortly 👍
