### ISSUE TITLE
[V3] [3.0.2] IE11 throws InvalidStateError and video is not played

### ISSUE THREAD

**Issue by MBWebTechMariusz** [sampotts/plyr#823]
### Expected behaviour
- IE11 should play the video

### Actual behaviour
- IE11 doesn't play it

### Environment

- Browser: IE11
- Version: Latest
- Operating System: Win
- Version: 8.1

### Steps to reproduce
See:
![image](https://user-images.githubusercontent.com/37508162/37669295-c55cb2ae-2c66-11e8-9b4a-1a4d8db3d6e6.png)

### Proposed fix:
```
if(this.media.currentTime.toFixed(4) !== targetTime.toFixed(4)) {
// Set
                this.media.currentTime = targetTime.toFixed(4);

                // Logging
                this.debug.log('Seeking to ' + this.currentTime + ' seconds');
}
```

**Comment by MBWebTechMariusz** [comment]
Hi @friday , 
on https://plyr.io/, I think it has something to do with YouTube/Vimeo Videos, because I can't change to them in IE11; it throws the same error, so I am assuming that it is the same problem, but I am not sure.

I'm a little bit concerned about pull requests from my site, as I am unsure if my fix is really working for all the different browsers and scenarios, so I'm raiseing the issue here. But I can create the pull requests nevertheless, you are right :)

**Comment by friday** [comment]
You don't have to think of PR's as definite, but more of a dialogue. @sampotts and contributors can review and comment, and you can address feedback by pushing new commits to your branch or rebase it. In addition, having those commits in the repo means _you_ are credited for _your_ work (boosting your github profile is useful for job applications for example).

If you decide to do PR's, try to change as little as possible (like your comments), and don't include the gulp build.

Thanks either way! :)

**Comment by friday** [comment]
@MBWebTechMariusz. Could you check if this still happens? I think Sam fixed it in https://github.com/sampotts/plyr/commit/05b8e8a6e0ed260801a4fe21f10656e86a47f8fd (v3.0.3).

**Comment by MBWebTechMariusz** [comment]
Unfortunately no, because in IE11 you can't set the this.media.currentTime to the same time. It needs an if before that:
`if(this.media.currentTime.toFixed(4) !== targetTime.toFixed(4)) {`

**Comment by friday** [comment]
Alright. Thanks for the quick update!

**Comment by sampotts** [comment]
OK will make the change and wait longingly for IE11 to fade away into the past.

**Comment by friday** [comment]
Are you sure though? I just using the demo with Ie11/Win10 (`player.currentTime = player.currentTime`) and this didn't throw any error.

**Comment by sampotts** [comment]
Yeah they really dropped the ball there. I'll take a look

**Comment by MBWebTechMariusz** [comment]
@friday you are right, It seem's to play now - I get another error in IE11, but the video plays. So I think this is fixed for now.

**Comment by friday** [comment]
Yeah, I'm getting a couple of non-critical errors in IE11 as well.
