### ISSUE TITLE
[V3] [3.0.2] Vimeo shows controls in fullscreen on mobile when height > 2xwidth

### ISSUE THREAD

**Issue by MBWebTechMariusz** [sampotts/plyr#826]
![image](https://user-images.githubusercontent.com/37508162/37684992-2b165598-2c92-11e8-8937-4eb064116715.png)

Newer devices have a high height and the vimeo-fix with the 200% solution does not work anymore.

Let's increase it to 300% :)
```
// Set aspect ratio
        // For Vimeo we have an extra 300% height <div> to hide the standard controls and UI
        setAspectRatio: function setAspectRatio(input) {
            var ratio = utils.is.string(input) ? input.split(':') : this.config.ratio.split(':');
            var padding = 100 / ratio[0] * ratio[1];
            var height = 300; <- Update
            var offset = (height - padding) / (height / 50);
            this.elements.wrapper.style.paddingBottom = padding + '%';
            this.media.style.transform = 'translateY(-' + offset + '%)';
        },
```

```
.plyr__video-embed {
    // Default to 16:9 ratio but this is set by JavaScript based on config
    $padding: ((100 / 16) * 9);
    $height: 300; <- Update
    $offset: to-percentage(($height - $padding) / ($height / 50));
```

After this changes, it looks good again:
![image](https://user-images.githubusercontent.com/37508162/37685098-7f907a04-2c92-11e8-985f-58bd1e965fee.png)

**Comment by sampotts** [comment]
I'm not sure what can be done about this. I settled on 200% as otherwise the Vimeo captions start appearing in the video and I'm not sure how to turn off their rendering. 

![image](https://user-images.githubusercontent.com/719092/37714245-2a38fbae-2d6d-11e8-87ae-bbf9c62c3866.png)

**Comment by sampotts** [comment]
Will try 240 and see if that helps with your screen size?
