### ISSUE TITLE
toFixed always response string, currentTime change type

### ISSUE THREAD

**Issue by Feverqwe** [sampotts/plyr#828]
currentTime defined as number.
https://github.com/sampotts/plyr/blob/7132eccf50c6f84a3fc06fae6f43e3f1951c91b4/dist/plyr.js#L5807
Here it replace to string. It can cause strange behavior.
https://github.com/sampotts/plyr/blob/7132eccf50c6f84a3fc06fae6f43e3f1951c91b4/dist/plyr.js#L7098
For example:
Youtube player require number in player.seekTo(number) but get string.
https://github.com/sampotts/plyr/blob/7132eccf50c6f84a3fc06fae6f43e3f1951c91b4/dist/plyr.js#L5526
Here work fine, but only because force change type "return Number(this.media.currentTime);"
https://github.com/sampotts/plyr/blob/7132eccf50c6f84a3fc06fae6f43e3f1951c91b4/dist/plyr.js#L6668

**Comment by sampotts** [comment]
Can you reference the source (`/src`) files? It's a little easier than the built (`/dist`) files.

**Comment by sampotts** [comment]
I think we can remove the `.toFixed()` completely?

**Comment by Feverqwe** [comment]
> Can you reference the source (/src) files
Ok
> I think we can remove the .toFixed() completely?
I don't know reason, why it was added. Maybe.

**Comment by tocsinDE** [comment]
The relevant line in `/src` is this one: https://github.com/sampotts/plyr/blob/5db73b13276bf50357cc98896421318de66ab042/src/js/plyr.js#L424
