### ISSUE TITLE
seek() method not existing in v3

### ISSUE THREAD

**Issue by nikola3244** [sampotts/plyr#829]
### Expected behaviour
`instance.seek(1)` seeking to first second (`stop()`, `play()`, are working correctly)

### Actual behaviour
>Uncaught TypeError: instance.seek is not a function
    at HTMLDivElement.<anonymous> (plyr_sm.js?ver=2.12.3:18)
    at Plyr.dispatchEvent (utils.js:610)
    at HTMLAudioElement.<anonymous> (listeners.js:373)
    at Plyr.dispatchEvent (utils.js:610)
    at ui.js:87

### Environment

- Browser: Chromium
- Version: 65.0.3325.146 (Developer Build) (64-bit)
- Operating System: Arch Linux
- Version: 4.15.8-1-ARCH

### Steps to reproduce
1. Call `seek()` on player instance

----
I assume that the function should be located [somewhere around here](https://github.com/sampotts/plyr/blob/b77756da04c2dbb3d665cc26724dfe455c5fc068/dist/plyr.js#L6702), but it doesn't exist.

**Comment by tocsinDE** [comment]
`currentTime` is a getter you could use: https://github.com/sampotts/plyr#getters-and-setters

**Comment by nikola3244** [comment]
Yup, my mistake - I didn't see it, thanks! :+1:
