### ISSUE TITLE
method: forward

### ISSUE THREAD

**Issue by suryaiiit** [sampotts/plyr#830]
Hi,
I'm trying to update from 2.0.18 to 3.0.3.

In 2.0.18 to move the Video to the last viewed point (in seconds) we use seek().
In 3.0.3 I think we should use forward(seekTime), but it doesn't look like it is working.

Here is the codepen: https://codepen.io/suryaiiit/pen/yKXxro

Please let me know if I'm doing something wrong.
Thanks.

**Comment by gurupras** [comment]
If you issue `player.forward(20)` once you start playing the video, it works as expected. Are you trying to start playing the video from 20 seconds in?

**Comment by suryaiiit** [comment]
Yes, the video should start playing from 20 seconds.

**Comment by gurupras** [comment]
It works as expected. The problem is that you're not waiting for `ready` before trying to `forward`

Try the following:
```
const player = new Plyr('#player');
player.on('ready', () => {
  console.log('currentTime:', player.currentTime);
  player.forward(20);  // This seems to trigger play as well
  console.log('forward currentTime:', player.currentTime);
})
```

**Comment by suryaiiit** [comment]
ah... thank you so much. I dint realise that :-(
