### ISSUE TITLE
Stop playback bug

### ISSUE THREAD

**Issue by Feverqwe** [sampotts/plyr#831]
When need stop, it starts play. 

https://github.com/sampotts/plyr/blob/3d2ba8c00942075ae387a09ab5aade1f680142c7/src/js/plyr.js#L383

**Comment by sampotts** [comment]
Which browser? The issue template helps me to work out these things. That's why I created it (and you deleted it 🤔)

**Comment by Feverqwe** [comment]
I think that this bug is simple. Sorry. I use electron, use player inside React component. I call plyr.destroy when unmount component. But sound continue play. I rollback changes and it again works fine. 
```js
     stop() {
-        this.restart();
-        this.pause();
+        if (this.isHTML5) {
+            this.media.load();
+        } else {
+            this.media.stop();
+        }
     }
```

**Comment by Feverqwe** [comment]
I don't know it right call .load when need stop playing, but I fixed my problem. Sorry again.

**Comment by sampotts** [comment]
All good 👍
