### ISSUE TITLE
preventDefault() does not work in listeners

### ISSUE THREAD

**Issue by gurupras** [sampotts/plyr#832]
### Expected behaviour
`event.preventDefault()` is expected to prevent default `plyr` handlers from executing.

### Actual behaviour
On Chrome, console throws up an error message stating:  
`Unable to preventDefault inside passive event listener invocation.`

On Firefox, it seems to have successfully executed `preventDefault()`, but `defaultPrevented` is still `false` which causes the default handler to execute.

### Environment
- Browser: Chrome/Firefox
- Version:
  - Chrome: 65.0.3325.181
  - Firefox: 59.0.1
- Operating System: Windows 10
- Version: Build 1703

### Steps to reproduce
Here's a [pen](https://codepen.io/gurupras/pen/rdzBLK)

**Comment by thexeos** [comment]
If we want to support `event.preventDefault()` no matter what, we can patch the event object before passing it to customHandler (only if such handler is present). For example with the following code:

    Object.defineProperty(event, 'defaultPrevented', {
        value: event.defaultPrevented,
        writable: true
    });
    event.preventDefault = () => {
        event.defaultPrevented = true;
    };

However, the better solution would be to have the custom handler return `false` to prevent the default handler from running.

**Comment by gurupras** [comment]
Cool! Your solution definitely works.
IIRC, the way plyr [sets up handlers](https://github.com/sampotts/plyr/blob/3d2ba8c00942075ae387a09ab5aade1f680142c7/src/js/listeners.js#L383-L395) doesn't lend itself to having `return false` work. 

```
        const proxy = (event, handlerKey, defaultHandler) => {
            const customHandler = this.player.config.listeners[handlerKey];


            // Execute custom handler
            if (utils.is.function(customHandler)) {
                customHandler.call(this.player, event);
            }


            // Only call default handler if not prevented in custom handler
            if (!event.defaultPrevented && utils.is.function(defaultHandler)) {
                defaultHandler.call(this.player, event);
            }
        };
```

**Comment by sampotts** [comment]
Found a fix and will push asap 👍

**Comment by cloudratha** [comment]
Please do push ASAP :)

**Comment by sampotts** [comment]
Can you guys give `v3.0.4` a go? I've put a fix in there

**Comment by gurupras** [comment]
Doesn't seem to be working for [me](https://codepen.io/gurupras/pen/rdzBLK).

**Comment by sampotts** [comment]
OK try `v3.0.6` but instead of event.preventDefault() you'll need to `return false`. I tried to get to event.preventDefault() working but failed. I will leave that for another day as it's late. I'll keep looking though.

**Comment by gurupras** [comment]
Works perfectly 👍

**Comment by cloudratha** [comment]
Yay! Works for me too :P

**Comment by drsmall** [comment]
I'm still running into issues with this using the latest version 3.5.2

`function initPlayer(){
    Player = new Plyr('#player',{
        autoplay: true,
        controls: ['play-large', 'play', 'current-time', 'progress', 'duration', 'mute', 'volume','fullscreen']
    });

    Player.on('timeupdate', handleTimeUpdate);

    Player.on('ended', handleVideoEnd);

    Player.on('seeking', handleSeek);
}

function handleSeek(event){

    event.preventDefault();

    return false;
}`

When I try to scrub, I get the error saying "**Unable to preventDefault inside passive event listener invocation.**"

**Comment by drsmall** [comment]
Ok it seems that "prevent default" and "return false' only work when initialized as part of the plyr object. Adding a listener with Player.on() doesn't seem to support preventdefault/return false.
