### ISSUE TITLE
[V3] [3.0.3] requestFullScreen is not a function

### ISSUE THREAD

**Issue by thexeos** [sampotts/plyr#834]
Clicking the "fullscreen" button causes `Uncaught TypeError: this.target.requestFullScreen is not a function`. It happens on the [demo page](https://plyr.io/) and on other sites.

![image](https://user-images.githubusercontent.com/2260539/37868539-22a3db9a-2fa0-11e8-9c00-d5c74c8a9eb8.png)

Extracting `this.target` using Chrome debugger, and then calling `requestFullScreen` works.

OS: Windows 10
Browser: Chrome 65.0.3325.181

**Comment by thexeos** [comment]
I was able to get the fullscreen button working by passing `listeners.fullscreen` click handler that calls the Fullscreen API. But since the listener is added as `passive`, calling `event.preventDefault()` has no effect, and the error still occurs.

**Comment by sampotts** [comment]
This should be fixed in `v3.0.5`

**Comment by thexeos** [comment]
Wanted to follow up on this one. The player goes into fullscreen perfectly, however on Chrome, it does not leave the fullscreen.

![image](https://user-images.githubusercontent.com/2260539/37972857-275d07a0-31d1-11e8-91ef-07d169c213a8.png)

Chrome only has `webkitCancelFullScreen` and [`exitFullscreen`](https://developer.mozilla.org/en-US/docs/Web/API/Document/exitFullscreen):
![image](https://user-images.githubusercontent.com/2260539/37973058-9158835a-31d1-11e8-80c6-19194689589c.png)
