### ISSUE TITLE
[V3] Cannot get iFrame to load with YouTube

### ISSUE THREAD

**Issue by sparkktv** [sampotts/plyr#835]
This is the code I'm using on my site for V3
`<script>const player = new Plyr('#player', {
controls:["play-large","play","progress","current-time","mute","volume","captions","settings","fullscreen","pip","airplay"],tooltips:{controls:!0},quailty:{ default: 'default', options: ['hd2160', 'hd1440', 'hd1080', 'hd720', 'large', 'medium', 'small', 'tiny', 'default'] }
});</script>`

For some reason I cannot get the iframe method to load with Youtube. The non-iframe method loads with no issues...

**Comment by sampotts** [comment]
What's your markup for the iframe?

**Comment by sparkktv** [comment]
`<div class="plyr__video-embed" id="player">
<iframe src="https://www.youtube.com/embed/4sx2ssZLpAk"></iframe>
</div>`

Nothing appears at all when I use that code.I ended up redoing all our pages with the non-iframe method which works but I opened another ticket for the Vi ads because that code makes everything disappear also...

**Comment by sampotts** [comment]
Did you read the docs at all? Might be a start 👍 

https://github.com/sampotts/plyr#youtube-embed

```html
<div class="plyr__video-embed" id="player">
    <iframe src="https://player.vimeo.com/video/76979871?loop=false&amp;byline=false&amp;portrait=false&amp;title=false&amp;speed=true&amp;transparent=0&amp;gesture=media" allowfullscreen allowtransparency allow="autoplay"></iframe>
</div>
```
