### ISSUE TITLE
onPlay event does not fire.

### ISSUE THREAD

**Issue by suvamkundu** [sampotts/plyr#836]
### Environment

- Browser:
- Version:
- Operating System:
- Version:

### Steps to reproduce
-

**Comment by sampotts** [comment]
You'll be waiting a long time for an event that doesn't exist. Read the docs 👍

**Comment by bitcloudTheFirst** [comment]
Is there any way to be clearer on this?

**Comment by sampotts** [comment]
Read the docs. It’s not hard 👍

**Comment by bitcloudTheFirst** [comment]
Anyone reading this who wants an answer: 

This appears to be the code that triggers when the media starts playing. 

```
player.on('playing', event => {
    const instance = event.detail.plyr;
});
```


I did this via: 
`vid.onplaying = function() `

Also "The docs" are here:
https://github.com/sampotts/plyr/blob/master/readme.md

Hope this is helpful. It wasn't hard. +1
