### ISSUE TITLE
Vimeo doesn't autoplay in Safari Desktop

### ISSUE THREAD

**Issue by ThatGuySam** [sampotts/plyr#844]
Thank you for you hard work on this tool. It's been indispensable to my project, however, I'm running into an autoplay issue for Vimeo embeds in Safari

### Expected behaviour
When you set _autoplay: true_ in the options argument for a Vimeo embed the video starts on page load. 

### Actual behaviour
In Safari: Doesn't autoplay
In Firefox: Autoplays but with circle play button in front
In Chrome: Works as expected

It does, however, still play when you fire the .play() method

### Environment
Tested with Plyr 3.0.7

- Browser: Safari
- Version: 11.0.3
- Operating System: macOS High Sierra
- Version: 10.13.3

### Steps to reproduce
-Visit this Codepen in Safari: https://codepen.io/ThatGuySam/full/eMyzgK

**Comment by friday** [comment]
This is a browser feature. Nothing Plyr can do. Disabling or muting audio make it work. For more details see https://github.com/sampotts/plyr/issues/716#issuecomment-345351316

**Comment by ThatGuySam** [comment]
Aw shoot, _muted: true_ and _volume: 0_ don't seem to work.

https://jsfiddle.net/thatguysam/zbt4b4f6/5/
(BTW I forgot to say that this is specifically Safari Desktop issue)

I can, however, do a _fake_ autoplay by just adding an event listener. 

`
player.on('ready', function () {
  player.play();
});
`

**Comment by friday** [comment]
I'm surprised your pseudo-autoplay works. This makes it not quite the same issue since it wasn't initiated by a gesture, and in turn perhaps there is something either Plyr or Vimeo could do to avoid this.

**Comment by friday** [comment]
BTW: https://economictimes.indiatimes.com/magazines/panache/google-chrome-officially-announces-to-permanently-block-audio-enabled-autoplay-videos/articleshow/63467106.cms

**Comment by ThatGuySam** [comment]
It looks like there are some exceptions to unmuted autoplay in the new policy based on what they call **Media Engagement Index** with includes several factors like, times unmuted, video size, and video length. 

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#mei

**Comment by friday** [comment]
Yeah. I'm not really a fan of MEI. It's a "but it works for me" blindspot that devs will not get, but end users wil. Also, it isn't really the issue you are having of course, but I thought you should know.

**Comment by sampotts** [comment]
Sorry yeah there are issues with the muted and volume options. Looking into it.

**Comment by sampotts** [comment]
Can you try again? I think this is fixed in `v3.0.11`

**Comment by ThatGuySam** [comment]
Thank You @sampotts!! You're a scholar and a gentleman. 

It's now working as expected in Safari Desktop and even Firefox is fixed. 

https://jsfiddle.net/thatguysam/zbt4b4f6/8/

**Comment by victor-theoption** [comment]
I add the
`player.on('ready', function () { player.play(); });`
with a timeout and then it works.

If anyone have the same problem it fix mine.
