### ISSUE TITLE
Vi Ads?

### ISSUE THREAD

**Issue by sparkktv** [sampotts/plyr#845]
I'm trying to setup the ads and anytime I put the code in anywhere, it stops my Plyr from appearing at all.
`<script>const player = new Plyr('#player', {
controls:["play-large","play","progress","current-time","mute","volume","captions","settings","fullscreen","pip","airplay"],tooltips:{controls:!0},quailty:{ default: 'default', options: ['hd2160', 'hd1440', 'hd1080', 'hd720', 'large', 'medium', 'small', 'tiny', 'default'] }
});</script>`

Here is when we try to add the ads and everything goes blank...
`<script>const player = new Plyr('#player', {
controls:["play-large","play","progress","current-time","mute","volume","captions","settings","fullscreen","pip","airplay"],ads { enabled: true, publisherId: '' },tooltips:{controls:!0},quailty:{ default: 'default', options: ['hd2160', 'hd1440', 'hd1080', 'hd720', 'large', 'medium', 'small', 'tiny', 'default'] }
});</script>`

Can someone tell me how I'm suppose to use the code or if the code is correct at all or how it should be?I know I'm putting my publisher ID between the ''

**Comment by ferdiemmen** [comment]
I need to ask but in the code that isn't working I noticed the missing colon after the ads property.

**Comment by sampotts** [comment]
You need to [sign up as a publisher with vi.ai](https://vi.ai/publisher-video-monetization/?aid=plyrio) and enter your ID but if you don't have that set it won't break anything. I think you have issues elsewhere based on your other issue.
