### ISSUE TITLE
Why does controls option can work but volume option fails?

### ISSUE THREAD

**Issue by 1057641912** [sampotts/plyr#848]
When using the Plyr, I set some options including controls and volume.
It's strange that the controls option can work but volume fails. If the my app has a question, the two options should both fail. However, only one option fails... Nobody has the question?

**Comment by sampotts** [comment]
I'm not sure what you mean?

**Comment by friday** [comment]
Closing this as the creator hasn't elaborated on the question. In case one of the option parameters passed to `new Plyr()` fails during some specific conditions, please create a new issue for this with the details to replicate it.

If you have questions or need help, ask them in [our slack](https://bit.ly/plyr-chat).
