### ISSUE TITLE
Request: add class modifier 'plyr--fullscreen-active' on fullscreen

### ISSUE THREAD

**Issue by yuriykuzin** [sampotts/plyr#849]
It would be convenient for styling purposes to have a class `plyr--fullscreen-active` on container `<div class="plyr">` when fullscreen is active. I guess, you had it on v2

In v3 currently, I see only `plyr--fullscreen-enabled` there.

**Comment by sampotts** [comment]
Yep can do this. The change in v3 was to use the native pseudo class `:fullscreen` instead but it'd be easy enough to add a class to extend that.

**Comment by sampotts** [comment]
On second thoughts, can you not use the CSS pseudo class `:fullscreen` too?

**Comment by jameshobden** [comment]
I would also be interested in this feature

**Comment by sampotts** [comment]
See my comment above ^

**Comment by sampotts** [comment]
Closing this. Please use the CSS selector above.

**Comment by yuriykuzin** [comment]
Sorry, I was away for a while and missed this thread. Solved a task in a different way, but next time will try this.

**Comment by stevelacey** [comment]
@sampotts amazingly (or not) `:fullscreen` support is still yet to make it into iOS Safari. `.plyr--fullscreen`? 🙏🏼
