### ISSUE TITLE
Audio Player autoplays in Fancybox 3

### ISSUE THREAD

**Issue by MigRozo** [sampotts/plyr#850]
### Expected behaviour
Hi, I have four plyr instances for playing diferent audios, but these start in a hidden div and are shown later in a fancybox modal. That is all good.

### Actual behaviour
The problem is that after fancybox is shown, the first instance autoplays, but I need it not to play automatically. I tried using the option "autoplay: false" but it is not working with fancybox.

Help please.
Thanks.

**Comment by friday** [comment]
You haven't provided any relevant information to help you (plyr version, media source, when and how you are initiating plyr vs fancybox). Create a minimal jsbin/codepen-example to replicate the issue, or at least I won't bother to help you.

**Comment by MigRozo** [comment]
Thank you for answer. Here I have created a JSFiddle:
https://jsfiddle.net/lsces93/aqLxwvpn/11/

These start paused and it is ok, but when you open the fancybox, the first player starts playing.

**Comment by friday** [comment]
You're not using Plyr though. You're creating a function `players` that would initiate Plyr if you executed it, but this is never done.

The actual issue might be some fancybox feature.

**Comment by MigRozo** [comment]
Sorry, I removed some parts of the script working in the JSFiddle, to keep it simple. You are right, Running the function works fine.
My local code was working with a previous version of Fancybox. Updating it to latest version solved the Problem.

Thank you so much!
