### ISSUE TITLE
Vimeo: Non-standard aspect ratio in fullscreen: adjust instead of crop

### ISSUE THREAD

**Issue by yuriykuzin** [sampotts/plyr#854]
I've noticed one more bug (or, lacking of a feature :)) with 4:3 aspect ratio:
https://codepen.io/yuriyku/pen/BrmgpQ

### Expected behaviour
I'd like to see the video adjusted, preserving aspect ratio

### Actual behaviour
In fullscreen the video is cropped. See screenshots.

![screen shot 2018-04-02 at 12 03 54 pm](https://user-images.githubusercontent.com/1729556/38190780-81dff218-366e-11e8-9f95-b995cc3ee554.png)

![screen shot 2018-04-02 at 12 08 53 pm](https://user-images.githubusercontent.com/1729556/38190819-ad13dcc4-366e-11e8-892b-a0fa29fde9be.png)

p.s. And thanks for your active support. Plyr is getting better and nicer every day :)

**Comment by sampotts** [comment]
It's been raised before. It's a tricky one though due to the responsive requirement. I'll keep looking into it though and see what I can do....

**Comment by friday** [comment]
I renamed this to clarify it's only for vimeo. Will change it back in case I got that wrong?

Also, the default behavior should probably be pad, not stretch (which is how I interpret the suggestion).

**Comment by dacostafilipe** [comment]
I have a similar scaling issue with Vimeo and Youtube videos (HTML5 is okay) when on my 21:9 screen:

![screen shot 2018-10-26 at 16 55 39](https://user-images.githubusercontent.com/922998/47574954-26b07400-d941-11e8-958c-fd518d580015.jpg)

**Comment by rklabal** [comment]
Hi, is there no temporary fix for this? I just built quite a large project on Plyr using Vimeo files and found this quite critical bug in the final testing phase. I consider it to be serious enough to throw away weeks of development and replace Plyr with another player,

**Comment by sampotts** [comment]
Hey @rklabal , could you check the latest version? I've pushed a fix which should mean that non standard aspect ratios will now be catered for in fullscreen.

**Comment by rklabal** [comment]
Hi @sampotts , I honestly didnt expect a reply, let alone an extremely fast one, but yes - it seems like the latest Plyr version works perfectly with different resolutions of Vimeo videos in fullscreen! Thank you so much for the quick fix!
