### ISSUE TITLE
How to add settings menu to custom controls?

### ISSUE THREAD

**Issue by yuriykuzin** [sampotts/plyr#855]
When I use controls declaration as described in https://github.com/sampotts/plyr/blob/master/controls.md, settings menu disappears. What is the proper way of adding it?

Thanks!

**Comment by sampotts** [comment]
It's not supported currently with passing custom HTML as outlined here:
https://github.com/sampotts/plyr/blob/master/controls.md#limitations

> Currently the settings menus are not supported with custom controls HTML

If you want to use the built-in controls, then simply add `settings` to your array for the controls option. Or omit it completely and use the defaults (which includes `settings`).

**Comment by tocsinDE** [comment]
It's not possible as stated under ["Limitations"](https://github.com/sampotts/plyr/blob/master/controls.md#limitations):

> Currently the settings menus are not supported with custom controls HTML

**Comment by westfalensgod** [comment]
Is there a way I can pass custom controls (as a string) and use the default settings control?

**Comment by cawa-93** [comment]
@sampotts, @tocsinde your links are broken

**Comment by tocsinde** [comment]
> @sampotts, @tocsinde your links are broken

https://github.com/sampotts/plyr/blob/master/CONTROLS.md#limitations
