### ISSUE TITLE
No UI embeds for ios 11.3 safari

### ISSUE THREAD

**Issue by devanflaherty** [sampotts/plyr#856]
### Expected behaviour
Progressive Youtube or Vimeo embeds show the plyr UI on mobile.

### Actual behaviour
Youtube shows their UI on mobile, vimeo has no controls what so ever.

### Environment

- Browser: Safari : Shows UI
- Version: Safari 11.0.3
- Operating System: Mac Osx
- Version: 10.13.3

- IOS 11.3: Safari: Does not show UI

### Steps to reproduce
Here is the page I'm running plyr on.
https://www.shopmoment.com/the-moment-invitational-film-festival

- I started by using Vue-Plyr. Very simply using the progressive enhanced option for plyr. It works great in desktop. Everything works as expected.

- When viewing from my iPhone X on safari the UI is no where to be seen. Youtube's play button and such are visible, but vimeo's is completely gone.

- I am running no options, just a basic plyr.

- I see that on http://plyr.io it's working correctly, not sure what setting needs to be set cause I can't get it to work for vue-plyr or just plyr.

**Comment by sampotts** [comment]
Can you raise this with vue-plyr please. I think it needs to be updated to v3. Thanks 👍

**Comment by devanflaherty** [comment]
I sure can.

But just want to leave a few notes.
I was still receiving this issue when just using plyr.

As well when using Vue plyr I added a plyr resolution in my package.json to make sure I was resolving any instance of the plyr module to the newest version.
