### ISSUE TITLE
Clicking on video does not trigger custom listeners

### ISSUE THREAD

**Issue by gurupras** [sampotts/plyr#858]
### Expected behaviour
Clicking video toggles play/pause as expected, but does not trigger functions registered via `listeners`

### Actual behaviour
Expect functions registered via `listeners` to trigger

### Environment
- Browser: Chrome/Firefox
- Version:
  - Chrome: 65.0.3325.181
  - Firefox: 59.0.1
- Operating System: Windows 10
- Version: Build 1703

### Steps to reproduce
 - Create plyr instance with a custom `play` listener
 - Click on the video to toggle play/pause
 - Observe that the custom handler you registered is not being called
Here's a [pen](https://codepen.io/gurupras/pen/OvEwyw) illustrating the problem

**Comment by gurupras** [comment]
I missed this while out of town. This issue is still present as of v3.3.21. Here's a [pen](https://codepen.io/gurupras/pen/BVbQjZ)

A slightly related issue that I will point out (while attempting to fix this) is that although the documentation lists `pause` as a valid event that we can bind an early-listener to, it seems impossible for me to get the code to trigger this in the current implementation.

**Comment by friday** [comment]
[Reduced test case](https://css-tricks.com/reduced-test-cases/):
https://codepen.io/anon/pen/ERJKmM?editors=0011

**Comment by SayGoodBey** [comment]
hi,I have a problem now. Listen for the return result of asynchronous function to judge return. For example, interact with native to get network status to decide whether to play or not. How to deal with this block?

**Comment by CyanoFresh** [comment]
also clicking on play button when video is playing triggers play event, instead of pause event

**Comment by gurupras** [comment]
Ah yes, this is because there is no `pause` event. Not sure if this change was documented (or intended).

Regardless, you handle it like this now:  

```
plyr = new Plyr(el, {
  listeners: {
    play (e) {
      if (self.plyr.playing) {
        ...
      } else {
        ...
      }
    }
  }
})

**Comment by sampotts** [comment]
Do you mean _event_ or _listener_ ?

**Comment by gurupras** [comment]
Sorry, you're right. I meant to say that there is no _listener_ for the `pause` event anymore. The `play` listener can however be multiplexed to handle pauses as shown above.

**Comment by CyanoFresh** [comment]
yep, need to use workaround for pause listener. maybe remove it from defaults.js? it's confusing now

**Comment by sampotts** [comment]
My preference would be to, you know, fix it 👍

**Comment by sampotts** [comment]
This is fixed thanks to @gurupras 👍
