### ISSUE TITLE
Bug with selecting speed rate on YouTube video

### ISSUE THREAD

**Issue by yuriykuzin** [sampotts/plyr#859]
I've recorded a video with this bug: https://youtu.be/IN5K8phnXYk

You can see it in this codepen: https://codepen.io/yuriyku/pen/eMKQdN

I see it only on youtube video, on vimeo it is okay.

- Browser: Chrome
- Version: 65.0.3325.181 (Official Build) (64-bit)
- Operating System: macOS Sierra
- Version: 10.12.6 (16G1212)

**Comment by sampotts** [comment]
This is fixed in `v3.1.0`
