### ISSUE TITLE
YouTube + Android Chrome: setting speed doesn't affect real speed

### ISSUE THREAD

**Issue by yuriykuzin** [sampotts/plyr#860]
### How to reproduce: 
1. Open demo video on Android Chrome: https://plyr.io/#youtube
2. Try to set any other speed than normal

### Environment
- Browser: Android Chrome
- Version: 65.0.3325.109
- Operating System: Android
- Version: 7.0 NRD90M

**Comment by sampotts** [comment]
Isn't this a duplicate of your other issue?

**Comment by yuriykuzin** [comment]
@sampotts Not, it is a different one. Here UI works properly and shows different selected values, but the speed remains the same.

**Comment by sampotts** [comment]
Ahh ok cool 👍 I've found the cause and both are related. Will push it to master shortly.

**Comment by sampotts** [comment]
This is fixed in `v3.1.0`
