### ISSUE TITLE
[v3] Settings menu depends on speed being enabled

### ISSUE THREAD

**Issue by friday** [sampotts/plyr#865]
If I initiate Plyr without speed in settings, the setting icon doesn't show:

```js
new Plyr(video, {settings: ['captions']});
```

This line in `setSpeedMenu` is what enables the icon, but it's only being executed from `setSpeedMenu`, requiring speed to be enabled:
https://github.com/sampotts/plyr/blob/ee79c46145578c77fbf37c93389a3c7e7a950b0c/src/js/controls.js#L728-L729

**Comment by friday** [comment]
#866 fixes this for html5, but not vimeo. Youtube presently only supports `speed` I believe, so it can't be tested.

**Comment by sampotts** [comment]
This should be resolved in `v3.2.0` but please let me know if not 👍

**Comment by friday** [comment]
Great! It does work as expected for my use case now anyway :)
