### ISSUE TITLE
No UI embeds for ios

### ISSUE THREAD

**Issue by oskarame** [sampotts/plyr#869]
### Expected behaviour

Vimeo embeds show the plyr UI on mobile during progress.

### Actual behaviour
 Vimeo videos has no controls. Impossible to pause the video and no play button on the first load.

### Environment

Browser: Safari : Shows UI
Version: Safari 11.0.3
Operating System: IOS 11.3
Version:

### Steps to reproduce
- http://morrison.fanowebconsole.com/directors.html

When viewing from my iPhone X on Safari the UI is no where to be seen. Vimeo's play button is completely gone.

I am running no options, just a basic plyr.

**Comment by oskarame** [comment]
@sampotts Yes, I'm using V3. But it's working https://plyr.io

**Comment by oskarame** [comment]
This is how I did it
`  var player = new Plyr('#player1');


      player.on('pause', event => {
          $('.directorName').removeClass("fadeOutDown");
          $('.slick-arrow').removeClass("fadeOut");
      });

      player.on('playing', event => {
        $('.directorName').addClass("fadeOutDown");
        $('.slick-arrow').addClass("fadeOut");
    
      });

      player.on('ended', event => {
        player.restart();
      });`

**Comment by sampotts** [comment]
This should be resolved in `v3.2.0` 👍
