### ISSUE TITLE
[v3] media.load() breaks hls.js

### ISSUE THREAD

**Issue by friday** [sampotts/plyr#870]
`media.load()` is used in a few places in the plyr codebase, with `stop`, or after playing the video if `showPosterOnEnd` is enabled, and also when changing the source or quality.

In effect this breaks hls.js (and possibly other streaming wrappers), since hls.js loads the video by some SourceBuffer voodoo after the element is created. For `showPosterOnEnd` and `stop` this is a problem, while if you're changing the source or quality you should be expecting to have to re-initiate hls.js.

Native hls support in Safari is unaffected.

Example:
https://codepen.io/fullkornslimpa/pen/XEParj

Let it play until it's complete (you can skip to the end), then press play again. It will fail unless you remove `showPosterOnEnd`.

(Added the [v3] tag since I haven't tested v2).

**Comment by friday** [comment]
I'm not going to attempt to fix this until it's been discussed, since I'm not clear on how to fix it or if it should be fixed at all.

One possibly strategy could be to initiate HLS.js in an event listener for the load `event` (which may also require triggering it depending on race conditions). I didn't actually test this.

**Comment by friday** [comment]
`video.src` / `video.currentSrc` is a blob URL

Ex: `"blob:https://example.com/5039ad07-9adc-471a-8e04-713331a8e350"`

There are probably other ways, but this works without having access the the hls instance, and I guess "false positives" (not using HLS) would also be cases where `media.load()` would have the same effect.

**Comment by friday** [comment]
Awaiting an official solution, this could be used as an alternate css hack for `showPosterOnEnd` without changing any Plyr code directly:

CSS
```css
.plyr__video-wrapper .poster {
  display: none;
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: black;
  background-size: contain;
}
.plyr--stopped .plyr__video-wrapper .poster {
  display: block;
}
```

Then run something like this after initiating Plyr
```js
Array.from(document.querySelectorAll('.plyr video[poster]')).forEach(video => {
  video.insertAdjacentHTML('afterend', `<div class="poster" style="background-image:url(${video.poster})"></div>`);
})
```

Plyr could use something similar imo. Perhaps toggling on/off should be strictly js though, and I guess it would be the usual issues with youtube and vimeo requiring separate solutions from html5. In addition to this, keeping the poster in sync with the poster property would require some MutationObserver work, but I think this might be overkill.

**Comment by sampotts** [comment]
I've renamed the property to `resetOnEnd` in v3.3.0 and it now applies to all media types. I've created a poster container much like @friday 's suggestion and the `poster` setter will now update both. This is also used for Vimeo and YouTube so the behaviour is consistent.

**Comment by sampotts** [comment]
I suspect .stop() could just do the same thing - pause and restart effectively. I'll make that change and see?

**Comment by sampotts** [comment]
Try v3.3.5!

**Comment by friday** [comment]
Works great!

I'll close this then :) As I remember it `media.load()` is still used in a couple of other places, but none that can be avoided like changing the source. Nothing you would try to use with hls.js anyway.
