### ISSUE TITLE
Create a mute button for multiple plyrs

### ISSUE THREAD

**Issue by cn-d** [sampotts/plyr#872]
I need help in creating a mute button that controls all the plyrs in an array. I have added a [JsFiddle](https://jsfiddle.net/LLe3hc0x/16/) for context. When the top of a plyr is between 10-100px of the top of the window it starts playing. I have one `#mute` button that should control all of the players. If `#mute` is clicked and a player is playing and is not muted, the player should be muted. And visa versa, If `#mute` is clicked and a player is playing and is muted, the player should be unmuted. It seems none of the conditions get satisfied, any help would be greatly appreciated.

```
const players = Array.from(document.querySelectorAll('.js-player'));
const wH      = window.innerHeight;
const mute    = document.querySelector('#mute');

  players.map(player => new Plyr(player, {
    controls: ['controls', 'progress'],
  }));

   mute.addEventListener('click', function() {
        players.forEach(function(player) {
            if(player.playing && !player.muted) {
                player.muted = true;
            } else if (player.playing && player.muted){
                player.muted = false;
            } else {
            	 console.log('no conditions satisfied');
            }
        });
    })

  window.addEventListener('scroll', function(e) {
    let matched = false;
    players.forEach(function(player) {
      if (matched) return;
      let distance = player.getBoundingClientRect().top;

      if (10 < distance && distance < 100) {
        player.play();
        mute.classList.add('active');
        matched = true;
      } else {
        player.pause();
        mute.classList.remove('active');
      }
    })
  });
```

**Comment by friday** [comment]
Could you try to simplify this to focus more on the issue (if any) and less on your implementation?

Also: Autoplay with audio is a bad idea. Next major Chrome version won't support it, and mobile browsers doesn't support it now.

**Comment by cn-d** [comment]
Thanks for taking the time to reply, I appreciate it, I should've been more specific. I'm sorry it's not best practice (it is what the client wants at the moment) I will relay the information about Chrome and convince them otherwise. The bit of code that I cannot get to work is click event listener for `#mute`. I cannot satisfy any of the first two conditions, this is is show in the [jsFiddle].(https://jsfiddle.net/LLe3hc0x/16/).

```
mute.addEventListener('click', function() {
        players.forEach(function(player) {
            if(player.playing && !player.muted) {
                player.muted = true;
            } else if (player.playing && player.muted){
                player.muted = false;
            } else {
            	 console.log('no conditions satisfied');
            }
        });
    })
```

**Comment by cn-d** [comment]
Thank you very much, that works.
