### ISSUE TITLE
Captions won't show unless the track(s) have a srclang attribute

### ISSUE THREAD

**Issue by FlipgridMartin** [sampotts/plyr#875]
### Expected behaviour
Closed captions show on the video if a track element with a valid source is present.

### Actual behaviour
No captions show unless a `srclang` attribute is set on the track element(s).

### Environment

- Browser: Google Chrome
- Version: 65.0.3325.181
- Operating System: macOS
- Version: 10.12.6

### Steps to reproduce
- Setup a Plyr instance with a `<track>`. Don't set the `srclang` attribute on the track element(s).

This is browser independent. The Plyr instance tries to get the current track via language matching on the tracks in the media object, so if you have one or more tracks and none of them have a srclang attribute, no captions will show. [Relevant Code](https://github.com/sampotts/plyr/blob/master/src/js/captions.js#L151)

I'm not sure that this is a bug, but the behavior changed between v2.0.18 and v3 and wasn't mentioned as a breaking change in the release notes. Just thought I'd file an issue since I worked at this for a while when upgrading.

**Comment by sampotts** [comment]
This should be resolved in `v3.2.0` 👍
