### ISSUE TITLE
Video Player without file extension doesn't get played

### ISSUE THREAD

**Issue by ZilMehta** [sampotts/plyr#884]
I have a  Video URL which consists of a video : 

https://s3.amazonaws.com/qbprod/52c28eb4f032400185acd45e78ff97e600

In the lower version, when I inserted this link in <video> source, it was getting played. However, in the new version it is not getting played. 

src = "https://s3.amazonaws.com/qbprod/52c28eb4f032400185acd45e78ff97e600" in video tag

**Comment by ZilMehta** [comment]
Example for the above mentioned issue :

<video poster="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.jpg" controls crossorigin class="js-player" id="video">
        <source src="https://s3.amazonaws.com/qbprod/52c28eb4f032400185acd45e78ff97e600" >
 </video>

**Comment by friday** [comment]
I just tested with that video, and it's working fine. Didn't need to specify any mimetype either since the server does.

Replicate the issue online using something like jsfiddle or codepen, or we won't be able to help you. Also minimize the code and remove anything unrelated to the issue when you're doing this.

**Comment by ZilMehta** [comment]
Please find the fiddle link below : 
https://jsfiddle.net/zilmehta7/oh0k3qgh/6/ 
The second video doesn't work with the above mentioned URL.

**Comment by friday** [comment]
The error is not a Plyr error and is clearly printed in the dev console.

**Comment by sampotts** [comment]
I'd say this is an issue outside of Plyr. We have no checks for file extension...

**Comment by IgorLesnevskiy** [comment]
For the future seekers. 
I got that bug on MacOS in Safari, but @sampotts was right - the problem is in Safari - https://stackoverflow.com/a/51901198/11673799
