### ISSUE TITLE
Annoying `Detach` button

### ISSUE THREAD

**Issue by Vedadiyan** [sampotts/plyr#889]
Plyr is indeed a very nice video player, but the detach button that is shown when the mouse pointer hovers over the screen is pretty annoying (at least to me as a developer) as I'd never need such functionality when playing back videos. 

I have read the info provided in the code page, but unfortunately I have not been able to find any way to remove that button, not event by overriding it using my own JQuery methods. 

What I want is simply to get it off the screen so that I can continue using this very nice player.

**Comment by friday** [comment]
I've never heard of or seen any "Detach"-button. The word "Detach" doesn't exist in the Plyr codebase. Probably some native browser feature or addon that you have installed?

**Comment by Vedadiyan** [comment]
Thanks for mentioning that, that didn't came into my mind, yes it turned out to be a feature exclusive to Opera. 

Plyr in one words is an amazing video player, nice job. 👍

**Comment by sampotts** [comment]
Not a Plyr issue. I'm not sure how we can disable that.

**Comment by friday** [comment]
For future reference, the feature is called "[video popout](https://blogs.opera.com/desktop/2016/04/opera-beta-update-video-pop/)". Opera users can disable it. Devs can't.
