### ISSUE TITLE
[Bug] vimeo throws error: "Seconds must be a positive number less than the duration"

### ISSUE THREAD

**Issue by yuriykuzin** [sampotts/plyr#891]
Vimeo's player throws error "Seconds must be a positive number less than the duration" when I drag progress cursor to the end of the range.

Happily it doesn't affect functionality.

Screen record: 
https://youtu.be/UGcTf1MSp54

### Steps to reproduce:
1. Open https://plyr.io/#vimeo
2. Open devtools console
3. Drag progress cursor to the last possible position, you'll see console error

### Environment

- Browser: Chrome 
- Version: Version 65.0.3325.181 (Official Build) (64-bit)
- Operating System: macOS High Sierra
- Version: 10.13.4 (17E199)

**Comment by friday** [comment]
Very helpful report!

This line is the issue (rounding, not flooring):
https://github.com/sampotts/plyr/blob/ffd265d0ae5fc146cb56aa1f99026fd2f98ff529/src/js/plyr.js#L449

It's happening after:
https://github.com/sampotts/plyr/blob/ffd265d0ae5fc146cb56aa1f99026fd2f98ff529/src/js/plyr.js#L444-L446

So it's really easy to fix.

I don't understand why we need `.toFixed(4)` there at all, but I guess we could move the order of these or replace `toFixed` with something that only rounds down.

**Comment by sampotts** [comment]
Yep. Sure enough if you get the duration after playback has begun, you get the correct value or close enough `61.87`.  I'll work something out.

**Comment by sampotts** [comment]
This should be resolved in the latest version - v3.2.1

**Comment by wesbos** [comment]
Oh sorry, this is an issue with Vimeo itself.I thought this was the vimeo repo! Looks like I need to manually floor the value myself - thanks
