### ISSUE TITLE
Dynamically added audio/video initializes all the players of same class again 

### ISSUE THREAD

**Issue by ZilMehta** [sampotts/plyr#892]
All the players with class "js-player" are initialized on page load. When the audio/video with same class "js-player" are added dynamically in the same page, all the previous players also gets initialized.
**Expected Behaviour :** Only the new ones should get initialized to avoid more processing. 

Fiddle Link : https://jsfiddle.net/zilmehta7/oh0k3qgh/19/

**Comment by friday** [comment]
Briefly looked at the code and think everything is working as it should. Looks like your code is initiating Plyr multiple times per element, not Plyr.
