### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by mvdb31** [sampotts/plyr#897]
Hi Sam,

i'm trying to force fullscreen on click button but it doesn't work (the play() function is ok)

var player =  document.querySelector("#story_"+id+" video");
    	    if($("#story_"+id+" video").attr("data-video-size")=='portrait'){
    	    	player.play();
    	    	player.fullscreen.enter();
    	    }else{
    	      player.play();
    	    } 

...video data-video-size="portrait" data-plyr='{ "loadSprite": false, "iconUrl": "/sites/all/libraries/plyr/plyr.svg" }' preload="none" id="player_1003"  autostartload="false" poster="https://i.vimeocdn.com/video/692849418_775x400.jpg" controls style="width:100%" playsinline webkit-playsinline...

Thanks for  #your help

**Comment by friday** [comment]
I'm not Sam, but have you tried going to [plyr.io](https://plyr.io/) and running `player.fullscreen.enter()` in your developer console? If it works (which it should), then the issue you are having is not likely with plyr.

**Comment by friday** [comment]
That workaround wouldn't only work in some browsers, and you also wouldn't get any of the controls even when it does work.
