### ISSUE TITLE
Why is property Getter playing true after I make a Player?

### ISSUE THREAD

**Issue by AlGantori** [sampotts/plyr#898]
### Expected behaviour
Right after I create an instance with new Plyr('#plyrjs')
plyr playing property should be false, unless there is a movie/media playing?

### Actual behaviour
playing is returned as true instead of false.
### Environment

Using plyr  v3.1.0

- Browser: Chrome  
- Version: v65
- Operating System: Windows 7
- Version: 7 :)

### Steps to reproduce
Here is my HTML...  I removed the default video key thinking that was causing playing to be true.
```
<!-- 20180413 -->
<div class="PlyrVideo_Container">
    <!-- v3.1.0 suggested using this div as the "progressive enhancement ???" -->
    <div class="plyr__video-embed"
        id="plyrjs">
        <iframe src="https://www.youtube.com/embed/?origin=https://plyr.io&amp;iv_load_policy=3&amp;modestbranding=1&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;enablejsapi=1"
    
            allowfullscreen
            allowtransparency
            allow="autoplay"></iframe>
    </div>
</div>
```
Here is my plyr Setup routine
![image](https://user-images.githubusercontent.com/11699920/38776208-1d5344e2-4048-11e8-8cad-60de2da35dc5.png)

Here is the output of above as seen on the Chrome console...
![image](https://user-images.githubusercontent.com/11699920/38776234-8b909004-4048-11e8-94b0-f299526f774d.png)

I also tried in my Setup() above calling .stop() or setting .source to {} but playing remains true.

How to specify the progressive Enhancements in the HTML without specifying a video at startup ??
Thank you.

**Comment by sampotts** [comment]
This should be resolved in `v3.2.0` 👍

**Comment by AlGantori** [comment]
One final point 
How can I specify the "Progressive Enhancements" in the HTML without specifying a video at startup ??
Thank you.

**Comment by friday** [comment]
> How can I specify the "Progressive Enhancements" in the HTML without specifying a video at startup 

It's the same thing, so you can't.
