### ISSUE TITLE
Work-Around Chrome disabling video playback when tab is not in focus?

### ISSUE THREAD

**Issue by joshcawthorne** [sampotts/plyr#899]
### Environment

- Browser: Google Chrome
- Version: 66 (Beta)
- Operating System: Mac OS 
- Version: 10.13.3

---

I understand that Chrome doesn't allow a video to begin if a tab isn't active, however is there a way to by-pass this by hot-swapping the playback URL and restarting the player rather than re-loading the entire play and subsequently stopping playback until the tab is given focus again.

**Comment by friday** [comment]
No. You need a user interaction to get it to start playing https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by joshcawthorne** [comment]
Just to clarify, I understand you need prior interaction to start it upon page load. Can I confirm that there's no way to continue playback with a second video _after_ a user has initiated when starting the first video, and then navigated away to another tab whilst the video plays?

**Comment by friday** [comment]
I don't see why not. I would try running setInterval from the user interaction event and listen for right evens (focus and blur on `window` I think, but not sure) to trigger pause and play.

In general I don't think this is desirable or a good idea, but your use case might warrant for it.

**Comment by joshcawthorne** [comment]
Ah, thanks for your response, however, I think I may have over-complicated my question. Essentially, I'm trying to build a music player that utilizes YouTube and a custom playlist system. At the moment I simply replace each instance of plyr on song end with a new one, and playback continues. However, if a user has tabbed out to another tab (as one does when listening to music!) the next track doesn't begin until a user returns to the tab. The track is buffered, so I know the code itself runs in the background, but it seems the Media Engagement algorithm introduced in Chrome 66 is stopping plyr from restarting itself in the background. 

I understand why this would be the case, and was simply wondering if there was a way to replace the current instance of plyr's src ID with an updated one and begin playing that video while the tab is still in the background if that makes sense? I don't believe this would be breaking any policy in Chrome, as the user has to initiate the playback on page load the first time, I just want it to continue automatically.

Thanks for the responses thus far.

**Comment by friday** [comment]
I'm closing this since you're asking about browser behavior you can simply test to find out and learn. There's nothing inherent in Plyr causing it.

**Comment by DanielKucal** [comment]
@joshcawthorne, have you figured out how to go over it?

**Comment by MarvinDrude** [comment]
@joshcawthorne @DanielKucal I would appreciate it if you could share your solutions, if any?

**Comment by Ivanca** [comment]
After reading out the code this plugin actually deletes the iframe and creates it again when you change youtube sources... which is incredibly stupid because it could just use the youtube API to change the video ID, so of course is not gonna auto-play because youtube considers this a "new" player created when the tab is out of focus. I saw the plugin looking so professional just to stumble upon this clusterfuck.

**Comment by Ivanca** [comment]
@MarvinDrude see https://github.com/sampotts/plyr/issues/1185#issuecomment-619506270

**Comment by friday** [comment]
@Ivanca That's only for YouTube
