### ISSUE TITLE
Bug with video aspect ratio

### ISSUE THREAD

**Issue by Saiuke** [sampotts/plyr#902]
Normaly, when you have a wide video, you have two black stripes covering the space not being used by the video. Usually the video plays in the middle of these two stripes.

What's happening is theres only one stripe, and the video stays not centralized in the screen.

![2018-04-17](https://user-images.githubusercontent.com/19313767/38880571-a83b1654-422b-11e8-92d2-7159d02e7448.png)

When you have a video that match the aspect ratio of the screen you have it right.

![2018-04-17 1](https://user-images.githubusercontent.com/19313767/38880730-1014bc80-422c-11e8-9953-3f2f5376a7af.png)

### Environment

- Browser: Firefox 64 bits
- Version:  59.02
- Operating System: Windows 64 bits
- Version: 10

I'm handling the player like this:

```
$(".botaoPlay").click(function () {
        var videoAtual = $(this).attr("videoAtual");;
        var videoContent = '<video controls class="telaPlayer"><source src="' + videoAtual + '" type="video/mp4"></video>';
        $(".videoContainer").html(videoContent).show();
        $(".videoPlayer").show();
        const player = new Plyr('.telaPlayer', {
            /* options */
        });
        $(".conteudoPagina").hide();
    });
```

When the user activate the "Play" button, the player is created inside a div that covers the entire viewport. Something like Netflix. If you want to check the actual files check this branch of my project >> [Player](https://github.com/Saiuke/Lambda/tree/Player).

**Comment by sampotts** [comment]
HTML5, YouTube or Vimeo? This is why I created the bug template 🙄

**Comment by sampotts** [comment]
Also, do you get this issue on https://plyr.io?

**Comment by Saiuke** [comment]
If I resize the window properly I get the usual two black stripes...

![2018-04-17 2](https://user-images.githubusercontent.com/19313767/38885267-0fa01d88-4238-11e8-925d-5980f22469e1.png)

**Comment by friday** [comment]
This is most likely an implementation (custom css) issue. Since it's not happening on plyr.io. I also haven't ever seen it happen (working with many aspect ratios). You need to put up a code playground (like jsfiddle, codepen etc) for this to be considered "replicated".

I'm closing the issue, but you can still comment. I will reopen if you do that and it turns out to be a Plyr issue.
