### ISSUE TITLE
Custom div over the video dissapear when autoplay

### ISSUE THREAD

**Issue by HectorLS** [sampotts/plyr#907]
"plyr": "^3.0.2"

Hi! one question.
i'm trying to put a div over the video ( like a play icon and title for example )
positioned aboslute and with z-index to be OVER the video.

But seems to disappear as soon as the video start the autoplay, kind of weird.
if i go to the inspector tool and touch the z-index and put the SAME value (just entering in the edit value mode) 

And the div shows again, if not is like behind.
Any idea why this is happening ? or there is a way to add these icons or text ? 

thanks in advance 🙏

**Comment by sampotts** [comment]
Not too sure - as it's not part of the core plugin functionality then you're kinda on your own, sorry.
