### ISSUE TITLE
[BUG] Attempting to change configurable attribute of unconfigurable property

### ISSUE THREAD

**Issue by kfeng0806** [sampotts/plyr#908]
This error occurred in some old webkit browser version such like Safari on IOS9.

Screenshot from browserstack:
![](https://i.imgur.com/0fI0wSB.jpg)

### Environment

- Plyr version: All versions above 3.0.2
- Browser: Safari for IOS
- Version: Default
- Operating System: IOS
- Version: 9

### Steps to reproduce
- It fails on page initialize

**Comment by sampotts** [comment]
Are you seeing this on https://plyr.io? There's certain things in the bug template that you've removed which help me debug issues...

**Comment by kfeng0806** [comment]
![](https://i.imgur.com/HjbmI7s.jpg)
@sampotts It happens also on the demo page
the actual behaviour should be page load normally, this error happened on the script load and it block other scripts behind this.

**Comment by sampotts** [comment]
Hmm I’ll take a look tonight then

**Comment by 66beta** [comment]
@sampotts 
same error on iOS 9.3.5
https://github.com/sampotts/plyr/blob/f1b275aedce897b42f025afac7a0937dc5871235/dist/plyr.js#L650

**Comment by 66beta** [comment]
@sampotts 
same error on iOS 9.3.5
https://github.com/sampotts/plyr/blob/f1b275aedce897b42f025afac7a0937dc5871235/dist/plyr.js#L2124
```
createClass(Fullscreen, [..., {
        key: 'name',
        get: function get$$1() {
            return this.prefix === 'moz' ? 'FullScreen' : 'Fullscreen';
        }
    }...
```
looks like __name__ is iOS 9.3.5's Reserved key.

I change it to other word (eg:originName), works fine!

**Comment by sampotts** [comment]
OK I've changed the property name in `v3.2.3` and it seems fixed now in the simulator.
