### ISSUE TITLE
Duration of an audio player is shown small from one side on the firefox browser

### ISSUE THREAD

**Issue by chaymafourati** [sampotts/plyr#909]
An audio player website is consuming your code , however the duration of the song is shown small from one side on the firefox browser so we checked and the bug was actually from the class="plyr__time--duration"

![duration](https://user-images.githubusercontent.com/30073269/38950775-da505da4-4346-11e8-8b85-b766bb6dbfef.PNG)

this is the project repository: 
https://github.com/zen-audio-player/zen-audio-player.github.io/pull/284

**Comment by friday** [comment]
That's Plyr v1.6.20. The latest version is 3.2.0

**Comment by chaymafourati** [comment]
Thank you !
