### ISSUE TITLE
Embedded youtube throw errors in console

### ISSUE THREAD

**Issue by KPeschke** [sampotts/plyr#910]
### Expected behaviour
No errors in Console.

### Actual behaviour
Mostly 2 errors are thrown.
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://plyr.io').

Failed to load https://googleads.g.doubleclick.net/pagead/id: Redirect from 'https://googleads.g.doubleclick.net/pagead/id' to 'data:text;charset=utf-8,' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.youtube.com' is therefore not allowed access.`

### Environment
- Browser: Chrome
- Version: 66.0.3359.117
- Operating System: macOS 
- Version: 10.13.4

### Steps to reproduce
- Open https://plyr.io/#youtube

**Comment by sampotts** [comment]
Unavoidable unfortunately. Please raise these issues with YouTube directly as the issue is with their API. Good luck 👍

**Comment by KPeschke** [comment]
Thank you @sampotts for the quick response.

**Comment by jochemkeller** [comment]
To add to this: I ran into this problem as well and my issue was related to a 'too aggressive' ad-blocker. Allowing 3rd party scripts in (in my case) uBlock Origin fixes the problem 👍

**Comment by benwoodward** [comment]
I just puzzled over this issue for way too long until I realised that Brave browsers 'shields' were preventing the Youtube embed from functioning properly.. just leaving this here for future googlers. 

I was also getting the following error: `Uncaught (in promise) undefined`.
