### ISSUE TITLE
I can't use the player more than one time in one page 

### ISSUE THREAD

**Issue by ariandemnika** [sampotts/plyr#911]
Im working on a project, and i implemented Plyr it works great, but when i use another video with <div class="player"> .......
it shows browsers default player.

[Screenshot 1 where player is working](http://prntscr.com/j7fps3)
[Screenshot 2 where player is not working](http://prntscr.com/j7fqcv)

[First player class](http://prntscr.com/j7fqr5)
[Second player class](http://prntscr.com/j7fr79)

How can i fix this?

**Comment by sampotts** [comment]
Hey, you need to setup each player individually... 

```javascript
const players = Array.from(document.querySelectorAll('.player')).map(player => new Plyr(player, { /* options */ }));
```

**Comment by ARHCG** [comment]
Can anyone upload a simple demo html (for noobs) with properly embedded 2 or more player on the same page. 
Thank you.
