### ISSUE TITLE
multiple players on phpBB

### ISSUE THREAD

**Issue by AlSarsawi** [sampotts/plyr#913]
Hello

I am using phpBB with BBCode and I couldn't find how to make multiple players in the same page, also I noticed that the speed control in the player not effect the play speed for both audio and video files

**Comment by sampotts** [comment]
https://github.com/sampotts/plyr#setting-up-multiple-players

**Comment by AlSarsawi** [comment]
yes I saw this but I didn't know where I should put it, I tried several things but it didn't work
