### ISSUE TITLE
Youtube: Seeked event fired only when video is playing

### ISSUE THREAD

**Issue by lazic-st** [sampotts/plyr#921]
As title says, seeked event is fired only if video is playing.
This could be issue only with YouTube, I didn't test with any other video source. I understand that YouTube is tricky because they have really retarded API for player... (only one worthwhile event)

### Expected behaviour
Seeked event is event that should be fired after mouse keyup event on 'seeking pin'.

### Actual behaviour
Seeked event is fired everytime seeking event happen followed by play event. Which means, if player is in PAUSED state seeked event is not fired.

### Environment

- Browser: Chrome
- Version: latest
- Operating System:  Windows
- Version: 10

### Steps to reproduce
- Embed any YouTube video with Plyr
- add event listener with console.log on event seeked()
- open page, play and pause video
- try to seek video

**Comment by gurupras** [comment]
I'm able to reproduce the issue reported here. I have also confirmed that it only occurs on YouTube. Here's a [pen](https://codepen.io/gurupras/pen/NMwPyR) to reproduce this issue.

**Comment by sampotts** [comment]
It’s likely due to their API not firing an event but I’ll take a look and see if I can mimic the event in lieu of the missing event.
