### ISSUE TITLE
Video player does not initialize on mobile devices 

### ISSUE THREAD

**Issue by mveenstra** [sampotts/plyr#924]
### Expected behavior
- Video player should initialize on mobile device. 

### Actual behavior
- Video player does not initialize correctly on mobile device. Currently, the video player looks as expected on desktop but does not look correct on mobile. 

Screenshot of video player on desktop:
![image](https://user-images.githubusercontent.com/3537667/39331043-4e0b08b8-4958-11e8-808c-600d941bb8bb.png)

Screenshot of what the same video loads like in mobile view:
![image](https://user-images.githubusercontent.com/3537667/39331074-68253642-4958-11e8-84d3-b55b27361a4f.png)

### Environment

- Browser: Chrome 
- Version: latest, auto updates
- Operating System: Windows 10

### Steps to reproduce
- Open Chrome browser
- Select mobile emulator in Chrome console
- Reload the page
- Video does not look correct on mobile device

**Comment by friday** [comment]
Doesn't seem like a problem on https://plyr.io/ though?

**Comment by mveenstra** [comment]
@friday I was actually just taking a look at that myself out of curiosity and you are correct it seems to be working on https://plyr.io/ - I am not sure why it would not work on mobile. There is no custom JS so its a tad confusing.

**Comment by friday** [comment]
Please verify that you're using the latest plyr version, and if so, could you replicate the non-working state with an online snippet editor such as jsfiddle/codepen/jsbin etc? :)

**Comment by mveenstra** [comment]
@friday aha! That was it. I did not realize I was referencing an older version of the plugin. Thank you so much for your time and help! Appreciate it. Have a great day!
