### ISSUE TITLE
Add support to skip the ads

### ISSUE THREAD

**Issue by filips123** [sampotts/plyr#929]
Add support to skip the ads after some time, like in YouTube.
Site owners should specify if users could skip the ads and the time that users need to wait before they can skip the ads. This time can also be 0 seconds.

**Comment by sampotts** [comment]
This is usually specified in the VAST tag. Have you spoken with [vi](https://vi.ai) about this? They manage the tags for the ads plugin.

**Comment by sampotts** [comment]
I've asked them and apparently the ability to skip the ads is controlled by the advertisers.
