### ISSUE TITLE
Seeking issues in full screen on touch devices with hidden controls

### ISSUE THREAD

**Issue by calvintam236** [sampotts/plyr#93]
If you went into full screen mode and pull up from bottom for the Android native navigation bar when the control is minimized (seeking bar will show), user will seek the media unintentionally. The action is common for Android users, and it is very annoying..

**Comment by calvintam236** [comment]
@SamPotts It is still an annoying issue when I just test for the new updates on my phone..

**Comment by SamPotts** [comment]
Yes but if I go ahead with this, you'll have to pause the video for the controls to show and then seek which is far from ideal. I think it needs some more thought than just disabling it otherwise it'll be annoying for some.

**Comment by calvintam236** [comment]
@SamPotts Is it possible to disable only the seeking when the control is minimized on mobile os? Or change play/ pause behavior to act after the controls are shown, not the first click like on the desktop? There should be differences on plyr's behavior for touch and mouse users.

**Comment by SamPotts** [comment]
Could definitely make it an option (defaulted to allowing seeking since thats what I think most users will want - it's not an issue on IOS for example). 

As for "Or change play/ pause behavior to act after the controls are shown, not the first click like on the desktop?", how do you see that working? The controls only show when the video is paused in fullscreen mode.

**Comment by calvintam236** [comment]
For native android video player (AwesomePlayer/ NuPlayer), clicking on the screen shows the control and it does not pause the video, users have to press the pause manually to do such action. I believe the same rule applies on iOS too.
For desktop users, clicking on the screen pause the video is what we used to.
Does this work here?

**Comment by SamPotts** [comment]
Sounds good. I'll implement something like that then. Nice one :+1:

**Comment by calvintam236** [comment]
So for mobile users, when the controls are hidden, no action (including seeking) by touch can trigger unless the user first clicked the screen once and reappear the controls. No changes for desktop users.

Also, can you make the seeking bar higher for mobile users? It is just too narrow for touch screen as it doesn't have the drag thing.

**Comment by SamPotts** [comment]
You can change the height in the LESS or SASS if you want to.

**Comment by friday** [comment]
Should be fixed by now. While playing with autoHide enabled, the controls will show if you touch (including pulling up from the bottom), but they don't start seeking unless you release your finger and tap the seeking bar. At least that's how it works in my tests.
