### ISSUE TITLE
custom buttons

### ISSUE THREAD

**Issue by francoiscop** [sampotts/plyr#931]
Hello,

In the previous version I was able to customize icon, and add my own buttons (like download or quality selector for HTML5 HLS) via the html attribute:
ex : 
`options.html = [
"<div class='plyr__controls'>",
"<div class='box-buttons'>",
    "<button type='button' data-plyr='play'>",
        "<svg><use xlink:href='#plyr-play'></use></svg>",
        "<span class='plyr__sr-only'>Play</span>",
    "</button>",
    "<button type='button' data-plyr='pause'>",
        "<svg><use xlink:href='#plyr-pause'></use></svg>",
        "<span class='plyr__sr-only'>Pause</span>",
    "</button>",
    "<span class='plyr__progress'>",
        "<label for='seek{id}' class='plyr__sr-only'>Seek</label>",
        "<input id='seek{id}' class='plyr__progress--seek' type='range' min='0' max='100' step='0.1' value='0' data-plyr='seek'>",
        "<progress class='plyr__progress--played' max='100' value='0' role='presentation'></progress>",
        "<progress class='plyr__progress--buffer' max='100' value='0'>",
            "<span>0</span>% buffered",
        "</progress>",
        "<span class='plyr__tooltip'>00:00</span>",
    "</span>", ETC ....
];`

In the new version (3.2.4), this html attribute doesn't exist anymore!

What is the new way to inject custom buttons ?

Many thanks for your attention

**Comment by sampotts** [comment]
The option is now called controls. Worth reading the docs first...
