### ISSUE TITLE
CSS not being applied to non-Youtube video urls

### ISSUE THREAD

**Issue by dailenspencer** [sampotts/plyr#934]
### Expected behaviour
CSS is properly applied in all cases 

### Actual behaviour
The adding of CSS classes and overall initialization of Plyr is not occurring when the video url supplied is anything other than a YouTube url. If I supply a video url from vimeo, or my AWS S3 bucket, the '#player' element doesnt have any of the appropriate html classes added to it and therefore never has any CSS applied. I tried to add the following basic HTML video tag to my app and still no luck 

```
<video id="player" playsinline controls>
    <source src="https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4" type="video/mp4">
</video>
```
and the initialization here 

```
const videoPlayer = new Plyr('#player', this.props.videoPlayerOptions);
```

the end result is a basic video element in the browser. Am I missing something here? Why would the styling only apply to videos that are from YouTube? 

### Environment

- Browser: Chrome
- Version: 64
- Operating System: OSX
- Version: 10.12.6

**Comment by dailenspencer** [comment]
UPDATE: 

I've found that the reason for the CSS classed not being applied is due to the following check 
```
if (utils.is.empty(this.provider) || !Object.keys(providers).includes(this.provider)) {
  this.debug.error('Setup failed: Invalid provider');
  return;
}
```

I've manually set this.provider to 'html5' in the line above. This manages to get a few of the appropriate class names applied to the '#player' element but still no styling.

**Comment by sampotts** [comment]
Given that's almost identical code to the demo (it's a basic HTML5 video initially) then I'm at a loss. Do you have multiple `#player` elements perhaps? 

Here's a basic codepen that might shed some light 
http://codepen.io/sampotts/pen/jARJYp

**Comment by dailenspencer** [comment]
@sampotts The functionality seems to be working appropriately now. I modified my code to check for the url source of the video(youtube/vimeo OR S3) - and then return the appropriate code accordingly(in React.js)

Youtube/Vimeo 
```
<div className='video-widget'>
                   <div className="plyr__video-embed" id={this.props.elementId} onClick={() => this.handleClick ()} onMouseOver={() => this.handleMouseOver ()} onMouseOut={() => this.handleMouseOut ()}>
                       <iframe src={this.props.videoPlayerData.src}></iframe>
                   </div>
                </div>
```
s3
```
<div className='video-widget'>
                    <video className="plyr__video-embed" id={this.props.elementId} playsinline onClick={() => this.handleClick ()} onMouseOver={() => this.handleMouseOver ()} onMouseOut={() => this.handleMouseOut ()}>
                        <source src={this.props.videoPlayerData.src} type="video/mp4"/>
                    </video>
                </div>
```

And now it seems to work. I thought this is what I was doing previously but maybe they were getting mixed up somehow. Closing out the issue :)
