### ISSUE TITLE
Error when rendering plyr server side

### ISSUE THREAD

**Issue by mimse** [sampotts/plyr#935]
### Expected behavior
Be able to use plyr with server-side rendering

### Actual behavior
Get this error "navigator is not defined"

### Environment

- Browser: nodejs
- Version: 8
- Operating System: macOS sierra
- Version: 3.2.4

### Steps to reproduce
- Try to render plyr server side

**Comment by friday** [comment]
I'm not sure what "Be able to use plyr with server-side rendering" means. Isn't it the opposite behavior you want? Plyr detecting that the environment isn't client and returning some kind of dummy object with noop methods in order not to break the build?

It's likely that whichever framework/library you're using exposes the environment so you could conditionally opt out of initializing Plyr in the SSR phase.

If you're using React this should help you: https://reactjs.org/docs/react-dom.html#hydrate Also in this case https://github.com/xDae/react-plyr seems to handle this already (https://github.com/xDae/react-plyr/issues/1).

**Comment by friday** [comment]
Thanks for the clarification! I didn't realize that.

Plyr wasn't built to be modular to begin with, but rather converted. Wrapping defaults in a function should solve the module import issue (although it might be needed in more places).

Would that suffice for both of your needs, or  do you also need to be able to initialize it?

**Comment by friday** [comment]
I'd say go for it, but @sampotts is the judge of that.

**Comment by sampotts** [comment]
Yeh go for it if it works 👍

**Comment by mimse** [comment]
@friday I have tested your #960 and it is working. Thank you for this.

**Comment by friday** [comment]
The PR was just released in v3.3.8
