### ISSUE TITLE
HTML5 autoplay duplicates video and results in two videos playing

### ISSUE THREAD

**Issue by DK999k** [sampotts/plyr#936]
### Expected behaviour
If autoplay is true (and browser conditions have been met), video should play on page load.

### Actual behaviour
The video gets duplicated, and both tracks play simultaneously. Controls will only be active for the original track (bound to plyr), so if a user pauses the video, only one track will pause and the other will continue playing.

### Environment
- Browser: Chrome
- Version: 66.0.3359.139
- Operating System: Win 7

### Steps to reproduce
- Firefox is easiest to test, since it has the most liberal autoplay policy:
- Open <a href="https://codepen.io/DK999k/pen/Qrvqxw">**This Pen**</a> in FireFox, wait a few seconds, and attempt to pause the video. One track pauses, while the other continues playing.
_
- If you can satisfy the browser conditions for autoplay, this behavior is identical in Chrome (same environment) and Safari (OSX 10.11.6). I believe both browsers allow you to configure autoplay settings to simplify testing (Chome: 'No User Gesture Required' here: chrome://flags/#autoplay-policy ).

**Comment by sampotts** [comment]
This is a real pain. We need to clone the original node for the `destroy()` method but this has the side effect of loading the video twice with no way that I can see, to prevent it. I've had a play and think I've found a fix though.

**Comment by sampotts** [comment]
This should be fixed in v3.3.0 but report back if not...
