### ISSUE TITLE
Quality menu items "selected" style is not displayed upon selection.

### ISSUE THREAD

**Issue by Billybobbonnet** [sampotts/plyr#940]
### Expected behaviour
When a quality is selected, it should have a dedicated style, and the quality menu should get back to the main menu

### Actual behaviour
The quality is not selected (in terms of visual feedback) and the menu stays in the same state

### Environment

- Browser: All
- Operating System:All

### Steps to reproduce

Change the quality with a standard HTML5 video

---

I assume this is because of the way menu events are handled (see https://github.com/sampotts/plyr/blob/master/src/js/controls.js#L595). Maybe the related hidden input selector looks for the raw value, while quality values are appended with a `p` (see https://github.com/sampotts/plyr/blob/master/src/js/controls.js#L524)? It then fails to find the radio input.

Moreover, once the input `checked` attribute is set to `true`, the span supposed to show that it is the selected value still has its `hidden` attribute (scss here:https://github.com/sampotts/plyr/blob/master/src/sass/components/menus.scss#L167)

I would have written a quick PR to fix that, but I lack the time to do so and I don't know where/how you would prefer to fix it.

**Comment by Billybobbonnet** [comment]
Nope. While investigating this, I made it appear but only using the browser dev tools. 

As  I understand it, the expected behavior should be:

1. User click on a quality menu item
2. The hidden input is set to `checked` (it's not)
3. all the menu spans `hidden` properties are removed (it's not)
4. The SCSS takes it from there with this rule: https://github.com/sampotts/plyr/blob/master/src/sass/components/menus.scss#L167
5. (UX wise, imho) the menu should make a step back to the main settings menu

**Comment by friday** [comment]
Please don't lump together separate suggestions or issues. If you want them done, create separate issues for separate issues/suggestions, and if not just don't bring them up.

As for the main issue, you seem to be on the case yourself so I'll leave you to it.

**Comment by sampotts** [comment]
When selecting an option, it'll now take you back to the home tab pane.

**Comment by sampotts** [comment]
Sorry - I reverted that change. While doing more testing I noticed that it meant that the menu and controls abruptly disappeared which was pretty jarring. Also realised that visually impaired users would be effected as keyboard selection also had the same effect. Will think about it again as an option.
