### ISSUE TITLE
Paused Class Missing

### ISSUE THREAD

**Issue by JesseHigson** [sampotts/plyr#941]
**Expected behaviour**

Plyr would have an additional class to _plyr--playing_ and _plyr--stopped_ of _plyr--paused_ in order to differentiate between whether the video has been paused by the user or stopped automatically due to reaching its end.

**Actual behaviour**

Plyr only has two classes _plyr--playing_ and _plyr--stopped_, _plyr--stopped_ is applied when both the video is paused and has stopped.

**Environment**

- Browser: Chrome
- Version: 66.0.3359.139 (Official Build) (64-bit)
- Operating System: macOS High Sierra
- Version: 10.13.4

**Comment by sampotts** [comment]
The weird thing is that the HTML5 media elements don't have the concept of stopped but I guess we can safely assume if the player is paused and currentTime is 0 then it's stopped. 

I'll take a look. 

BTW I'm originally from Portsmouth, just down the road. Small world! 👍

**Comment by JesseHigson** [comment]
Weird, I've never realised that about HTML5 media.
The logic you suggested makes sense though, thanks for looking into it.

Nice! As am I actually, small world indeed 😎

**Comment by friday** [comment]
By the sound of it, wouldn't that also toggle the class on if you pause it, and move the progress slider to 0:00?

**Comment by sampotts** [comment]
Yep. It’d be effectively the same state. It’s probably why the standard API doesn’t support it. 

Sam

**Comment by sampotts** [comment]
This should be resolved now in the latest version (v3.3.0)
