### ISSUE TITLE
On pause do exitfullscreen event

### ISSUE THREAD

**Issue by lbachkur** [sampotts/plyr#944]
http://prntscr.com/jeqzsj
when key press backspace execute pause or play event with fullscreen  

and problem with buffering video in 1.5 - 2 x speed

### Environment

- Browser: Mozilla 
- Version: 59.0.3. 64-bit
- Operating System: Windows
- Version: 7

### Steps to reproduce
-

**Comment by sampotts** [comment]
Buffering video would be down to the quality/compression vs network speed. Just a factor of how much you can get down the pipe. 

The other issue I’m not sure what’s up. Are you saying backspace triggers play/pause when I’m full screen?

**Comment by lbachkur** [comment]
Yes, fullscreen triggers work with backspace button
When I am press backspace video is paused or played  with fullscreen exit or show 
It is in Mozilla problem

**Comment by lbachkur** [comment]
https://drive.google.com/open?id=1kCaqX5_RPZKNjT07nfdmfagxo7A34K8QcJpehbjgDHg

**Comment by sampotts** [comment]
I think this is just due to the history api - backspace = go back. I don't think we should disable that behaviour.
