### ISSUE TITLE
Playback not working on mobile (click obscured by poster elem)

### ISSUE THREAD

**Issue by mhluska** [sampotts/plyr#946]
### Expected behaviour

Expect video to play when clicking play on iOS mobile Chrome.

### Actual behaviour

Video does not play. Play button animation happens.

### Environment

- Browser: Chrome
- Version: 66.0.3359.122
- Operating System: iOS
- Version: 11.3

### Steps to reproduce

- Click play on player

**Comment by sampotts** [comment]
Which video type? I can't replicate on https://plyr.io for HTML5, YouTube or Vimeo.

**Comment by mhluska** [comment]
The video type is webm. The first `<source>` tag is webm and the second is mp4 as a fallback.

**Comment by sampotts** [comment]
As I say I can't replicate on the demo site. Could you link to the player with the issue? Any errors in the console perhaps?

**Comment by mhluska** [comment]
I'm seeing this error in sentry: `The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

**Comment by friday** [comment]
@mhluska Your fix will be included in the next plyr release. In the meanwhile you have to keep that in your css 👍

**Comment by sampotts** [comment]
@mhluska @friday It's now released in v3.3.7 👍

**Comment by medoingthings** [comment]
It seems like this fix was removed again. Came across the same issue with plyr on iPhone where the (progressive iframe) YouTube player would not be playable, because the poster layer „eats” the tap. Will use the workaround, but am curious why `pointer-events: none;` is gone.

plyr-version: 3.6.2
