### ISSUE TITLE
AdError 1101: The provided content information: currentTime is invalid.

### ISSUE THREAD

**Issue by BesrourMS** [sampotts/plyr#949]
### Environment

- Browser: Chrome & Firefox
- Version:
- Operating System: Windows 7
- Version:

### Steps to reproduce
-

**Comment by friday** [comment]
Does this happen on the plyr demo https://plyr.io/? Didn't get this myself but there is a similar error logged recently https://sentry.io/plyr-js/demo/issues/550854898/?referrer=slack (which only Sam can see).

**Comment by BesrourMS** [comment]
![plyrerror](https://user-images.githubusercontent.com/12979318/39782204-69089742-5309-11e8-8f49-a703e6f242c2.jpg)

**Comment by friday** [comment]
Don't take it personal. The ads called me that as well. It's a minified error so it means pretty much nothing. If you expand it it will say "The ad response was not understood and cannot be parsed" or "Unable to request ads from server due to network error" or something.

**Comment by BesrourMS** [comment]
![plyer](https://user-images.githubusercontent.com/12979318/39782536-64148f92-530a-11e8-970f-18ab02da301e.jpg)

**Comment by BesrourMS** [comment]
![plyrerror](https://user-images.githubusercontent.com/12979318/40723677-4e87ca40-6417-11e8-8b5c-257f836f6a28.jpg)

**Comment by sampotts** [comment]
This should now be resolved in v3.4.0 but please report back if you're still seeing it.
