### ISSUE TITLE
Autoplay api doesn't work in the new chrome

### ISSUE THREAD

**Issue by Garfill** [sampotts/plyr#955]
### Do not work in the newest Chrome while work in the Firefox(FF). The chrome console pannel tell me that 
>Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.

### Environment

- Browser: Chrome and Firefox
- Version: Chrome 66 and FF dev version
- Operating System: win7
- Version: 

### Steps to reproduce
-

**Comment by friday** [comment]
This is a feature in Chrome that we can do nothing about. You could try muting it or setting the volume to 0.

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by liamtarpey** [comment]
FYI this now also happens in Safari 11.1 but with this (less helpful) exception:

`Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

**Comment by kripul** [comment]
Try  to
1. Open chrome://flags/#autoplay-policy
2. Setting No user gesture is required

Relaunch Chrome

**Comment by friday** [comment]
Now you just have to tell all you users to do that ;)
