### ISSUE TITLE
How should I set the color of played progress?

### ISSUE THREAD

**Issue by Garfill** [sampotts/plyr#962]
I need to set a special color to the played progress but I can't  find the option.
### Actual behaviour
Here is my code of porgress:
```
                            <div class="plyr__progress">
                                <input data-plyr="seek" type="range" min="0" max="100" step="0.01" value="0" id="plyr-seek-{id}">
                                <progress class="plyr__progress--played" max="100" value="0" role="presentation"></progress>
                                <progress class="plyr__progress--buffer" max="100" value="0"><span>0</span>%</progress>
                            </div>
```

I found that there is not a progress bar for played in default controls options, not like the old version. So is there any chance I can set the color of the played  progress within the plyr of newest version

**Comment by sampotts** [comment]
Using the SASS variable as per the previous version:
https://github.com/sampotts/plyr/blob/master/src/sass/settings/colors.scss#L5
