### ISSUE TITLE
Fullscreen works inconsistently on Safari 11.1

### ISSUE THREAD

**Issue by ricardoalcocer** [sampotts/plyr#964]
### Expected behaviour
Fullscreen should be fullscreen every time

### Actual behaviour
If I start the video fullscreen, it works fine.  As soon as I bring it to it's normal size and fullscreen again, the video is expanded but it's only viewable from a small area of the screen.

### Environment

- Browser: Only happens in Safari
- Version: 11.1
- Operating System: OSX High Sierra
- Version: 0.13.4 (17E202)

### Steps to reproduce
- Here's a GIF that shows the issue: http://drops.ricardoalcocer.com/drops/plyr-error.gif

**Comment by friday** [comment]
Great initiative to include the gif :) However, if it's not happening on the https://plyr.io/ demo (which it isn't for me in Safari) or you can replicate it on a code playground like jsfiddle or codepen, then there is nothing that says this is a Plyr issue. It could be, but it could just be your own css.

I would use the inspector to try and figure out if an element is not getting full width, which element and why.

**Comment by ricardoalcocer** [comment]
Thanks @friday.  I'll do some more digging.  I just figured that since it's only happening on Safari (works on Chrome and Firefox), maybe there could be something.  I'll report back...but I'm with you.  I definitely don't trust my own CSS :)

**Comment by friday** [comment]
It doesn't mean any css is invalid. Judging by the gif I think it looks more like a browser render bug. But I would start with the inspector either way. Maybe some combination of things in fully valid css causes that, and can be avoided. @sampotts has fixed a [similar issue](https://github.com/sampotts/plyr/issues/664) in the past and may know something I don't.

**Comment by ricardoalcocer** [comment]
I think you're right.  It appears to be related to the "collapsing" classes I'm using from Bootstrap.  If I remove the 2nd column everything goes back to normal.  Then again, my CSS skills are at hacker-level, so don't know for sure at the moment.  

I won't have time to get back to this until mid-june, so feel free to close it and I can re-open later.  Thanks for the super quick replies!

**Comment by friday** [comment]
I think you need permission to reopen it, but you can comment either way and I can reopen it if it turns out to be a Plyr issue.
