### ISSUE TITLE
Touch devices doesn't pause when tapping playing video

### ISSUE THREAD

**Issue by LittleHamster** [sampotts/plyr#968]
### Expected behaviour
Pause the video on mobile when clicking on the viedeo

### Actual behaviour
Cannot pause the video on mobile when clicking on the video

### Environment

- Browser: safari
- Version: latest
- Operating System:iOS
- Version: latest

### Steps to reproduce
-

**Comment by friday** [comment]
Does it happen on https://plyr.io/?

**Comment by LittleHamster** [comment]
@friday 
yes, so if you open it on safari (i said chrome by accident, updated the issue) the video plays
then try to tap on the video again to stop it but it wont stop 
you have to stop the video using the video controller at the bottom controllers

**Comment by friday** [comment]
I think that's how it's intended to work with touch-devices. Tapping to stop is problematic since tap mean "show the controls" when `autoHide` is enabled.

**Comment by LittleHamster** [comment]
@friday 
oh I see, I hide the controllers via css so I couldn't stop the video on mobile by clicking on the video
when on desktop, you can click on the video and it pauses so I thought same thing should happen on mobile

**Comment by 0cool-f** [comment]
The fact is that tapping is not an exclusive behaviour of mobile devices: I'm on a Desktop, but I have a touchscreen monitor, so every mouseclick for me works like tap on Plyr.

**Comment by friday** [comment]
Yes of course. If your screen is a touch device and you touch it, your interactions counts as touch interactions. It goes without saying.

**Comment by sampotts** [comment]
This should now be resolved in v3.4.0

**Comment by 0cool-f** [comment]
@sampotts 👍 yeah, solved my mouseclick issue ([#1067](https://github.com/sampotts/plyr/issues/1067)), mouse behaviour and touch events now act different, there's still a little problem just for touch: if the video is playing and I tap the video it will pause itself, but when this one is paused and I tap the video it will not come back to play, it just show me next frame and then return to pause immediately, instead if I hold tap for about 1sec it will come back to play normally...

**Comment by LittleHamster** [comment]
@sampotts 
"This should now be resolved in v3.4.0"
but tapping on the video still does not pause the video - may I know what changed?

**Comment by sampotts** [comment]
It shows the controls instead. This mimics most other video players behavior.

**Comment by jamesoflol** [comment]
Yep, and the reason other players do it is because you have to touch it to get to settings/seek (no hover)

**Comment by LittleHamster** [comment]
> It shows the controls instead; which allows you to pause. This mimics most other video players behavior and makes the most sense.

Is there an event listener we can set to true when initializing the player so when tapping on the video, it pauses the video?

**Comment by mayeaux** [comment]
> > It shows the controls instead; which allows you to pause. This mimics most other video players behavior and makes the most sense.
> 
> Is there an event listener we can set to true when initializing the player so when tapping on the video, it pauses the video?

You could do onclick , or ontouch via javascript?
