### ISSUE TITLE
plyr don't initalize

### ISSUE THREAD

**Issue by danbulant** [sampotts/plyr#970]
### Expected behaviour
Just copy the codes from readme and edit YT links.
### Actual behaviour
I just copied the codes from readme. I'm using fastly CDN. Console don't show any error. I'm just using the default codes, from youtube.
### Environment

- User agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)Chrome/64.0.3282.186 Safari/537.36 Avast/64.0.388.186
- Operating System: Windows 10
- Version: newest

### Steps to reproduce
- I don't know, I just used codes from readme tutorial..

**Comment by danbulant** [comment]
Why invalid and closed? 
I don't know how to fix it

**Comment by friday** [comment]
You failed to set up working environment (the easiest part), assumed the problem couldn't possibly be in your code, so it must be in ours, didn't provide any link or snippet so the issue could be replicated, and additionally skipped the question regarding if it's happened at https://plyr.io/ page

If "the codes" are not working for you, why would they be working for us?

It's just too rude and ignorant.

**Comment by danbulant** [comment]
OK....
But where I failed?

**Comment by danbulant** [comment]
fixed..
