### ISSUE TITLE
Captions not works in Vimeo player

### ISSUE THREAD

**Issue by matoni555** [sampotts/plyr#972]
### Actual behaviour
Captions not works in Vimeo player, see demo http://www.matonoha.cz/_html/plyr/
Plyr v3.3.7

### Environment

- Browser: Chrome
- Version: 66.0.3359.181
- Operating System: Windows
- Version: 11

Thanks

**Comment by friday** [comment]
Seems like all of their caption files (among others) currently result in "404 Not Found" server errors. It happens without Plyr too. https://player.vimeo.com/video/76979871

**Comment by sampotts** [comment]
Ah, excellent. I'll wait for them to fix that then 👍
