### ISSUE TITLE
Install using npm < 6 installs npm as a dependency

### ISSUE THREAD

**Issue by ashleahhill** [sampotts/plyr#974]
### Expected behaviour

Installing `plyr@3.3.7.` using `npm install` shouldn't install npm locally

### Actual behaviour

`npm@6.1.0` is being installed in node_modules like it is a local dependency. 

This causes a fatal error when I try to build:

```bash
To use this template, you must update following to modules:

  npm: 6.1.0 should be >= 5.3.0 <= 5.6.0
```
(The app that I'm upgrading plyr on has npm locked down in its `engines` field. )

`package.json` in `master` has this, however the version in `develop` does not.

```json
"dependencies": {
    "babel-polyfill": "^6.26.0",
    "custom-event-polyfill": "^0.3.0",
    "loadjs": "^3.5.4",
    "npm": "^6.0.0",
    "raven-js": "^3.24.2"
  },
```

I've never seen npm installng npm as a local dependency before. Not sure if this is something unique to Plyr's setup that I'm missing or a new best practice with NPM. I'm part of a dev team where it won't be insignificant to upgrade everyone's NPM from 5.6.0 to 6, so an explanation would be appreciated if this isn't, in fact, a bug.

### Environment

- Browser: N/A
- Version: N/A
- Operating System: Mac OS
- Version: 10.13.4

### Steps to reproduce
- Be using npm `5.6.0` 
- Set `engines.npm` to `>= 5.3.0 <= 5.6.0` in `package.json`
- install plyr using `npm install`
- Try to run an npm script and see error

**Comment by sampotts** [comment]
It’s a bug. Will fix it. 

Sam

**Comment by sampotts** [comment]
This should now be resolved! Cheers 👍
