### ISSUE TITLE
the audio player of the demo does not work.

### ISSUE THREAD

**Issue by rcasunshare** [sampotts/plyr#982]
The last demo of the pack to download does not work the audio player.

**Comment by friday** [comment]
The demo in the release download is the same as https://plyr.io/#audio, which is working great. I can also run it locally with for example `python -m SimpleHTTPServer 8080` and then going to http://localhost:8080/demo/. If it doesn't work for you locally it's probably your server. You need the right mimetypes etc. See your console for errors.

**Comment by rcasunshare** [comment]
Yes or if you need to be on a server? since the direct PC does not work?

**Comment by friday** [comment]
A server is a computer (or software depending on the context). You can run server software on your PC. Anyway, it's not a bug, has nothing to do with the functionality of Plyr, and you have to figure this out on your own.

**Comment by friday** [comment]
In the future, please use slack https://bit.ly/plyr-chat for questions or issues, if they're not happening on https://plyr.io
