### ISSUE TITLE
Plyr problem please help

### ISSUE THREAD

**Issue by spencer237** [sampotts/plyr#984]
Hello to all the great devellopers of Github, I come to you because I have a problem with plyr. I just installed it on my site but it remains black, no Youtube video and no controller on it. really need help thank you in advance.

**Comment by sampotts** [comment]
Head over to the Slack for help. This is for software bugs.

**Comment by spencer237** [comment]
Please, I do not understand what you are going to say

**Comment by sampotts** [comment]
[Slack Chat](https://bit.ly/plyr-chat)
