### ISSUE TITLE
Does not show poster if not set

### ISSUE THREAD

**Issue by matoni555** [sampotts/plyr#985]
Is it possible to show first frame of a video like a poster image?
In previous realeses videos without posters showed first frame like a poster.
In current realese video without poster shows just black background.

Thank you

**Comment by friday** [comment]
The poster element should only be shown when the poster image can be loaded. Are you sure the first frame isn't just black or that you didn't disabled preload for the video?

**Comment by friday** [comment]
Please post a link to a code playground (like jsfiddle, jsbin, codepen etc) where this is happening. Closing until then.
