### ISSUE TITLE
Resume playback when changing quality

### ISSUE THREAD

**Issue by philipgiuliani** [sampotts/plyr#991]
### Expected behaviour
I would like that the playback resumes at currentTime when changing the quality.

### Actual behaviour
If I change the quality, the playback restarts from 0.

### Environment

- Browser: Google Chrome
- Version: Latest
- Operating System: Mac OS X

### Steps to reproduce
- Go to https://plyr.io
- Skip to 1 minute
- Change quality

**Comment by sampotts** [comment]
This is a regression I think as this was the original behaviour

**Comment by philipgiuliani** [comment]
I have a fix 👍 PR is on the way!
