### ISSUE TITLE
Please update document & demo about `plyr__progress__buffer`

### ISSUE THREAD

**Issue by nanyang24** [sampotts/plyr#996]
The version: v3.3.10

When I use the custom controls in this version.I checked [controls.md](https://github.com/sampotts/plyr/blob/master/controls.md) and [demo on Codepen](http://codepen.io/sampotts/pen/jARJYp).

I copied the code for the custom control example.But the parts of the code about the buffer are old versions of the deprecated code.

Like this:

```js
plyr__progress--buffer
```

Rather than:

```js
plyr__progress__buffer
```

so please update the part of code.

**Comment by sampotts** [comment]
Done! Cheers 👍
