### ISSUE TITLE
Overlapping caption cues are skipped

### ISSUE THREAD

**Issue by philipgiuliani** [sampotts/plyr#998]
### Expected behaviour
If you are using the following VTT File, the overlapping cue from 18:10 - 18:15 is skipped. It should be shown though.

```
WEBVTT
TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:0

18:06.399 --> 18:11.399
Vielleicht sollten wir
eine Routine-Untersuchung starten.

18:10.59 --> 18:15.59
Geben Sie mir mal das PrÃ¤sidium.
- Ja.

18:13.259 --> 18:18.259
Frau Pfeifer, ...
- Ja?
```

From https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API
>  The end time must be greater than the start time, and the start time must be greater than or equal to all previous start times. Cues may have overlapping timings.

### Actual behaviour
VLC is showing the overlapping captions stacked (new captions appears from top, old ones are removed at the bottom).

### Environment

- Browser: Google Chrome
- Version: Latest
- Operating System: mac OS
- Version: 10.12.6

**Comment by sampotts** [comment]
I'm wondering if this is a browser bug since we use the browser `cuechange` events to render captions so I wonder if they miss out overlapping captions for some reason. Did you try with a native HTML5 `<video>`?

**Comment by philipgiuliani** [comment]
I haven't done a lot of investigation yet, but I'm gonna do some checks! :)

**Comment by philipgiuliani** [comment]
Maybe the problem is that we're only taking the `activeCues[0]` 🤔 

https://github.com/sampotts/plyr/blob/master/src/js/captions.js#L201
